package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnActivityLogMarked generated by hbm2java
 */
@Entity
@Table(name="PN_ACTIVITY_LOG_MARKED"
)
public class PnActivityLogMarked  implements java.io.Serializable {


     private PnActivityLogMarkedPK comp_id;
     
     private Integer isMarked;
     
     private PnActivityLog pnActivityLog;
     
     private PnPerson pnPerson;

     public PnActivityLogMarked() {
     }

    public PnActivityLogMarked(PnActivityLogMarkedPK comp_id) {
        this.comp_id = comp_id;
    }
    
	public PnActivityLogMarked(net.project.hibernate.model.PnActivityLogMarkedPK comp_id, Integer isMarked){
		this.comp_id = comp_id;
		this.isMarked = isMarked;
	}
	
    public PnActivityLogMarked(PnActivityLogMarkedPK comp_id, Integer isMarked, PnActivityLog pnActivityLog, PnPerson pnPerson) {
       this.comp_id = comp_id;
       this.isMarked = isMarked;
       this.pnActivityLog = pnActivityLog;
       this.pnPerson = pnPerson;
    }
   
     @EmbeddedId

    @AttributeOverrides( {
        @AttributeOverride(name="activityLogId", column=@Column(name="ACTIVITY_LOG_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", nullable=false, length=20) ) } )
    public PnActivityLogMarkedPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnActivityLogMarkedPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="IS_MARKED", length=1)
    public Integer getIsMarked() {
        return this.isMarked;
    }
    
    public void setIsMarked(Integer isMarked) {
        this.isMarked = isMarked;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnActivityLog.class)
    @JoinColumn(name="ACTIVITY_LOG_ID", insertable=false, updatable=false)
    public PnActivityLog getPnActivityLog() {
        return this.pnActivityLog;
    }
    
    public void setPnActivityLog(PnActivityLog pnActivityLog) {
        this.pnActivityLog = pnActivityLog;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="PERSON_ID", insertable=false, updatable=false)
    public PnPerson getPnPerson() {
        return this.pnPerson;
    }
    
    public void setPnPerson(PnPerson pnPerson) {
        this.pnPerson = pnPerson;
    }

}


