package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PnAssignmentTimesheet generated by hbm2java
 */
@Entity
@Table(name = "pn_assignment_timesheet")
public class PnAssignmentTimesheet implements Serializable {

	private PnAssignmentTimesheetPK pk;

	public PnAssignmentTimesheet() {
	}

	public PnAssignmentTimesheet(PnAssignmentTimesheetPK pk) {
		this.pk = pk;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "timesheet_id", column = @Column(name = "timesheet_id", nullable = false, length = 20)),
			@AttributeOverride(name = "space_id", column = @Column(name = "space_id", nullable = false, length = 20)),
			@AttributeOverride(name = "object_id", column = @Column(name = "object_id", nullable = false, length = 20)) })
	public PnAssignmentTimesheetPK getPk() {
		return this.pk;
	}

	public void setPk(PnAssignmentTimesheetPK pk) {
		this.pk = pk;
	}

}
