/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBaseline generated by hbm2java
 */
@Entity
@Table(name = "PN_BASELINE")
public class PnBaseline implements java.io.Serializable {

	private Integer baselineId;

	private Integer objectId;

	private String name;

	private String description;

	private Integer isDefaultForObject;

	private Date dateCreated;

	private Date dateModified;

	private String recordStatus;

	private Set pnBaselineHasTasks = new HashSet(0);

	private Set pnBaselineHasPlans = new HashSet(0);

	public PnBaseline() {
	}

	public PnBaseline(Integer baselineId, Integer objectId, String recordStatus) {
		this.baselineId = baselineId;
		this.objectId = objectId;
		this.recordStatus = recordStatus;
	}

	public PnBaseline(Integer baselineId, Integer objectId, String name, String description,
			Integer isDefaultForObject, Date dateCreated, Date dateModified, String recordStatus,
			Set pnBaselineHasTasks, Set pnBaselineHasPlans) {
		this.baselineId = baselineId;
		this.objectId = objectId;
		this.name = name;
		this.description = description;
		this.isDefaultForObject = isDefaultForObject;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.recordStatus = recordStatus;
		this.pnBaselineHasTasks = pnBaselineHasTasks;
		this.pnBaselineHasPlans = pnBaselineHasPlans;
	}

	/** minimal constructor */
	public PnBaseline(Integer baselineId, Integer objectId, String recordStatus, Set pnBaselineHasTasks,
			Set pnBaselineHasPlans) {
		this.baselineId = baselineId;
		this.objectId = objectId;
		this.recordStatus = recordStatus;
		this.pnBaselineHasTasks = pnBaselineHasTasks;
		this.pnBaselineHasPlans = pnBaselineHasPlans;
	}

	@Id
	@Column(name = "BASELINE_ID", nullable = false)
	public Integer getBaselineId() {
		return this.baselineId;
	}

	public void setBaselineId(Integer baselineId) {
		this.baselineId = baselineId;
	}

	@Column(name = "OBJECT_ID", nullable = false, length = 20)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IS_DEFAULT_FOR_OBJECT", length = 1)
	public Integer getIsDefaultForObject() {
		return this.isDefaultForObject;
	}

	public void setIsDefaultForObject(Integer isDefaultForObject) {
		this.isDefaultForObject = isDefaultForObject;
	}

	@Column(name = "DATE_CREATED", length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "DATE_MODIFIED", length = 7)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnBaseline", targetEntity = PnBaselineHasTask.class)
	@Transient
	public Set getPnBaselineHasTasks() {
		return this.pnBaselineHasTasks;
	}

	public void setPnBaselineHasTasks(Set pnBaselineHasTasks) {
		this.pnBaselineHasTasks = pnBaselineHasTasks;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnBaseline", targetEntity = PnBaselineHasPlan.class)
	@Transient
	public Set getPnBaselineHasPlans() {
		return this.pnBaselineHasPlans;
	}

	public void setPnBaselineHasPlans(Set pnBaselineHasPlans) {
		this.pnBaselineHasPlans = pnBaselineHasPlans;
	}

	public String toString() {
		return new ToStringBuilder(this).append("baselineId", getBaselineId()).toString();
	}
}
