/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDiscussionHistoryPK generated by hbm2java
 */
@Embeddable
public class PnDiscussionHistoryPK  implements java.io.Serializable {

    /** identifier field */
    private Integer discussionGroupId;

    /** identifier field */
    private Integer discussionGroupHistoryId;

    public PnDiscussionHistoryPK() {
    }

    public PnDiscussionHistoryPK(Integer discussionGroupId, Integer discussionGroupHistoryId) {
       this.discussionGroupId = discussionGroupId;
       this.discussionGroupHistoryId = discussionGroupHistoryId;
    }
   


    @Column(name="DISCUSSION_GROUP_ID", nullable=false, length=20)
    public Integer getDiscussionGroupId() {
        return this.discussionGroupId;
    }
    
    public void setDiscussionGroupId(Integer discussionGroupId) {
        this.discussionGroupId = discussionGroupId;
    }


    @Column(name="DISCUSSION_GROUP_HISTORY_ID", nullable=false, length=20)
    public Integer getDiscussionGroupHistoryId() {
        return this.discussionGroupHistoryId;
    }
    
    public void setDiscussionGroupHistoryId(Integer discussionGroupHistoryId) {
        this.discussionGroupHistoryId = discussionGroupHistoryId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("discussionGroupId", getDiscussionGroupId())
            .append("discussionGroupHistoryId", getDiscussionGroupHistoryId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDiscussionHistoryPK) ) return false;
        PnDiscussionHistoryPK castOther = (PnDiscussionHistoryPK) other;
        return new EqualsBuilder()
            .append(this.getDiscussionGroupId(), castOther.getDiscussionGroupId())
            .append(this.getDiscussionGroupHistoryId(), castOther.getDiscussionGroupHistoryId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getDiscussionGroupId())
            .append(getDiscussionGroupHistoryId())
            .toHashCode();
    }
}


