/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeVersionView generated by hbm2java
 */
@Entity
@Table(name="PN_ENVELOPE_VERSION_VIEW"
)
public class PnEnvelopeVersionView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal envelopeId;

    /** identifier field */
    private BigDecimal versionId;

    /** identifier field */
    private BigDecimal workflowId;

    /** identifier field */
    private BigDecimal stepId;

    /** identifier field */
    private String stepName;

    /** identifier field */
    private String stepDescription;

    /** identifier field */
    private Clob stepNotesClob;

    /** identifier field */
    private BigDecimal statusId;

    /** identifier field */
    private String statusName;

    /** identifier field */
    private String statusDescription;

    /** identifier field */
    private BigDecimal transitionId;

    /** identifier field */
    private String transitionVerb;

    /** identifier field */
    private String transitionDescription;

    /** identifier field */
    private BigDecimal priorityId;

    /** identifier field */
    private String priorityName;

    /** identifier field */
    private String priorityDescription;

    /** identifier field */
    private Clob commentsClob;

    /** identifier field */
    private BigDecimal createdById;

    /** identifier field */
    private String createdByFullName;

    /** identifier field */
    private Date createdDatetime;

    /** identifier field */
    private Date crc;

    /** identifier field */
    private String recordStatus;

    public PnEnvelopeVersionView() {
    }

    public PnEnvelopeVersionView(BigDecimal envelopeId, BigDecimal versionId, BigDecimal workflowId, BigDecimal stepId, String stepName, String stepDescription, Clob stepNotesClob, BigDecimal statusId, String statusName, String statusDescription, BigDecimal transitionId, String transitionVerb, String transitionDescription, BigDecimal priorityId, String priorityName, String priorityDescription, Clob commentsClob, BigDecimal createdById, String createdByFullName, Date createdDatetime, Date crc, String recordStatus) {
       this.envelopeId = envelopeId;
       this.versionId = versionId;
       this.workflowId = workflowId;
       this.stepId = stepId;
       this.stepName = stepName;
       this.stepDescription = stepDescription;
       this.stepNotesClob = stepNotesClob;
       this.statusId = statusId;
       this.statusName = statusName;
       this.statusDescription = statusDescription;
       this.transitionId = transitionId;
       this.transitionVerb = transitionVerb;
       this.transitionDescription = transitionDescription;
       this.priorityId = priorityId;
       this.priorityName = priorityName;
       this.priorityDescription = priorityDescription;
       this.commentsClob = commentsClob;
       this.createdById = createdById;
       this.createdByFullName = createdByFullName;
       this.createdDatetime = createdDatetime;
       this.crc = crc;
       this.recordStatus = recordStatus;
    }
    
    @Column(name="ENVELOPE_ID", nullable=false, length=20)
    public BigDecimal getEnvelopeId() {
        return this.envelopeId;
    }
    
    public void setEnvelopeId(BigDecimal envelopeId) {
        this.envelopeId = envelopeId;
    }

    @Column(name="VERSION_ID", nullable=false, length=20)
    public BigDecimal getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(BigDecimal versionId) {
        this.versionId = versionId;
    }

    @Column(name="WORKFLOW_ID", nullable=false, length=20)
    public BigDecimal getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(BigDecimal workflowId) {
        this.workflowId = workflowId;
    }

    @Column(name="STEP_ID", nullable=false, length=20)
    public BigDecimal getStepId() {
        return this.stepId;
    }
    
    public void setStepId(BigDecimal stepId) {
        this.stepId = stepId;
    }

    @Column(name="STEP_NAME", nullable=false, length=80)
    public String getStepName() {
        return this.stepName;
    }
    
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }
    
    @Column(name="STEP_DESCRIPTION", nullable=false, length=500)
    public String getStepDescription() {
        return this.stepDescription;
    }
    
    public void setStepDescription(String stepDescription) {
        this.stepDescription = stepDescription;
    }

    @Column(name="STEP_NOTES_CLOB", nullable=false, length=4000)
    public Clob getStepNotesClob() {
        return this.stepNotesClob;
    }
    
    public void setStepNotesClob(Clob stepNotesClob) {
        this.stepNotesClob = stepNotesClob;
    }

    @Column(name="STATUS_ID", nullable=false, length=20)
    public BigDecimal getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(BigDecimal statusId) {
        this.statusId = statusId;
    }
    
    @Column(name="STATUS_NAME", nullable=false, length=80)
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    
    @Column(name="STATUS_DESCRIPTION", nullable=false, length=500)
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }

    
    @Column(name="TRANSITION_ID", nullable=false, length=20)
    public BigDecimal getTransitionId() {
        return this.transitionId;
    }
    
    public void setTransitionId(BigDecimal transitionId) {
        this.transitionId = transitionId;
    }

    
    @Column(name="TRANSITION_VERB", nullable=false, length=80)
    public String getTransitionVerb() {
        return this.transitionVerb;
    }
    
    public void setTransitionVerb(String transitionVerb) {
        this.transitionVerb = transitionVerb;
    }

    
    @Column(name="TRANSITION_DESCRIPTION", nullable=false, length=500)
    public String getTransitionDescription() {
        return this.transitionDescription;
    }
    
    public void setTransitionDescription(String transitionDescription) {
        this.transitionDescription = transitionDescription;
    }

    
    @Column(name="PRIORITY_ID", nullable=false, length=20)
    public BigDecimal getPriorityId() {
        return this.priorityId;
    }
    
    public void setPriorityId(BigDecimal priorityId) {
        this.priorityId = priorityId;
    }

    
    @Column(name="PRIORITY_NAME", nullable=false, length=80)
    public String getPriorityName() {
        return this.priorityName;
    }
    
    public void setPriorityName(String priorityName) {
        this.priorityName = priorityName;
    }

    
    @Column(name="PRIORITY_DESCRIPTION", nullable=false, length=80)
    public String getPriorityDescription() {
        return this.priorityDescription;
    }
    
    public void setPriorityDescription(String priorityDescription) {
        this.priorityDescription = priorityDescription;
    }

    
    @Column(name="COMMENTS_CLOB", nullable=false, length=4000)
    public Clob getCommentsClob() {
        return this.commentsClob;
    }
    
    public void setCommentsClob(Clob commentsClob) {
        this.commentsClob = commentsClob;
    }
    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public BigDecimal getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(BigDecimal createdById) {
        this.createdById = createdById;
    }
    
    @Column(name="CREATED_BY_FULL_NAME", nullable=false, length=240)
    public String getCreatedByFullName() {
        return this.createdByFullName;
    }
    
    public void setCreatedByFullName(String createdByFullName) {
        this.createdByFullName = createdByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("envelopeId", getEnvelopeId())
            .append("versionId", getVersionId())
            .append("workflowId", getWorkflowId())
            .append("stepId", getStepId())
            .append("stepName", getStepName())
            .append("stepDescription", getStepDescription())
            .append("stepNotesClob", getStepNotesClob())
            .append("statusId", getStatusId())
            .append("statusName", getStatusName())
            .append("statusDescription", getStatusDescription())
            .append("transitionId", getTransitionId())
            .append("transitionVerb", getTransitionVerb())
            .append("transitionDescription", getTransitionDescription())
            .append("priorityId", getPriorityId())
            .append("priorityName", getPriorityName())
            .append("priorityDescription", getPriorityDescription())
            .append("commentsClob", getCommentsClob())
            .append("createdById", getCreatedById())
            .append("createdByFullName", getCreatedByFullName())
            .append("createdDatetime", getCreatedDatetime())
            .append("crc", getCrc())
            .append("recordStatus", getRecordStatus())
            .toString();
    }

}


