/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnJavaErrorLog generated by hbm2java
 */
@Embeddable
public class PnJavaErrorLogPK implements java.io.Serializable {

	/** identifier field */
	private Date errorDate;

	/** identifier field */
	private Integer personId;

	/** identifier field */
	private String errorName;

	/** identifier field */
	private String errorMessage;

	/** identifier field */
	private String stackTrace;

	/** identifier field */
	private String severity;

	public PnJavaErrorLogPK() {
	}

	public PnJavaErrorLogPK(Date errorDate, Integer personId, String errorName, String errorMessage, String stackTrace,
			String severity) {
		this.errorDate = errorDate;
		this.personId = personId;
		this.errorName = errorName;
		this.errorMessage = errorMessage;
		this.stackTrace = stackTrace;
		this.severity = severity;
	}

	@Column(name = "ERROR_DATE", nullable = false, length = 7)
	public Date getErrorDate() {
		return this.errorDate;
	}

	public void setErrorDate(Date errorDate) {
		this.errorDate = errorDate;
	}

	@Column(name = "PERSON_ID", nullable = false, length = 20)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "ERROR_NAME", nullable = false)
	public String getErrorName() {
		return this.errorName;
	}

	public void setErrorName(String errorName) {
		this.errorName = errorName;
	}

	@Column(name = "ERROR_MESSAGE", nullable = false, length = 4000)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "STACK_TRACE", nullable = false, length = 4000)
	public String getStackTrace() {
		return this.stackTrace;
	}

	public void setStackTrace(String stackTrace) {
		this.stackTrace = stackTrace;
	}

	@Column(name = "SEVERITY", nullable = false, length = 80)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	public String toString() {
		return new ToStringBuilder(this).append("errorDate", getErrorDate()).append("personId", getPersonId()).append(
				"errorName", getErrorName()).append("errorMessage", getErrorMessage()).append("stackTrace",
				getStackTrace()).append("severity", getSeverity()).toString();
	}

}
