/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLedger generated by hbm2java
 */
@Entity
@Table(name = "PN_LEDGER")
public class PnLedger implements java.io.Serializable {

	/** identifier field */
	private Integer ledgerId;

	/** persistent field */
	private Integer responsiblePartyId;

	/** persistent field */
	private Date dueSinceDatetime;

	/** persistent field */
	private Integer unitPriceValue;

	/** persistent field */
	private Integer quantityAmount;

	/** persistent field */
	private Integer quantityUomId;

	/** persistent field */
	private Integer categoryId;

	/** persistent field */
	private String partDetailsPartNumber;

	/** nullable persistent field */
	private String partDetailsPartDescription;

	/** persistent field */
	private Integer groupTypeId;

	/** nullable persistent field */
	private String groupValue;

	/** nullable persistent field */
	private String groupDescription;

	/** nullable persistent field */
	private String recordStatus;

	/** nullable persistent field */
	private Date invoiceDate;

	/** persistent field */
	private Integer invoiceStatusId;

	/** persistent field */
	private PnInvoice pnInvoice;

	private PnBill pnBill;

	private PnPaymentInformation pnPaymentInformation;

	public PnLedger() {
	}

	public PnLedger(Integer ledgerId, Integer responsiblePartyId, Date dueSinceDatetime, Integer unitPriceValue,
			Integer quantityAmount, Integer quantityUomId, Integer categoryId, String partDetailsPartNumber,
			Integer groupTypeId, Integer invoiceStatusId) {
		this.ledgerId = ledgerId;
		this.responsiblePartyId = responsiblePartyId;
		this.dueSinceDatetime = dueSinceDatetime;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.groupTypeId = groupTypeId;
		this.invoiceStatusId = invoiceStatusId;
	}

	public PnLedger(Integer ledgerId, Integer responsiblePartyId, Date dueSinceDatetime, Integer unitPriceValue,
			Integer quantityAmount, Integer quantityUomId, Integer categoryId, String partDetailsPartNumber,
			String partDetailsPartDescription, Integer groupTypeId, String groupValue, String groupDescription,
			String recordStatus, Date invoiceDate, Integer invoiceStatusId, PnInvoice pnInvoice, PnBill pnBill,
			PnPaymentInformation pnPaymentInformation) {
		this.ledgerId = ledgerId;
		this.responsiblePartyId = responsiblePartyId;
		this.dueSinceDatetime = dueSinceDatetime;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.partDetailsPartDescription = partDetailsPartDescription;
		this.groupTypeId = groupTypeId;
		this.groupValue = groupValue;
		this.groupDescription = groupDescription;
		this.recordStatus = recordStatus;
		this.invoiceDate = invoiceDate;
		this.invoiceStatusId = invoiceStatusId;
		this.pnInvoice = pnInvoice;
		this.pnBill = pnBill;
		this.pnPaymentInformation = pnPaymentInformation;
	}

	/** minimal constructor */
	public PnLedger(Integer ledgerId, Integer responsiblePartyId, Date dueSinceDatetime, Integer unitPriceValue,
			Integer quantityAmount, Integer quantityUomId, Integer categoryId, String partDetailsPartNumber,
			Integer groupTypeId, Integer invoiceStatusId, net.project.hibernate.model.PnInvoice pnInvoice,
			net.project.hibernate.model.PnBill pnBill,
			net.project.hibernate.model.PnPaymentInformation pnPaymentInformation) {
		this.ledgerId = ledgerId;
		this.responsiblePartyId = responsiblePartyId;
		this.dueSinceDatetime = dueSinceDatetime;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.groupTypeId = groupTypeId;
		this.invoiceStatusId = invoiceStatusId;
		this.pnInvoice = pnInvoice;
		this.pnBill = pnBill;
		this.pnPaymentInformation = pnPaymentInformation;
	}

	@Id
	@Column(name = "LEDGER_ID", nullable = false)
	public Integer getLedgerId() {
		return this.ledgerId;
	}

	public void setLedgerId(Integer ledgerId) {
		this.ledgerId = ledgerId;
	}

	@Column(name = "RESPONSIBLE_PARTY_ID", nullable = false, length = 20)
	public Integer getResponsiblePartyId() {
		return this.responsiblePartyId;
	}

	public void setResponsiblePartyId(Integer responsiblePartyId) {
		this.responsiblePartyId = responsiblePartyId;
	}

	@Column(name = "DUE_SINCE_DATETIME", nullable = false, length = 7)
	public Date getDueSinceDatetime() {
		return this.dueSinceDatetime;
	}

	public void setDueSinceDatetime(Date dueSinceDatetime) {
		this.dueSinceDatetime = dueSinceDatetime;
	}

	@Column(name = "UNIT_PRICE_VALUE", nullable = false, length = 22)
	public Integer getUnitPriceValue() {
		return this.unitPriceValue;
	}

	public void setUnitPriceValue(Integer unitPriceValue) {
		this.unitPriceValue = unitPriceValue;
	}

	@Column(name = "QUANTITY_AMOUNT", nullable = false, length = 22)
	public Integer getQuantityAmount() {
		return this.quantityAmount;
	}

	public void setQuantityAmount(Integer quantityAmount) {
		this.quantityAmount = quantityAmount;
	}

	@Column(name = "QUANTITY_UOM_ID", nullable = false, length = 22)
	public Integer getQuantityUomId() {
		return this.quantityUomId;
	}

	public void setQuantityUomId(Integer quantityUomId) {
		this.quantityUomId = quantityUomId;
	}

	@Column(name = "CATEGORY_ID", nullable = false, length = 22)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "PART_DETAILS_PART_NUMBER", nullable = false, length = 500)
	public String getPartDetailsPartNumber() {
		return this.partDetailsPartNumber;
	}

	public void setPartDetailsPartNumber(String partDetailsPartNumber) {
		this.partDetailsPartNumber = partDetailsPartNumber;
	}

	@Column(name = "PART_DETAILS_PART_DESCRIPTION", length = 1000)
	public String getPartDetailsPartDescription() {
		return this.partDetailsPartDescription;
	}

	public void setPartDetailsPartDescription(String partDetailsPartDescription) {
		this.partDetailsPartDescription = partDetailsPartDescription;
	}

	@Column(name = "GROUP_TYPE_ID", nullable = false, length = 20)
	public Integer getGroupTypeId() {
		return this.groupTypeId;
	}

	public void setGroupTypeId(Integer groupTypeId) {
		this.groupTypeId = groupTypeId;
	}

	@Column(name = "GROUP_VALUE", length = 500)
	public String getGroupValue() {
		return this.groupValue;
	}

	public void setGroupValue(String groupValue) {
		this.groupValue = groupValue;
	}

	@Column(name = "GROUP_DESCRIPTION", length = 1000)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "INVOICE_DATE", length = 7)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "INVOICE_STATUS_ID", nullable = false, length = 20)
	public Integer getInvoiceStatusId() {
		return this.invoiceStatusId;
	}

	public void setInvoiceStatusId(Integer invoiceStatusId) {
		this.invoiceStatusId = invoiceStatusId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnInvoice.class)
	@JoinColumn(name = "INVOICE_ID")
	public PnInvoice getPnInvoice() {
		return this.pnInvoice;
	}

	public void setPnInvoice(PnInvoice pnInvoice) {
		this.pnInvoice = pnInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnBill.class)
	@JoinColumn(name = "BILL_ID")
	public PnBill getPnBill() {
		return this.pnBill;
	}

	public void setPnBill(PnBill pnBill) {
		this.pnBill = pnBill;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPaymentInformation.class)
	@JoinColumn(name = "ORIGINATING_PAYMENT_ID")
	public PnPaymentInformation getPnPaymentInformation() {
		return this.pnPaymentInformation;
	}

	public void setPnPaymentInformation(PnPaymentInformation pnPaymentInformation) {
		this.pnPaymentInformation = pnPaymentInformation;
	}

	public String toString() {
		return new ToStringBuilder(this).append("ledgerId", getLedgerId()).toString();
	}

}
