/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnNotificationLog generated by hbm2java
 */
@Entity
@Table(name = "PN_NOTIFICATION_LOG")
public class PnNotificationLog implements Serializable {

	private Integer notificationLogId;

	private Integer numberOfAttempts;

	private Integer deliveryStatus;

	private Date deliveryTime;

	private String deliveryNotes;

	private String recordStatus;

	private PnNotification pnNotification;

	public PnNotificationLog() {
	}

	public PnNotificationLog(Integer notificationLogId, Integer deliveryStatus,
			net.project.hibernate.model.PnNotification pnNotification) {
		this.notificationLogId = notificationLogId;
		this.deliveryStatus = deliveryStatus;
		this.pnNotification = pnNotification;
	}

	public PnNotificationLog(Integer notificationLogId, Integer numberOfAttempts, Integer deliveryStatus,
			Date deliveryTime, String deliveryNotes, String recordStatus, PnNotification pnNotification) {
		this.notificationLogId = notificationLogId;
		this.numberOfAttempts = numberOfAttempts;
		this.deliveryStatus = deliveryStatus;
		this.deliveryTime = deliveryTime;
		this.deliveryNotes = deliveryNotes;
		this.recordStatus = recordStatus;
		this.pnNotification = pnNotification;
	}

	@Id
	@Column(name = "NOTIFICATION_LOG_ID", nullable = false)
	public Integer getNotificationLogId() {
		return this.notificationLogId;
	}

	public void setNotificationLogId(Integer notificationLogId) {
		this.notificationLogId = notificationLogId;
	}

	@Column(name = "NUMBER_OF_ATTEMPTS", length = 22)
	public Integer getNumberOfAttempts() {
		return this.numberOfAttempts;
	}

	public void setNumberOfAttempts(Integer numberOfAttempts) {
		this.numberOfAttempts = numberOfAttempts;
	}

	@Column(name = "DELIVERY_STATUS", nullable = false, length = 20)
	public Integer getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(Integer deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	@Column(name = "DELIVERY_TIME", length = 7)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "DELIVERY_NOTES")
	public String getDeliveryNotes() {
		return this.deliveryNotes;
	}

	public void setDeliveryNotes(String deliveryNotes) {
		this.deliveryNotes = deliveryNotes;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnNotification.class)
	//@JoinColumn(name = "NOTIFICATION_ID")
	@Transient
	public PnNotification getPnNotification() {
		return this.pnNotification;
	}

	public void setPnNotification(PnNotification pnNotification) {
		this.pnNotification = pnNotification;
	}

	public String toString() {
		return new ToStringBuilder(this).append("notificationLogId", getNotificationLogId()).toString();
	}

}
