/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnObjectLink generated by hbm2java
 */
@Entity
@Table(name = "PN_OBJECT_LINK")
public class PnObjectLink implements Serializable {

	private PnObjectLinkPK comp_id;

	private PnObject pnObjectByToObjectId;

	private PnObject pnObjectByFromObjectId;

	public PnObjectLink() {
	}

	public PnObjectLink(PnObjectLinkPK comp_id) {
		this.comp_id = comp_id;
	}
	
	public PnObjectLink(Integer fromObjectId, Integer toObjectId, Integer context) {
		this.comp_id = new PnObjectLinkPK(fromObjectId, toObjectId, context);
	}

	public PnObjectLink(PnObjectLinkPK comp_id, PnObject pnObjectByToObjectId, PnObject pnObjectByFromObjectId) {
		this.comp_id = comp_id;
		this.pnObjectByToObjectId = pnObjectByToObjectId;
		this.pnObjectByFromObjectId = pnObjectByFromObjectId;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fromObjectId", column = @Column(name = "FROM_OBJECT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "toObjectId", column = @Column(name = "TO_OBJECT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "context", column = @Column(name = "CONTEXT", nullable = false, length = 4)) })
	public PnObjectLinkPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnObjectLinkPK comp_id) {
		this.comp_id = comp_id;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	@JoinColumn(name = "TO_OBJECT_ID", insertable = false, updatable = false)
	public PnObject getPnObjectByToObjectId() {
		return this.pnObjectByToObjectId;
	}

	public void setPnObjectByToObjectId(PnObject pnObjectByToObjectId) {
		this.pnObjectByToObjectId = pnObjectByToObjectId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	@JoinColumn(name = "FROM_OBJECT_ID", insertable = false, updatable = false)
	public PnObject getPnObjectByFromObjectId() {
		return this.pnObjectByFromObjectId;
	}

	public void setPnObjectByFromObjectId(PnObject pnObjectByFromObjectId) {
		this.pnObjectByFromObjectId = pnObjectByFromObjectId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnObjectLink))
			return false;
		PnObjectLink castOther = (PnObjectLink) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
