/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnWorkflowHasObjectType generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW_HAS_OBJECT_TYPE")
public class PnWorkflowHasObjectType implements Serializable {

	private PnWorkflowHasObjectTypePK comp_id;

	private String subTypeId;

	private PnWorkflow pnWorkflow;

	private PnObjectType pnObjectType;

	public PnWorkflowHasObjectType() {
	}

	public PnWorkflowHasObjectType(PnWorkflowHasObjectTypePK comp_id) {
		this.comp_id = comp_id;
	}

	public PnWorkflowHasObjectType(PnWorkflowHasObjectTypePK comp_id, String subTypeId, PnWorkflow pnWorkflow,
			PnObjectType pnObjectType) {
		this.comp_id = comp_id;
		this.subTypeId = subTypeId;
		this.pnWorkflow = pnWorkflow;
		this.pnObjectType = pnObjectType;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "workflowId", column = @Column(name = "WORKFLOW_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "objectType", column = @Column(name = "OBJECT_TYPE", nullable = false, length = 80)) })
	public PnWorkflowHasObjectTypePK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnWorkflowHasObjectTypePK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "SUB_TYPE_ID", length = 80)
	public String getSubTypeId() {
		return this.subTypeId;
	}

	public void setSubTypeId(String subTypeId) {
		this.subTypeId = subTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflow.class)
	@JoinColumn(name = "WORKFLOW_ID", insertable = false, updatable = false)
	public PnWorkflow getPnWorkflow() {
		return this.pnWorkflow;
	}

	public void setPnWorkflow(PnWorkflow pnWorkflow) {
		this.pnWorkflow = pnWorkflow;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObjectType.class)
	@JoinColumn(name = "OBJECT_TYPE", insertable = false, updatable = false)
	public PnObjectType getPnObjectType() {
		return this.pnObjectType;
	}

	public void setPnObjectType(PnObjectType pnObjectType) {
		this.pnObjectType = pnObjectType;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWorkflowHasObjectType))
			return false;
		PnWorkflowHasObjectType castOther = (PnWorkflowHasObjectType) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
