/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnZipcodeFeedLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_ZIPCODE_FEED_LOOKUP")
public class PnZipcodeFeedLookup implements Serializable {

	private String zipcode;

	private String feed;

	private Set pnSpaceHasWeathers = new HashSet(0);

	public PnZipcodeFeedLookup() {
	}

	public PnZipcodeFeedLookup(String zipcode, String feed) {
		this.zipcode = zipcode;
		this.feed = feed;
	}

	public PnZipcodeFeedLookup(String zipcode, String feed, Set pnSpaceHasWeathers) {
		this.zipcode = zipcode;
		this.feed = feed;
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
	}

	@Id
	@Column(name = "ZIPCODE", nullable = false)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "FEED", nullable = false, length = 120)
	public String getFeed() {
		return this.feed;
	}

	public void setFeed(String feed) {
		this.feed = feed;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnZipcodeFeedLookup", targetEntity = PnSpaceHasWeather.class)
	@Transient
	public Set getPnSpaceHasWeathers() {
		return this.pnSpaceHasWeathers;
	}

	public void setPnSpaceHasWeathers(Set pnSpaceHasWeathers) {
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
	}

	public String toString() {
		return new ToStringBuilder(this).append("zipcode", getZipcode()).toString();
	}

}
