/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.31 at 09:10:26 PM CEST 
//


package net.project.form.soa.binding;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.project.form.soa.binding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RowSpan_QNAME = new QName("", "row_span");
    private final static QName _ElementLabel_QNAME = new QName("", "element_label");
    private final static QName _Abbreviation_QNAME = new QName("", "abbreviation");
    private final static QName _FieldGroup_QNAME = new QName("", "field_group");
    private final static QName _UseDefault_QNAME = new QName("", "use_default");
    private final static QName _WrapMode_QNAME = new QName("", "wrap_mode");
    private final static QName _IsCalculateTotal_QNAME = new QName("", "is_calculate_total");    
    private final static QName _ClassTypeId_QNAME = new QName("", "class_type_id");
    private final static QName _Datatype_QNAME = new QName("", "datatype");
    private final static QName _IsListField_QNAME = new QName("", "is_list_field");
    private final static QName _DefaultValue_QNAME = new QName("", "default_value");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _IsSubfield_QNAME = new QName("", "is_subfield");
    private final static QName _IsShared_QNAME = new QName("", "is_shared");
    private final static QName _SortAscending_QNAME = new QName("", "sort_ascending");
    private final static QName _MaxColumn_QNAME = new QName("", "max_column");
    private final static QName _ColumnName_QNAME = new QName("", "column_name");
    private final static QName _MaxRow_QNAME = new QName("", "max_row");
    private final static QName _ElementId_QNAME = new QName("", "element_id");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _ColumnId_QNAME = new QName("", "column_id");
    private final static QName _Multiselect_QNAME = new QName("", "multiselect");
    private final static QName _SortOrder_QNAME = new QName("", "sort_order");
    private final static QName _Required_QNAME = new QName("", "required");
    private final static QName _DataColumnScale_QNAME = new QName("", "data_column_scale");
    private final static QName _MinValue_QNAME = new QName("", "min_value");
    private final static QName _ColumnNum_QNAME = new QName("", "column_num");
    private final static QName _JoinOperator_QNAME = new QName("", "join_operator");
    private final static QName _OwnerSpaceId_QNAME = new QName("", "owner_space_id");
    private final static QName _MaxValue_QNAME = new QName("", "max_value");
    private final static QName _FieldOrder_QNAME = new QName("", "field_order");
    private final static QName _FilterValue_QNAME = new QName("", "filter_value");
    private final static QName _DataColumnSize_QNAME = new QName("", "data_column_size");
    private final static QName _Label_QNAME = new QName("", "label");
    private final static QName _ElementName_QNAME = new QName("", "element_name");
    private final static QName _RowNum_QNAME = new QName("", "row_num");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _IsDefault_QNAME = new QName("", "is_default");
    private final static QName _ElementDisplayClassId_QNAME = new QName("", "element_display_class_id");
    private final static QName _IsAdmin_QNAME = new QName("", "is_admin");
    private final static QName _FieldCount_QNAME = new QName("", "field_count");
    private final static QName _FieldWidth_QNAME = new QName("", "field_width");
    private final static QName _IsSortField_QNAME = new QName("", "is_sort_field");
    private final static QName _ColumnSpan_QNAME = new QName("", "column_span");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.project.form.soa.binding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormList }
     * 
     */
    public FormList createFormList() {
        return new FormList();
    }

    /**
     * Create an instance of {@link FormField }
     * 
     */
    public FormField createFormField() {
        return new FormField();
    }

    /**
     * Create an instance of {@link FormFields }
     * 
     */
    public FormFields createFormFields() {
        return new FormFields();
    }

    /**
     * Create an instance of {@link DomainValue }
     * 
     */
    public DomainValue createDomainValue() {
        return new DomainValue();
    }
    
    /**
     * Create an instance of {@link FieldPropertyValue }
     * 
     */
    public FieldPropertyValue createFieldPropertyValue() {
        return new FieldPropertyValue();
    }
    
    /**
     * Create an instance of {@link FieldPropertyValues }
     * 
     */
    public FieldPropertyValues createFieldPropertyValues() {
        return new FieldPropertyValues();
    }    
    

    /**
     * Create an instance of {@link ListField }
     * 
     */
    public ListField createListField() {
        return new ListField();
    }

    /**
     * Create an instance of {@link DomainValues }
     * 
     */
    public DomainValues createDomainValues() {
        return new DomainValues();
    }

    /**
     * Create an instance of {@link FieldFilter }
     * 
     */
    public FieldFilter createFieldFilter() {
        return new FieldFilter();
    }

    /**
     * Create an instance of {@link FormLists }
     * 
     */
    public FormLists createFormLists() {
        return new FormLists();
    }

    /**
     * Create an instance of {@link FormDef }
     * 
     */
    public FormDef createFormDef() {
        return new FormDef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_span")
    public JAXBElement<Integer> createRowSpan(Integer value) {
        return new JAXBElement<Integer>(_RowSpan_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element_label")
    public JAXBElement<String> createElementLabel(String value) {
        return new JAXBElement<String>(_ElementLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "abbreviation")
    public JAXBElement<String> createAbbreviation(String value) {
        return new JAXBElement<String>(_Abbreviation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field_group")
    public JAXBElement<String> createFieldGroup(String value) {
        return new JAXBElement<String>(_FieldGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "use_default")
    public JAXBElement<Boolean> createUseDefault(Boolean value) {
        return new JAXBElement<Boolean>(_UseDefault_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wrap_mode")
    public JAXBElement<Boolean> createWrapMode(Boolean value) {
        return new JAXBElement<Boolean>(_WrapMode_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_calculate_total")
    public JAXBElement<Boolean> createIsCalculateTotal(Boolean value) {
        return new JAXBElement<Boolean>(_IsCalculateTotal_QNAME, Boolean.class, null, value);
    }
    
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "class_type_id")
    public JAXBElement<BigInteger> createClassTypeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ClassTypeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datatype")
    public JAXBElement<String> createDatatype(String value) {
        return new JAXBElement<String>(_Datatype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_list_field")
    public JAXBElement<Boolean> createIsListField(Boolean value) {
        return new JAXBElement<Boolean>(_IsListField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "default_value")
    public JAXBElement<String> createDefaultValue(String value) {
        return new JAXBElement<String>(_DefaultValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_subfield")
    public JAXBElement<Boolean> createIsSubfield(Boolean value) {
        return new JAXBElement<Boolean>(_IsSubfield_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_shared")
    public JAXBElement<Boolean> createIsShared(Boolean value) {
        return new JAXBElement<Boolean>(_IsShared_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sort_ascending")
    public JAXBElement<Boolean> createSortAscending(Boolean value) {
        return new JAXBElement<Boolean>(_SortAscending_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "max_column")
    public JAXBElement<Integer> createMaxColumn(Integer value) {
        return new JAXBElement<Integer>(_MaxColumn_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_name")
    public JAXBElement<String> createColumnName(String value) {
        return new JAXBElement<String>(_ColumnName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "max_row")
    public JAXBElement<Integer> createMaxRow(Integer value) {
        return new JAXBElement<Integer>(_MaxRow_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element_id")
    public JAXBElement<BigInteger> createElementId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ElementId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_id")
    public JAXBElement<Integer> createColumnId(Integer value) {
        return new JAXBElement<Integer>(_ColumnId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "multiselect")
    public JAXBElement<Boolean> createMultiselect(Boolean value) {
        return new JAXBElement<Boolean>(_Multiselect_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sort_order")
    public JAXBElement<Integer> createSortOrder(Integer value) {
        return new JAXBElement<Integer>(_SortOrder_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "required")
    public JAXBElement<Boolean> createRequired(Boolean value) {
        return new JAXBElement<Boolean>(_Required_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data_column_scale")
    public JAXBElement<String> createDataColumnScale(String value) {
        return new JAXBElement<String>(_DataColumnScale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "min_value")
    public JAXBElement<String> createMinValue(String value) {
        return new JAXBElement<String>(_MinValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_num")
    public JAXBElement<Integer> createColumnNum(Integer value) {
        return new JAXBElement<Integer>(_ColumnNum_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "join_operator")
    public JAXBElement<String> createJoinOperator(String value) {
        return new JAXBElement<String>(_JoinOperator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "owner_space_id")
    public JAXBElement<BigInteger> createOwnerSpaceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_OwnerSpaceId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "max_value")
    public JAXBElement<String> createMaxValue(String value) {
        return new JAXBElement<String>(_MaxValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field_order")
    public JAXBElement<Integer> createFieldOrder(Integer value) {
        return new JAXBElement<Integer>(_FieldOrder_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filter_value")
    public JAXBElement<String> createFilterValue(String value) {
        return new JAXBElement<String>(_FilterValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data_column_size")
    public JAXBElement<String> createDataColumnSize(String value) {
        return new JAXBElement<String>(_DataColumnSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element_name")
    public JAXBElement<String> createElementName(String value) {
        return new JAXBElement<String>(_ElementName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_num")
    public JAXBElement<Integer> createRowNum(Integer value) {
        return new JAXBElement<Integer>(_RowNum_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_default")
    public JAXBElement<Boolean> createIsDefault(Boolean value) {
        return new JAXBElement<Boolean>(_IsDefault_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element_display_class_id")
    public JAXBElement<BigInteger> createElementDisplayClassId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ElementDisplayClassId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_admin")
    public JAXBElement<Boolean> createIsAdmin(Boolean value) {
        return new JAXBElement<Boolean>(_IsAdmin_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field_count")
    public JAXBElement<Integer> createFieldCount(Integer value) {
        return new JAXBElement<Integer>(_FieldCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field_width")
    public JAXBElement<String> createFieldWidth(String value) {
        return new JAXBElement<String>(_FieldWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_sort_field")
    public JAXBElement<Boolean> createIsSortField(Boolean value) {
        return new JAXBElement<Boolean>(_IsSortField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_span")
    public JAXBElement<Integer> createColumnSpan(Integer value) {
        return new JAXBElement<Integer>(_ColumnSpan_QNAME, Integer.class, null, value);
    }

}
