PROMPT Connecting &1 
conn &1/&2@&3;

PROMPT creating synonym for PN_METHODOLOGY_MODULES table.
CREATE OR REPLACE SYNONYM PN_METHODOLOGY_MODULES FOR PNET.PN_METHODOLOGY_MODULES;

PROMPT creating synonym for PN_BUSINESS_HAS_VIEW table.
CREATE OR REPLACE SYNONYM PN_BUSINESS_HAS_VIEW FOR PNET.PN_BUSINESS_HAS_VIEW;

PROMPT creating synonym for PN_CHARGE_CODE table.
CREATE OR REPLACE SYNONYM PN_CHARGE_CODE FOR PNET.PN_CHARGE_CODE;

PROMPT creating synonym for PN_OBJECT_HAS_CHARGE_CODE table.
CREATE OR REPLACE SYNONYM PN_OBJECT_HAS_CHARGE_CODE FOR PNET.PN_OBJECT_HAS_CHARGE_CODE;