/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnCcTransactionPaymentPK generated by hbm2java
 */
@Embeddable
public class PnCcTransactionPaymentPK  implements java.io.Serializable {

    /** identifier field */
    private Integer transactionId;

    /** identifier field */
    private Integer paymentId;

    public PnCcTransactionPaymentPK() {
    }

    public PnCcTransactionPaymentPK(Integer transactionId, Integer paymentId) {
       this.transactionId = transactionId;
       this.paymentId = paymentId;
    }
   


    @Column(name="TRANSACTION_ID", nullable=false, length=20)
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }


    @Column(name="PAYMENT_ID", nullable=false, length=20)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("transactionId", getTransactionId())
            .append("paymentId", getPaymentId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnCcTransactionPaymentPK) ) return false;
        PnCcTransactionPaymentPK castOther = (PnCcTransactionPaymentPK) other;
        return new EqualsBuilder()
            .append(this.getTransactionId(), castOther.getTransactionId())
            .append(this.getPaymentId(), castOther.getPaymentId())
            .isEquals();
    }

 	public int hashCode() {
        return new HashCodeBuilder()
            .append(getTransactionId())
            .append(getPaymentId())
            .toHashCode();
    }
}


