/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.sql.Clob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassField generated by hbm2java
 */
@Entity
@Table(name = "PN_CLASS_FIELD")
public class PnClassField implements java.io.Serializable {

	/** identifier field */
	private PnClassFieldPK comp_id;

	/** nullable persistent field */
	private String dataColumnName;

	/** nullable persistent field */
	private String dataTableName;

	/** nullable persistent field */
	private String fieldLabel;

	/** nullable persistent field */
	private Integer dataColumnSize;

	/** persistent field */
	private int dataColumnExists;

	/** persistent field */
	private int rowNum;

	/** persistent field */
	private int rowSpan;

	/** persistent field */
	private int columnNum;

	/** nullable persistent field */
	private Integer columnSpan;

	/** nullable persistent field */
	private Integer columnId;

	/** persistent field */
	private int useDefault;

	/** nullable persistent field */
	private String fieldGroup;

	/** persistent field */
	private int hasDomain;

	/** nullable persistent field */
	private String maxValue;

	/** nullable persistent field */
	private String minValue;

	/** nullable persistent field */
	private String defaultValue;

	/** persistent field */
	private int isMultiSelect;

	/** nullable persistent field */
	private Integer sourceFieldId;

	/** nullable persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	/** nullable persistent field */
	private Integer dataColumnScale;

	/** nullable persistent field */
	private Clob instructionsClob;

	/** nullable persistent field */
	private Integer isValueRequired;

	/** nullable persistent field */
	private PnObject pnObject;

	/** nullable persistent field */
	private PnClass pnClass;

	/** persistent field */
	private PnElement pnElement;

	/** persistent field */
	private PnClassDomain pnClassDomain;

	public PnClassField() {
	}

	public PnClassField(PnClassFieldPK comp_id, int dataColumnExists, int rowNum, int rowSpan, int columnNum,
			int useDefault, int hasDomain, int isMultiSelect, String recordStatus) {
		this.comp_id = comp_id;
		this.dataColumnExists = dataColumnExists;
		this.rowNum = rowNum;
		this.rowSpan = rowSpan;
		this.columnNum = columnNum;
		this.useDefault = useDefault;
		this.hasDomain = hasDomain;
		this.isMultiSelect = isMultiSelect;
		this.recordStatus = recordStatus;
	}

	public PnClassField(PnClassFieldPK comp_id, String dataColumnName, String dataTableName, String fieldLabel,
			Integer dataColumnSize, int dataColumnExists, int rowNum, int rowSpan, int columnNum, Integer columnSpan,
			Integer columnId, int useDefault, String fieldGroup, int hasDomain, String maxValue, String minValue,
			String defaultValue, int isMultiSelect, Integer sourceFieldId, Date crc, String recordStatus,
			Integer dataColumnScale, Clob instructionsClob, Integer isValueRequired, PnObject pnObject,
			PnClass pnClass, PnElement pnElement, PnClassDomain pnClassDomain) {
		this.comp_id = comp_id;
		this.dataColumnName = dataColumnName;
		this.dataTableName = dataTableName;
		this.fieldLabel = fieldLabel;
		this.dataColumnSize = dataColumnSize;
		this.dataColumnExists = dataColumnExists;
		this.rowNum = rowNum;
		this.rowSpan = rowSpan;
		this.columnNum = columnNum;
		this.columnSpan = columnSpan;
		this.columnId = columnId;
		this.useDefault = useDefault;
		this.fieldGroup = fieldGroup;
		this.hasDomain = hasDomain;
		this.maxValue = maxValue;
		this.minValue = minValue;
		this.defaultValue = defaultValue;
		this.isMultiSelect = isMultiSelect;
		this.sourceFieldId = sourceFieldId;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.dataColumnScale = dataColumnScale;
		this.instructionsClob = instructionsClob;
		this.isValueRequired = isValueRequired;
		this.pnObject = pnObject;
		this.pnClass = pnClass;
		this.pnElement = pnElement;
		this.pnClassDomain = pnClassDomain;
	}

	/** minimal constructor */
	public PnClassField(net.project.hibernate.model.PnClassFieldPK comp_id, int dataColumnExists, int rowNum,
			int rowSpan, int columnNum, int useDefault, int hasDomain, int isMultiSelect, String recordStatus,
			net.project.hibernate.model.PnElement pnElement, net.project.hibernate.model.PnClassDomain pnClassDomain) {
		this.comp_id = comp_id;
		this.dataColumnExists = dataColumnExists;
		this.rowNum = rowNum;
		this.rowSpan = rowSpan;
		this.columnNum = columnNum;
		this.useDefault = useDefault;
		this.hasDomain = hasDomain;
		this.isMultiSelect = isMultiSelect;
		this.recordStatus = recordStatus;
		this.pnElement = pnElement;
		this.pnClassDomain = pnClassDomain;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "spaceId", column = @Column(name = "SPACE_ID", nullable = false, length = 22)),
			@AttributeOverride(name = "classId", column = @Column(name = "CLASS_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "fieldId", column = @Column(name = "FIELD_ID", nullable = false, length = 20)) })
	public PnClassFieldPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnClassFieldPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "DATA_COLUMN_NAME", length = 80)
	public String getDataColumnName() {
		return this.dataColumnName;
	}

	public void setDataColumnName(String dataColumnName) {
		this.dataColumnName = dataColumnName;
	}

	@Column(name = "DATA_TABLE_NAME", length = 80)
	public String getDataTableName() {
		return this.dataTableName;
	}

	public void setDataTableName(String dataTableName) {
		this.dataTableName = dataTableName;
	}

	@Column(name = "FIELD_LABEL", length = 80)
	public String getFieldLabel() {
		return this.fieldLabel;
	}

	public void setFieldLabel(String fieldLabel) {
		this.fieldLabel = fieldLabel;
	}

	@Column(name = "DATA_COLUMN_SIZE", length = 8)
	public Integer getDataColumnSize() {
		return this.dataColumnSize;
	}

	public void setDataColumnSize(Integer dataColumnSize) {
		this.dataColumnSize = dataColumnSize;
	}

	@Column(name = "DATA_COLUMN_EXISTS", nullable = false, length = 1)
	public int getDataColumnExists() {
		return this.dataColumnExists;
	}

	public void setDataColumnExists(int dataColumnExists) {
		this.dataColumnExists = dataColumnExists;
	}

	@Column(name = "ROW_NUM", nullable = false, length = 8)
	public int getRowNum() {
		return this.rowNum;
	}

	public void setRowNum(int rowNum) {
		this.rowNum = rowNum;
	}

	@Column(name = "ROW_SPAN", nullable = false, length = 8)
	public int getRowSpan() {
		return this.rowSpan;
	}

	public void setRowSpan(int rowSpan) {
		this.rowSpan = rowSpan;
	}

	@Column(name = "COLUMN_NUM", nullable = false, length = 8)
	public int getColumnNum() {
		return this.columnNum;
	}

	public void setColumnNum(int columnNum) {
		this.columnNum = columnNum;
	}

	@Column(name = "COLUMN_SPAN", length = 8)
	public Integer getColumnSpan() {
		return this.columnSpan;
	}

	public void setColumnSpan(Integer columnSpan) {
		this.columnSpan = columnSpan;
	}

	@Column(name = "COLUMN_ID", length = 20)
	public Integer getColumnId() {
		return this.columnId;
	}

	public void setColumnId(Integer columnId) {
		this.columnId = columnId;
	}

	@Column(name = "USE_DEFAULT", nullable = false, length = 1)
	public int getUseDefault() {
		return this.useDefault;
	}

	public void setUseDefault(int useDefault) {
		this.useDefault = useDefault;
	}

	@Column(name = "FIELD_GROUP", length = 80)
	public String getFieldGroup() {
		return this.fieldGroup;
	}

	public void setFieldGroup(String fieldGroup) {
		this.fieldGroup = fieldGroup;
	}

	@Column(name = "HAS_DOMAIN", nullable = false, length = 1)
	public int getHasDomain() {
		return this.hasDomain;
	}

	public void setHasDomain(int hasDomain) {
		this.hasDomain = hasDomain;
	}

	@Column(name = "MAX_VALUE", length = 80)
	public String getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(String maxValue) {
		this.maxValue = maxValue;
	}

	@Column(name = "MIN_VALUE", length = 80)
	public String getMinValue() {
		return this.minValue;
	}

	public void setMinValue(String minValue) {
		this.minValue = minValue;
	}

	@Column(name = "DEFAULT_VALUE", length = 80)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "IS_MULTI_SELECT", nullable = false, length = 1)
	public int getIsMultiSelect() {
		return this.isMultiSelect;
	}

	public void setIsMultiSelect(int isMultiSelect) {
		this.isMultiSelect = isMultiSelect;
	}

	@Column(name = "SOURCE_FIELD_ID", length = 20)
	public Integer getSourceFieldId() {
		return this.sourceFieldId;
	}

	public void setSourceFieldId(Integer sourceFieldId) {
		this.sourceFieldId = sourceFieldId;
	}

	@Column(name = "CRC", length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "DATA_COLUMN_SCALE", length = 8)
	public Integer getDataColumnScale() {
		return this.dataColumnScale;
	}

	public void setDataColumnScale(Integer dataColumnScale) {
		this.dataColumnScale = dataColumnScale;
	}

	@Column(name = "INSTRUCTIONS_CLOB", length = 4000)
	public Clob getInstructionsClob() {
		return this.instructionsClob;
	}

	public void setInstructionsClob(Clob instructionsClob) {
		this.instructionsClob = instructionsClob;
	}

	@Column(name = "IS_VALUE_REQUIRED", length = 1)
	public Integer getIsValueRequired() {
		return this.isValueRequired;
	}

	public void setIsValueRequired(Integer isValueRequired) {
		this.isValueRequired = isValueRequired;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name = "FIELD_ID", insertable = false, updatable = false)
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnClass.class)
	@JoinColumn(name = "CLASS_ID", insertable = false, updatable = false)
	public PnClass getPnClass() {
		return this.pnClass;
	}

	public void setPnClass(PnClass pnClass) {
		this.pnClass = pnClass;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnElement.class)
	@JoinColumn(name = "ELEMENT_ID")
	public PnElement getPnElement() {
		return this.pnElement;
	}

	public void setPnElement(PnElement pnElement) {
		this.pnElement = pnElement;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnClassDomain.class)
	@JoinColumn(name = "DOMAIN_ID")
	public PnClassDomain getPnClassDomain() {
		return this.pnClassDomain;
	}

	public void setPnClassDomain(PnClassDomain pnClassDomain) {
		this.pnClassDomain = pnClassDomain;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnClassField))
			return false;
		PnClassField castOther = (PnClassField) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}
}
