/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDeliveryAddress generated by hbm2java
 */
@Entity
@Table(name="PN_DELIVERY_ADDRESS"
)
public class PnDeliveryAddress  implements java.io.Serializable {

    /** identifier field */
    private Integer addressId;

    /** persistent field */
    private Integer addressGroupId;

    /** persistent field */
    private String address;

    /** persistent field */
    private PnNotificationDeliveryType pnNotificationDeliveryType;

    public PnDeliveryAddress() {
    }

	
    public PnDeliveryAddress(Integer addressId, Integer addressGroupId, String address) {
        this.addressId = addressId;
        this.addressGroupId = addressGroupId;
        this.address = address;
    }
    
    public PnDeliveryAddress(Integer addressId, Integer addressGroupId, String address, PnNotificationDeliveryType pnNotificationDeliveryType) {
       this.addressId = addressId;
       this.addressGroupId = addressGroupId;
       this.address = address;
       this.pnNotificationDeliveryType = pnNotificationDeliveryType;
    }
   
    @Id 
    @Column(name="ADDRESS_ID", nullable=false)
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="ADDRESS_GROUP_ID", nullable=false, length=20)
    public Integer getAddressGroupId() {
        return this.addressGroupId;
    }
    
    public void setAddressGroupId(Integer addressGroupId) {
        this.addressGroupId = addressGroupId;
    }

    
    @Column(name="ADDRESS", nullable=false, length=80)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnNotificationDeliveryType.class)
    @JoinColumn(name="DELIVERY_TYPE_ID")
    public PnNotificationDeliveryType getPnNotificationDeliveryType() {
        return this.pnNotificationDeliveryType;
    }
    
    public void setPnNotificationDeliveryType(PnNotificationDeliveryType pnNotificationDeliveryType) {
        this.pnNotificationDeliveryType = pnNotificationDeliveryType;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("addressId", getAddressId())
            .toString();
    }

}


