/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocProviderType generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_PROVIDER_TYPE")
public class PnDocProviderType implements java.io.Serializable {

	/** identifier field */
	private Integer docProviderTypeId;

	/** nullable persistent field */
	private String docProviderTypeName;

	/** nullable persistent field */
	private String docProviderTypeDesc;

	private Set pnDocProviders = new HashSet(0);

	public PnDocProviderType() {
	}

	public PnDocProviderType(Integer docProviderTypeId) {
		this.docProviderTypeId = docProviderTypeId;
	}

	public PnDocProviderType(Integer docProviderTypeId, String docProviderTypeName, String docProviderTypeDesc,
			Set pnDocProviders) {
		this.docProviderTypeId = docProviderTypeId;
		this.docProviderTypeName = docProviderTypeName;
		this.docProviderTypeDesc = docProviderTypeDesc;
		this.pnDocProviders = pnDocProviders;
	}

	/** minimal constructor */
	public PnDocProviderType(Integer docProviderTypeId, Set pnDocProviders) {
		this.docProviderTypeId = docProviderTypeId;
		this.pnDocProviders = pnDocProviders;
	}

	@Id
	@Column(name = "DOC_PROVIDER_TYPE_ID", nullable = false)
	public Integer getDocProviderTypeId() {
		return this.docProviderTypeId;
	}

	public void setDocProviderTypeId(Integer docProviderTypeId) {
		this.docProviderTypeId = docProviderTypeId;
	}

	@Column(name = "DOC_PROVIDER_TYPE_NAME", length = 80)
	public String getDocProviderTypeName() {
		return this.docProviderTypeName;
	}

	public void setDocProviderTypeName(String docProviderTypeName) {
		this.docProviderTypeName = docProviderTypeName;
	}

	@Column(name = "DOC_PROVIDER_TYPE_DESC", length = 500)
	public String getDocProviderTypeDesc() {
		return this.docProviderTypeDesc;
	}

	public void setDocProviderTypeDesc(String docProviderTypeDesc) {
		this.docProviderTypeDesc = docProviderTypeDesc;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocProviderType", targetEntity = PnDocProvider.class)
	@Transient
	public Set getPnDocProviders() {
		return this.pnDocProviders;
	}

	public void setPnDocProviders(Set pnDocProviders) {
		this.pnDocProviders = pnDocProviders;
	}

	public String toString() {
		return new ToStringBuilder(this).append("docProviderTypeId", getDocProviderTypeId()).toString();
	}

}
