/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocConfigurationHasDocPK generated by hbm2java
 */
@Embeddable
public class PnDocConfigurationHasDocPK  implements java.io.Serializable {

    /** identifier field */
    private Integer docConfigurationId;

    /** identifier field */
    private Integer docVersionId;

    public PnDocConfigurationHasDocPK() {
    }

    public PnDocConfigurationHasDocPK(Integer docConfigurationId, Integer docVersionId) {
       this.docConfigurationId = docConfigurationId;
       this.docVersionId = docVersionId;
    }
   


    @Column(name="DOC_CONFIGURATION_ID", nullable=false, length=20)
    public Integer getDocConfigurationId() {
        return this.docConfigurationId;
    }
    
    public void setDocConfigurationId(Integer docConfigurationId) {
        this.docConfigurationId = docConfigurationId;
    }


    @Column(name="DOC_VERSION_ID", nullable=false, length=20)
    public Integer getDocVersionId() {
        return this.docVersionId;
    }
    
    public void setDocVersionId(Integer docVersionId) {
        this.docVersionId = docVersionId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docConfigurationId", getDocConfigurationId())
            .append("docVersionId", getDocVersionId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocConfigurationHasDocPK) ) return false;
        PnDocConfigurationHasDocPK castOther = (PnDocConfigurationHasDocPK) other;
        return new EqualsBuilder()
            .append(this.getDocConfigurationId(), castOther.getDocConfigurationId())
            .append(this.getDocVersionId(), castOther.getDocVersionId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getDocConfigurationId())
            .append(getDocVersionId())
            .toHashCode();
    }
}


