/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocContentRenditionPK generated by hbm2java
 */
@Embeddable
public class PnDocContentRenditionPK  implements java.io.Serializable {

    /** identifier field */
    private Integer docRenditionId;

    /** identifier field */
    private Integer docContentId;

    public PnDocContentRenditionPK() {
    }

    public PnDocContentRenditionPK(Integer docRenditionId, Integer docContentId) {
       this.docRenditionId = docRenditionId;
       this.docContentId = docContentId;
    }
   


    @Column(name="DOC_RENDITION_ID", nullable=false, length=20)
    public Integer getDocRenditionId() {
        return this.docRenditionId;
    }
    
    public void setDocRenditionId(Integer docRenditionId) {
        this.docRenditionId = docRenditionId;
    }


    @Column(name="DOC_CONTENT_ID", nullable=false, length=20)
    public Integer getDocContentId() {
        return this.docContentId;
    }
    
    public void setDocContentId(Integer docContentId) {
        this.docContentId = docContentId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docRenditionId", getDocRenditionId())
            .append("docContentId", getDocContentId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocContentRenditionPK) ) return false;
        PnDocContentRenditionPK castOther = (PnDocContentRenditionPK) other;
        return new EqualsBuilder()
            .append(this.getDocRenditionId(), castOther.getDocRenditionId())
            .append(this.getDocContentId(), castOther.getDocContentId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getDocRenditionId())
            .append(getDocContentId())
            .toHashCode();
    }
}


