/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnGlobalDomainPK generated by hbm2java
 */
@Embeddable
public class PnGlobalDomainPK  implements java.io.Serializable {

    /** identifier field */
    private String tableName;

    /** identifier field */
    private String columnName;

    /** identifier field */
    private Integer code;

    public PnGlobalDomainPK() {
    }

    public PnGlobalDomainPK(String tableName, String columnName, Integer code) {
       this.tableName = tableName;
       this.columnName = columnName;
       this.code = code;
    }

    @Column(name="TABLE_NAME", nullable=false, length=80)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    @Column(name="COLUMN_NAME", nullable=false, length=80)
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    @Column(name="CODE", nullable=false, length=8)
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("tableName", getTableName())
            .append("columnName", getColumnName())
            .append("code", getCode())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnGlobalDomainPK) ) return false;
        PnGlobalDomainPK castOther = (PnGlobalDomainPK) other;
        return new EqualsBuilder()
            .append(this.getTableName(), castOther.getTableName())
            .append(this.getColumnName(), castOther.getColumnName())
            .append(this.getCode(), castOther.getCode())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTableName())
            .append(getColumnName())
            .append(getCode())
            .toHashCode();
    }
}


