/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnGroupView generated by hbm2java
 */
@Entity
@Table(name = "PN_GROUP_VIEW")
public class PnGroupView implements java.io.Serializable {

	/** identifier field */
	private BigDecimal groupId;

	/** identifier field */
	private String groupName;

	/** identifier field */
	private String groupDesc;

	/** identifier field */
	private Integer isPrincipal;

	/** identifier field */
	private Integer isSystemGroup;

	/** identifier field */
	private String recordStatus;

	/** identifier field */
	private BigDecimal groupTypeId;

	/** identifier field */
	private BigDecimal memberCount;

	/** identifier field */
	private BigDecimal principalOwnerId;

	/** identifier field */
	private String principalOwnerDisplayName;

	public PnGroupView() {
	}

	public PnGroupView(BigDecimal groupId, String groupName, String groupDesc, int isPrincipal, int isSystemGroup,
			String recordStatus, BigDecimal groupTypeId, BigDecimal memberCount, BigDecimal principalOwnerId,
			String principalOwnerDisplayName) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupDesc = groupDesc;
		this.isPrincipal = isPrincipal;
		this.isSystemGroup = isSystemGroup;
		this.recordStatus = recordStatus;
		this.groupTypeId = groupTypeId;
		this.memberCount = memberCount;
		this.principalOwnerId = principalOwnerId;
		this.principalOwnerDisplayName = principalOwnerDisplayName;
	}

	@Column(name = "GROUP_ID", nullable = false, length = 20)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GROUP_NAME", nullable = false, length = 80)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GROUP_DESC", nullable = false)
	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	@Column(name = "IS_PRINCIPAL", nullable = false, length = 1)
	public int getIsPrincipal() {
		return this.isPrincipal;
	}

	public void setIsPrincipal(int isPrincipal) {
		this.isPrincipal = isPrincipal;
	}

	@Column(name = "IS_SYSTEM_GROUP", nullable = false, length = 1)
	public int getIsSystemGroup() {
		return this.isSystemGroup;
	}

	public void setIsSystemGroup(int isSystemGroup) {
		this.isSystemGroup = isSystemGroup;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "GROUP_TYPE_ID", nullable = false, length = 20)
	public BigDecimal getGroupTypeId() {
		return this.groupTypeId;
	}

	public void setGroupTypeId(BigDecimal groupTypeId) {
		this.groupTypeId = groupTypeId;
	}

	@Column(name = "MEMBER_COUNT", nullable = false, length = 22)
	public BigDecimal getMemberCount() {
		return this.memberCount;
	}

	public void setMemberCount(BigDecimal memberCount) {
		this.memberCount = memberCount;
	}

	@Column(name = "PRINCIPAL_OWNER_ID", nullable = false, length = 20)
	public BigDecimal getPrincipalOwnerId() {
		return this.principalOwnerId;
	}

	public void setPrincipalOwnerId(BigDecimal principalOwnerId) {
		this.principalOwnerId = principalOwnerId;
	}

	@Column(name = "PRINCIPAL_OWNER_DISPLAY_NAME", nullable = false, length = 240)
	public String getPrincipalOwnerDisplayName() {
		return this.principalOwnerDisplayName;
	}

	public void setPrincipalOwnerDisplayName(String principalOwnerDisplayName) {
		this.principalOwnerDisplayName = principalOwnerDisplayName;
	}

	public String toString() {
		return new ToStringBuilder(this).append("groupId", getGroupId()).append("groupName", getGroupName()).append(
				"groupDesc", getGroupDesc()).append("isPrincipal", getIsPrincipal()).append("isSystemGroup",
				getIsSystemGroup()).append("recordStatus", getRecordStatus()).append("groupTypeId", getGroupTypeId())
				.append("memberCount", getMemberCount()).append("principalOwnerId", getPrincipalOwnerId()).append(
						"principalOwnerDisplayName", getPrincipalOwnerDisplayName()).toString();
	}

}
