/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnObjectHasDocContainer generated by hbm2java
 */
@Embeddable
public class PnObjectHasDocContainerPK implements Serializable {

	private Integer objectId;

	private Integer containerId;

	public PnObjectHasDocContainerPK() {
	}

	public PnObjectHasDocContainerPK(Integer objectId, Integer containerId) {
		this.objectId = objectId;
		this.containerId = containerId;
	}

	@Column(name = "OBJECT_ID", nullable = false, length = 20)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "CONTAINER_ID", nullable = false, length = 20)
	public Integer getContainerId() {
		return this.containerId;
	}

	public void setContainerId(Integer containerId) {
		this.containerId = containerId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("objectId", getObjectId()).append("containerId", getContainerId())
				.toString();
	}

}
