/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPersonPicksSpam generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_PICKS_SPAM")
public class PnPersonPicksSpam implements Serializable {

	private PnPersonPicksSpamPK comp_id;

	private PnPersonSurvey pnPersonSurvey;

	private PnSpamLookup pnSpamLookup;

	public PnPersonPicksSpam() {
	}

	public PnPersonPicksSpam(PnPersonPicksSpamPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnPersonPicksSpam(PnPersonPicksSpamPK comp_id, PnPersonSurvey pnPersonSurvey, PnSpamLookup pnSpamLookup) {
		this.comp_id = comp_id;
		this.pnPersonSurvey = pnPersonSurvey;
		this.pnSpamLookup = pnSpamLookup;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "spamTypeCode", column = @Column(name = "SPAM_TYPE_CODE", nullable = false, length = 4)) })
	public PnPersonPicksSpamPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnPersonPicksSpamPK comp_id) {
		this.comp_id = comp_id;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPersonSurvey.class)
	//@JoinColumn(name = "PERSON_ID", insertable = false, updatable = false)
	@Transient
	public PnPersonSurvey getPnPersonSurvey() {
		return this.pnPersonSurvey;
	}

	public void setPnPersonSurvey(PnPersonSurvey pnPersonSurvey) {
		this.pnPersonSurvey = pnPersonSurvey;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnSpamLookup.class)
	//@JoinColumn(name = "SPAM_TYPE_CODE", insertable = false, updatable = false)
	@Transient
	public PnSpamLookup getPnSpamLookup() {
		return this.pnSpamLookup;
	}

	public void setPnSpamLookup(PnSpamLookup pnSpamLookup) {
		this.pnSpamLookup = pnSpamLookup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnPersonPicksSpam))
			return false;
		PnPersonPicksSpam castOther = (PnPersonPicksSpam) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
