/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPropCategoryHasPropertyPK generated by hbm2java
 */
@Embeddable
public class PnPropCategoryHasPropertyPK implements Serializable {


     private Integer categoryId;
     private String property;

    public PnPropCategoryHasPropertyPK() {
    }

    public PnPropCategoryHasPropertyPK(Integer categoryId, String property) {
       this.categoryId = categoryId;
       this.property = property;
    }
   


    @Column(name="CATEGORY_ID", nullable=false, length=20)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name="PROPERTY", nullable=false, length=500)
    public String getProperty() {
        return this.property;
    }
    
    public void setProperty(String property) {
        this.property = property;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("categoryId", getCategoryId())
            .append("property", getProperty())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPropCategoryHasPropertyPK) ) return false;
        PnPropCategoryHasPropertyPK castOther = (PnPropCategoryHasPropertyPK) other;
        return new EqualsBuilder()
            .append(this.getCategoryId(), castOther.getCategoryId())
            .append(this.getProperty(), castOther.getProperty())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCategoryId())
            .append(getProperty())
            .toHashCode();
    }

}
