/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnReportSequence generated by hbm2java
 */
@Entity
@Table(name="PN_REPORT_SEQUENCE"
)
public class PnReportSequence implements Serializable {


     private String reportType;
     private Integer sequence;

    public PnReportSequence() {
    }

	
    public PnReportSequence(String reportType) {
        this.reportType = reportType;
    }

    public PnReportSequence(String reportType, Integer sequence) {
       this.reportType = reportType;
       this.sequence = sequence;
    }
   
     @Id 
    @Column(name="REPORT_TYPE", nullable=false)
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    @Column(name="SEQUENCE", length=22)
    public Integer getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("reportType", getReportType())
            .toString();
    }

}
