/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnSpaceHasSpacePK generated by hbm2java
 */
@Embeddable
public class PnSpaceHasSpacePK implements Serializable {


     private Integer parentSpaceId;
     private Integer childSpaceId;

    public PnSpaceHasSpacePK() {
    }

    public PnSpaceHasSpacePK(Integer parentSpaceId, Integer childSpaceId) {
       this.parentSpaceId = parentSpaceId;
       this.childSpaceId = childSpaceId;
    }
   


    @Column(name="PARENT_SPACE_ID", nullable=false, length=20)
    public Integer getParentSpaceId() {
        return this.parentSpaceId;
    }
    
    public void setParentSpaceId(Integer parentSpaceId) {
        this.parentSpaceId = parentSpaceId;
    }


    @Column(name="CHILD_SPACE_ID", nullable=false, length=20)
    public Integer getChildSpaceId() {
        return this.childSpaceId;
    }
    
    public void setChildSpaceId(Integer childSpaceId) {
        this.childSpaceId = childSpaceId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("parentSpaceId", getParentSpaceId())
            .append("childSpaceId", getChildSpaceId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSpaceHasSpacePK) ) return false;
        PnSpaceHasSpacePK castOther = (PnSpaceHasSpacePK) other;
        return new EqualsBuilder()
            .append(this.getParentSpaceId(), castOther.getParentSpaceId())
            .append(this.getChildSpaceId(), castOther.getChildSpaceId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getParentSpaceId())
            .append(getChildSpaceId())
            .toHashCode();
    }

}
