/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnSpamLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_SPAM_LOOKUP")
public class PnSpamLookup implements Serializable {

	private Integer spamTypeCode;

	private String spamType;

	private Set pnPersonPicksSpams = new HashSet(0);

	public PnSpamLookup() {
	}

	public PnSpamLookup(Integer spamTypeCode, String spamType) {
		this.spamTypeCode = spamTypeCode;
		this.spamType = spamType;
	}

	public PnSpamLookup(Integer spamTypeCode, String spamType, Set pnPersonPicksSpams) {
		this.spamTypeCode = spamTypeCode;
		this.spamType = spamType;
		this.pnPersonPicksSpams = pnPersonPicksSpams;
	}

	@Id
	@Column(name = "SPAM_TYPE_CODE", nullable = false)
	public Integer getSpamTypeCode() {
		return this.spamTypeCode;
	}

	public void setSpamTypeCode(Integer spamTypeCode) {
		this.spamTypeCode = spamTypeCode;
	}

	@Column(name = "SPAM_TYPE", nullable = false, length = 40)
	public String getSpamType() {
		return this.spamType;
	}

	public void setSpamType(String spamType) {
		this.spamType = spamType;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSpamLookup", targetEntity = PnPersonPicksSpam.class)
	@Transient
	public Set getPnPersonPicksSpams() {
		return this.pnPersonPicksSpams;
	}

	public void setPnPersonPicksSpams(Set pnPersonPicksSpams) {
		this.pnPersonPicksSpams = pnPersonPicksSpams;
	}

	public String toString() {
		return new ToStringBuilder(this).append("spamTypeCode", getSpamTypeCode()).toString();
	}

}
