/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnTmpHeartbeatMetric generated by hbm2java
 */
@Entity
@Table(name="PN_TMP_HEARTBEAT_METRICS"
)
public class PnTmpHeartbeatMetric implements Serializable {


     private Integer collectionId;
     private String moduleName;
     private Integer total;
     private Integer totalOpen;
     private Integer totalClosed;
     private Integer totalClosedLastWeek;

    public PnTmpHeartbeatMetric() {
    }

	
    public PnTmpHeartbeatMetric(Integer collectionId) {
        this.collectionId = collectionId;
    }
    public PnTmpHeartbeatMetric(Integer collectionId, String moduleName, Integer total, Integer totalOpen, Integer totalClosed, Integer totalClosedLastWeek) {
       this.collectionId = collectionId;
       this.moduleName = moduleName;
       this.total = total;
       this.totalOpen = totalOpen;
       this.totalClosed = totalClosed;
       this.totalClosedLastWeek = totalClosedLastWeek;
    }
   
     @Id 

    
    @Column(name="COLLECTION_ID", nullable=false)
    public Integer getCollectionId() {
        return this.collectionId;
    }
    
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    
    @Column(name="MODULE_NAME", length=80)
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    
    @Column(name="TOTAL", length=9)
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }

    
    @Column(name="TOTAL_OPEN", length=9)
    public Integer getTotalOpen() {
        return this.totalOpen;
    }
    
    public void setTotalOpen(Integer totalOpen) {
        this.totalOpen = totalOpen;
    }

    
    @Column(name="TOTAL_CLOSED", length=9)
    public Integer getTotalClosed() {
        return this.totalClosed;
    }
    
    public void setTotalClosed(Integer totalClosed) {
        this.totalClosed = totalClosed;
    }

    
    @Column(name="TOTAL_CLOSED_LAST_WEEK", length=9)
    public Integer getTotalClosedLastWeek() {
        return this.totalClosedLastWeek;
    }
    
    public void setTotalClosedLastWeek(Integer totalClosedLastWeek) {
        this.totalClosedLastWeek = totalClosedLastWeek;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("collectionId", getCollectionId())
            .toString();
    }

}
