/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnUserView generated by hbm2java
 */
@Entity
@Table(name="PN_USER_VIEW"
)
public class PnUserView implements Serializable {


     private BigDecimal userId;
     private String displayName;
     private String username;
     private String userStatus;
     private BigDecimal domainId;
     private Date lastLogin;
    private Integer isLogin;
     private BigDecimal lastBrandId;
     private BigDecimal hasLicense;

    public PnUserView() {
    }

    public PnUserView(BigDecimal userId, String displayName, String username, String userStatus, BigDecimal domainId, Date lastLogin, Integer isLogin, BigDecimal lastBrandId, BigDecimal hasLicense) {
       this.userId = userId;
       this.displayName = displayName;
       this.username = username;
       this.userStatus = userStatus;
       this.domainId = domainId;
       this.lastLogin = lastLogin;
       this.isLogin = isLogin;
       this.lastBrandId = lastBrandId;
       this.hasLicense = hasLicense;
    }
   

    @Id
    @Column(name="USER_ID", nullable=false, length=20)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="DISPLAY_NAME", nullable=false, length=240)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    
    @Column(name="USERNAME", nullable=false, length=32)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="USER_STATUS", nullable=false, length=80)
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    
    @Column(name="DOMAIN_ID", nullable=false, length=20)
    public BigDecimal getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(BigDecimal domainId) {
        this.domainId = domainId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_LOGIN", nullable=false, length=7)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    @Column(name="IS_LOGIN", nullable=false, length=1)
    public int getIsLogin() {
        return this.isLogin;
    }
    
    public void setIsLogin(int isLogin) {
        this.isLogin = isLogin;
    }

    
    @Column(name="LAST_BRAND_ID", nullable=false, length=20)
    public BigDecimal getLastBrandId() {
        return this.lastBrandId;
    }
    
    public void setLastBrandId(BigDecimal lastBrandId) {
        this.lastBrandId = lastBrandId;
    }

    
    @Column(name="HAS_LICENSE", nullable=false, length=22)
    public BigDecimal getHasLicense() {
        return this.hasLicense;
    }
    
    public void setHasLicense(BigDecimal hasLicense) {
        this.hasLicense = hasLicense;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("userId", getUserId())
            .append("displayName", getDisplayName())
            .append("username", getUsername())
            .append("userStatus", getUserStatus())
            .append("domainId", getDomainId())
            .append("lastLogin", getLastLogin())
            .append("isLogin", getIsLogin())
            .append("lastBrandId", getLastBrandId())
            .append("hasLicense", getHasLicense())
            .toString();
    }

}
