/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnViewDefaultSettingPK generated by hbm2java
 */
@Embeddable
public class PnViewDefaultSettingPK implements Serializable {


     private Integer contextId;
     private Integer scenarioId;

    public PnViewDefaultSettingPK() {
    }

    public PnViewDefaultSettingPK(Integer contextId, Integer scenarioId) {
       this.contextId = contextId;
       this.scenarioId = scenarioId;
    }
   


    @Column(name="CONTEXT_ID", nullable=false, length=20)
    public Integer getContextId() {
        return this.contextId;
    }
    
    public void setContextId(Integer contextId) {
        this.contextId = contextId;
    }


    @Column(name="SCENARIO_ID", nullable=false, length=20)
    public Integer getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(Integer scenarioId) {
        this.scenarioId = scenarioId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("contextId", getContextId())
            .append("scenarioId", getScenarioId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnViewDefaultSettingPK) ) return false;
        PnViewDefaultSettingPK castOther = (PnViewDefaultSettingPK) other;
        return new EqualsBuilder()
            .append(this.getContextId(), castOther.getContextId())
            .append(this.getScenarioId(), castOther.getScenarioId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getContextId())
            .append(getScenarioId())
            .toHashCode();
    }

}
