/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * PnWikiHistory generated by hbm2java
 */
@Entity
@Table(name = "PN_WIKI_HISTORY")
public class PnWikiHistory implements Serializable {

	private Integer wikiHistoryId;

	private String content;

	private Date editDate;

	private String commentText;

	private PnPerson editedBy;

	private PnWikiPage wikiPageId;

	private Integer versionNo;
	
	private String editType;

	public PnWikiHistory() {
	}

	public PnWikiHistory(java.lang.Integer wikiHistoryId) {
		this.setWikiHistoryId(wikiHistoryId);
	}

	public PnWikiHistory(String content, Date editDate) {
		this.content = content;
		this.editDate = editDate;
	}

	public PnWikiHistory(java.lang.Integer wikiHistoryId,
			java.lang.String content, //FIX Uros: java.lang.String commentText,
			net.project.hibernate.model.PnPerson editedBy, java.util.Date editDate,
			net.project.hibernate.model.PnWikiPage wikiPageId) {

		this.setWikiHistoryId(wikiHistoryId);
		this.setContent(content);
		//		this.setCommentText(commentText);
		this.setEditedBy(editedBy);
		this.setEditDate(editDate);
		this.setWikiPageId(wikiPageId);
	}

	public PnWikiHistory(String content, Date editDate, String commentText, PnPerson editedBy, PnWikiPage wikiPageId) {
		this.content = content;
		this.editDate = editDate;
		this.commentText = commentText;
		this.editedBy = editedBy;
		this.wikiPageId = wikiPageId;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "WIKI_HISTORY_ID", nullable = false)
	public Integer getWikiHistoryId() {
		return this.wikiHistoryId;
	}

	public void setWikiHistoryId(Integer wikiHistoryId) {
		this.wikiHistoryId = wikiHistoryId;
	}

	@Column(name = "CONTENT", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "EDIT_DATE", nullable = false)
	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	@Column(name = "COMMENT_TEXT")
	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "EDITED_BY")
	public PnPerson getEditedBy() {
		return this.editedBy;
	}

	public void setEditedBy(PnPerson editedBy) {
		this.editedBy = editedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWikiPage.class)
	@JoinColumn(name = "WIKI_PAGE_ID")
	public PnWikiPage getWikiPageId() {
		return this.wikiPageId;
	}

	public void setWikiPageId(PnWikiPage wikiPageId) {
		this.wikiPageId = wikiPageId;
	}

	/**
	 * @return the versionNo
	 */
	@Transient
	public java.lang.Integer getVersionNo() {
		return versionNo;
	}

	/**
	 * @param versionNo the versionNo to set
	 */
	public void setVersionNo(java.lang.Integer versionNo) {
		this.versionNo = versionNo;
	}

	/**
	 * @return editType
	 */
	@Column(name = "EDIT_TYPE")
	public String getEdityType() {
		return editType;
	}

	/**
	 * @param editType the editType to set
	 */
	public void setEdityType(String editType) {
		this.editType = editType;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof net.project.hibernate.model.PnWikiHistory))
			return false;
		else {
			net.project.hibernate.model.PnWikiHistory pnWikiHistory = (net.project.hibernate.model.PnWikiHistory) obj;
			if (null == this.getWikiHistoryId() || null == pnWikiHistory.getWikiHistoryId())
				return false;
			else
				return (this.getWikiHistoryId().equals(pnWikiHistory.getWikiHistoryId()));
		}
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(getWikiHistoryId()).toHashCode();
	}

	public String toString() {
		return new ToStringBuilder(this).append("wikiHistoryId", getWikiHistoryId()).toString();
	}

}
