/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflowStep generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW_STEP")
public class PnWorkflowStep implements Serializable {

	private PnWorkflowStepPK comp_id;

	private String stepName;

	private String stepDescription;

	private int isFinalStep;

	private int isInitialStep;

	private Integer entryStatusId;

	private Integer createdById;

	private Date createdDatetime;

	private Integer modifiedById;

	private Date modifiedDatetime;

	private Date crc;

	private String recordStatus;

	private Clob notesClob;

	private Integer stepSequence;

	private PnWorkflow pnWorkflow;

	private PnSubscription pnSubscription;

	private Set pnWorkflowStepHasGroups = new HashSet(0);

	private Set pnWorkflowTransitionsByEndStepIdAndWorkflowId = new HashSet(0);

	private Set pnWorkflowTransitionsByBeginStepIdAndWorkflowId = new HashSet(0);

	private Set pnEnvelopeVersions = new HashSet(0);

	public PnWorkflowStep() {
	}

	public PnWorkflowStep(PnWorkflowStepPK comp_id, int isFinalStep, int isInitialStep, Integer createdById,
			Date createdDatetime, Date crc, String recordStatus) {
		this.comp_id = comp_id;
		this.isFinalStep = isFinalStep;
		this.isInitialStep = isInitialStep;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnWorkflowStep(net.project.hibernate.model.PnWorkflowStepPK comp_id, int isFinalStep, int isInitialStep,
			Integer createdById, Date createdDatetime, Date crc, String recordStatus,
			net.project.hibernate.model.PnSubscription pnSubscription, Set pnWorkflowStepHasGroups,
			Set pnWorkflowTransitionsByEndStepIdAndWorkflowId, Set pnWorkflowTransitionsByBeginStepIdAndWorkflowId,
			Set pnEnvelopeVersions) {
		this.comp_id = comp_id;
		this.isFinalStep = isFinalStep;
		this.isInitialStep = isInitialStep;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnSubscription = pnSubscription;
		this.pnWorkflowStepHasGroups = pnWorkflowStepHasGroups;
		this.pnWorkflowTransitionsByEndStepIdAndWorkflowId = pnWorkflowTransitionsByEndStepIdAndWorkflowId;
		this.pnWorkflowTransitionsByBeginStepIdAndWorkflowId = pnWorkflowTransitionsByBeginStepIdAndWorkflowId;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	public PnWorkflowStep(PnWorkflowStepPK comp_id, String stepName, String stepDescription, int isFinalStep,
			int isInitialStep, Integer entryStatusId, Integer createdById, Date createdDatetime, Integer modifiedById,
			Date modifiedDatetime, Date crc, String recordStatus, Clob notesClob, Integer stepSequence,
			PnWorkflow pnWorkflow, PnSubscription pnSubscription, Set pnWorkflowStepHasGroups,
			Set pnWorkflowTransitionsByEndStepIdAndWorkflowId, Set pnWorkflowTransitionsByBeginStepIdAndWorkflowId,
			Set pnEnvelopeVersions) {
		this.comp_id = comp_id;
		this.stepName = stepName;
		this.stepDescription = stepDescription;
		this.isFinalStep = isFinalStep;
		this.isInitialStep = isInitialStep;
		this.entryStatusId = entryStatusId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.notesClob = notesClob;
		this.stepSequence = stepSequence;
		this.pnWorkflow = pnWorkflow;
		this.pnSubscription = pnSubscription;
		this.pnWorkflowStepHasGroups = pnWorkflowStepHasGroups;
		this.pnWorkflowTransitionsByEndStepIdAndWorkflowId = pnWorkflowTransitionsByEndStepIdAndWorkflowId;
		this.pnWorkflowTransitionsByBeginStepIdAndWorkflowId = pnWorkflowTransitionsByBeginStepIdAndWorkflowId;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "stepId", column = @Column(name = "STEP_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "workflowId", column = @Column(name = "WORKFLOW_ID", nullable = false, length = 20)) })
	public PnWorkflowStepPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnWorkflowStepPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "STEP_NAME", length = 80)
	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	@Column(name = "STEP_DESCRIPTION", length = 500)
	public String getStepDescription() {
		return this.stepDescription;
	}

	public void setStepDescription(String stepDescription) {
		this.stepDescription = stepDescription;
	}

	@Column(name = "IS_FINAL_STEP", nullable = false, length = 1)
	public int getIsFinalStep() {
		return this.isFinalStep;
	}

	public void setIsFinalStep(int isFinalStep) {
		this.isFinalStep = isFinalStep;
	}

	@Column(name = "IS_INITIAL_STEP", nullable = false, length = 1)
	public int getIsInitialStep() {
		return this.isInitialStep;
	}

	public void setIsInitialStep(int isInitialStep) {
		this.isInitialStep = isInitialStep;
	}

	@Column(name = "ENTRY_STATUS_ID", length = 20)
	public Integer getEntryStatusId() {
		return this.entryStatusId;
	}

	public void setEntryStatusId(Integer entryStatusId) {
		this.entryStatusId = entryStatusId;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "NOTES_CLOB", length = 4000)
	public Clob getNotesClob() {
		return this.notesClob;
	}

	public void setNotesClob(Clob notesClob) {
		this.notesClob = notesClob;
	}

	@Column(name = "STEP_SEQUENCE", length = 5)
	public Integer getStepSequence() {
		return this.stepSequence;
	}

	public void setStepSequence(Integer stepSequence) {
		this.stepSequence = stepSequence;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnWorkflow.class)
	@JoinColumn(name = "WORKFLOW_ID", insertable = false, updatable = false)
	public PnWorkflow getPnWorkflow() {
		return this.pnWorkflow;
	}

	public void setPnWorkflow(PnWorkflow pnWorkflow) {
		this.pnWorkflow = pnWorkflow;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnSubscription.class)
	//@JoinColumn(name = "SUBSCRIPTION_ID")
	@Transient
	public PnSubscription getPnSubscription() {
		return this.pnSubscription;
	}

	public void setPnSubscription(PnSubscription pnSubscription) {
		this.pnSubscription = pnSubscription;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowStep", targetEntity = PnWorkflowStepHasGroup.class)
	@Transient
	public Set getPnWorkflowStepHasGroups() {
		return this.pnWorkflowStepHasGroups;
	}

	public void setPnWorkflowStepHasGroups(Set pnWorkflowStepHasGroups) {
		this.pnWorkflowStepHasGroups = pnWorkflowStepHasGroups;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowStepByEndStepIdAndWorkflowId", targetEntity = PnWorkflowTransition.class)
	@Transient
	public Set getPnWorkflowTransitionsByEndStepIdAndWorkflowId() {
		return this.pnWorkflowTransitionsByEndStepIdAndWorkflowId;
	}

	public void setPnWorkflowTransitionsByEndStepIdAndWorkflowId(Set pnWorkflowTransitionsByEndStepIdAndWorkflowId) {
		this.pnWorkflowTransitionsByEndStepIdAndWorkflowId = pnWorkflowTransitionsByEndStepIdAndWorkflowId;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowStepByBeginStepIdAndWorkflowId", targetEntity = PnWorkflowTransition.class)
	@Transient
	public Set getPnWorkflowTransitionsByBeginStepIdAndWorkflowId() {
		return this.pnWorkflowTransitionsByBeginStepIdAndWorkflowId;
	}

	public void setPnWorkflowTransitionsByBeginStepIdAndWorkflowId(Set pnWorkflowTransitionsByBeginStepIdAndWorkflowId) {
		this.pnWorkflowTransitionsByBeginStepIdAndWorkflowId = pnWorkflowTransitionsByBeginStepIdAndWorkflowId;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowStep", targetEntity = PnEnvelopeVersion.class)
	@Transient
	public Set getPnEnvelopeVersions() {
		return this.pnEnvelopeVersions;
	}

	public void setPnEnvelopeVersions(Set pnEnvelopeVersions) {
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWorkflowStep))
			return false;
		PnWorkflowStep castOther = (PnWorkflowStep) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
