/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * StatusMessage generated by hbm2java
 */
@Entity
@Table(name="STATUS_MESSAGES"
)
public class StatusMessage  implements java.io.Serializable {


     private Integer messageId;
     private String title;
     private String message;
     private String activeIndicator;
     private Date timestamp;

    public StatusMessage() {
    }

    public StatusMessage(Integer messageId, String title, String message, String activeIndicator, Date timestamp) {
       this.messageId = messageId;
       this.title = title;
       this.message = message;
       this.activeIndicator = activeIndicator;
       this.timestamp = timestamp;
    }
   
     @Id 
    @Column(name="MESSAGE_ID", nullable=false)
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="TITLE", nullable=false, length=30)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="MESSAGE", nullable=false, length=500)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false, length=1)
    public String getActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(String activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    
    @Column(name="TIMESTAMP", nullable=false, length=7)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("messageId", getMessageId())
            .toString();
    }

}
