 
-- Alter table PN_USER to add USER_SESSION_KEY column
ALTER TABLE PN_USER
ADD (USER_SESSION_KEY VARCHAR2(50 BYTE) )
/

-- Alter table PN_USER to add LAST_LOGIN_TIME column
ALTER TABLE PN_USER
ADD (LAST_LOGIN_TIME TIMESTAMP(6) )
/