DROP TABLE "PNET"."PN_SPACE_HAS_MATERIAL";
DROP TABLE "PNET"."PN_ASSOCIATED_MATERIAL";
DROP TABLE "PNET"."PN_MATERIAL";
DROP TABLE "PNET"."PN_MATERIAL_TYPE";

CREATE TABLE PN_MATERIAL_TYPE (
  MATERIAL_TYPE_ID number(20),
  MATERIAL_TYPE_NAME varchar(40),
  RECORD_STATUS varchar(1),
  constraint MATERIAL_TYPE_PK primary key (MATERIAL_TYPE_ID),
  constraint RECORD_STATUS_MT1 check (RECORD_STATUS in ('A','I'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_MATERIAL_TYPE FOR PNET.PN_MATERIAL_TYPE;

CREATE TABLE PN_MATERIAL (
  MATERIAL_ID number(20),
  MATERIAL_NAME varchar(40),
  MATERIAL_DESCRIPTION varchar(240),
  MATERIAL_TYPE_ID number(20),
  MATERIAL_COST number(20,2),
  RECORD_STATUS varchar(1),
  constraint MATERIAL_PK primary key (MATERIAL_ID),
  constraint MATERIAL_TYPE_FK1 FOREIGN KEY (material_type_id) REFERENCES pn_material_type(material_type_id),
  constraint RECORD_STATUS_M1 check (RECORD_STATUS in ('A','I'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_MATERIAL FOR PNET.PN_MATERIAL;

CREATE TABLE PN_SPACE_HAS_MATERIAL (
  SPACE_ID number(20) not null,
  MATERIAL_ID number(20) not null,
  RECORD_STATUS varchar(1) not null,
  constraint PN_SPACE_HAS_MATERIAL_PK primary key (SPACE_ID,MATERIAL_ID),
  constraint SPACE_MATERIAL_FK1 FOREIGN KEY (material_id) REFERENCES pn_material(material_id),
  constraint RECORD_STATUS_SM1 check (RECORD_STATUS in ('A','P','D','H'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_SPACE_HAS_MATERIAL FOR PNET.PN_SPACE_HAS_MATERIAL;

CREATE TABLE PN_ASSOCIATED_MATERIAL (
  ASSOCIATION_CODE number(6) not null,
  SPACE_ID number(20) not null,
  ASSOCIATOR_ID number(20) not null,
  DATE_ASSOCIATED date not null,
  DATE_APPROVED date,
  ASSOCIATED_STATUS varchar(20) not null,
  MATERIAL_ID number(20) not null,
  constraint ASSOCIATED_MATERIAL_PK1 primary key (ASSOCIATION_CODE),
  constraint ASSOCIATED_MATERIAL_FK1 FOREIGN KEY (MATERIAL_ID) REFERENCES pn_material(material_id),
  constraint ASSOCIATED_MATERIAL_FK2 FOREIGN KEY (ASSOCIATOR_ID) REFERENCES PN_USER(USER_ID),
  constraint ASSOCIATED_STATUS check (ASSOCIATED_STATUS in ('Associated','Approved','Rejected','Deleted'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_ASSOCIATED_MATERIAL FOR PNET.PN_ASSOCIATED_MATERIAL;

COMMIT;





