DROP TABLE "PNET"."PN_MATERIAL_ASSIGNMENT";
DROP TABLE "PNET"."PN_SPACE_HAS_MATERIAL";
DROP TABLE "PNET"."PN_MATERIAL";
DROP TABLE "PNET"."PN_MATERIAL_TYPE";

CREATE TABLE PN_MATERIAL_TYPE (
  MATERIAL_TYPE_ID number(20),
  MATERIAL_TYPE_NAME varchar(40),
  RECORD_STATUS varchar(1),
  constraint MATERIAL_TYPE_PK primary key (MATERIAL_TYPE_ID),
  constraint RECORD_STATUS_MT1 check (RECORD_STATUS in ('A','D'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_MATERIAL_TYPE FOR PNET.PN_MATERIAL_TYPE;

CREATE TABLE PN_MATERIAL (
  MATERIAL_ID number(20),
  MATERIAL_NAME varchar(40),
  MATERIAL_DESCRIPTION varchar(240),
  MATERIAL_TYPE_ID number(20),
  MATERIAL_COST number(20,2),
  MATERIAL_CONSUMABLE varchar(5),
  RECORD_STATUS varchar(1),
  constraint MATERIAL_PK primary key (MATERIAL_ID),
  constraint MATERIAL_TYPE_FK1 FOREIGN KEY (material_type_id) REFERENCES pn_material_type(material_type_id),
  constraint RECORD_STATUS_M1 check (RECORD_STATUS in ('A','D')),
  constraint MATERIAL_CONSUMABLE check (MATERIAL_CONSUMABLE in ('true','false'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_MATERIAL FOR PNET.PN_MATERIAL;

CREATE TABLE PN_SPACE_HAS_MATERIAL (
  SPACE_ID number(20) not null,
  MATERIAL_ID number(20) not null,
  RECORD_STATUS varchar(1) not null,
  constraint PN_SPACE_HAS_MATERIAL_PK primary key (SPACE_ID,MATERIAL_ID),
  constraint SPACE_MATERIAL_FK1 FOREIGN KEY (material_id) REFERENCES pn_material(material_id),
  constraint RECORD_STATUS_SM1 check (RECORD_STATUS in ('A','P','D','H'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_SPACE_HAS_MATERIAL FOR PNET.PN_SPACE_HAS_MATERIAL;

CREATE TABLE PN_MATERIAL_ASSIGNMENT (
  SPACE_ID number(20) not null,
  MATERIAL_ID number(20) not null,
  OBJECT_ID number(20) not null,
  PERCENT_ALLOCATED number,
  RECORD_STATUS varchar(1),
  START_DATE date,
  END_DATE date,
  DATE_CREATED date,
  MODIFIED_DATE date,
  MODIFIED_BY number(20),
  ASSIGNOR_ID number(20),
  constraint MATERIAL_ASSIGNMENT__PK primary key (SPACE_ID,MATERIAL_ID,OBJECT_ID),
  constraint MATERIAL_ASSIGNMENT_FK1 FOREIGN KEY (SPACE_ID, MATERIAL_ID) REFERENCES PN_SPACE_HAS_MATERIAL(SPACE_ID, MATERIAL_ID),
  constraint MATERIAL_ASSIGNMENT_FK2 FOREIGN KEY (OBJECT_ID) REFERENCES PN_OBJECT(OBJECT_ID),
  constraint MATERIAL_ASSIGNMENT_FK3 FOREIGN KEY (ASSIGNOR_ID) REFERENCES PN_PERSON(PERSON_ID),
  constraint RECORD_STATUS_MA1 check (RECORD_STATUS in ('A','D'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_MATERIAL_ASSIGNMENT FOR PNET.PN_MATERIAL_ASSIGNMENT;

COMMIT;

/



