package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnAgendaItemPK generated by hbm2java
 */
@Embeddable
public class PnAgendaItemPK  implements java.io.Serializable {

/** identifier field */
     private Integer meetingId;

   /** identifier field */
     private Integer agendaItemId;
	 
	 
 /** default constructor */
    public PnAgendaItemPK() {
    }

 /** full constructor */
    public PnAgendaItemPK(Integer meetingId, Integer agendaItemId) {
       this.meetingId = meetingId;
       this.agendaItemId = agendaItemId;
    }
   


    @Column(name="MEETING_ID", nullable=false, length=20)
    public Integer getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }


    @Column(name="AGENDA_ITEM_ID", nullable=false, length=20)
    public Integer getAgendaItemId() {
        return this.agendaItemId;
    }
    
    public void setAgendaItemId(Integer agendaItemId) {
        this.agendaItemId = agendaItemId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("meetingId", getMeetingId())
            .append("agendaItemId", getAgendaItemId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnAgendaItemPK) ) return false;
        PnAgendaItemPK castOther = (PnAgendaItemPK) other;
        return new EqualsBuilder()
            .append(this.getMeetingId(), castOther.getMeetingId())
            .append(this.getAgendaItemId(), castOther.getAgendaItemId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getMeetingId())
            .append(getAgendaItemId())
            .toHashCode();
    }

}
