package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * PnApplicationSpace generated by hbm2java
 */
@Entity
@Table(name="PN_APPLICATION_SPACE"
)
public class PnApplicationSpace  implements java.io.Serializable {


     private Integer applicationId;
     
     private String applicationName;
     
     private String applicationDesc;
     
     private Integer createdById;
     
     private Date createdDatetime;
     
     private Date crc;
     
     private String recordStatus;

    public PnApplicationSpace() {
    }

    public PnApplicationSpace(Integer applicationId, String applicationName, Integer createdById, Date createdDatetime, Date crc, String recordStatus) {
        this.applicationId = applicationId;
        this.applicationName = applicationName;
        this.createdById = createdById;
        this.createdDatetime = createdDatetime;
        this.crc = crc;
        this.recordStatus = recordStatus;
    }
    public PnApplicationSpace(Integer applicationId, String applicationName, String applicationDesc, Integer createdById, Date createdDatetime, Date crc, String recordStatus) {
       this.applicationId = applicationId;
       this.applicationName = applicationName;
       this.applicationDesc = applicationDesc;
       this.createdById = createdById;
       this.createdDatetime = createdDatetime;
       this.crc = crc;
       this.recordStatus = recordStatus;
    }
   
    @Id 
    @Column(name="APPLICATION_ID", nullable=false)
    public Integer getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    
    @Column(name="APPLICATION_NAME", nullable=false, length=80)
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    
    @Column(name="APPLICATION_DESC", length=1000)
    public String getApplicationDesc() {
        return this.applicationDesc;
    }
    
    public void setApplicationDesc(String applicationDesc) {
        this.applicationDesc = applicationDesc;
    }

    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public Integer getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("applicationId", getApplicationId())
            .toString();
    }

}


