package net.project.hibernate.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnAssignmentPK generated by hbm2java
 */
@Embeddable
public class PnAssignmentPK implements java.io.Serializable {

	private Integer spaceId;

	private Integer personId;

	private Integer objectId;

	public PnAssignmentPK() {
	}

	public PnAssignmentPK(Integer spaceId, Integer personId, Integer objectId) {
		this.spaceId = spaceId;
		this.personId = personId;
		this.objectId = objectId;
	}

	@Column(name = "SPACE_ID", nullable = false, length = 20)
	public Integer getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	@Column(name = "PERSON_ID", nullable = false, length = 20)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "OBJECT_ID", nullable = false, length = 20)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

}
