/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnBill generated by hbm2java
 */
@Entity
@Table(name = "PN_BILL")
public class PnBill implements java.io.Serializable {

	private Integer billId;

	private Integer unitPriceValue;

	private Integer quantityAmount;

	private Integer quantityUomId;

	private Integer categoryId;

	private String partDetailsPartNumber;

	private String partDetailsPartDescription;

	private Integer groupTypeId;

	private String groupValue;

	private String groupDescription;

	private Integer billStatusId;

	private String recordStatus;

	private Date creationDatetime;

	private Date dueDatetime;

	private PnPerson pnPerson;

	private Set pnLedgers = new HashSet(0);

	private PnLicense pnLicense;

	private PnPaymentInformation pnPaymentInformation;

	public PnBill() {
	}

	public PnBill(Integer billId, Integer unitPriceValue, Integer quantityAmount, Integer quantityUomId,
			Integer categoryId, String partDetailsPartNumber, Integer groupTypeId, Integer billStatusId,
			Date creationDatetime, Date dueDatetime) {
		this.billId = billId;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.groupTypeId = groupTypeId;
		this.billStatusId = billStatusId;
		this.creationDatetime = creationDatetime;
		this.dueDatetime = dueDatetime;
	}

	public PnBill(Integer billId, Integer unitPriceValue, Integer quantityAmount, Integer quantityUomId,
			Integer categoryId, String partDetailsPartNumber, String partDetailsPartDescription, Integer groupTypeId,
			String groupValue, String groupDescription, Integer billStatusId, String recordStatus,
			Date creationDatetime, Date dueDatetime, PnPerson pnPerson, Set pnLedgers, PnLicense pnLicense,
			PnPaymentInformation pnPaymentInformation) {
		this.billId = billId;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.partDetailsPartDescription = partDetailsPartDescription;
		this.groupTypeId = groupTypeId;
		this.groupValue = groupValue;
		this.groupDescription = groupDescription;
		this.billStatusId = billStatusId;
		this.recordStatus = recordStatus;
		this.creationDatetime = creationDatetime;
		this.dueDatetime = dueDatetime;
		this.pnPerson = pnPerson;
		this.pnLedgers = pnLedgers;
		this.pnLicense = pnLicense;
		this.pnPaymentInformation = pnPaymentInformation;
	}

	/** minimal constructor */
	public PnBill(Integer billId, Integer unitPriceValue, Integer quantityAmount, Integer quantityUomId,
			Integer categoryId, String partDetailsPartNumber, Integer groupTypeId, Integer billStatusId,
			Date creationDatetime, Date dueDatetime, net.project.hibernate.model.PnPerson pnPerson,
			net.project.hibernate.model.PnLicense pnLicense,
			net.project.hibernate.model.PnPaymentInformation pnPaymentInformation, Set pnLedgers) {
		this.billId = billId;
		this.unitPriceValue = unitPriceValue;
		this.quantityAmount = quantityAmount;
		this.quantityUomId = quantityUomId;
		this.categoryId = categoryId;
		this.partDetailsPartNumber = partDetailsPartNumber;
		this.groupTypeId = groupTypeId;
		this.billStatusId = billStatusId;
		this.creationDatetime = creationDatetime;
		this.dueDatetime = dueDatetime;
		this.pnPerson = pnPerson;
		this.pnLicense = pnLicense;
		this.pnPaymentInformation = pnPaymentInformation;
		this.pnLedgers = pnLedgers;
	}

	@Id
	@Column(name = "BILL_ID", nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Column(name = "UNIT_PRICE_VALUE", nullable = false, length = 22)
	public Integer getUnitPriceValue() {
		return this.unitPriceValue;
	}

	public void setUnitPriceValue(Integer unitPriceValue) {
		this.unitPriceValue = unitPriceValue;
	}

	@Column(name = "QUANTITY_AMOUNT", nullable = false, length = 22)
	public Integer getQuantityAmount() {
		return this.quantityAmount;
	}

	public void setQuantityAmount(Integer quantityAmount) {
		this.quantityAmount = quantityAmount;
	}

	@Column(name = "QUANTITY_UOM_ID", nullable = false, length = 22)
	public Integer getQuantityUomId() {
		return this.quantityUomId;
	}

	public void setQuantityUomId(Integer quantityUomId) {
		this.quantityUomId = quantityUomId;
	}

	@Column(name = "CATEGORY_ID", nullable = false, length = 22)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "PART_DETAILS_PART_NUMBER", nullable = false, length = 500)
	public String getPartDetailsPartNumber() {
		return this.partDetailsPartNumber;
	}

	public void setPartDetailsPartNumber(String partDetailsPartNumber) {
		this.partDetailsPartNumber = partDetailsPartNumber;
	}

	@Column(name = "PART_DETAILS_PART_DESCRIPTION", length = 1000)
	public String getPartDetailsPartDescription() {
		return this.partDetailsPartDescription;
	}

	public void setPartDetailsPartDescription(String partDetailsPartDescription) {
		this.partDetailsPartDescription = partDetailsPartDescription;
	}

	@Column(name = "GROUP_TYPE_ID", nullable = false, length = 20)
	public Integer getGroupTypeId() {
		return this.groupTypeId;
	}

	public void setGroupTypeId(Integer groupTypeId) {
		this.groupTypeId = groupTypeId;
	}

	@Column(name = "GROUP_VALUE", length = 500)
	public String getGroupValue() {
		return this.groupValue;
	}

	public void setGroupValue(String groupValue) {
		this.groupValue = groupValue;
	}

	@Column(name = "GROUP_DESCRIPTION", length = 1000)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "BILL_STATUS_ID", nullable = false, length = 20)
	public Integer getBillStatusId() {
		return this.billStatusId;
	}

	public void setBillStatusId(Integer billStatusId) {
		this.billStatusId = billStatusId;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "CREATION_DATETIME", nullable = false, length = 7)
	public Date getCreationDatetime() {
		return this.creationDatetime;
	}

	public void setCreationDatetime(Date creationDatetime) {
		this.creationDatetime = creationDatetime;
	}

	@Column(name = "DUE_DATETIME", nullable = false, length = 7)
	public Date getDueDatetime() {
		return this.dueDatetime;
	}

	public void setDueDatetime(Date dueDatetime) {
		this.dueDatetime = dueDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "ORIGINATING_PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnBill", targetEntity = PnLedger.class)
	@Transient
	public Set getPnLedgers() {
		return this.pnLedgers;
	}

	public void setPnLedgers(Set pnLedgers) {
		this.pnLedgers = pnLedgers;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnLicense.class)
	@JoinColumn(name = "ORIGINATING_LICENSE_ID")
	public PnLicense getPnLicense() {
		return this.pnLicense;
	}

	public void setPnLicense(PnLicense pnLicense) {
		this.pnLicense = pnLicense;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPaymentInformation.class)
	@JoinColumn(name = "ORIGINATING_PAYMENT_ID")
	public PnPaymentInformation getPnPaymentInformation() {
		return this.pnPaymentInformation;
	}

	public void setPnPaymentInformation(PnPaymentInformation pnPaymentInformation) {
		this.pnPaymentInformation = pnPaymentInformation;
	}

}
