/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassListFilter generated by hbm2java
 */
@Entity
@Table(name="PN_CLASS_LIST_FILTER"
)
public class PnClassListFilter  implements java.io.Serializable {

	/** identifier field */
     private PnClassListFilterPK comp_id;

    /** persistent field */
    private String operator;

    /** persistent field */
    private String filterValue;

    public PnClassListFilter() {
    }

    public PnClassListFilter(PnClassListFilterPK comp_id, String operator, String filterValue) {
       this.comp_id = comp_id;
       this.operator = operator;
       this.filterValue = filterValue;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="classId", column=@Column(name="CLASS_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="listId", column=@Column(name="LIST_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="fieldId", column=@Column(name="FIELD_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="valueId", column=@Column(name="VALUE_ID", nullable=false, length=20) ) } )
    public PnClassListFilterPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnClassListFilterPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="OPERATOR", nullable=false, length=10)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }

    
    @Column(name="FILTER_VALUE", nullable=false, length=80)
    public String getFilterValue() {
        return this.filterValue;
    }
    
    public void setFilterValue(String filterValue) {
        this.filterValue = filterValue;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnClassListFilter) ) return false;
        PnClassListFilter castOther = (PnClassListFilter) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }
}


