/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassInstActiveCntView generated by hbm2java
 */
@Entity
@Table(name="PN_CLASS_INST_ACTIVE_CNT_VIEW"
)
public class PnClassInstActiveCntView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal classId;

    /** identifier field */
    private BigDecimal activeCount;

    public PnClassInstActiveCntView() {
    }

    public PnClassInstActiveCntView(BigDecimal classId, BigDecimal activeCount) {
       this.classId = classId;
       this.activeCount = activeCount;
    }
   

    
    @Column(name="CLASS_ID", nullable=false, length=20)
    public BigDecimal getClassId() {
        return this.classId;
    }
    
    public void setClassId(BigDecimal classId) {
        this.classId = classId;
    }

    
    @Column(name="ACTIVE_COUNT", nullable=false, length=22)
    public BigDecimal getActiveCount() {
        return this.activeCount;
    }
    
    public void setActiveCount(BigDecimal activeCount) {
        this.activeCount = activeCount;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("classId", getClassId())
            .append("activeCount", getActiveCount())
            .toString();
    }

}


