/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDirectoryProviderType generated by hbm2java
 */
@Entity
@Table(name = "PN_DIRECTORY_PROVIDER_TYPE")
public class PnDirectoryProviderType implements java.io.Serializable {

	/** identifier field */
	private Integer providerTypeId;

	/** persistent field */
	private String name;

	/** nullable persistent field */
	private String description;

	/** persistent field */
	private String serviceProviderClassName;

	/** persistent field */
	private String configuratorClassName;

	/** persistent field */
	private String configurationClassName;

	/** persistent field */
	private Set pnUserDomains = new HashSet(0);

	public PnDirectoryProviderType() {
	}

	public PnDirectoryProviderType(Integer providerTypeId, String name, String serviceProviderClassName,
			String configuratorClassName, String configurationClassName) {
		this.providerTypeId = providerTypeId;
		this.name = name;
		this.serviceProviderClassName = serviceProviderClassName;
		this.configuratorClassName = configuratorClassName;
		this.configurationClassName = configurationClassName;
	}

	public PnDirectoryProviderType(Integer providerTypeId, String name, String description,
			String serviceProviderClassName, String configuratorClassName, String configurationClassName,
			Set pnUserDomains) {
		this.providerTypeId = providerTypeId;
		this.name = name;
		this.description = description;
		this.serviceProviderClassName = serviceProviderClassName;
		this.configuratorClassName = configuratorClassName;
		this.configurationClassName = configurationClassName;
		this.pnUserDomains = pnUserDomains;
	}

	/** minimal constructor */
	public PnDirectoryProviderType(Integer providerTypeId, String name, String serviceProviderClassName,
			String configuratorClassName, String configurationClassName, Set pnUserDomains) {
		this.providerTypeId = providerTypeId;
		this.name = name;
		this.serviceProviderClassName = serviceProviderClassName;
		this.configuratorClassName = configuratorClassName;
		this.configurationClassName = configurationClassName;
		this.pnUserDomains = pnUserDomains;
	}

	@Id
	@Column(name = "PROVIDER_TYPE_ID", nullable = false)
	public Integer getProviderTypeId() {
		return this.providerTypeId;
	}

	public void setProviderTypeId(Integer providerTypeId) {
		this.providerTypeId = providerTypeId;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SERVICE_PROVIDER_CLASS_NAME", nullable = false, length = 1000)
	public String getServiceProviderClassName() {
		return this.serviceProviderClassName;
	}

	public void setServiceProviderClassName(String serviceProviderClassName) {
		this.serviceProviderClassName = serviceProviderClassName;
	}

	@Column(name = "CONFIGURATOR_CLASS_NAME", nullable = false, length = 1000)
	public String getConfiguratorClassName() {
		return this.configuratorClassName;
	}

	public void setConfiguratorClassName(String configuratorClassName) {
		this.configuratorClassName = configuratorClassName;
	}

	@Column(name = "CONFIGURATION_CLASS_NAME", nullable = false, length = 1000)
	public String getConfigurationClassName() {
		return this.configurationClassName;
	}

	public void setConfigurationClassName(String configurationClassName) {
		this.configurationClassName = configurationClassName;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDirectoryProviderType", targetEntity = PnUserDomain.class)
	@Transient
	public Set getPnUserDomains() {
		return this.pnUserDomains;
	}

	public void setPnUserDomains(Set pnUserDomains) {
		this.pnUserDomains = pnUserDomains;
	}

	public String toString() {
		return new ToStringBuilder(this).append("providerTypeId", getProviderTypeId()).toString();
	}

}
