/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocument generated by hbm2java
 */
@Entity
@Table(name = "PN_DOCUMENT")
public class PnDocument implements java.io.Serializable {

	/** identifier field */
	private Integer docId;

	/** nullable persistent field */
	private String docName;

	/** nullable persistent field */
	private String docDescription;

	/** persistent field */
	private Integer currentVersionId;

	/** nullable persistent field */
	private Integer docStatusId;

	/** persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	/** nullable persistent field */
	private Integer oldStorageId;

	/** nullable persistent field */
	private PnObject pnObject;

	/** persistent field */
	private Set pnProjectSpaces = new HashSet(0);

	/** persistent field */
	private Set pnDocHistories = new HashSet(0);

	/** persistent field */
	private Set pnDocCheckoutLocations = new HashSet(0);

	/** persistent field */
	private Set pnDocVersions = new HashSet(0);

	/** persistent field */
	private PnDocType pnDocType;

	public PnDocument() {
	}

	public PnDocument(Integer docId, Integer currentVersionId, Date crc, String recordStatus) {
		this.docId = docId;
		this.currentVersionId = currentVersionId;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnDocument(Integer docId, String docName, String docDescription, Integer currentVersionId,
			Integer docStatusId, Date crc, String recordStatus, Integer oldStorageId, PnObject pnObject,
			Set pnProjectSpaces, Set pnDocHistories, Set pnDocCheckoutLocations, Set pnDocVersions, PnDocType pnDocType) {
		this.docId = docId;
		this.docName = docName;
		this.docDescription = docDescription;
		this.currentVersionId = currentVersionId;
		this.docStatusId = docStatusId;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.oldStorageId = oldStorageId;
		this.pnObject = pnObject;
		this.pnProjectSpaces = pnProjectSpaces;
		this.pnDocHistories = pnDocHistories;
		this.pnDocCheckoutLocations = pnDocCheckoutLocations;
		this.pnDocVersions = pnDocVersions;
		this.pnDocType = pnDocType;
	}

	/** minimal constructor */
	public PnDocument(Integer docId, Integer currentVersionId, Date crc, String recordStatus,
			net.project.hibernate.model.PnDocType pnDocType, Set pnProjectSpaces, Set pnDocHistories,
			Set pnDocCheckoutLocations, Set pnDocVersions) {
		this.docId = docId;
		this.currentVersionId = currentVersionId;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnDocType = pnDocType;
		this.pnProjectSpaces = pnProjectSpaces;
		this.pnDocHistories = pnDocHistories;
		this.pnDocCheckoutLocations = pnDocCheckoutLocations;
		this.pnDocVersions = pnDocVersions;
	}

	public PnDocument(Integer docId) {
		this.docId = docId;
	}

	@Id
	@Column(name = "DOC_ID", nullable = false)
	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@Column(name = "DOC_NAME", length = 256)
	public String getDocName() {
		return this.docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	@Column(name = "DOC_DESCRIPTION", length = 4000)
	public String getDocDescription() {
		return this.docDescription;
	}

	public void setDocDescription(String docDescription) {
		this.docDescription = docDescription;
	}

	@Column(name = "CURRENT_VERSION_ID", nullable = false, length = 20)
	public Integer getCurrentVersionId() {
		return this.currentVersionId;
	}

	public void setCurrentVersionId(Integer currentVersionId) {
		this.currentVersionId = currentVersionId;
	}

	@Column(name = "DOC_STATUS_ID", length = 20)
	public Integer getDocStatusId() {
		return this.docStatusId;
	}

	public void setDocStatusId(Integer docStatusId) {
		this.docStatusId = docStatusId;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "OLD_STORAGE_ID", length = 20)
	public Integer getOldStorageId() {
		return this.oldStorageId;
	}

	public void setOldStorageId(Integer oldStorageId) {
		this.oldStorageId = oldStorageId;
	}

	//@OneToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name="DOC_ID")
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocument", targetEntity = PnProjectSpace.class)	
	public Set getPnProjectSpaces() {
		return this.pnProjectSpaces;
	}

	public void setPnProjectSpaces(Set pnProjectSpaces) {
		this.pnProjectSpaces = pnProjectSpaces;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocument", targetEntity = PnDocHistory.class)
	@Transient
	public Set getPnDocHistories() {
		return this.pnDocHistories;
	}

	public void setPnDocHistories(Set pnDocHistories) {
		this.pnDocHistories = pnDocHistories;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocument", targetEntity = PnDocCheckoutLocation.class)
	@Transient
	public Set getPnDocCheckoutLocations() {
		return this.pnDocCheckoutLocations;
	}

	public void setPnDocCheckoutLocations(Set pnDocCheckoutLocations) {
		this.pnDocCheckoutLocations = pnDocCheckoutLocations;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocument", targetEntity = PnDocVersion.class)
	@Transient
	public Set getPnDocVersions() {
		return this.pnDocVersions;
	}

	public void setPnDocVersions(Set pnDocVersions) {
		this.pnDocVersions = pnDocVersions;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocType.class)
	@JoinColumn(name = "DOC_TYPE_ID")
	public PnDocType getPnDocType() {
		return this.pnDocType;
	}

	public void setPnDocType(PnDocType pnDocType) {
		this.pnDocType = pnDocType;
	}

	public String toString() {
		return new ToStringBuilder(this).append("docId", getDocId()).toString();
	}

}
