/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnFormsActionLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_FORMS_ACTION_LOOKUP")
public class PnFormsActionLookup implements java.io.Serializable {

	/** identifier field */
	private String action;

	/** persistent field */
	private String recordStatus;

	/** persistent field */
	private Set pnFormsHistories = new HashSet(0);

	public PnFormsActionLookup() {
	}

	public PnFormsActionLookup(String action, String recordStatus) {
		this.action = action;
		this.recordStatus = recordStatus;
	}

	public PnFormsActionLookup(String action, String recordStatus, Set pnFormsHistories) {
		this.action = action;
		this.recordStatus = recordStatus;
		this.pnFormsHistories = pnFormsHistories;
	}

	@Id
	@Column(name = "ACTION", nullable = false)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnFormsActionLookup", targetEntity = PnFormsHistory.class)
	@Transient
	public Set getPnFormsHistories() {
		return this.pnFormsHistories;
	}

	public void setPnFormsHistories(Set pnFormsHistories) {
		this.pnFormsHistories = pnFormsHistories;
	}

	public String toString() {
		return new ToStringBuilder(this).append("action", getAction()).toString();
	}
}
