/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnIndustryHasCategoryPK generated by hbm2java
 */
@Embeddable
public class PnIndustryHasCategoryPK  implements java.io.Serializable {

    /** identifier field */
    private Integer industryId;

    /** identifier field */
    private Integer categoryId;

    public PnIndustryHasCategoryPK() {
    }

    public PnIndustryHasCategoryPK(Integer industryId, Integer categoryId) {
       this.industryId = industryId;
       this.categoryId = categoryId;
    }

    @Column(name="INDUSTRY_ID", nullable=false, length=20)
    public Integer getIndustryId() {
        return this.industryId;
    }
    
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    @Column(name="CATEGORY_ID", nullable=false, length=20)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("industryId", getIndustryId())
            .append("categoryId", getCategoryId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnIndustryHasCategoryPK) ) return false;
        PnIndustryHasCategoryPK castOther = (PnIndustryHasCategoryPK) other;
        return new EqualsBuilder()
            .append(this.getIndustryId(), castOther.getIndustryId())
            .append(this.getCategoryId(), castOther.getCategoryId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getIndustryId())
            .append(getCategoryId())
            .toHashCode();
    }
}


