/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnIndustryClassification generated by hbm2java
 */
@Entity
@Table(name = "PN_INDUSTRY_CLASSIFICATION")
public class PnIndustryClassification implements java.io.Serializable {

	/** identifier field */
	private Integer industryId;

	/** persistent field */
	private String name;

	/** nullable persistent field */
	private String description;

	public PnIndustryClassification() {
	}

	public PnIndustryClassification(Integer industryId, String name) {
		this.industryId = industryId;
		this.name = name;
	}

	public PnIndustryClassification(Integer industryId, String name, String description) {
		this.industryId = industryId;
		this.name = name;
		this.description = description;
	}

	@Id
	@Column(name = "INDUSTRY_ID", nullable = false)
	public Integer getIndustryId() {
		return this.industryId;
	}

	public void setIndustryId(Integer industryId) {
		this.industryId = industryId;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String toString() {
		return new ToStringBuilder(this).append("industryId", getIndustryId()).toString();
	}

}
