/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLicensePersonHistory generated by hbm2java
 */
@Entity
@Table(name="PN_LICENSE_PERSON_HISTORY"
)
public class PnLicensePersonHistory  implements java.io.Serializable {

    /** identifier field */
    private Integer historyId;

    /** persistent field */
    private Integer licenseId;

    /** persistent field */
    private Integer personId;

    /** persistent field */
    private Date createdDatetime;

    public PnLicensePersonHistory() {
    }

    public PnLicensePersonHistory(Integer historyId, Integer licenseId, Integer personId, Date createdDatetime) {
       this.historyId = historyId;
       this.licenseId = licenseId;
       this.personId = personId;
       this.createdDatetime = createdDatetime;
    }
   
    @Id 
    @Column(name="HISTORY_ID", nullable=false)
    public Integer getHistoryId() {
        return this.historyId;
    }
    
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    @Column(name="LICENSE_ID", nullable=false, length=20)
    public Integer getLicenseId() {
        return this.licenseId;
    }
    
    public void setLicenseId(Integer licenseId) {
        this.licenseId = licenseId;
    }

    @Column(name="PERSON_ID", nullable=false, length=20)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("historyId", getHistoryId())
            .toString();
    }

}


