/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPersonHasDisciplinePK generated by hbm2java
 */
@Embeddable
public class PnPersonHasDisciplinePK implements Serializable {


     private Integer personId;
     private Integer disciplineCode;

    public PnPersonHasDisciplinePK() {
    }

    public PnPersonHasDisciplinePK(Integer personId, Integer disciplineCode) {
       this.personId = personId;
       this.disciplineCode = disciplineCode;
    }
   
    @Column(name="PERSON_ID", nullable=false, length=20)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Column(name="DISCIPLINE_CODE", nullable=false, length=4)
    public Integer getDisciplineCode() {
        return this.disciplineCode;
    }
    
    public void setDisciplineCode(Integer disciplineCode) {
        this.disciplineCode = disciplineCode;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("personId", getPersonId())
            .append("disciplineCode", getDisciplineCode())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPersonHasDisciplinePK) ) return false;
        PnPersonHasDisciplinePK castOther = (PnPersonHasDisciplinePK) other;
        return new EqualsBuilder()
            .append(this.getPersonId(), castOther.getPersonId())
            .append(this.getDisciplineCode(), castOther.getDisciplineCode())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getPersonId())
            .append(getDisciplineCode())
            .toHashCode();
    }

}
