/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * PnPersonHasLicense generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_HAS_LICENSE")
public class PnPersonHasLicense implements Serializable {

	private Integer personId;

	private PnPerson pnPerson;

	private PnLicense pnLicense;

	public PnPersonHasLicense() {
	}

	public PnPersonHasLicense(Integer personId) {
		this.personId = personId;
	}

	public PnPersonHasLicense(Integer personId, net.project.hibernate.model.PnLicense pnLicense) {
		this.personId = personId;
		this.pnLicense = pnLicense;
	}

	public PnPersonHasLicense(Integer personId, PnPerson pnPerson, PnLicense pnLicense) {
		this.personId = personId;
		this.pnPerson = pnPerson;
		this.pnLicense = pnLicense;
	}

	@Id
	@Column(name = "PERSON_ID", nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@OneToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnLicense.class)
	@JoinColumn(name = "LICENSE_ID")
	public PnLicense getPnLicense() {
		return this.pnLicense;
	}

	public void setPnLicense(PnLicense pnLicense) {
		this.pnLicense = pnLicense;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).toString();
	}

}
