/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPersonSkillCommentPK generated by hbm2java
 */
@Embeddable
public class PnPersonSkillCommentPK implements Serializable {


     private Integer personId;
     private Integer skillId;
     private Integer commentId;

    public PnPersonSkillCommentPK() {
    }

    public PnPersonSkillCommentPK(Integer personId, Integer skillId, Integer commentId) {
       this.personId = personId;
       this.skillId = skillId;
       this.commentId = commentId;
    }
   
    @Column(name="PERSON_ID", nullable=false, length=20)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Column(name="SKILL_ID", nullable=false, length=20)
    public Integer getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @Column(name="COMMENT_ID", nullable=false, length=20)
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("personId", getPersonId())
            .append("skillId", getSkillId())
            .append("commentId", getCommentId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPersonSkillCommentPK) ) return false;
        PnPersonSkillCommentPK castOther = (PnPersonSkillCommentPK) other;
        return new EqualsBuilder()
            .append(this.getPersonId(), castOther.getPersonId())
            .append(this.getSkillId(), castOther.getSkillId())
            .append(this.getCommentId(), castOther.getCommentId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getPersonId())
            .append(getSkillId())
            .append(getCommentId())
            .toHashCode();
    }

}
