/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnPhaseHasDeliverable generated by hbm2java
 */
@Entity
@Table(name = "PN_PHASE_HAS_DELIVERABLE")
public class PnPhaseHasDeliverable implements Serializable {

	private PnPhaseHasDeliverablePK comp_id;

	private PnDeliverable pnDeliverable;

	private PnPhase pnPhase;

	public PnPhaseHasDeliverable() {
	}

	public PnPhaseHasDeliverable(PnPhaseHasDeliverablePK comp_id) {
		this.comp_id = comp_id;
	}

	public PnPhaseHasDeliverable(PnPhaseHasDeliverablePK comp_id, PnDeliverable pnDeliverable, PnPhase pnPhase) {
		this.comp_id = comp_id;
		this.pnDeliverable = pnDeliverable;
		this.pnPhase = pnPhase;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "phaseId", column = @Column(name = "PHASE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "deliverableId", column = @Column(name = "DELIVERABLE_ID", nullable = false, length = 20)) })
	public PnPhaseHasDeliverablePK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnPhaseHasDeliverablePK comp_id) {
		this.comp_id = comp_id;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDeliverable.class)
	@JoinColumn(name = "DELIVERABLE_ID", insertable = false, updatable = false)
	public PnDeliverable getPnDeliverable() {
		return this.pnDeliverable;
	}

	public void setPnDeliverable(PnDeliverable pnDeliverable) {
		this.pnDeliverable = pnDeliverable;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPhase.class)
	@JoinColumn(name = "PHASE_ID", insertable = false, updatable = false)
	public PnPhase getPnPhase() {
		return this.pnPhase;
	}

	public void setPnPhase(PnPhase pnPhase) {
		this.pnPhase = pnPhase;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnPhaseHasDeliverable))
			return false;
		PnPhaseHasDeliverable castOther = (PnPhaseHasDeliverable) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
