/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnSpaceTypeHasReportTypePK generated by hbm2java
 */
@Embeddable
public class PnSpaceTypeHasReportTypePK implements Serializable {


     private String spaceType;
     private String reportType;

    public PnSpaceTypeHasReportTypePK() {
    }

    public PnSpaceTypeHasReportTypePK(String spaceType, String reportType) {
       this.spaceType = spaceType;
       this.reportType = reportType;
    }
   


    @Column(name="SPACE_TYPE", nullable=false, length=80)
    public String getSpaceType() {
        return this.spaceType;
    }
    
    public void setSpaceType(String spaceType) {
        this.spaceType = spaceType;
    }


    @Column(name="REPORT_TYPE", nullable=false, length=10)
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("spaceType", getSpaceType())
            .append("reportType", getReportType())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSpaceTypeHasReportTypePK) ) return false;
        PnSpaceTypeHasReportTypePK castOther = (PnSpaceTypeHasReportTypePK) other;
        return new EqualsBuilder()
            .append(this.getSpaceType(), castOther.getSpaceType())
            .append(this.getReportType(), castOther.getReportType())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getSpaceType())
            .append(getReportType())
            .toHashCode();
    }

}
