/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnSpaceHasWeather generated by hbm2java
 */
@Entity
@Table(name = "PN_SPACE_HAS_WEATHER")
public class PnSpaceHasWeather implements Serializable {

	private PnSpaceHasWeatherPK comp_id;

	private String name;

	private int isPrimary;

	private PnStateLookup pnStateLookup;

	private PnCountryLookup pnCountryLookup;

	private PnZipcodeFeedLookup pnZipcodeFeedLookup;

	public PnSpaceHasWeather() {
	}

	public PnSpaceHasWeather(PnSpaceHasWeatherPK comp_id, String name, int isPrimary) {
		this.comp_id = comp_id;
		this.name = name;
		this.isPrimary = isPrimary;
	}

	public PnSpaceHasWeather(PnSpaceHasWeatherPK comp_id, String name, int isPrimary, PnStateLookup pnStateLookup,
			PnCountryLookup pnCountryLookup, PnZipcodeFeedLookup pnZipcodeFeedLookup) {
		this.comp_id = comp_id;
		this.name = name;
		this.isPrimary = isPrimary;
		this.pnStateLookup = pnStateLookup;
		this.pnCountryLookup = pnCountryLookup;
		this.pnZipcodeFeedLookup = pnZipcodeFeedLookup;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "spaceId", column = @Column(name = "SPACE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "city", column = @Column(name = "CITY", nullable = false, length = 80)),
			@AttributeOverride(name = "stateCode", column = @Column(name = "STATE_CODE", nullable = false, length = 2)),
			@AttributeOverride(name = "countryCode", column = @Column(name = "COUNTRY_CODE", nullable = false, length = 2)) })
	public PnSpaceHasWeatherPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnSpaceHasWeatherPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IS_PRIMARY", nullable = false, length = 1)
	public int getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(int isPrimary) {
		this.isPrimary = isPrimary;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnStateLookup.class)
	//@JoinColumn(name = "STATE_CODE", insertable = false, updatable = false)
	@Transient
	public PnStateLookup getPnStateLookup() {
		return this.pnStateLookup;
	}

	public void setPnStateLookup(PnStateLookup pnStateLookup) {
		this.pnStateLookup = pnStateLookup;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnCountryLookup.class)
	//@JoinColumn(name = "COUNTRY_CODE", insertable = false, updatable = false)
	@Transient
	public PnCountryLookup getPnCountryLookup() {
		return this.pnCountryLookup;
	}

	public void setPnCountryLookup(PnCountryLookup pnCountryLookup) {
		this.pnCountryLookup = pnCountryLookup;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnZipcodeFeedLookup.class)
	//@JoinColumn(name = "POSTAL_CODE")
	@Transient
	public PnZipcodeFeedLookup getPnZipcodeFeedLookup() {
		return this.pnZipcodeFeedLookup;
	}

	public void setPnZipcodeFeedLookup(PnZipcodeFeedLookup pnZipcodeFeedLookup) {
		this.pnZipcodeFeedLookup = pnZipcodeFeedLookup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnSpaceHasWeather))
			return false;
		PnSpaceHasWeather castOther = (PnSpaceHasWeather) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
