/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnTimezoneLookup generated by hbm2java
 */
@Entity
@Table(name="PN_TIMEZONE_LOOKUP"
)
public class PnTimezoneLookup implements Serializable {


     private String timezoneCode;
     private String timezoneDescription;
     private String gmtOffset;

    public PnTimezoneLookup() {
    }

	
    public PnTimezoneLookup(String timezoneCode, String gmtOffset) {
        this.timezoneCode = timezoneCode;
        this.gmtOffset = gmtOffset;
    }

    public PnTimezoneLookup(String timezoneCode, String timezoneDescription, String gmtOffset) {
       this.timezoneCode = timezoneCode;
       this.timezoneDescription = timezoneDescription;
       this.gmtOffset = gmtOffset;
    }
   
     @Id 

    
    @Column(name="TIMEZONE_CODE", nullable=false)
    public String getTimezoneCode() {
        return this.timezoneCode;
    }
    
    public void setTimezoneCode(String timezoneCode) {
        this.timezoneCode = timezoneCode;
    }

    
    @Column(name="TIMEZONE_DESCRIPTION", length=60)
    public String getTimezoneDescription() {
        return this.timezoneDescription;
    }
    
    public void setTimezoneDescription(String timezoneDescription) {
        this.timezoneDescription = timezoneDescription;
    }

    
    @Column(name="GMT_OFFSET", nullable=false, length=8)
    public String getGmtOffset() {
        return this.gmtOffset;
    }
    
    public void setGmtOffset(String gmtOffset) {
        this.gmtOffset = gmtOffset;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("timezoneCode", getTimezoneCode())
            .toString();
    }

}
