/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnTmpDocPathInfo generated by hbm2java
 */
@Entity
@Table(name="PN_TMP_DOC_PATH_INFO"
)
public class PnTmpDocPathInfo implements Serializable {


     private Integer collectionId;
     private Integer objectId;
     private String objectName;
     private Integer parentId;
     private String parentName;
    private Integer isRoot;

    public PnTmpDocPathInfo() {
    }

    public PnTmpDocPathInfo(Integer collectionId, Integer objectId, String objectName, Integer parentId, String parentName, Integer isRoot) {
        this.collectionId = collectionId;
        this.objectId = objectId;
        this.objectName = objectName;
        this.parentId = parentId;
        this.parentName = parentName;
        this.isRoot = isRoot;
    }
   

    @Id
    @Column(name="COLLECTION_ID", nullable=false, length=20)
    public Integer getCollectionId() {
        return this.collectionId;
    }
    
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    
    @Column(name="OBJECT_ID", nullable=false, length=20)
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    
    @Column(name="OBJECT_NAME", nullable=false, length=80)
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    
    @Column(name="PARENT_ID", nullable=false, length=20)
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="PARENT_NAME", nullable=false, length=80)
    public String getParentName() {
        return this.parentName;
    }
    
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    
    @Column(name="IS_ROOT", nullable=false, length=1)
    public Integer getIsRoot() {
        return this.isRoot;
    }
    
    public void setIsRoot(Integer isRoot) {
        this.isRoot = isRoot;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("collectionId", getCollectionId())
            .append("objectId", getObjectId())
            .append("objectName", getObjectName())
            .append("parentId", getParentId())
            .append("parentName", getParentName())
            .append("isRoot", getIsRoot())
            .toString();
    }

}
