/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflow generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW")
public class PnWorkflow implements Serializable {

	private Integer workflowId;

	private String workflowName;

	private String workflowDescription;

	private Integer createdById;

	private String notes;

	private Date createdDatetime;

	private Integer modifiedById;

	private Integer ownerId;

	private Date modifiedDatetime;

	private int isPublished;

	private int isGeneric;

	private Date crc;

	private String recordStatus;

	private Set pnWorkflowEnvelopes = new HashSet(0);

	private Set pnWorkflowTransitions = new HashSet(0);

	private Set pnWorkflowHasObjectTypes = new HashSet(0);

	private Set pnSpaceHasWorkflows = new HashSet(0);

	private Set pnWorkflowSteps = new HashSet(0);

	private PnWorkflowStrictness pnWorkflowStrictness;

	public PnWorkflow() {
	}

	public PnWorkflow(Integer workflowId, Integer createdById, Date createdDatetime, Integer ownerId, int isPublished,
			int isGeneric, Date crc, String recordStatus) {
		this.workflowId = workflowId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.ownerId = ownerId;
		this.isPublished = isPublished;
		this.isGeneric = isGeneric;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnWorkflow(Integer workflowId, Integer createdById, Date createdDatetime, Integer ownerId, int isPublished,
			int isGeneric, Date crc, String recordStatus,
			net.project.hibernate.model.PnWorkflowStrictness pnWorkflowStrictness, Set pnWorkflowEnvelopes,
			Set pnWorkflowTransitions, Set pnWorkflowHasObjectTypes, Set pnSpaceHasWorkflows, Set pnWorkflowSteps) {
		this.workflowId = workflowId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.ownerId = ownerId;
		this.isPublished = isPublished;
		this.isGeneric = isGeneric;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflowStrictness = pnWorkflowStrictness;
		this.pnWorkflowEnvelopes = pnWorkflowEnvelopes;
		this.pnWorkflowTransitions = pnWorkflowTransitions;
		this.pnWorkflowHasObjectTypes = pnWorkflowHasObjectTypes;
		this.pnSpaceHasWorkflows = pnSpaceHasWorkflows;
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	public PnWorkflow(Integer workflowId, String workflowName, String workflowDescription, Integer createdById,
			String notes, Date createdDatetime, Integer modifiedById, Integer ownerId, Date modifiedDatetime,
			int isPublished, int isGeneric, Date crc, String recordStatus,
			net.project.hibernate.model.PnWorkflowStrictness pnWorkflowStrictness, Set pnWorkflowEnvelopes,
			Set pnWorkflowTransitions, Set pnWorkflowHasObjectTypes, Set pnSpaceHasWorkflows, Set pnWorkflowSteps) {
		this.workflowId = workflowId;
		this.workflowName = workflowName;
		this.workflowDescription = workflowDescription;
		this.createdById = createdById;
		this.notes = notes;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.ownerId = ownerId;
		this.modifiedDatetime = modifiedDatetime;
		this.isPublished = isPublished;
		this.isGeneric = isGeneric;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflowStrictness = pnWorkflowStrictness;
		this.pnWorkflowEnvelopes = pnWorkflowEnvelopes;
		this.pnWorkflowTransitions = pnWorkflowTransitions;
		this.pnWorkflowHasObjectTypes = pnWorkflowHasObjectTypes;
		this.pnSpaceHasWorkflows = pnSpaceHasWorkflows;
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	@Id
	@Column(name = "WORKFLOW_ID", nullable = false)
	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "WORKFLOW_NAME", length = 80)
	public String getWorkflowName() {
		return this.workflowName;
	}

	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	@Column(name = "WORKFLOW_DESCRIPTION", length = 500)
	public String getWorkflowDescription() {
		return this.workflowDescription;
	}

	public void setWorkflowDescription(String workflowDescription) {
		this.workflowDescription = workflowDescription;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "NOTES", length = 4000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "OWNER_ID", nullable = false, length = 20)
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "IS_PUBLISHED", nullable = false, length = 1)
	public int getIsPublished() {
		return this.isPublished;
	}

	public void setIsPublished(int isPublished) {
		this.isPublished = isPublished;
	}

	@Column(name = "IS_GENERIC", nullable = false, length = 1)
	public int getIsGeneric() {
		return this.isGeneric;
	}

	public void setIsGeneric(int isGeneric) {
		this.isGeneric = isGeneric;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflow", targetEntity = PnWorkflowEnvelope.class)
	public Set getPnWorkflowEnvelopes() {
		return this.pnWorkflowEnvelopes;
	}

	public void setPnWorkflowEnvelopes(Set pnWorkflowEnvelopes) {
		this.pnWorkflowEnvelopes = pnWorkflowEnvelopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflow", targetEntity = PnWorkflowTransition.class)
	public Set getPnWorkflowTransitions() {
		return this.pnWorkflowTransitions;
	}

	public void setPnWorkflowTransitions(Set pnWorkflowTransitions) {
		this.pnWorkflowTransitions = pnWorkflowTransitions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflow", targetEntity = PnWorkflowHasObjectType.class)
	public Set getPnWorkflowHasObjectTypes() {
		return this.pnWorkflowHasObjectTypes;
	}

	public void setPnWorkflowHasObjectTypes(Set pnWorkflowHasObjectTypes) {
		this.pnWorkflowHasObjectTypes = pnWorkflowHasObjectTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflow", targetEntity = PnSpaceHasWorkflow.class)
	public Set getPnSpaceHasWorkflows() {
		return this.pnSpaceHasWorkflows;
	}

	public void setPnSpaceHasWorkflows(Set pnSpaceHasWorkflows) {
		this.pnSpaceHasWorkflows = pnSpaceHasWorkflows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflow", targetEntity = PnWorkflowStep.class)
	public Set getPnWorkflowSteps() {
		return this.pnWorkflowSteps;
	}

	public void setPnWorkflowSteps(Set pnWorkflowSteps) {
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnWorkflowStrictness.class)
	@JoinColumn(name = "STRICTNESS_ID")
	public PnWorkflowStrictness getPnWorkflowStrictness() {
		return this.pnWorkflowStrictness;
	}

	public void setPnWorkflowStrictness(PnWorkflowStrictness pnWorkflowStrictness) {
		this.pnWorkflowStrictness = pnWorkflowStrictness;
	}

	public String toString() {
		return new ToStringBuilder(this).append("workflowId", getWorkflowId()).toString();
	}

}
