/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflowRuleView generated by hbm2java
 */
@Entity
@Table(name="PN_WORKFLOW_RULE_VIEW"
)
public class PnWorkflowRuleView implements Serializable {


     private BigDecimal ruleId;
     private BigDecimal transitionId;
     private BigDecimal workflowId;
     private BigDecimal ruleTypeId;
     private String ruleTypeName;
     private BigDecimal ruleStatusId;
     private String ruleStatusName;
     private String ruleName;
     private String ruleDescription;
     private String notes;
     private BigDecimal createdById;
     private String createdByFullName;
     private Date createdDatetime;
     private BigDecimal modifiedById;
     private String modifiedByFullName;
     private Date modifiedDatetime;
     private Date crc;
     private String recordStatus;

    public PnWorkflowRuleView() {
    }

    public PnWorkflowRuleView(BigDecimal ruleId, BigDecimal transitionId, BigDecimal workflowId, BigDecimal ruleTypeId, String ruleTypeName, BigDecimal ruleStatusId, String ruleStatusName, String ruleName, String ruleDescription, String notes, BigDecimal createdById, String createdByFullName, Date createdDatetime, BigDecimal modifiedById, String modifiedByFullName, Date modifiedDatetime, Date crc, String recordStatus) {
       this.ruleId = ruleId;
       this.transitionId = transitionId;
       this.workflowId = workflowId;
       this.ruleTypeId = ruleTypeId;
       this.ruleTypeName = ruleTypeName;
       this.ruleStatusId = ruleStatusId;
       this.ruleStatusName = ruleStatusName;
       this.ruleName = ruleName;
       this.ruleDescription = ruleDescription;
       this.notes = notes;
       this.createdById = createdById;
       this.createdByFullName = createdByFullName;
       this.createdDatetime = createdDatetime;
       this.modifiedById = modifiedById;
       this.modifiedByFullName = modifiedByFullName;
       this.modifiedDatetime = modifiedDatetime;
       this.crc = crc;
       this.recordStatus = recordStatus;
    }
   

    @Id
    @Column(name="RULE_ID", nullable=false, length=20)
    public BigDecimal getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(BigDecimal ruleId) {
        this.ruleId = ruleId;
    }

    
    @Column(name="TRANSITION_ID", nullable=false, length=20)
    public BigDecimal getTransitionId() {
        return this.transitionId;
    }
    
    public void setTransitionId(BigDecimal transitionId) {
        this.transitionId = transitionId;
    }

    
    @Column(name="WORKFLOW_ID", nullable=false, length=20)
    public BigDecimal getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(BigDecimal workflowId) {
        this.workflowId = workflowId;
    }

    
    @Column(name="RULE_TYPE_ID", nullable=false, length=20)
    public BigDecimal getRuleTypeId() {
        return this.ruleTypeId;
    }
    
    public void setRuleTypeId(BigDecimal ruleTypeId) {
        this.ruleTypeId = ruleTypeId;
    }

    
    @Column(name="RULE_TYPE_NAME", nullable=false, length=80)
    public String getRuleTypeName() {
        return this.ruleTypeName;
    }
    
    public void setRuleTypeName(String ruleTypeName) {
        this.ruleTypeName = ruleTypeName;
    }

    
    @Column(name="RULE_STATUS_ID", nullable=false, length=20)
    public BigDecimal getRuleStatusId() {
        return this.ruleStatusId;
    }
    
    public void setRuleStatusId(BigDecimal ruleStatusId) {
        this.ruleStatusId = ruleStatusId;
    }

    
    @Column(name="RULE_STATUS_NAME", nullable=false, length=80)
    public String getRuleStatusName() {
        return this.ruleStatusName;
    }
    
    public void setRuleStatusName(String ruleStatusName) {
        this.ruleStatusName = ruleStatusName;
    }

    
    @Column(name="RULE_NAME", nullable=false, length=80)
    public String getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    
    @Column(name="RULE_DESCRIPTION", nullable=false, length=500)
    public String getRuleDescription() {
        return this.ruleDescription;
    }
    
    public void setRuleDescription(String ruleDescription) {
        this.ruleDescription = ruleDescription;
    }

    
    @Column(name="NOTES", nullable=false, length=4000)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public BigDecimal getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(BigDecimal createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="CREATED_BY_FULL_NAME", nullable=false, length=240)
    public String getCreatedByFullName() {
        return this.createdByFullName;
    }
    
    public void setCreatedByFullName(String createdByFullName) {
        this.createdByFullName = createdByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    
    @Column(name="MODIFIED_BY_ID", nullable=false, length=20)
    public BigDecimal getModifiedById() {
        return this.modifiedById;
    }
    
    public void setModifiedById(BigDecimal modifiedById) {
        this.modifiedById = modifiedById;
    }

    
    @Column(name="MODIFIED_BY_FULL_NAME", nullable=false, length=240)
    public String getModifiedByFullName() {
        return this.modifiedByFullName;
    }
    
    public void setModifiedByFullName(String modifiedByFullName) {
        this.modifiedByFullName = modifiedByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFIED_DATETIME", nullable=false, length=7)
    public Date getModifiedDatetime() {
        return this.modifiedDatetime;
    }
    
    public void setModifiedDatetime(Date modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("ruleId", getRuleId())
            .append("transitionId", getTransitionId())
            .append("workflowId", getWorkflowId())
            .append("ruleTypeId", getRuleTypeId())
            .append("ruleTypeName", getRuleTypeName())
            .append("ruleStatusId", getRuleStatusId())
            .append("ruleStatusName", getRuleStatusName())
            .append("ruleName", getRuleName())
            .append("ruleDescription", getRuleDescription())
            .append("notes", getNotes())
            .append("createdById", getCreatedById())
            .append("createdByFullName", getCreatedByFullName())
            .append("createdDatetime", getCreatedDatetime())
            .append("modifiedById", getModifiedById())
            .append("modifiedByFullName", getModifiedByFullName())
            .append("modifiedDatetime", getModifiedDatetime())
            .append("crc", getCrc())
            .append("recordStatus", getRecordStatus())
            .toString();
    }

}
