/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductVersionPK generated by hbm2java
 */
@Embeddable
public class ProductVersionPK implements Serializable {


     private String product;
     private Integer majorVersion;
     private Integer minorVersion;
     private Integer subMinorVersion;
     private Integer buildVersion;

    public ProductVersionPK() {
    }

    public ProductVersionPK(String product, Integer majorVersion, Integer minorVersion, Integer subMinorVersion, Integer buildVersion) {
       this.product = product;
       this.majorVersion = majorVersion;
       this.minorVersion = minorVersion;
       this.subMinorVersion = subMinorVersion;
       this.buildVersion = buildVersion;
    }
   


    @Column(name="PRODUCT", nullable=false, length=40)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }


    @Column(name="MAJOR_VERSION", nullable=false, length=3)
    public Integer getMajorVersion() {
        return this.majorVersion;
    }
    
    public void setMajorVersion(Integer majorVersion) {
        this.majorVersion = majorVersion;
    }


    @Column(name="MINOR_VERSION", nullable=false, length=3)
    public Integer getMinorVersion() {
        return this.minorVersion;
    }
    
    public void setMinorVersion(Integer minorVersion) {
        this.minorVersion = minorVersion;
    }


    @Column(name="SUB_MINOR_VERSION", nullable=false, length=3)
    public Integer getSubMinorVersion() {
        return this.subMinorVersion;
    }
    
    public void setSubMinorVersion(Integer subMinorVersion) {
        this.subMinorVersion = subMinorVersion;
    }


    @Column(name="BUILD_VERSION", nullable=false, length=3)
    public Integer getBuildVersion() {
        return this.buildVersion;
    }
    
    public void setBuildVersion(Integer buildVersion) {
        this.buildVersion = buildVersion;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("product", getProduct())
            .append("majorVersion", getMajorVersion())
            .append("minorVersion", getMinorVersion())
            .append("subMinorVersion", getSubMinorVersion())
            .append("buildVersion", getBuildVersion())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof ProductVersionPK) ) return false;
        ProductVersionPK castOther = (ProductVersionPK) other;
        return new EqualsBuilder()
            .append(this.getProduct(), castOther.getProduct())
            .append(this.getMajorVersion(), castOther.getMajorVersion())
            .append(this.getMinorVersion(), castOther.getMinorVersion())
            .append(this.getSubMinorVersion(), castOther.getSubMinorVersion())
            .append(this.getBuildVersion(), castOther.getBuildVersion())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getProduct())
            .append(getMajorVersion())
            .append(getMinorVersion())
            .append(getSubMinorVersion())
            .append(getBuildVersion())
            .toHashCode();
    }

}
