/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QrtzFiredTrigger generated by hbm2java
 */
@Entity
@Table(name="QRTZ_FIRED_TRIGGERS"
)
public class QrtzFiredTrigger implements Serializable {


     private String entryId;
     private String triggerName;
     private String triggerGroup;
     private String isVolatile;
     private String instanceName;
     private long firedTime;
     private String state;
     private String jobName;
     private String jobGroup;
     private String isStateful;
     private String requestsRecovery;

    public QrtzFiredTrigger() {
    }

	
    public QrtzFiredTrigger(String entryId, String triggerName, String triggerGroup, String isVolatile, String instanceName, long firedTime, String state) {
        this.entryId = entryId;
        this.triggerName = triggerName;
        this.triggerGroup = triggerGroup;
        this.isVolatile = isVolatile;
        this.instanceName = instanceName;
        this.firedTime = firedTime;
        this.state = state;
    }
    public QrtzFiredTrigger(String entryId, String triggerName, String triggerGroup, String isVolatile, String instanceName, long firedTime, String state, String jobName, String jobGroup, String isStateful, String requestsRecovery) {
       this.entryId = entryId;
       this.triggerName = triggerName;
       this.triggerGroup = triggerGroup;
       this.isVolatile = isVolatile;
       this.instanceName = instanceName;
       this.firedTime = firedTime;
       this.state = state;
       this.jobName = jobName;
       this.jobGroup = jobGroup;
       this.isStateful = isStateful;
       this.requestsRecovery = requestsRecovery;
    }
   
     @Id 

    
    @Column(name="ENTRY_ID", nullable=false)
    public String getEntryId() {
        return this.entryId;
    }
    
    public void setEntryId(String entryId) {
        this.entryId = entryId;
    }

    
    @Column(name="TRIGGER_NAME", nullable=false, length=80)
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    
    @Column(name="TRIGGER_GROUP", nullable=false, length=80)
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    
    @Column(name="IS_VOLATILE", nullable=false, length=1)
    public String getIsVolatile() {
        return this.isVolatile;
    }
    
    public void setIsVolatile(String isVolatile) {
        this.isVolatile = isVolatile;
    }

    
    @Column(name="INSTANCE_NAME", nullable=false, length=80)
    public String getInstanceName() {
        return this.instanceName;
    }
    
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    
    @Column(name="FIRED_TIME", nullable=false, length=13)
    public long getFiredTime() {
        return this.firedTime;
    }
    
    public void setFiredTime(long firedTime) {
        this.firedTime = firedTime;
    }

    
    @Column(name="STATE", nullable=false, length=16)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="JOB_NAME", length=80)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="JOB_GROUP", length=80)
    public String getJobGroup() {
        return this.jobGroup;
    }
    
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    
    @Column(name="IS_STATEFUL", length=1)
    public String getIsStateful() {
        return this.isStateful;
    }
    
    public void setIsStateful(String isStateful) {
        this.isStateful = isStateful;
    }

    
    @Column(name="REQUESTS_RECOVERY", length=1)
    public String getRequestsRecovery() {
        return this.requestsRecovery;
    }
    
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("entryId", getEntryId())
            .toString();
    }

}
