/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnAuthenticatorType generated by hbm2java
 */
@Entity
@Table(name = "PN_AUTHENTICATOR_TYPE")
public class PnAuthenticatorType implements java.io.Serializable {

	private String type;

	private String description;

	private String recordStatus;

	private Set pnAuthenticators = new HashSet(0);

	public PnAuthenticatorType() {
	}

	public PnAuthenticatorType(String type, String recordStatus) {
		this.type = type;
		this.recordStatus = recordStatus;
	}

	public PnAuthenticatorType(String type, String description, String recordStatus, Set pnAuthenticators) {
		this.type = type;
		this.description = description;
		this.recordStatus = recordStatus;
		this.pnAuthenticators = pnAuthenticators;
	}

	/** minimal constructor */
	public PnAuthenticatorType(String type, String recordStatus, Set pnAuthenticators) {
		this.type = type;
		this.recordStatus = recordStatus;
		this.pnAuthenticators = pnAuthenticators;
	}

	@Id
	@Column(name = "TYPE", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "DESCRIPTION", length = 240)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, targetEntity = PnAuthenticator.class)
	@Transient
	public Set getPnAuthenticators() {
		return this.pnAuthenticators;
	}

	public void setPnAuthenticators(Set pnAuthenticators) {
		this.pnAuthenticators = pnAuthenticators;
	}
}
