/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBaselineHasTask generated by hbm2java
 */
@Entity
@Table(name = "PN_BASELINE_HAS_TASK")
public class PnBaselineHasTask implements java.io.Serializable {

	private PnBaselineHasTaskPK comp_id;

	private Integer taskVersionId;

	private PnBaseline pnBaseline;

	public PnBaselineHasTask() {
	}

	public PnBaselineHasTask(PnBaselineHasTaskPK comp_id, Integer taskVersionId) {
		this.comp_id = comp_id;
		this.taskVersionId = taskVersionId;
	}

	public PnBaselineHasTask(PnBaselineHasTaskPK comp_id, Integer taskVersionId, PnBaseline pnBaseline) {
		this.comp_id = comp_id;
		this.taskVersionId = taskVersionId;
		this.pnBaseline = pnBaseline;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "baselineId", column = @Column(name = "BASELINE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "taskId", column = @Column(name = "TASK_ID", nullable = false, length = 20)) })
	public PnBaselineHasTaskPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnBaselineHasTaskPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "TASK_VERSION_ID", nullable = false, length = 20)
	public Integer getTaskVersionId() {
		return this.taskVersionId;
	}

	public void setTaskVersionId(Integer taskVersionId) {
		this.taskVersionId = taskVersionId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnBaseline.class)
	@JoinColumn(name = "BASELINE_ID", insertable = false, updatable = false)
	public PnBaseline getPnBaseline() {
		return this.pnBaseline;
	}

	public void setPnBaseline(PnBaseline pnBaseline) {
		this.pnBaseline = pnBaseline;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnBaselineHasTask))
			return false;
		PnBaselineHasTask castOther = (PnBaselineHasTask) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
