/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnCodeType generated by hbm2java
 */
@Entity
@Table(name = "PN_CODE_TYPE")
public class PnCodeType implements java.io.Serializable {

	/** identifier field */
	private Integer codeTypeId;

	/** nullable persistent field */
	private String codeTypeName;

	/** nullable persistent field */
	private String description;

	/** persistent field */
	private Set pnGlobalCodes = new HashSet(0);

	/** persistent field */
	private Set pnCustomCodes = new HashSet(0);

	public PnCodeType() {
	}

	public PnCodeType(Integer codeTypeId) {
		this.codeTypeId = codeTypeId;
	}

	public PnCodeType(Integer codeTypeId, String codeTypeName, String description, Set pnGlobalCodes, Set pnCustomCodes) {
		this.codeTypeId = codeTypeId;
		this.codeTypeName = codeTypeName;
		this.description = description;
		this.pnGlobalCodes = pnGlobalCodes;
		this.pnCustomCodes = pnCustomCodes;
	}

	/** minimal constructor */
	public PnCodeType(Integer codeTypeId, Set pnGlobalCodes, Set pnCustomCodes) {
		this.codeTypeId = codeTypeId;
		this.pnGlobalCodes = pnGlobalCodes;
		this.pnCustomCodes = pnCustomCodes;
	}

	@Id
	@Column(name = "CODE_TYPE_ID", nullable = false)
	public Integer getCodeTypeId() {
		return this.codeTypeId;
	}

	public void setCodeTypeId(Integer codeTypeId) {
		this.codeTypeId = codeTypeId;
	}

	@Column(name = "CODE_TYPE_NAME", length = 80)
	public String getCodeTypeName() {
		return this.codeTypeName;
	}

	public void setCodeTypeName(String codeTypeName) {
		this.codeTypeName = codeTypeName;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnCodeType", targetEntity = PnGlobalCode.class)
	@Transient
	public Set getPnGlobalCodes() {
		return this.pnGlobalCodes;
	}

	public void setPnGlobalCodes(Set pnGlobalCodes) {
		this.pnGlobalCodes = pnGlobalCodes;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnCodeType", targetEntity = PnCustomCode.class)
	@Transient
	public Set getPnCustomCodes() {
		return this.pnCustomCodes;
	}

	public void setPnCustomCodes(Set pnCustomCodes) {
		this.pnCustomCodes = pnCustomCodes;
	}

	public String toString() {
		return new ToStringBuilder(this).append("codeTypeId", getCodeTypeId()).toString();
	}

}
