/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocContainerHasObjectPK generated by hbm2java
 */
@Embeddable
public class PnDocContainerHasObjectPK  implements java.io.Serializable {

    /** identifier field */
    private Integer docContainerId;

    /** identifier field */
    private Integer objectId;

    public PnDocContainerHasObjectPK() {
    }

    public PnDocContainerHasObjectPK(Integer docContainerId, Integer objectId) {
       this.docContainerId = docContainerId;
       this.objectId = objectId;
    }
   


    @Column(name="DOC_CONTAINER_ID", nullable=false, length=20)
    public Integer getDocContainerId() {
        return this.docContainerId;
    }
    
    public void setDocContainerId(Integer docContainerId) {
        this.docContainerId = docContainerId;
    }


    @Column(name="OBJECT_ID", nullable=false, length=20)
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docContainerId", getDocContainerId())
            .append("objectId", getObjectId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocContainerHasObjectPK) ) return false;
        PnDocContainerHasObjectPK castOther = (PnDocContainerHasObjectPK) other;
        return new EqualsBuilder()
            .append(this.getDocContainerId(), castOther.getDocContainerId())
            .append(this.getObjectId(), castOther.getObjectId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getDocContainerId())
            .append(getObjectId())
            .toHashCode();
    }
	
}