/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocDelHistoryView generated by hbm2java
 */
@Entity
@Table(name="PN_DOC_DEL_HISTORY_VIEW"
)
public class PnDocDelHistoryView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal documentId;

    /** identifier field */
    private String documentName;

    /** identifier field */
    private BigDecimal docHistoryId;

    /** identifier field */
    private String action;

    /** identifier field */
    private String actionName;

    /** identifier field */
    private BigDecimal actionById;

    /** identifier field */
    private String actionBy;

    /** identifier field */
    private Date actionDate;

    /** identifier field */
    private String actionComment;

    public PnDocDelHistoryView() {
    }

    public PnDocDelHistoryView(BigDecimal documentId, String documentName, BigDecimal docHistoryId, String action, String actionName, BigDecimal actionById, String actionBy, Date actionDate, String actionComment) {
       this.documentId = documentId;
       this.documentName = documentName;
       this.docHistoryId = docHistoryId;
       this.action = action;
       this.actionName = actionName;
       this.actionById = actionById;
       this.actionBy = actionBy;
       this.actionDate = actionDate;
       this.actionComment = actionComment;
    }
   

    
    @Column(name="DOCUMENT_ID", nullable=false, length=20)
    public BigDecimal getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(BigDecimal documentId) {
        this.documentId = documentId;
    }

    
    @Column(name="DOCUMENT_NAME", nullable=false, length=256)
    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    
    @Column(name="DOC_HISTORY_ID", nullable=false, length=20)
    public BigDecimal getDocHistoryId() {
        return this.docHistoryId;
    }
    
    public void setDocHistoryId(BigDecimal docHistoryId) {
        this.docHistoryId = docHistoryId;
    }

    
    @Column(name="ACTION", nullable=false, length=80)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="ACTION_NAME", nullable=false, length=80)
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    
    @Column(name="ACTION_BY_ID", nullable=false, length=20)
    public BigDecimal getActionById() {
        return this.actionById;
    }
    
    public void setActionById(BigDecimal actionById) {
        this.actionById = actionById;
    }

    
    @Column(name="ACTION_BY", nullable=false, length=101)
    public String getActionBy() {
        return this.actionBy;
    }
    
    public void setActionBy(String actionBy) {
        this.actionBy = actionBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTION_DATE", nullable=false, length=7)
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    
    @Column(name="ACTION_COMMENT", nullable=false)
    public String getActionComment() {
        return this.actionComment;
    }
    
    public void setActionComment(String actionComment) {
        this.actionComment = actionComment;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("documentId", getDocumentId())
            .append("documentName", getDocumentName())
            .append("docHistoryId", getDocHistoryId())
            .append("action", getAction())
            .append("actionName", getActionName())
            .append("actionById", getActionById())
            .append("actionBy", getActionBy())
            .append("actionDate", getActionDate())
            .append("actionComment", getActionComment())
            .toString();
    }

}


