/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeHistoryView generated by hbm2java
 */
@Entity
@Table(name="PN_ENVELOPE_HISTORY_VIEW"
)
public class PnEnvelopeHistoryView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal historyId;

    /** identifier field */
    private BigDecimal envelopeId;

    /** identifier field */
    private String envelopeName;

    /** identifier field */
    private String envelopeDescription;

    /** identifier field */
    private BigDecimal actionById;

    /** identifier field */
    private String actionByFullName;

    /** identifier field */
    private BigDecimal historyActionId;

    /** identifier field */
    private String actionName;

    /** identifier field */
    private String actionDescription;

    /** identifier field */
    private Date actionDatetime;

    /** identifier field */
    private BigDecimal historyMessageId;

    /** identifier field */
    private Date crc;

    /** identifier field */
    private String recordStatus;

    public PnEnvelopeHistoryView() {
    }

    public PnEnvelopeHistoryView(BigDecimal historyId, BigDecimal envelopeId, String envelopeName, String envelopeDescription, BigDecimal actionById, String actionByFullName, BigDecimal historyActionId, String actionName, String actionDescription, Date actionDatetime, BigDecimal historyMessageId, Date crc, String recordStatus) {
       this.historyId = historyId;
       this.envelopeId = envelopeId;
       this.envelopeName = envelopeName;
       this.envelopeDescription = envelopeDescription;
       this.actionById = actionById;
       this.actionByFullName = actionByFullName;
       this.historyActionId = historyActionId;
       this.actionName = actionName;
       this.actionDescription = actionDescription;
       this.actionDatetime = actionDatetime;
       this.historyMessageId = historyMessageId;
       this.crc = crc;
       this.recordStatus = recordStatus;
    }
   

    
    @Column(name="HISTORY_ID", nullable=false, length=20)
    public BigDecimal getHistoryId() {
        return this.historyId;
    }
    
    public void setHistoryId(BigDecimal historyId) {
        this.historyId = historyId;
    }

    
    @Column(name="ENVELOPE_ID", nullable=false, length=20)
    public BigDecimal getEnvelopeId() {
        return this.envelopeId;
    }
    
    public void setEnvelopeId(BigDecimal envelopeId) {
        this.envelopeId = envelopeId;
    }

    
    @Column(name="ENVELOPE_NAME", nullable=false, length=80)
    public String getEnvelopeName() {
        return this.envelopeName;
    }
    
    public void setEnvelopeName(String envelopeName) {
        this.envelopeName = envelopeName;
    }

    
    @Column(name="ENVELOPE_DESCRIPTION", nullable=false, length=500)
    public String getEnvelopeDescription() {
        return this.envelopeDescription;
    }
    
    public void setEnvelopeDescription(String envelopeDescription) {
        this.envelopeDescription = envelopeDescription;
    }

    
    @Column(name="ACTION_BY_ID", nullable=false, length=20)
    public BigDecimal getActionById() {
        return this.actionById;
    }
    
    public void setActionById(BigDecimal actionById) {
        this.actionById = actionById;
    }

    
    @Column(name="ACTION_BY_FULL_NAME", nullable=false, length=240)
    public String getActionByFullName() {
        return this.actionByFullName;
    }
    
    public void setActionByFullName(String actionByFullName) {
        this.actionByFullName = actionByFullName;
    }

    
    @Column(name="HISTORY_ACTION_ID", nullable=false, length=20)
    public BigDecimal getHistoryActionId() {
        return this.historyActionId;
    }
    
    public void setHistoryActionId(BigDecimal historyActionId) {
        this.historyActionId = historyActionId;
    }

    
    @Column(name="ACTION_NAME", nullable=false, length=80)
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    
    @Column(name="ACTION_DESCRIPTION", nullable=false, length=500)
    public String getActionDescription() {
        return this.actionDescription;
    }
    
    public void setActionDescription(String actionDescription) {
        this.actionDescription = actionDescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTION_DATETIME", nullable=false, length=7)
    public Date getActionDatetime() {
        return this.actionDatetime;
    }
    
    public void setActionDatetime(Date actionDatetime) {
        this.actionDatetime = actionDatetime;
    }

    
    @Column(name="HISTORY_MESSAGE_ID", nullable=false, length=20)
    public BigDecimal getHistoryMessageId() {
        return this.historyMessageId;
    }
    
    public void setHistoryMessageId(BigDecimal historyMessageId) {
        this.historyMessageId = historyMessageId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("historyId", getHistoryId())
            .append("envelopeId", getEnvelopeId())
            .append("envelopeName", getEnvelopeName())
            .append("envelopeDescription", getEnvelopeDescription())
            .append("actionById", getActionById())
            .append("actionByFullName", getActionByFullName())
            .append("historyActionId", getHistoryActionId())
            .append("actionName", getActionName())
            .append("actionDescription", getActionDescription())
            .append("actionDatetime", getActionDatetime())
            .append("historyMessageId", getHistoryMessageId())
            .append("crc", getCrc())
            .append("recordStatus", getRecordStatus())
            .toString();
    }

}


