/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnInvitedUser generated by hbm2java
 */
@Entity
@Table(name="PN_INVITED_USERS"
)
public class PnInvitedUser  implements java.io.Serializable {

    /** identifier field */
    private Integer invitationCode;

    /** persistent field */
    private Integer spaceId;

    /** persistent field */
    private String inviteeEmail;

    /** persistent field */
    private Date dateInvited;

    /** nullable persistent field */
    private Date dateResponded;

    /** nullable persistent field */
    private String inviteeFirstname;

    /** nullable persistent field */
    private String inviteeLastname;

    /** nullable persistent field */
    private String inviteeResponsibilities;

    /** persistent field */
    private String invitedStatus;

    /** persistent field */
    private int invitationActedUpon;

    /** persistent field */
    private Integer personId;

    private PnPerson pnPerson;
    
    public PnInvitedUser() {
    }

    public PnInvitedUser(Integer invitationCode, Integer spaceId, String inviteeEmail, Date dateInvited, String invitedStatus, int invitationActedUpon, Integer personId) {
        this.invitationCode = invitationCode;
        this.spaceId = spaceId;
        this.inviteeEmail = inviteeEmail;
        this.dateInvited = dateInvited;
        this.invitedStatus = invitedStatus;
        this.invitationActedUpon = invitationActedUpon;
        this.personId = personId;
    }
    
    public PnInvitedUser(Integer invitationCode, Integer spaceId, String inviteeEmail, Date dateInvited, Date dateResponded, String inviteeFirstname, String inviteeLastname, String inviteeResponsibilities, String invitedStatus, int invitationActedUpon, Integer personId, PnPerson pnPerson) {
       this.invitationCode = invitationCode;
       this.spaceId = spaceId;
       this.inviteeEmail = inviteeEmail;
       this.dateInvited = dateInvited;
       this.dateResponded = dateResponded;
       this.inviteeFirstname = inviteeFirstname;
       this.inviteeLastname = inviteeLastname;
       this.inviteeResponsibilities = inviteeResponsibilities;
       this.invitedStatus = invitedStatus;
       this.invitationActedUpon = invitationActedUpon;
       this.personId = personId;
       this.pnPerson = pnPerson;
    }
   
    /** minimal constructor */
    public PnInvitedUser(Integer invitationCode, Integer spaceId, String inviteeEmail, Date dateInvited, String invitedStatus, int invitationActedUpon, Integer personId, net.project.hibernate.model.PnPerson pnPerson) {
        this.invitationCode = invitationCode;
        this.spaceId = spaceId;
        this.inviteeEmail = inviteeEmail;
        this.dateInvited = dateInvited;
        this.invitedStatus = invitedStatus;
        this.invitationActedUpon = invitationActedUpon;
        this.personId = personId;
        this.pnPerson = pnPerson;
    }
	
    @Id 
    @Column(name="INVITATION_CODE", nullable=false)
    public Integer getInvitationCode() {
        return this.invitationCode;
    }
    
    public void setInvitationCode(Integer invitationCode) {
        this.invitationCode = invitationCode;
    }

    
    @Column(name="SPACE_ID", nullable=false, length=20)
    public Integer getSpaceId() {
        return this.spaceId;
    }
    
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    
    @Column(name="INVITEE_EMAIL", nullable=false, length=240)
    public String getInviteeEmail() {
        return this.inviteeEmail;
    }
    
    public void setInviteeEmail(String inviteeEmail) {
        this.inviteeEmail = inviteeEmail;
    }

    
    @Column(name="DATE_INVITED", nullable=false, length=7)
    public Date getDateInvited() {
        return this.dateInvited;
    }
    
    public void setDateInvited(Date dateInvited) {
        this.dateInvited = dateInvited;
    }

    
    @Column(name="DATE_RESPONDED", length=7)
    public Date getDateResponded() {
        return this.dateResponded;
    }
    
    public void setDateResponded(Date dateResponded) {
        this.dateResponded = dateResponded;
    }

    
    @Column(name="INVITEE_FIRSTNAME", length=40)
    public String getInviteeFirstname() {
        return this.inviteeFirstname;
    }
    
    public void setInviteeFirstname(String inviteeFirstname) {
        this.inviteeFirstname = inviteeFirstname;
    }

    
    @Column(name="INVITEE_LASTNAME", length=60)
    public String getInviteeLastname() {
        return this.inviteeLastname;
    }
    
    public void setInviteeLastname(String inviteeLastname) {
        this.inviteeLastname = inviteeLastname;
    }

    
    @Column(name="INVITEE_RESPONSIBILITIES", length=500)
    public String getInviteeResponsibilities() {
        return this.inviteeResponsibilities;
    }
    
    public void setInviteeResponsibilities(String inviteeResponsibilities) {
        this.inviteeResponsibilities = inviteeResponsibilities;
    }

    
    @Column(name="INVITED_STATUS", nullable=false, length=20)
    public String getInvitedStatus() {
        return this.invitedStatus;
    }
    
    public void setInvitedStatus(String invitedStatus) {
        this.invitedStatus = invitedStatus;
    }

    
    @Column(name="INVITATION_ACTED_UPON", nullable=false, length=1)
    public int getInvitationActedUpon() {
        return this.invitationActedUpon;
    }
    
    public void setInvitationActedUpon(int invitationActedUpon) {
        this.invitationActedUpon = invitationActedUpon;
    }

    
    @Column(name="PERSON_ID", nullable=false, length=20)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="INVITOR_ID")
    public PnPerson getPnPerson() {
        return this.pnPerson;
    }
    
    public void setPnPerson(PnPerson pnPerson) {
        this.pnPerson = pnPerson;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("invitationCode", getInvitationCode())
            .toString();
    }



}


