/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLdapDirectoryConfig generated by hbm2java
 */
@Entity
@Table(name = "PN_LDAP_DIRECTORY_CONFIG")
public class PnLdapDirectoryConfig implements java.io.Serializable {

	/** identifier field */
	private Integer contextId;

	/** nullable persistent field */
	private String hostnameValues;

	/** nullable persistent field */
	private String secureHostnameValues;

	/** nullable persistent field */
	private Integer isUseSsl;

	/** nullable persistent field */
	private String searchBaseDn;

	/** nullable persistent field */
	private String searchTypeId;

	/** nullable persistent field */
	private String usernameAttributeName;

	/** nullable persistent field */
	private String searchSubtrees;

	/** nullable persistent field */
	private String nonAuthAccessTypeId;

	/** nullable persistent field */
	private String specificUserRelativeDn;

	/** nullable persistent field */
	private String specificUserPassword;

	/** nullable persistent field */
	private Integer isAvailableDirectorySearch;

	/** nullable persistent field */
	private String directorySearchDisplayName;

	/** nullable persistent field */
	private String searchFilterExpression;

	/** nullable persistent field */
	private Integer allowsAutomaticRegistration;

	/** persistent field */
	private Set pnLdapDirectoryAttrMaps = new HashSet(0);

	public PnLdapDirectoryConfig() {
	}

	public PnLdapDirectoryConfig(Integer contextId) {
		this.contextId = contextId;
	}

	public PnLdapDirectoryConfig(Integer contextId, String hostnameValues, String secureHostnameValues,
			Integer isUseSsl, String searchBaseDn, String searchTypeId, String usernameAttributeName,
			String searchSubtrees, String nonAuthAccessTypeId, String specificUserRelativeDn,
			String specificUserPassword, Integer isAvailableDirectorySearch, String directorySearchDisplayName,
			String searchFilterExpression, Integer allowsAutomaticRegistration, Set pnLdapDirectoryAttrMaps) {
		this.contextId = contextId;
		this.hostnameValues = hostnameValues;
		this.secureHostnameValues = secureHostnameValues;
		this.isUseSsl = isUseSsl;
		this.searchBaseDn = searchBaseDn;
		this.searchTypeId = searchTypeId;
		this.usernameAttributeName = usernameAttributeName;
		this.searchSubtrees = searchSubtrees;
		this.nonAuthAccessTypeId = nonAuthAccessTypeId;
		this.specificUserRelativeDn = specificUserRelativeDn;
		this.specificUserPassword = specificUserPassword;
		this.isAvailableDirectorySearch = isAvailableDirectorySearch;
		this.directorySearchDisplayName = directorySearchDisplayName;
		this.searchFilterExpression = searchFilterExpression;
		this.allowsAutomaticRegistration = allowsAutomaticRegistration;
		this.pnLdapDirectoryAttrMaps = pnLdapDirectoryAttrMaps;
	}

	/** minimal constructor */
	public PnLdapDirectoryConfig(Integer contextId, Set pnLdapDirectoryAttrMaps) {
		this.contextId = contextId;
		this.pnLdapDirectoryAttrMaps = pnLdapDirectoryAttrMaps;
	}

	@Id
	@Column(name = "CONTEXT_ID", nullable = false)
	public Integer getContextId() {
		return this.contextId;
	}

	public void setContextId(Integer contextId) {
		this.contextId = contextId;
	}

	@Column(name = "HOSTNAME_VALUES", length = 4000)
	public String getHostnameValues() {
		return this.hostnameValues;
	}

	public void setHostnameValues(String hostnameValues) {
		this.hostnameValues = hostnameValues;
	}

	@Column(name = "SECURE_HOSTNAME_VALUES", length = 4000)
	public String getSecureHostnameValues() {
		return this.secureHostnameValues;
	}

	public void setSecureHostnameValues(String secureHostnameValues) {
		this.secureHostnameValues = secureHostnameValues;
	}

	@Column(name = "IS_USE_SSL", length = 1)
	public Integer getIsUseSsl() {
		return this.isUseSsl;
	}

	public void setIsUseSsl(Integer isUseSsl) {
		this.isUseSsl = isUseSsl;
	}

	@Column(name = "SEARCH_BASE_DN", length = 4000)
	public String getSearchBaseDn() {
		return this.searchBaseDn;
	}

	public void setSearchBaseDn(String searchBaseDn) {
		this.searchBaseDn = searchBaseDn;
	}

	@Column(name = "SEARCH_TYPE_ID", length = 80)
	public String getSearchTypeId() {
		return this.searchTypeId;
	}

	public void setSearchTypeId(String searchTypeId) {
		this.searchTypeId = searchTypeId;
	}

	@Column(name = "USERNAME_ATTRIBUTE_NAME", length = 1000)
	public String getUsernameAttributeName() {
		return this.usernameAttributeName;
	}

	public void setUsernameAttributeName(String usernameAttributeName) {
		this.usernameAttributeName = usernameAttributeName;
	}

	@Column(name = "SEARCH_SUBTREES", length = 1000)
	public String getSearchSubtrees() {
		return this.searchSubtrees;
	}

	public void setSearchSubtrees(String searchSubtrees) {
		this.searchSubtrees = searchSubtrees;
	}

	@Column(name = "NON_AUTH_ACCESS_TYPE_ID", length = 80)
	public String getNonAuthAccessTypeId() {
		return this.nonAuthAccessTypeId;
	}

	public void setNonAuthAccessTypeId(String nonAuthAccessTypeId) {
		this.nonAuthAccessTypeId = nonAuthAccessTypeId;
	}

	@Column(name = "SPECIFIC_USER_RELATIVE_DN", length = 4000)
	public String getSpecificUserRelativeDn() {
		return this.specificUserRelativeDn;
	}

	public void setSpecificUserRelativeDn(String specificUserRelativeDn) {
		this.specificUserRelativeDn = specificUserRelativeDn;
	}

	@Column(name = "SPECIFIC_USER_PASSWORD", length = 1000)
	public String getSpecificUserPassword() {
		return this.specificUserPassword;
	}

	public void setSpecificUserPassword(String specificUserPassword) {
		this.specificUserPassword = specificUserPassword;
	}

	@Column(name = "IS_AVAILABLE_DIRECTORY_SEARCH", length = 1)
	public Integer getIsAvailableDirectorySearch() {
		return this.isAvailableDirectorySearch;
	}

	public void setIsAvailableDirectorySearch(Integer isAvailableDirectorySearch) {
		this.isAvailableDirectorySearch = isAvailableDirectorySearch;
	}

	@Column(name = "DIRECTORY_SEARCH_DISPLAY_NAME", length = 80)
	public String getDirectorySearchDisplayName() {
		return this.directorySearchDisplayName;
	}

	public void setDirectorySearchDisplayName(String directorySearchDisplayName) {
		this.directorySearchDisplayName = directorySearchDisplayName;
	}

	@Column(name = "SEARCH_FILTER_EXPRESSION", length = 1000)
	public String getSearchFilterExpression() {
		return this.searchFilterExpression;
	}

	public void setSearchFilterExpression(String searchFilterExpression) {
		this.searchFilterExpression = searchFilterExpression;
	}

	@Column(name = "ALLOWS_AUTOMATIC_REGISTRATION", length = 1)
	public Integer getAllowsAutomaticRegistration() {
		return this.allowsAutomaticRegistration;
	}

	public void setAllowsAutomaticRegistration(Integer allowsAutomaticRegistration) {
		this.allowsAutomaticRegistration = allowsAutomaticRegistration;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnLdapDirectoryConfig", targetEntity = PnLdapDirectoryAttrMap.class)
	@Transient
	public Set getPnLdapDirectoryAttrMaps() {
		return this.pnLdapDirectoryAttrMaps;
	}

	public void setPnLdapDirectoryAttrMaps(Set pnLdapDirectoryAttrMaps) {
		this.pnLdapDirectoryAttrMaps = pnLdapDirectoryAttrMaps;
	}

	public String toString() {
		return new ToStringBuilder(this).append("contextId", getContextId()).toString();
	}

}
