/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLicenseCertificate generated by hbm2java
 */
@Entity
@Table(name = "PN_LICENSE_CERTIFICATE")
public class PnLicenseCertificate implements java.io.Serializable {

	/** identifier field */
	private Integer certificateId;

	private Set pnLicenses = new HashSet(0);

	public PnLicenseCertificate() {
	}

	public PnLicenseCertificate(Integer certificateId) {
		this.certificateId = certificateId;
	}

	public PnLicenseCertificate(Integer certificateId, Set pnLicenses) {
		this.certificateId = certificateId;
		this.pnLicenses = pnLicenses;
	}

	@Id
	@Column(name = "CERTIFICATE_ID", nullable = false)
	public Integer getCertificateId() {
		return this.certificateId;
	}

	public void setCertificateId(Integer certificateId) {
		this.certificateId = certificateId;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnLicenseCertificate", targetEntity = PnLicense.class)
	@Transient
	public Set getPnLicenses() {
		return this.pnLicenses;
	}

	public void setPnLicenses(Set pnLicenses) {
		this.pnLicenses = pnLicenses;
	}

	public String toString() {
		return new ToStringBuilder(this).append("certificateId", getCertificateId()).toString();
	}

}
