/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnObjectHasDiscussion generated by hbm2java
 */
@Entity
@Table(name = "PN_OBJECT_HAS_DISCUSSION")
public class PnObjectHasDiscussion implements Serializable {

	private PnObjectHasDiscussionPK comp_id;

	private PnObject pnObject;

	private PnDiscussionGroup pnDiscussionGroup;

	public PnObjectHasDiscussion() {
	}

	public PnObjectHasDiscussion(PnObjectHasDiscussionPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnObjectHasDiscussion(PnObjectHasDiscussionPK comp_id, PnObject pnObject, PnDiscussionGroup pnDiscussionGroup) {
		this.comp_id = comp_id;
		this.pnObject = pnObject;
		this.pnDiscussionGroup = pnDiscussionGroup;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "objectId", column = @Column(name = "OBJECT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "discussionGroupId", column = @Column(name = "DISCUSSION_GROUP_ID", nullable = false, length = 20)) })
	public PnObjectHasDiscussionPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnObjectHasDiscussionPK comp_id) {
		this.comp_id = comp_id;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	@JoinColumn(name = "OBJECT_ID", insertable = false, updatable = false)
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDiscussionGroup.class)
	@JoinColumn(name = "DISCUSSION_GROUP_ID", insertable = false, updatable = false)
	public PnDiscussionGroup getPnDiscussionGroup() {
		return this.pnDiscussionGroup;
	}

	public void setPnDiscussionGroup(PnDiscussionGroup pnDiscussionGroup) {
		this.pnDiscussionGroup = pnDiscussionGroup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnObjectHasDiscussion))
			return false;
		PnObjectHasDiscussion castOther = (PnObjectHasDiscussion) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
