/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPersonAllocation generated by hbm2java
 */
@Entity
@Table(name="PN_PERSON_ALLOCATION"
)
public class PnPersonAllocation implements Serializable {


     private PnPersonAllocationPK comp_id;
     private BigDecimal hoursAllocated;
     private Date allocationDate;
     private PnPerson pnPerson;

    public PnPersonAllocation() {
    }

	
    public PnPersonAllocation(PnPersonAllocationPK comp_id) {
        this.comp_id = comp_id;
    }

    public PnPersonAllocation(PnPersonAllocationPK comp_id, BigDecimal hoursAllocated, Date allocationDate, PnPerson pnPerson) {
       this.comp_id = comp_id;
       this.hoursAllocated = hoursAllocated;
       this.allocationDate = allocationDate;
       this.pnPerson = pnPerson;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="spaceId", column=@Column(name="SPACE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="allocationId", column=@Column(name="ALLOCATION_ID", nullable=false, length=20) ) } )
    public PnPersonAllocationPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnPersonAllocationPK comp_id) {
        this.comp_id = comp_id;
    }

    @Column(name="HOURS_ALLOCATED", length=5)
    public BigDecimal getHoursAllocated() {
        return this.hoursAllocated;
    }
    
    public void setHoursAllocated(BigDecimal hoursAllocated) {
        this.hoursAllocated = hoursAllocated;
    }

    @Column(name="ALLOCATION_DATE", length=7)
    public Date getAllocationDate() {
        return this.allocationDate;
    }
    
    public void setAllocationDate(Date allocationDate) {
        this.allocationDate = allocationDate;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="PERSON_ID", insertable=false, updatable=false)
    public PnPerson getPnPerson() {
        return this.pnPerson;
    }
    
    public void setPnPerson(PnPerson pnPerson) {
        this.pnPerson = pnPerson;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPersonAllocation) ) return false;
        PnPersonAllocation castOther = (PnPersonAllocation) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
