/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPersonHasVote generated by hbm2java
 */
@Embeddable
public class PnPersonHasVotePK implements Serializable {

	private Integer personId;

	private Integer voteId;

	public PnPersonHasVotePK() {
	}

	public PnPersonHasVotePK(Integer personId, Integer voteId) {
		this.personId = personId;
		this.voteId = voteId;
	}

	@Column(name = "PERSON_ID", nullable = false, length = 20)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "VOTE_ID", nullable = false, length = 20)
	public Integer getVoteId() {
		return this.voteId;
	}

	public void setVoteId(Integer voteId) {
		this.voteId = voteId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).append("voteId", getVoteId()).toString();
	}

}
