/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnProfCertLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_PROF_CERT_LOOKUP")
public class PnProfCertLookup implements Serializable {

	private Integer profCertCode;

	private String profCertName;

	private String profCertDescription;

	private Set pnPersonHasProfCerts = new HashSet(0);

	public PnProfCertLookup() {
	}

	public PnProfCertLookup(Integer profCertCode, String profCertName) {
		this.profCertCode = profCertCode;
		this.profCertName = profCertName;
	}

	public PnProfCertLookup(Integer profCertCode, String profCertName, Set pnPersonHasProfCerts) {
		this.profCertCode = profCertCode;
		this.profCertName = profCertName;
		this.pnPersonHasProfCerts = pnPersonHasProfCerts;
	}

	public PnProfCertLookup(Integer profCertCode, String profCertName, String profCertDescription,
			Set pnPersonHasProfCerts) {
		this.profCertCode = profCertCode;
		this.profCertName = profCertName;
		this.profCertDescription = profCertDescription;
		this.pnPersonHasProfCerts = pnPersonHasProfCerts;
	}

	@Id
	@Column(name = "PROF_CERT_CODE", nullable = false)
	public Integer getProfCertCode() {
		return this.profCertCode;
	}

	public void setProfCertCode(Integer profCertCode) {
		this.profCertCode = profCertCode;
	}

	@Column(name = "PROF_CERT_NAME", nullable = false, length = 30)
	public String getProfCertName() {
		return this.profCertName;
	}

	public void setProfCertName(String profCertName) {
		this.profCertName = profCertName;
	}

	@Column(name = "PROF_CERT_DESCRIPTION", length = 40)
	public String getProfCertDescription() {
		return this.profCertDescription;
	}

	public void setProfCertDescription(String profCertDescription) {
		this.profCertDescription = profCertDescription;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnProfCertLookup", targetEntity = PnPersonHasProfCert.class)
	@Transient
	public Set getPnPersonHasProfCerts() {
		return this.pnPersonHasProfCerts;
	}

	public void setPnPersonHasProfCerts(Set pnPersonHasProfCerts) {
		this.pnPersonHasProfCerts = pnPersonHasProfCerts;
	}

	public String toString() {
		return new ToStringBuilder(this).append("profCertCode", getProfCertCode()).toString();
	}

}
