/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPropertySheetType generated by hbm2java
 */
@Entity
@Table(name = "PN_PROPERTY_SHEET_TYPE")
public class PnPropertySheetType implements Serializable {

	private Integer propertySheetType;

	private String propertySheetName;

	private String propertySheetDesc;

	private String propertiesTableName;

	private Set pnPropertySheets = new HashSet(0);

	public PnPropertySheetType() {
	}

	public PnPropertySheetType(Integer propertySheetType) {
		this.propertySheetType = propertySheetType;
	}

	public PnPropertySheetType(Integer propertySheetType, String propertySheetName, Set pnPropertySheets) {
		this.propertySheetType = propertySheetType;
		this.propertySheetName = propertySheetName;
		this.pnPropertySheets = pnPropertySheets;
	}

	public PnPropertySheetType(Integer propertySheetType, String propertySheetName, String propertySheetDesc,
			String propertiesTableName, Set pnPropertySheets) {
		this.propertySheetType = propertySheetType;
		this.propertySheetName = propertySheetName;
		this.propertySheetDesc = propertySheetDesc;
		this.propertiesTableName = propertiesTableName;
		this.pnPropertySheets = pnPropertySheets;
	}

	@Id
	@Column(name = "PROPERTY_SHEET_TYPE", nullable = false)
	public Integer getPropertySheetType() {
		return this.propertySheetType;
	}

	public void setPropertySheetType(Integer propertySheetType) {
		this.propertySheetType = propertySheetType;
	}

	@Column(name = "PROPERTY_SHEET_NAME", nullable = false, length = 80)
	public String getPropertySheetName() {
		return this.propertySheetName;
	}

	public void setPropertySheetName(String propertySheetName) {
		this.propertySheetName = propertySheetName;
	}

	@Column(name = "PROPERTY_SHEET_DESC")
	public String getPropertySheetDesc() {
		return this.propertySheetDesc;
	}

	public void setPropertySheetDesc(String propertySheetDesc) {
		this.propertySheetDesc = propertySheetDesc;
	}

	@Column(name = "PROPERTIES_TABLE_NAME", length = 80)
	public String getPropertiesTableName() {
		return this.propertiesTableName;
	}

	public void setPropertiesTableName(String propertiesTableName) {
		this.propertiesTableName = propertiesTableName;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPropertySheetType", targetEntity = PnPropertySheet.class)
	@Transient
	public Set getPnPropertySheets() {
		return this.pnPropertySheets;
	}

	public void setPnPropertySheets(Set pnPropertySheets) {
		this.pnPropertySheets = pnPropertySheets;
	}

	public String toString() {
		return new ToStringBuilder(this).append("propertySheetType", getPropertySheetType()).toString();
	}

}
