/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnSkillHasSubskillPK generated by hbm2java
 */
@Embeddable
public class PnSkillHasSubskillPK implements Serializable {


     private Integer parentSkillId;
     private Integer childSkillId;

    public PnSkillHasSubskillPK() {
    }

    public PnSkillHasSubskillPK(Integer parentSkillId, Integer childSkillId) {
       this.parentSkillId = parentSkillId;
       this.childSkillId = childSkillId;
    }
   


    @Column(name="PARENT_SKILL_ID", nullable=false, length=20)
    public Integer getParentSkillId() {
        return this.parentSkillId;
    }
    
    public void setParentSkillId(Integer parentSkillId) {
        this.parentSkillId = parentSkillId;
    }


    @Column(name="CHILD_SKILL_ID", nullable=false, length=22)
    public Integer getChildSkillId() {
        return this.childSkillId;
    }
    
    public void setChildSkillId(Integer childSkillId) {
        this.childSkillId = childSkillId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("parentSkillId", getParentSkillId())
            .append("childSkillId", getChildSkillId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSkillHasSubskillPK) ) return false;
        PnSkillHasSubskillPK castOther = (PnSkillHasSubskillPK) other;
        return new EqualsBuilder()
            .append(this.getParentSkillId(), castOther.getParentSkillId())
            .append(this.getChildSkillId(), castOther.getChildSkillId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getParentSkillId())
            .append(getChildSkillId())
            .toHashCode();
    }

}
