/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnSubscription generated by hbm2java
 */
@Entity
@Table(name = "PN_SUBSCRIPTION")
public class PnSubscription implements Serializable {

	private Integer subscriptionId;

	private String name;

	private String description;

	private Integer subscriptionTypeId;

	private Date createdDate;

	private Integer createdById;

	private Date modifiedDate;

	private Integer modifiedBy;

	private String recordStatus;

	private Date crc;

	private Integer deliveryInterval;

	private Integer subscriberBatchId;

	private Clob customMessageClob;

	private Set pnObjectTypeSubscriptions = new HashSet(0);

	private Set pnObjectHasSubscriptions = new HashSet(0);

	private Set pnSpaceHasSubscriptions = new HashSet(0);

	private Set pnSubHasNotifyTypes = new HashSet(0);

	private Set pnSubscriptionHasGroups = new HashSet(0);

	private Set pnWorkflowSteps = new HashSet(0);

	public PnSubscription() {
	}

	public PnSubscription(Integer subscriptionId, String name, String recordStatus, Integer subscriberBatchId) {
		this.subscriptionId = subscriptionId;
		this.name = name;
		this.recordStatus = recordStatus;
		this.subscriberBatchId = subscriberBatchId;
	}

	public PnSubscription(Integer subscriptionId, String name, String description, Integer subscriptionTypeId,
			Date createdDate, Integer createdById, Date modifiedDate, Integer modifiedBy, String recordStatus,
			Date crc, Integer deliveryInterval, Integer subscriberBatchId, Clob customMessageClob,
			Set pnObjectTypeSubscriptions, Set pnObjectHasSubscriptions, Set pnSpaceHasSubscriptions,
			Set pnSubHasNotifyTypes, Set pnSubscriptionHasGroups, Set pnWorkflowSteps) {
		this.subscriptionId = subscriptionId;
		this.name = name;
		this.description = description;
		this.subscriptionTypeId = subscriptionTypeId;
		this.createdDate = createdDate;
		this.createdById = createdById;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.recordStatus = recordStatus;
		this.crc = crc;
		this.deliveryInterval = deliveryInterval;
		this.subscriberBatchId = subscriberBatchId;
		this.customMessageClob = customMessageClob;
		this.pnObjectTypeSubscriptions = pnObjectTypeSubscriptions;
		this.pnObjectHasSubscriptions = pnObjectHasSubscriptions;
		this.pnSpaceHasSubscriptions = pnSpaceHasSubscriptions;
		this.pnSubHasNotifyTypes = pnSubHasNotifyTypes;
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	public PnSubscription(Integer subscriptionId, String name, String recordStatus, Integer subscriberBatchId,
			Set pnObjectTypeSubscriptions, Set pnObjectHasSubscriptions, Set pnSpaceHasSubscriptions,
			Set pnSubHasNotifyTypes, Set pnSubscriptionHasGroups, Set pnWorkflowSteps) {
		this.subscriptionId = subscriptionId;
		this.name = name;
		this.recordStatus = recordStatus;
		this.subscriberBatchId = subscriberBatchId;
		this.pnObjectTypeSubscriptions = pnObjectTypeSubscriptions;
		this.pnObjectHasSubscriptions = pnObjectHasSubscriptions;
		this.pnSpaceHasSubscriptions = pnSpaceHasSubscriptions;
		this.pnSubHasNotifyTypes = pnSubHasNotifyTypes;
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	@Id
	@Column(name = "SUBSCRIPTION_ID", nullable = false)
	public Integer getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(Integer subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SUBSCRIPTION_TYPE_ID", length = 20)
	public Integer getSubscriptionTypeId() {
		return this.subscriptionTypeId;
	}

	public void setSubscriptionTypeId(Integer subscriptionTypeId) {
		this.subscriptionTypeId = subscriptionTypeId;
	}

	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY_ID", length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 20)
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "CRC", length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "DELIVERY_INTERVAL", length = 3)
	public Integer getDeliveryInterval() {
		return this.deliveryInterval;
	}

	public void setDeliveryInterval(Integer deliveryInterval) {
		this.deliveryInterval = deliveryInterval;
	}

	@Column(name = "SUBSCRIBER_BATCH_ID", nullable = false, length = 20)
	public Integer getSubscriberBatchId() {
		return this.subscriberBatchId;
	}

	public void setSubscriberBatchId(Integer subscriberBatchId) {
		this.subscriberBatchId = subscriberBatchId;
	}

	@Column(name = "CUSTOM_MESSAGE_CLOB", length = 4000)
	public Clob getCustomMessageClob() {
		return this.customMessageClob;
	}

	public void setCustomMessageClob(Clob customMessageClob) {
		this.customMessageClob = customMessageClob;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnObjectTypeSubscription.class)
	@Transient
	public Set getPnObjectTypeSubscriptions() {
		return this.pnObjectTypeSubscriptions;
	}

	public void setPnObjectTypeSubscriptions(Set pnObjectTypeSubscriptions) {
		this.pnObjectTypeSubscriptions = pnObjectTypeSubscriptions;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnObjectHasSubscription.class)
	@Transient
	public Set getPnObjectHasSubscriptions() {
		return this.pnObjectHasSubscriptions;
	}

	public void setPnObjectHasSubscriptions(Set pnObjectHasSubscriptions) {
		this.pnObjectHasSubscriptions = pnObjectHasSubscriptions;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnSpaceHasSubscription.class)
	@Transient
	public Set getPnSpaceHasSubscriptions() {
		return this.pnSpaceHasSubscriptions;
	}

	public void setPnSpaceHasSubscriptions(Set pnSpaceHasSubscriptions) {
		this.pnSpaceHasSubscriptions = pnSpaceHasSubscriptions;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnSubHasNotifyType.class)
	@Transient
	public Set getPnSubHasNotifyTypes() {
		return this.pnSubHasNotifyTypes;
	}

	public void setPnSubHasNotifyTypes(Set pnSubHasNotifyTypes) {
		this.pnSubHasNotifyTypes = pnSubHasNotifyTypes;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnSubscriptionHasGroup.class)
	@Transient
	public Set getPnSubscriptionHasGroups() {
		return this.pnSubscriptionHasGroups;
	}

	public void setPnSubscriptionHasGroups(Set pnSubscriptionHasGroups) {
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSubscription", targetEntity = PnWorkflowStep.class)
	@Transient
	public Set getPnWorkflowSteps() {
		return this.pnWorkflowSteps;
	}

	public void setPnWorkflowSteps(Set pnWorkflowSteps) {
		this.pnWorkflowSteps = pnWorkflowSteps;
	}

	public String toString() {
		return new ToStringBuilder(this).append("subscriptionId", getSubscriptionId()).toString();
	}

}
