/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkingtimeCalendar generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKINGTIME_CALENDAR")
public class PnWorkingtimeCalendar implements Serializable {

	private Integer calendarId;

	private String isBaseCalendar;

	private String name;

	private String recordStatus;

	private PnPerson pnPerson;

	private Set pnWorkingtimeCalendarEntries = new HashSet(0);

	private Set pnWorkingtimeCalendars = new HashSet(0);

	private PnWorkingtimeCalendar pnWorkingtimeCalendar;

	private PnPlan pnPlan;

	public PnWorkingtimeCalendar() {
	}

	public PnWorkingtimeCalendar(Integer calendarId, String isBaseCalendar, String recordStatus) {
		this.calendarId = calendarId;
		this.isBaseCalendar = isBaseCalendar;
		this.recordStatus = recordStatus;
	}

	public PnWorkingtimeCalendar(Integer calendarId, String isBaseCalendar, String name, String recordStatus,
			net.project.hibernate.model.PnPerson pnPerson,
			net.project.hibernate.model.PnWorkingtimeCalendar pnWorkingtimeCalendar,
			net.project.hibernate.model.PnPlan pnPlan, Set pnWorkingtimeCalendarEntries, Set pnWorkingtimeCalendars) {
		this.calendarId = calendarId;
		this.isBaseCalendar = isBaseCalendar;
		this.name = name;
		this.recordStatus = recordStatus;
		this.pnPerson = pnPerson;
		this.pnWorkingtimeCalendar = pnWorkingtimeCalendar;
		this.pnPlan = pnPlan;
		this.pnWorkingtimeCalendarEntries = pnWorkingtimeCalendarEntries;
		this.pnWorkingtimeCalendars = pnWorkingtimeCalendars;
	}

	public PnWorkingtimeCalendar(Integer calendarId, String isBaseCalendar, String recordStatus,
			net.project.hibernate.model.PnPerson pnPerson,
			net.project.hibernate.model.PnWorkingtimeCalendar pnWorkingtimeCalendar,
			net.project.hibernate.model.PnPlan pnPlan, Set pnWorkingtimeCalendarEntries, Set pnWorkingtimeCalendars) {
		this.calendarId = calendarId;
		this.isBaseCalendar = isBaseCalendar;
		this.recordStatus = recordStatus;
		this.pnPerson = pnPerson;
		this.pnWorkingtimeCalendar = pnWorkingtimeCalendar;
		this.pnPlan = pnPlan;
		this.pnWorkingtimeCalendarEntries = pnWorkingtimeCalendarEntries;
		this.pnWorkingtimeCalendars = pnWorkingtimeCalendars;
	}

	@Id
	@Column(name = "CALENDAR_ID", nullable = false)
	public Integer getCalendarId() {
		return this.calendarId;
	}

	public void setCalendarId(Integer calendarId) {
		this.calendarId = calendarId;
	}

	@Column(name = "IS_BASE_CALENDAR", nullable = false, length = 1)
	public String getIsBaseCalendar() {
		return this.isBaseCalendar;
	}

	public void setIsBaseCalendar(String isBaseCalendar) {
		this.isBaseCalendar = isBaseCalendar;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "RESOURCE_PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkingtimeCalendar", targetEntity = PnWorkingtimeCalendarEntry.class)
	@Transient
	public Set getPnWorkingtimeCalendarEntries() {
		return this.pnWorkingtimeCalendarEntries;
	}

	public void setPnWorkingtimeCalendarEntries(Set pnWorkingtimeCalendarEntries) {
		this.pnWorkingtimeCalendarEntries = pnWorkingtimeCalendarEntries;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkingtimeCalendar", targetEntity = PnWorkingtimeCalendar.class)
	@Transient
	public Set getPnWorkingtimeCalendars() {
		return this.pnWorkingtimeCalendars;
	}

	public void setPnWorkingtimeCalendars(Set pnWorkingtimeCalendars) {
		this.pnWorkingtimeCalendars = pnWorkingtimeCalendars;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkingtimeCalendar.class)
	//@JoinColumn(name = "PARENT_CALENDAR_ID")
	@Transient
	public PnWorkingtimeCalendar getPnWorkingtimeCalendar() {
		return this.pnWorkingtimeCalendar;
	}

	public void setPnWorkingtimeCalendar(PnWorkingtimeCalendar pnWorkingtimeCalendar) {
		this.pnWorkingtimeCalendar = pnWorkingtimeCalendar;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPlan.class)
	//@JoinColumn(name = "PLAN_ID")
	@Transient
	public PnPlan getPnPlan() {
		return this.pnPlan;
	}

	public void setPnPlan(PnPlan pnPlan) {
		this.pnPlan = pnPlan;
	}

	public String toString() {
		return new ToStringBuilder(this).append("calendarId", getCalendarId()).toString();
	}

}
