/* Alter the pn_activitylog table */


ALTER TABLE PN_ACTIVITY_LOG MODIFY (
   ACTIVITY_ON_DATE TIMESTAMP(6),
   DESCRIPTION VARCHAR(1000)
)
/

ALTER TABLE PN_ACTIVITY_LOG ADD
   ("SPACE_ID" NUMBER(20,0))
/

ALTER TABLE PN_ACTIVITY_LOG ADD
   ("PARENT_OBJECT_ID" NUMBER(20,0))
/

ALTER TABLE PN_ACTIVITY_LOG ADD
   ("IS_IMPORTANT" NUMBER(1,0))
/
