/* Creating PN_ACTIVITY_LOG_MARKED table */

CREATE TABLE PN_ACTIVITY_LOG_MARKED
(
  ACTIVITY_LOG_ID NUMBER(20) NOT NULL,
  PERSON_ID NUMBER(20) NOT NULL,
  IS_MARKED NUMBER(1),
  PRIMARY KEY (ACTIVITY_LOG_ID, PERSON_ID),
  CONSTRAINT ACTIVITY_LOG_MARKED_FK1 FOREIGN KEY (ACTIVITY_LOG_ID) REFERENCES PN_ACTIVITY_LOG (ACTIVITY_LOG_ID) , 
  CONSTRAINT ACTIVITY_LOG_MARKED_FK2 FOREIGN KEY (PERSON_ID) REFERENCES PN_PERSON (PERSON_ID)
)
/

