/* Creating PN_ACTIVITY_LOG table */


CREATE TABLE PN_ACTIVITY_LOG 
(	ACTIVITY_LOG_ID NUMBER(20,0) NOT NULL,
	ACTIVITY_TYPE VARCHAR2(240 BYTE) NOT NULL,
	ACTIVITY_ON_DATE DATE NOT NULL,
	ACTIVITY_BY NUMBER(20,0) NOT NULL,
	TARGET_OBJECT_TYPE VARCHAR2(240 BYTE) NOT NULL,
	TARGET_OBJECT_ID NUMBER(20,0) NOT NULL,
	DESCRIPTION VARCHAR2(240 BYTE),	
	CONSTRAINT ACTIVITY_LOG_PK PRIMARY KEY (ACTIVITY_LOG_ID),
	CONSTRAINT ACTIVITY_LOG_FK FOREIGN KEY (ACTIVITY_BY)
	REFERENCES PNET.PN_PERSON (PERSON_ID)
) 
/

