/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassTypeElementPK generated by hbm2java
 */
@Embeddable
public class PnClassTypeElementPK  implements java.io.Serializable {

    /** identifier field */
    private Integer classTypeId;

    /** identifier field */
    private Integer elementId;

    public PnClassTypeElementPK() {
    }

    public PnClassTypeElementPK(Integer classTypeId, Integer elementId) {
       this.classTypeId = classTypeId;
       this.elementId = elementId;
    }

    @Column(name="CLASS_TYPE_ID", nullable=false, length=20)
    public Integer getClassTypeId() {
        return this.classTypeId;
    }
    
    public void setClassTypeId(Integer classTypeId) {
        this.classTypeId = classTypeId;
    }

    @Column(name="ELEMENT_ID", nullable=false, length=20)
    public Integer getElementId() {
        return this.elementId;
    }
    
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("classTypeId", getClassTypeId())
            .append("elementId", getElementId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnClassTypeElementPK) ) return false;
        PnClassTypeElementPK castOther = (PnClassTypeElementPK) other;
        return new EqualsBuilder()
            .append(this.getClassTypeId(), castOther.getClassTypeId())
            .append(this.getElementId(), castOther.getElementId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getClassTypeId())
            .append(getElementId())
            .toHashCode();
    }
}


