/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassDomainValuePK generated by hbm2java
 */
@Embeddable
public class PnClassDomainValuePK  implements java.io.Serializable {

    /** identifier field */
    private Integer domainId;

    /** identifier field */
    private Integer domainValueId;

    public PnClassDomainValuePK() {
    }

    public PnClassDomainValuePK(Integer domainId, Integer domainValueId) {
       this.domainId = domainId;
       this.domainValueId = domainValueId;
    }

    @Column(name="DOMAIN_ID", nullable=false, length=20)
    public Integer getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }


    @Column(name="DOMAIN_VALUE_ID", nullable=false, length=20)
    public Integer getDomainValueId() {
        return this.domainValueId;
    }
    
    public void setDomainValueId(Integer domainValueId) {
        this.domainValueId = domainValueId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("domainId", getDomainId())
            .append("domainValueId", getDomainValueId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnClassDomainValuePK) ) return false;
        PnClassDomainValuePK castOther = (PnClassDomainValuePK) other;
        return new EqualsBuilder()
            .append(this.getDomainId(), castOther.getDomainId())
            .append(this.getDomainValueId(), castOther.getDomainValueId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getDomainId())
            .append(getDomainValueId())
            .toHashCode();
    }
  }

