/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeHistoryClob generated by hbm2java
 */
@Entity
@Table(name = "PN_ENVELOPE_HISTORY_CLOB")
public class PnEnvelopeHistoryClob implements java.io.Serializable {

	/** identifier field */
	private Integer objectId;

	/** nullable persistent field */
	private Clob clobField;

	/** persistent field */
	private Set pnEnvelopeHistories = new HashSet(0);

	public PnEnvelopeHistoryClob() {
	}

	public PnEnvelopeHistoryClob(Integer objectId) {
		this.objectId = objectId;
	}

	public PnEnvelopeHistoryClob(Integer objectId, Clob clobField, Set pnEnvelopeHistories) {
		this.objectId = objectId;
		this.clobField = clobField;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	/** minimal constructor */
	public PnEnvelopeHistoryClob(Integer objectId, Set pnEnvelopeHistories) {
		this.objectId = objectId;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	@Id
	@Column(name = "OBJECT_ID", nullable = false)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "CLOB_FIELD", length = 4000)
	public Clob getClobField() {
		return this.clobField;
	}

	public void setClobField(Clob clobField) {
		this.clobField = clobField;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnEnvelopeHistoryClob", targetEntity = PnEnvelopeHistory.class)
	@Transient
	public Set getPnEnvelopeHistories() {
		return this.pnEnvelopeHistories;
	}

	public void setPnEnvelopeHistories(Set pnEnvelopeHistories) {
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	public String toString() {
		return new ToStringBuilder(this).append("objectId", getObjectId()).toString();
	}

}
