/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnMethodologyView generated by hbm2java
 */
@Entity
@Table(name = "PN_METHODOLOGY_VIEW")
public class PnMethodologyView implements java.io.Serializable {

	/** identifier field */
	private BigDecimal methodologyId;

	/** identifier field */
	private BigDecimal parentSpaceId;

	/** identifier field */
	private BigDecimal childSpaceId;

	/** identifier field */
	private String methodologyName;

	/** identifier field */
	private String methodologyDesc;

	/** identifier field */
	private Clob useScenarioClob;

	/** identifier field */
	private BigDecimal statusId;

	/** identifier field */
	private BigDecimal createdById;

	/** identifier field */
	private String createdBy;

	/** identifier field */
	private Date createdDate;

	/** identifier field */
	private BigDecimal modifiedById;

	/** identifier field */
	private Date modifiedDate;

	/** identifier field */
	private String modifiedBy;

	/** identifier field */
	private String recordStatus;

	/** identifier field */
	private Integer isGlobal;

	/** identifier field */
	private Date crc;

	public PnMethodologyView() {
	}

	public PnMethodologyView(BigDecimal methodologyId, BigDecimal parentSpaceId, BigDecimal childSpaceId,
			String methodologyName, String methodologyDesc, Clob useScenarioClob, BigDecimal statusId,
			BigDecimal createdById, String createdBy, Date createdDate, BigDecimal modifiedById, Date modifiedDate,
			String modifiedBy, String recordStatus, int isGlobal, Date crc) {
		this.methodologyId = methodologyId;
		this.parentSpaceId = parentSpaceId;
		this.childSpaceId = childSpaceId;
		this.methodologyName = methodologyName;
		this.methodologyDesc = methodologyDesc;
		this.useScenarioClob = useScenarioClob;
		this.statusId = statusId;
		this.createdById = createdById;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedById = modifiedById;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.recordStatus = recordStatus;
		this.isGlobal = isGlobal;
		this.crc = crc;
	}

	@Id
	@Column(name = "METHODOLOGY_ID", nullable = false, length = 20)
	public BigDecimal getMethodologyId() {
		return this.methodologyId;
	}

	public void setMethodologyId(BigDecimal methodologyId) {
		this.methodologyId = methodologyId;
	}

	@Column(name = "PARENT_SPACE_ID", nullable = false, length = 20)
	public BigDecimal getParentSpaceId() {
		return this.parentSpaceId;
	}

	public void setParentSpaceId(BigDecimal parentSpaceId) {
		this.parentSpaceId = parentSpaceId;
	}

	@Column(name = "CHILD_SPACE_ID", nullable = false, length = 20)
	public BigDecimal getChildSpaceId() {
		return this.childSpaceId;
	}

	public void setChildSpaceId(BigDecimal childSpaceId) {
		this.childSpaceId = childSpaceId;
	}

	@Column(name = "METHODOLOGY_NAME", nullable = false, length = 80)
	public String getMethodologyName() {
		return this.methodologyName;
	}

	public void setMethodologyName(String methodologyName) {
		this.methodologyName = methodologyName;
	}

	@Column(name = "METHODOLOGY_DESC", nullable = false, length = 1000)
	public String getMethodologyDesc() {
		return this.methodologyDesc;
	}

	public void setMethodologyDesc(String methodologyDesc) {
		this.methodologyDesc = methodologyDesc;
	}

	@Column(name = "USE_SCENARIO_CLOB", nullable = false, length = 4000)
	public Clob getUseScenarioClob() {
		return this.useScenarioClob;
	}

	public void setUseScenarioClob(Clob useScenarioClob) {
		this.useScenarioClob = useScenarioClob;
	}

	@Column(name = "STATUS_ID", nullable = false, length = 20)
	public BigDecimal getStatusId() {
		return this.statusId;
	}

	public void setStatusId(BigDecimal statusId) {
		this.statusId = statusId;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public BigDecimal getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(BigDecimal createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 4000)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY_ID", nullable = false, length = 20)
	public BigDecimal getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(BigDecimal modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", nullable = false, length = 4000)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "IS_GLOBAL", nullable = false, length = 1)
	public int getIsGlobal() {
		return this.isGlobal;
	}

	public void setIsGlobal(int isGlobal) {
		this.isGlobal = isGlobal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	public String toString() {
		return new ToStringBuilder(this).append("methodologyId", getMethodologyId()).append("parentSpaceId",
				getParentSpaceId()).append("childSpaceId", getChildSpaceId()).append("methodologyName",
				getMethodologyName()).append("methodologyDesc", getMethodologyDesc()).append("useScenarioClob",
				getUseScenarioClob()).append("statusId", getStatusId()).append("createdById", getCreatedById()).append(
				"createdBy", getCreatedBy()).append("createdDate", getCreatedDate()).append("modifiedById",
				getModifiedById()).append("modifiedDate", getModifiedDate()).append("modifiedBy", getModifiedBy())
				.append("recordStatus", getRecordStatus()).append("isGlobal", getIsGlobal()).append("crc", getCrc())
				.toString();
	}

}
