/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPaymentModelType generated by hbm2java
 */
@Entity
@Table(name = "PN_PAYMENT_MODEL_TYPE")
public class PnPaymentModelType implements Serializable {

	private Integer modelTypeId;

	private String className;

	private String description;

	private Set pnPaymentModels = new HashSet(0);

	public PnPaymentModelType() {
	}

	public PnPaymentModelType(Integer modelTypeId, String className, String description) {
		this.modelTypeId = modelTypeId;
		this.className = className;
		this.description = description;
	}

	public PnPaymentModelType(Integer modelTypeId, String className, String description, Set pnPaymentModels) {
		this.modelTypeId = modelTypeId;
		this.className = className;
		this.description = description;
		this.pnPaymentModels = pnPaymentModels;
	}

	@Id
	@Column(name = "MODEL_TYPE_ID", nullable = false)
	public Integer getModelTypeId() {
		return this.modelTypeId;
	}

	public void setModelTypeId(Integer modelTypeId) {
		this.modelTypeId = modelTypeId;
	}

	@Column(name = "CLASS_NAME", nullable = false, length = 1000)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPaymentModelType", targetEntity = PnPaymentModel.class)
	@Transient
	public Set getPnPaymentModels() {
		return this.pnPaymentModels;
	}

	public void setPnPaymentModels(Set pnPaymentModels) {
		this.pnPaymentModels = pnPaymentModels;
	}

	public String toString() {
		return new ToStringBuilder(this).append("modelTypeId", getModelTypeId()).toString();
	}

}
