/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnPaymentModelCreditcard generated by hbm2java
 */
@Entity
@Table(name="PN_PAYMENT_MODEL_CREDITCARD"
)
public class PnPaymentModelCreditcard implements Serializable {


     private Integer paymentModelId;
     private String cardNumber;
     private int cardExpiryMonth;
     private int cardExpiryYear;

    public PnPaymentModelCreditcard() {
    }

    public PnPaymentModelCreditcard(Integer paymentModelId, String cardNumber, int cardExpiryMonth, int cardExpiryYear) {
       this.paymentModelId = paymentModelId;
       this.cardNumber = cardNumber;
       this.cardExpiryMonth = cardExpiryMonth;
       this.cardExpiryYear = cardExpiryYear;
    }
   
     @Id 
    @Column(name="PAYMENT_MODEL_ID", nullable=false)
    public Integer getPaymentModelId() {
        return this.paymentModelId;
    }
    
    public void setPaymentModelId(Integer paymentModelId) {
        this.paymentModelId = paymentModelId;
    }

    @Column(name="CARD_NUMBER", nullable=false, length=100)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    @Column(name="CARD_EXPIRY_MONTH", nullable=false, length=2)
    public int getCardExpiryMonth() {
        return this.cardExpiryMonth;
    }
    
    public void setCardExpiryMonth(int cardExpiryMonth) {
        this.cardExpiryMonth = cardExpiryMonth;
    }

    @Column(name="CARD_EXPIRY_YEAR", nullable=false, length=4)
    public int getCardExpiryYear() {
        return this.cardExpiryYear;
    }
    
    public void setCardExpiryYear(int cardExpiryYear) {
        this.cardExpiryYear = cardExpiryYear;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("paymentModelId", getPaymentModelId())
            .toString();
    }

}
