/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPostHistoryPK generated by hbm2java
 */
@Embeddable
public class PnPostHistoryPK implements Serializable {


     private Integer postId;
     private Integer discussionGroupId;
     private Integer postHistoryId;

    public PnPostHistoryPK() {
    }

    public PnPostHistoryPK(Integer postId, Integer discussionGroupId, Integer postHistoryId) {
       this.postId = postId;
       this.discussionGroupId = discussionGroupId;
       this.postHistoryId = postHistoryId;
    }
   


    @Column(name="POST_ID", nullable=false, length=20)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }


    @Column(name="DISCUSSION_GROUP_ID", nullable=false, length=20)
    public Integer getDiscussionGroupId() {
        return this.discussionGroupId;
    }
    
    public void setDiscussionGroupId(Integer discussionGroupId) {
        this.discussionGroupId = discussionGroupId;
    }


    @Column(name="POST_HISTORY_ID", nullable=false, length=20)
    public Integer getPostHistoryId() {
        return this.postHistoryId;
    }
    
    public void setPostHistoryId(Integer postHistoryId) {
        this.postHistoryId = postHistoryId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("postId", getPostId())
            .append("discussionGroupId", getDiscussionGroupId())
            .append("postHistoryId", getPostHistoryId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPostHistoryPK) ) return false;
        PnPostHistoryPK castOther = (PnPostHistoryPK) other;
        return new EqualsBuilder()
            .append(this.getPostId(), castOther.getPostId())
            .append(this.getDiscussionGroupId(), castOther.getDiscussionGroupId())
            .append(this.getPostHistoryId(), castOther.getPostHistoryId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getPostId())
            .append(getDiscussionGroupId())
            .append(getPostHistoryId())
            .toHashCode();
    }

}
