/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPortfolioHasProjectsView generated by hbm2java
 */
@Entity
@Table(name = "PN_PORTFOLIO_HAS_PROJECTS_VIEW")
public class PnPortfolioHasProjectsView implements Serializable {
	
	private PnPortfolioHasProjectsViewPK comp_id;

	public PnPortfolioHasProjectsView() {
	}

	public PnPortfolioHasProjectsView(PnPortfolioHasProjectsViewPK comp_id) {
		this.comp_id = comp_id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "portfolioId", column = @Column(name = "PORTFOLIO_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "portfolioName", column = @Column(name = "PORTFOLIO_NAME", nullable = false, length = 80)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "projectName", column = @Column(name = "PROJECT_NAME", nullable = false, length = 80)),
			@AttributeOverride(name = "projectDesc", column = @Column(name = "PROJECT_DESC", nullable = false, length = 1000)),
			@AttributeOverride(name = "statusCodeId", column = @Column(name = "STATUS_CODE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "percentComplete", column = @Column(name = "PERCENT_COMPLETE", nullable = false, length = 3)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", nullable = false, length = 80)),
			@AttributeOverride(name = "colorCodeId", column = @Column(name = "COLOR_CODE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "color", column = @Column(name = "COLOR", nullable = false, length = 80)),
			@AttributeOverride(name = "colorImageUrl", column = @Column(name = "COLOR_IMAGE_URL", nullable = false, length = 240)),
			@AttributeOverride(name = "isSubproject", column = @Column(name = "IS_SUBPROJECT", nullable = false, length = 1)),
			@AttributeOverride(name = "recordStatus", column = @Column(name = "RECORD_STATUS", nullable = false, length = 1)) })
	public PnPortfolioHasProjectsViewPK getComp_id() {
		return comp_id;
	}

	/**
	 * @param comp_id the comp_id to set
	 */
	public void setComp_id(PnPortfolioHasProjectsViewPK comp_id) {
		this.comp_id = comp_id;
	}
	
	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

}
