/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnProjectSpaceMetaValuePK generated by hbm2java
 */
@Embeddable
public class PnProjectSpaceMetaValuePK  implements java.io.Serializable {


     private Integer projectId;
     private Integer propertyId;

    public PnProjectSpaceMetaValuePK() {
    }

    public PnProjectSpaceMetaValuePK(Integer projectId, Integer propertyId) {
       this.projectId = projectId;
       this.propertyId = propertyId;
    }
   


    @Column(name="PROJECT_ID", nullable=false, length=20)
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }


    @Column(name="PROPERTY_ID", nullable=false, length=20)
    public Integer getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }




}


