/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PnResourceListHasPersons generated by hbm2java
 */
@Entity
@Table(name="PN_RESOURCE_LIST_HAS_PERSONS"
)
public class PnResourceListHasPersons implements Serializable {


    private PnResourceListHasPersonsPK comp_id;
     
 	private Integer type;

    public PnResourceListHasPersons() {
    }

    public PnResourceListHasPersons(PnResourceListHasPersonsPK comp_id) {
       this.comp_id = comp_id;
    }
    
    public PnResourceListHasPersons(PnResourceListHasPersonsPK comp_id, int type) {
        this.comp_id = comp_id;
        this.type = type;
     }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="resourceListId", column=@Column(name="RESOURCE_LIST_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", nullable=false, length=20) ) } )
    public PnResourceListHasPersonsPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnResourceListHasPersonsPK comp_id) {
        this.comp_id = comp_id;
    }

	/**
	 * @return the type
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}




}


