/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnSpaceHasDocSpace generated by hbm2java
 */
@Entity
@Table(name="PN_SPACE_HAS_DOC_SPACE"
)
public class PnSpaceHasDocSpace implements Serializable {


     private PnSpaceHasDocSpacePK comp_id;
     private int isOwner;
     private PnDocSpace pnDocSpace;

    public PnSpaceHasDocSpace() {
    }

	
    public PnSpaceHasDocSpace(PnSpaceHasDocSpacePK comp_id, int isOwner) {
        this.comp_id = comp_id;
        this.isOwner = isOwner;
    }

    public PnSpaceHasDocSpace(PnSpaceHasDocSpacePK comp_id, int isOwner, PnDocSpace pnDocSpace) {
       this.comp_id = comp_id;
       this.isOwner = isOwner;
       this.pnDocSpace = pnDocSpace;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="spaceId", column=@Column(name="SPACE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="docSpaceId", column=@Column(name="DOC_SPACE_ID", nullable=false, length=20) ) } )
    public PnSpaceHasDocSpacePK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnSpaceHasDocSpacePK comp_id) {
        this.comp_id = comp_id;
    }

    @Column(name="IS_OWNER", nullable=false, length=1)
    public int getIsOwner() {
        return this.isOwner;
    }
    
    public void setIsOwner(int isOwner) {
        this.isOwner = isOwner;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnDocSpace.class)
    @JoinColumn(name="DOC_SPACE_ID", insertable=false, updatable=false)
    public PnDocSpace getPnDocSpace() {
        return this.pnDocSpace;
    }
    
    public void setPnDocSpace(PnDocSpace pnDocSpace) {
        this.pnDocSpace = pnDocSpace;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSpaceHasDocSpace) ) return false;
        PnSpaceHasDocSpace castOther = (PnSpaceHasDocSpace) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
