/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnSubscriptionHasGroup generated by hbm2java
 */
@Entity
@Table(name = "PN_SUBSCRIPTION_HAS_GROUP")
public class PnSubscriptionHasGroup implements Serializable {

	private PnSubscriptionHasGroupPK comp_id;

	private Integer subscriberBatchId;

	private PnSubscription pnSubscription;

	private PnNotificationDeliveryType pnNotificationDeliveryType;

	public PnSubscriptionHasGroup() {
	}

	public PnSubscriptionHasGroup(PnSubscriptionHasGroupPK comp_id, Integer subscriberBatchId) {
		this.comp_id = comp_id;
		this.subscriberBatchId = subscriberBatchId;
	}

	public PnSubscriptionHasGroup(PnSubscriptionHasGroupPK comp_id, Integer subscriberBatchId,
			PnSubscription pnSubscription, PnNotificationDeliveryType pnNotificationDeliveryType) {
		this.comp_id = comp_id;
		this.subscriberBatchId = subscriberBatchId;
		this.pnSubscription = pnSubscription;
		this.pnNotificationDeliveryType = pnNotificationDeliveryType;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "subscriptionId", column = @Column(name = "SUBSCRIPTION_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "deliveryGroupId", column = @Column(name = "DELIVERY_GROUP_ID", nullable = false, length = 20)) })
	public PnSubscriptionHasGroupPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnSubscriptionHasGroupPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "SUBSCRIBER_BATCH_ID", nullable = false, length = 20)
	public Integer getSubscriberBatchId() {
		return this.subscriberBatchId;
	}

	public void setSubscriberBatchId(Integer subscriberBatchId) {
		this.subscriberBatchId = subscriberBatchId;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnSubscription.class)
	//@JoinColumn(name = "SUBSCRIPTION_ID", insertable = false, updatable = false)
	@Transient
	public PnSubscription getPnSubscription() {
		return this.pnSubscription;
	}

	public void setPnSubscription(PnSubscription pnSubscription) {
		this.pnSubscription = pnSubscription;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnNotificationDeliveryType.class)
	//@JoinColumn(name = "DELIVERY_TYPE_ID")
	@Transient
	public PnNotificationDeliveryType getPnNotificationDeliveryType() {
		return this.pnNotificationDeliveryType;
	}

	public void setPnNotificationDeliveryType(PnNotificationDeliveryType pnNotificationDeliveryType) {
		this.pnNotificationDeliveryType = pnNotificationDeliveryType;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnSubscriptionHasGroup))
			return false;
		PnSubscriptionHasGroup castOther = (PnSubscriptionHasGroup) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
