/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PnTimesheet generated by hbm2java
 */
@Entity
@Table(name="PN_TIMESHEET"
)
public class PnTimesheet implements Serializable {

     private Integer object_id;
     private PnPerson person;
     private Integer status;
     private Timestamp startDate;
     private Timestamp endDate;
     private Integer work;
     private Integer work_units;
     private Timestamp dateSumbitted;
     private Timestamp dateApproveReject;
     private String comments;
     private PnPerson approveReject;
     private String recordStatus;

    public PnTimesheet() {
    }
	
    public PnTimesheet(Integer object_id) {
        this.object_id = object_id;
    }

    public PnTimesheet(Integer object_id, PnPerson person, Integer status, Timestamp startDate, Timestamp endDate, Integer work, Integer work_units, Timestamp dateSumbitted, Timestamp dateApproveReject, String comments, PnPerson approveReject, String recordStatus) {
       this.object_id = object_id;
       this.person = person;
       this.status = status;
       this.startDate = startDate;
       this.endDate = endDate;
       this.work = work;
       this.work_units = work_units;
       this.dateSumbitted = dateSumbitted;
       this.dateApproveReject = dateApproveReject;
       this.comments = comments;
       this.approveReject = approveReject;
       this.recordStatus = recordStatus;
    }
   
     @Id 
    @Column(name="OBJECT_ID", nullable=false, length=20)
    public Integer getObject_id() {
        return this.object_id;
    }
    
    public void setObject_id(Integer object_id) {
        this.object_id = object_id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="PERSON_ID")
    public PnPerson getPerson() {
        return this.person;
    }
    
    public void setPerson(PnPerson person) {
        this.person = person;
    }

    @Column(name="STATUS_ID")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Column(name="START_DATE", length=7)
    public Timestamp getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    @Column(name="END_DATE", length=7)
    public Timestamp getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="WORK", length=20)
    public Integer getWork() {
        return this.work;
    }
    
    public void setWork(Integer work) {
        this.work = work;
    }
    
    @Column(name="WORK_UNITS", length=3)
    public Integer getWork_units() {
        return this.work_units;
    }
    
    public void setWork_units(Integer work_units) {
        this.work_units = work_units;
    }

    @Column(name="DATE_SUBMITTED", length=7)
    public Timestamp getDateSumbitted() {
        return this.dateSumbitted;
    }
    
    public void setDateSumbitted(Timestamp dateSumbitted) {
        this.dateSumbitted = dateSumbitted;
    }

    @Column(name="DATE_APPROVE_REJECT", length=7)
    public Timestamp getDateApproveReject() {
        return this.dateApproveReject;
    }
    
    public void setDateApproveReject(Timestamp dateApproveReject) {
        this.dateApproveReject = dateApproveReject;
    }
    
    @Column(name="COMMENTS", length=4000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="APPROVE_REJECT_BY_ID")
    public PnPerson getApproveReject() {
        return this.approveReject;
    }
    
    public void setApproveReject(PnPerson approveReject) {
        this.approveReject = approveReject;
    }
    
    @Column(name="RECORD_STATUS", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public static final String OBJECT_TYPE = "timesheet";

}


