/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnWeblog generated by hbm2java
 */
@Entity
@Table(name = "PN_WEBLOG")
public class PnWeblog implements Serializable {

	private Integer weblogId;

	private String name;

	private String description;

	private Integer allowComments;

	private Integer emailComments;

	private String emailFromAddress;

	private String emailAddress;

	private String locale;

	private String timezone;

	private Integer isEnabled;

	private Integer isActive;

	private Date createdDate;

	private Integer defaultAllowComments;

	private Integer defaultCommentDays;

	private Integer spaceId;

	private PnPerson pnPerson;

	public PnWeblog() {
	}

	public PnWeblog(java.lang.Integer weblogId) {
		this.setWeblogId(weblogId);
	}

	public PnWeblog(java.lang.Integer weblogId, java.lang.Integer spaceId) {
		this.weblogId = weblogId;
		this.spaceId = spaceId;
	}

	public PnWeblog(java.lang.Integer weblogId, java.lang.String name, java.lang.String description,
			net.project.hibernate.model.PnPerson pnPerson, java.lang.Integer allowComments,
			java.lang.Integer emailComments, java.lang.String emailFromAddress, java.lang.String emailAddress,
			java.lang.String locale, java.lang.String timezone, java.lang.Integer isEnabled,
			java.lang.Integer isActive, java.util.Date createdDate, java.lang.Integer defaultAllowComments,
			java.lang.Integer defaultCommentDays, java.lang.Integer spaceId) {

		this.setWeblogId(weblogId);
		this.setName(name);
		this.setDescription(description);
		this.setPnPerson(pnPerson);
		this.setAllowComments(allowComments);
		this.setEmailComments(emailComments);
		this.setEmailFromAddress(emailFromAddress);
		this.setEmailAddress(emailAddress);
		this.setLocale(locale);
		this.setTimezone(timezone);
		this.setIsEnabled(isEnabled);
		this.setIsActive(isActive);
		this.setCreatedDate(createdDate);
		this.setDefaultAllowComments(defaultAllowComments);
		this.setDefaultCommentDays(defaultCommentDays);
		this.setSpaceId(spaceId);
	}

	public PnWeblog(Integer weblogId, String name, String description, Integer allowComments, Integer emailComments,
			String emailAddress, Integer isEnabled, Integer isActive, Integer defaultAllowComments,
			Integer defaultCommentDays, Integer spaceId) {
		this.weblogId = weblogId;
		this.name = name;
		this.description = description;
		this.allowComments = allowComments;
		this.emailComments = emailComments;
		this.emailAddress = emailAddress;
		this.isEnabled = isEnabled;
		this.isActive = isActive;
		this.defaultAllowComments = defaultAllowComments;
		this.defaultCommentDays = defaultCommentDays;
		this.spaceId = spaceId;
	}

	public PnWeblog(Integer weblogId, String name, String description, Integer allowComments, Integer emailComments,
			String emailFromAddress, String emailAddress, String locale, String timezone, Integer isEnabled,
			Integer isActive, Date createdDate, Integer defaultAllowComments, Integer defaultCommentDays,
			Integer spaceId, PnPerson pnPerson) {
		this.weblogId = weblogId;
		this.name = name;
		this.description = description;
		this.allowComments = allowComments;
		this.emailComments = emailComments;
		this.emailFromAddress = emailFromAddress;
		this.emailAddress = emailAddress;
		this.locale = locale;
		this.timezone = timezone;
		this.isEnabled = isEnabled;
		this.isActive = isActive;
		this.createdDate = createdDate;
		this.defaultAllowComments = defaultAllowComments;
		this.defaultCommentDays = defaultCommentDays;
		this.spaceId = spaceId;
		this.pnPerson = pnPerson;
	}

	@Id
	@Column(name = "WEBLOG_ID", nullable = false)
	public Integer getWeblogId() {
		return this.weblogId;
	}

	public void setWeblogId(Integer weblogId) {
		this.weblogId = weblogId;
	}

	@Column(name = "NAME", nullable = false, length = 240)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	// description column size is 1000 bytes only
	@Column(name = "DESCRIPTION", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ALLOW_COMMENTS", nullable = false, length = 1)
	public Integer getAllowComments() {
		return this.allowComments;
	}

	public void setAllowComments(Integer allowComments) {
		this.allowComments = allowComments;
	}

	@Column(name = "EMAIL_COMMENTS", nullable = false, length = 1)
	public Integer getEmailComments() {
		return this.emailComments;
	}

	public void setEmailComments(Integer emailComments) {
		this.emailComments = emailComments;
	}

	@Column(name = "EMAIL_FROM_ADDRESS", length = 240)
	public String getEmailFromAddress() {
		return this.emailFromAddress;
	}

	public void setEmailFromAddress(String emailFromAddress) {
		this.emailFromAddress = emailFromAddress;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false, length = 240)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "LOCALE", length = 20)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	@Column(name = "TIMEZONE", length = 50)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "IS_ENABLED", nullable = false, length = 1)
	public Integer getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Integer isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 1)
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DEFAULT_ALLOW_COMMENTS", nullable = false, length = 1)
	public Integer getDefaultAllowComments() {
		return this.defaultAllowComments;
	}

	public void setDefaultAllowComments(Integer defaultAllowComments) {
		this.defaultAllowComments = defaultAllowComments;
	}

	@Column(name = "DEFAULT_COMMENT_DAYS", nullable = false, length = 11)
	public Integer getDefaultCommentDays() {
		return this.defaultCommentDays;
	}

	public void setDefaultCommentDays(Integer defaultCommentDays) {
		this.defaultCommentDays = defaultCommentDays;
	}

	@Column(name = "SPACE_ID", nullable = false, length = 20)
	public Integer getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof net.project.hibernate.model.PnWeblog))
			return false;
		else {
			net.project.hibernate.model.PnWeblog pnWeblog = (net.project.hibernate.model.PnWeblog) obj;
			if (null == this.getWeblogId() || null == pnWeblog.getWeblogId())
				return false;
			else
				return (this.getWeblogId().equals(pnWeblog.getWeblogId()));
		}
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(getWeblogId()).toHashCode();
	}

	public String toString() {
		return new ToStringBuilder(this).append("weblogId", getWeblogId()).toString();
	}

}
