/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWeblogComment generated by hbm2java
 */
@Entity
@Table(name = "PN_WEBLOG_COMMENT")
public class PnWeblogComment implements Serializable, Comparable<PnWeblogComment> {

	private Integer commentId;

	private String name;

	private String email;

	private String url;

	private String content;

	private Date postTime;

	private Integer notify;

	private String remoteHost;

	private String referrer;

	private String userAgent;

	private String status;

	private String contentType;
	
	private Integer personId;

	private PnWeblogEntry pnWeblogEntry;

	private String postTimeString;

	private boolean isLastEntry;
	
	private String postDateString;
	
	private Integer entryByPersonId;
	
	private boolean isDeletable;
	
	public PnWeblogComment() {
	}

	public PnWeblogComment(java.lang.Integer commentId) {
		this.setCommentId(commentId);
	}

	public PnWeblogComment(Integer commentId, Date postTime, Integer notify, String status, String contentType) {
		this.commentId = commentId;
		this.postTime = postTime;
		this.notify = notify;
		this.status = status;
		this.contentType = contentType;
	}

	public PnWeblogComment(java.lang.Integer commentId, net.project.hibernate.model.PnWeblogEntry pnWeblogEntry,
			java.lang.Integer personId, java.util.Date postTime, java.lang.Integer notify, java.lang.String status,
			java.lang.String contentType) {

		this.setCommentId(commentId);
		this.setPnWeblogEntry(pnWeblogEntry);
		this.setPersonId(personId);
		this.setPostTime(postTime);
		this.setNotify(notify);
		this.setStatus(status);
		this.setContentType(contentType);
	}

	public PnWeblogComment(Integer commentId, String name, String email, String url, String content, Date postTime,
			Integer notify, String remoteHost, String referrer, String userAgent, String status, String contentType,
			Integer personId, PnWeblogEntry pnWeblogEntry) {
		this.commentId = commentId;
		this.name = name;
		this.email = email;
		this.url = url;
		this.content = content;
		this.postTime = postTime;
		this.notify = notify;
		this.remoteHost = remoteHost;
		this.referrer = referrer;
		this.userAgent = userAgent;
		this.status = status;
		this.contentType = contentType;
		this.personId = personId;
		this.pnWeblogEntry = pnWeblogEntry;
	}

	@Id
	@Column(name = "COMMENT_ID", nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@Column(name = "NAME", length = 240)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", length = 240)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "URL", length = 240)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "CONTENT")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "POST_TIME", nullable = false, length = 7)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Column(name = "NOTIFY", nullable = false, length = 1)
	public Integer getNotify() {
		return this.notify;
	}

	public void setNotify(Integer notify) {
		this.notify = notify;
	}

	@Column(name = "REMOTE_HOST", length = 128)
	public String getRemoteHost() {
		return this.remoteHost;
	}

	public void setRemoteHost(String remoteHost) {
		this.remoteHost = remoteHost;
	}

	@Column(name = "REFERRER", length = 240)
	public String getReferrer() {
		return this.referrer;
	}

	public void setReferrer(String referrer) {
		this.referrer = referrer;
	}

	@Column(name = "USER_AGENT", length = 240)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CONTENT_TYPE", nullable = false, length = 128)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "PERSON_ID", length = 20)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWeblogEntry.class)
	@JoinColumn(name = "WEBLOG_ENTRY_ID")
	public PnWeblogEntry getPnWeblogEntry() {
		return this.pnWeblogEntry;
	}

	public void setPnWeblogEntry(PnWeblogEntry pnWeblogEntry) {
		this.pnWeblogEntry = pnWeblogEntry;
	}

	/**
	 * @return the postTimeString
	 */
	@Transient
	public java.lang.String getPostTimeString() {
		return postTimeString;
	}

	/**
	 * @param postTimeString the postTimeString to set
	 */
	public void setPostTimeString(java.lang.String postTimeString) {
		this.postTimeString = postTimeString;
	}

	/**
	 * @return boolean
	 */
	 @Transient
	public boolean getIsLastEntry() {
		return isLastEntry;
	}

	/**
	 * @param boolean isLastEntry
	 */
	public void setIsLastEntry(boolean isLastEntry) {
		this.isLastEntry = isLastEntry;
	}

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof net.project.hibernate.model.PnWeblogComment))
			return false;
		else {
			net.project.hibernate.model.PnWeblogComment pnWeblogComment = (net.project.hibernate.model.PnWeblogComment) obj;
			if (null == this.getCommentId() || null == pnWeblogComment.getCommentId())
				return false;
			else
				return (this.getCommentId().equals(pnWeblogComment.getCommentId()));
		}
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(getCommentId()).toHashCode();
	}

	public String toString() {
		return new ToStringBuilder(this).append("commentId", getCommentId()).toString();
	}

	/* 
	 * To sort the weblog comments in chronological order
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	public int compareTo(PnWeblogComment comment) {
		return -this.commentId.compareTo(comment.commentId);
	}

	/**
	 * @return the postDateString
	 */
	@Transient
	public String getPostDateString() {
		return postDateString;
	}

	/**
	 * @param postDateString the postDateString to set
	 */
	public void setPostDateString(String postDateString) {
		this.postDateString = postDateString;
	}

	/**
	 * @return the entryByPersonId
	 */
	@Transient
	public Integer getEntryByPersonId() {
		return entryByPersonId;
	}

	/**
	 * @param entryByPersonId the entryByPersonId to set
	 */
	public void setEntryByPersonId(Integer entryByPersonId) {
		this.entryByPersonId = entryByPersonId;
	}

	/**
	 * @return the isDeletable
	 */
	 @Transient
	public boolean getIsDeletable() {
		return isDeletable;
	}

	/**
	 * @param isDeletable the isDeletable to set
	 */
	public void setIsDeletable(boolean isDeletable) {
		this.isDeletable = isDeletable;
	}

}
