/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWfRuleAuthHasGroup generated by hbm2java
 */
@Entity
@Table(name="PN_WF_RULE_AUTH_HAS_GROUP"
)
public class PnWfRuleAuthHasGroup implements Serializable {


     private PnWfRuleAuthHasGroupPK comp_id;
     private PnWorkflowStepHasGroup pnWorkflowStepHasGroup;
     private PnWfRuleAuth pnWfRuleAuth;

    public PnWfRuleAuthHasGroup() {
    }

	
    public PnWfRuleAuthHasGroup(PnWfRuleAuthHasGroupPK comp_id) {
        this.comp_id = comp_id;
    }
    public PnWfRuleAuthHasGroup(PnWfRuleAuthHasGroupPK comp_id, PnWorkflowStepHasGroup pnWorkflowStepHasGroup, PnWfRuleAuth pnWfRuleAuth) {
       this.comp_id = comp_id;
       this.pnWorkflowStepHasGroup = pnWorkflowStepHasGroup;
       this.pnWfRuleAuth = pnWfRuleAuth;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ruleId", column=@Column(name="RULE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="workflowId", column=@Column(name="WORKFLOW_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="transitionId", column=@Column(name="TRANSITION_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="groupId", column=@Column(name="GROUP_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="stepId", column=@Column(name="STEP_ID", nullable=false, length=20) ) } )
    public PnWfRuleAuthHasGroupPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnWfRuleAuthHasGroupPK comp_id) {
        this.comp_id = comp_id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWorkflowStepHasGroup.class)
    @JoinColumns( { 
        @JoinColumn(name="WORKFLOW_ID", referencedColumnName="GROUP_ID", insertable=false, updatable=false), 
        @JoinColumn(name="GROUP_ID", referencedColumnName="STEP_ID", insertable=false, updatable=false), 
        @JoinColumn(name="STEP_ID", referencedColumnName="WORKFLOW_ID", insertable=false, updatable=false) } )
    public PnWorkflowStepHasGroup getPnWorkflowStepHasGroup() {
        return this.pnWorkflowStepHasGroup;
    }
    
    public void setPnWorkflowStepHasGroup(PnWorkflowStepHasGroup pnWorkflowStepHasGroup) {
        this.pnWorkflowStepHasGroup = pnWorkflowStepHasGroup;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWfRuleAuth.class)
    @JoinColumns( { 
        @JoinColumn(name="RULE_ID", referencedColumnName="RULE_ID", insertable=false, updatable=false), 
        @JoinColumn(name="WORKFLOW_ID", referencedColumnName="WORKFLOW_ID", insertable=false, updatable=false), 
        @JoinColumn(name="TRANSITION_ID", referencedColumnName="TRANSITION_ID", insertable=false, updatable=false) } )
    public PnWfRuleAuth getPnWfRuleAuth() {
        return this.pnWfRuleAuth;
    }
    
    public void setPnWfRuleAuth(PnWfRuleAuth pnWfRuleAuth) {
        this.pnWfRuleAuth = pnWfRuleAuth;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnWfRuleAuthHasGroup) ) return false;
        PnWfRuleAuthHasGroup castOther = (PnWfRuleAuthHasGroup) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
