/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * PnWikiAttachment generated by hbm2java
 */
@Entity
@Table(name="PN_WIKI_ATTACHMENT"
)
public class PnWikiAttachment implements Serializable {


     private Integer wikiAttachmentId;
     private String attachmentName;
     private Integer fileId;
     private Date attachedOnDate;
     private String description;
     private String recordStatus;
     private PnPerson attachedBy;
     private PnWikiPage wikiPageId;

    public PnWikiAttachment() {
    }

	public PnWikiAttachment(java.lang.Integer wikiAttachmentId) {
		this.setWikiAttachmentId(wikiAttachmentId);
	}
	
    public PnWikiAttachment(String attachmentName, Integer fileId, Date attachedOnDate) {
        this.attachmentName = attachmentName;
        this.fileId = fileId;
        this.attachedOnDate = attachedOnDate;
    }

	public PnWikiAttachment(java.lang.Integer wikiAttachmentId, java.lang.String attachmentName, Integer fileId , java.lang.String desciption,
			net.project.hibernate.model.PnPerson attachedBy, java.util.Date attachedOnDate, 
			net.project.hibernate.model.PnWikiPage wikiPageId) {

		this.setWikiAttachmentId(wikiAttachmentId);
		this.setAttachmentName(attachmentName);
		this.setFileId(fileId);
		this.setDescription(desciption);
		this.setAttachedBy(attachedBy);
		this.setAttachedOnDate(attachedOnDate);
		this.setWikiPageId(wikiPageId);
	}

    public PnWikiAttachment(String attachmentName, Integer fileId, Date attachedOnDate, String description, String recordStatus, PnPerson attachedBy, PnWikiPage wikiPageId) {
       this.attachmentName = attachmentName;
       this.fileId = fileId;
       this.attachedOnDate = attachedOnDate;
       this.description = description;
       this.recordStatus = recordStatus;
       this.attachedBy = attachedBy;
       this.wikiPageId = wikiPageId;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="WIKI_ATTACHMENT_ID", nullable=false)
    public Integer getWikiAttachmentId() {
        return this.wikiAttachmentId;
    }
    
    public void setWikiAttachmentId(Integer wikiAttachmentId) {
        this.wikiAttachmentId = wikiAttachmentId;
    }

    
    @Column(name="ATTACHMENT_NAME", nullable=false, length=240)
    public String getAttachmentName() {
        return this.attachmentName;
    }
    
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    
    @Column(name="FILE_ID", nullable=false, length=20)
    public Integer getFileId() {
        return this.fileId;
    }
    
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    
    @Column(name="ATTACHED_ON_DATE", nullable=false)
    public Date getAttachedOnDate() {
        return this.attachedOnDate;
    }
    
    public void setAttachedOnDate(Date attachedOnDate) {
        this.attachedOnDate = attachedOnDate;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="RECORD_STATUS")
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="ATTACHED_BY")
    public PnPerson getAttachedBy() {
        return this.attachedBy;
    }
    
    public void setAttachedBy(PnPerson attachedBy) {
        this.attachedBy = attachedBy;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWikiPage.class)
    @JoinColumn(name="WIKI_PAGE_ID")
    public PnWikiPage getWikiPageId() {
        return this.wikiPageId;
    }
    
    public void setWikiPageId(PnWikiPage wikiPageId) {
        this.wikiPageId = wikiPageId;
    }

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof net.project.hibernate.model.PnWikiAttachment))
			return false;
		else {
			net.project.hibernate.model.PnWikiAttachment pnWikiAttachment = (net.project.hibernate.model.PnWikiAttachment) obj;
			if (null == this.getWikiAttachmentId() || null == pnWikiAttachment.getWikiAttachmentId())
				return false;
			else
				return (this.getWikiAttachmentId().equals(pnWikiAttachment.getWikiAttachmentId()));
		}
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder()
        .append(getWikiAttachmentId())
        .toHashCode();
	}

	public String toString() {
		return new ToStringBuilder(this)
        .append("wikiAttachmentId", getWikiAttachmentId())
        .toString();
	}



}


