/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Timestamp;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkingtimeCalendarEntry generated by hbm2java
 */
@Entity
@Table(name="PN_WORKINGTIME_CALENDAR_ENTRY"
)
public class PnWorkingtimeCalendarEntry implements Serializable {


     private PnWorkingtimeCalendarEntryPK comp_id;
     private String isWorkingDay;
     private String isDayOfWeek;
     private Integer dayNumber;
     private Timestamp startDate;
     private Timestamp endDate;
     private Timestamp time1Start;
     private Timestamp time1End;
     private Timestamp time2Start;
     private Timestamp time2End;
     private Timestamp time3Start;
     private Timestamp time3End;
     private Timestamp time4Start;
     private Timestamp time4End;
     private Timestamp time5Start;
     private Timestamp time5End;
     private String recordStatus;
     private String description;
     private PnWorkingtimeCalendar pnWorkingtimeCalendar;

    public PnWorkingtimeCalendarEntry() {
    }

	
    public PnWorkingtimeCalendarEntry(PnWorkingtimeCalendarEntryPK comp_id, String isWorkingDay, String isDayOfWeek, String recordStatus) {
        this.comp_id = comp_id;
        this.isWorkingDay = isWorkingDay;
        this.isDayOfWeek = isDayOfWeek;
        this.recordStatus = recordStatus;
    }
    public PnWorkingtimeCalendarEntry(PnWorkingtimeCalendarEntryPK comp_id, String isWorkingDay, String isDayOfWeek, Integer dayNumber, Timestamp startDate, Timestamp endDate, Timestamp time1Start, Timestamp time1End, Timestamp time2Start, Timestamp time2End, Timestamp time3Start, Timestamp time3End, Timestamp time4Start, Timestamp time4End, Timestamp time5Start, Timestamp time5End, String recordStatus, String description, PnWorkingtimeCalendar pnWorkingtimeCalendar) {
       this.comp_id = comp_id;
       this.isWorkingDay = isWorkingDay;
       this.isDayOfWeek = isDayOfWeek;
       this.dayNumber = dayNumber;
       this.startDate = startDate;
       this.endDate = endDate;
       this.time1Start = time1Start;
       this.time1End = time1End;
       this.time2Start = time2Start;
       this.time2End = time2End;
       this.time3Start = time3Start;
       this.time3End = time3End;
       this.time4Start = time4Start;
       this.time4End = time4End;
       this.time5Start = time5Start;
       this.time5End = time5End;
       this.recordStatus = recordStatus;
       this.pnWorkingtimeCalendar = pnWorkingtimeCalendar;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="calendarId", column=@Column(name="CALENDAR_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="entryId", column=@Column(name="ENTRY_ID", nullable=false, length=20) ) } )
    public PnWorkingtimeCalendarEntryPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnWorkingtimeCalendarEntryPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="IS_WORKING_DAY", nullable=false, length=1)
    public String getIsWorkingDay() {
        return this.isWorkingDay;
    }
    
    public void setIsWorkingDay(String isWorkingDay) {
        this.isWorkingDay = isWorkingDay;
    }

    
    @Column(name="IS_DAY_OF_WEEK", nullable=false, length=1)
    public String getIsDayOfWeek() {
        return this.isDayOfWeek;
    }
    
    public void setIsDayOfWeek(String isDayOfWeek) {
        this.isDayOfWeek = isDayOfWeek;
    }

    
    @Column(name="DAY_NUMBER", length=1)
    public Integer getDayNumber() {
        return this.dayNumber;
    }
    
    public void setDayNumber(Integer dayNumber) {
        this.dayNumber = dayNumber;
    }

    @Column(name="START_DATE", length=7)
    public Timestamp getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    @Column(name="END_DATE", length=7)
    public Timestamp getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    @Column(name="TIME1_START", length=7)
    public Timestamp getTime1Start() {
        return this.time1Start;
    }
    
    public void setTime1Start(Timestamp time1Start) {
        this.time1Start = time1Start;
    }

    @Column(name="TIME1_END", length=7)
    public Timestamp getTime1End() {
        return this.time1End;
    }
    
    public void setTime1End(Timestamp time1End) {
        this.time1End = time1End;
    }

    @Column(name="TIME2_START", length=7)
    public Timestamp getTime2Start() {
        return this.time2Start;
    }
    
    public void setTime2Start(Timestamp time2Start) {
        this.time2Start = time2Start;
    }

    @Column(name="TIME2_END", length=7)
    public Timestamp getTime2End() {
        return this.time2End;
    }
    
    public void setTime2End(Timestamp time2End) {
        this.time2End = time2End;
    }

    @Column(name="TIME3_START", length=7)
    public Timestamp getTime3Start() {
        return this.time3Start;
    }
    
    public void setTime3Start(Timestamp time3Start) {
        this.time3Start = time3Start;
    }

    @Column(name="TIME3_END", length=7)
    public Timestamp getTime3End() {
        return this.time3End;
    }
    
    public void setTime3End(Timestamp time3End) {
        this.time3End = time3End;
    }

    @Column(name="TIME4_START", length=7)
    public Timestamp getTime4Start() {
        return this.time4Start;
    }
    
    public void setTime4Start(Timestamp time4Start) {
        this.time4Start = time4Start;
    }

    @Column(name="TIME4_END", length=7)
    public Timestamp getTime4End() {
        return this.time4End;
    }
    
    public void setTime4End(Timestamp time4End) {
        this.time4End = time4End;
    }

    @Column(name="TIME5_START", length=7)
    public Timestamp getTime5Start() {
        return this.time5Start;
    }
    
    public void setTime5Start(Timestamp time5Start) {
        this.time5Start = time5Start;
    }

    @Column(name="TIME5_END", length=7)
    public Timestamp getTime5End() {
        return this.time5End;
    }
    
    public void setTime5End(Timestamp time5End) {
        this.time5End = time5End;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWorkingtimeCalendar.class)
    @JoinColumn(name="CALENDAR_ID", insertable=false, updatable=false)
    public PnWorkingtimeCalendar getPnWorkingtimeCalendar() {
        return this.pnWorkingtimeCalendar;
    }
    
    public void setPnWorkingtimeCalendar(PnWorkingtimeCalendar pnWorkingtimeCalendar) {
        this.pnWorkingtimeCalendar = pnWorkingtimeCalendar;
    }

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWorkingtimeCalendarEntry))
			return false;
		PnWorkingtimeCalendarEntry castOther = (PnWorkingtimeCalendarEntry) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}



}


