/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnWorkingtimeCalendarEntryPK generated by hbm2java
 */
@Embeddable
public class PnWorkingtimeCalendarEntryPK implements Serializable {


     private Integer calendarId;
     private Integer entryId;

    public PnWorkingtimeCalendarEntryPK() {
    }

    public PnWorkingtimeCalendarEntryPK(Integer calendarId, Integer entryId) {
       this.calendarId = calendarId;
       this.entryId = entryId;
    }
   


    @Column(name="CALENDAR_ID", nullable=false, length=20)
    public Integer getCalendarId() {
        return this.calendarId;
    }
    
    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }


    @Column(name="ENTRY_ID", nullable=false, length=20)
    public Integer getEntryId() {
        return this.entryId;
    }
    
    public void setEntryId(Integer entryId) {
        this.entryId = entryId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("calendarId", getCalendarId())
            .append("entryId", getEntryId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnWorkingtimeCalendarEntryPK) ) return false;
        PnWorkingtimeCalendarEntryPK castOther = (PnWorkingtimeCalendarEntryPK) other;
        return new EqualsBuilder()
            .append(this.getCalendarId(), castOther.getCalendarId())
            .append(this.getEntryId(), castOther.getEntryId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCalendarId())
            .append(getEntryId())
            .toHashCode();
    }

}
