/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflowRule generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW_RULE")
public class PnWorkflowRule implements Serializable {

	private PnWorkflowRulePK comp_id;

	private String ruleName;

	private String ruleDescription;

	private String notes;

	private Integer createdById;

	private Date createdDatetime;

	private Integer modifiedById;

	private Date modifiedDatetime;

	private Date crc;

	private String recordStatus;

	private PnWorkflowTransition pnWorkflowTransition;

	private PnWorkflowRuleType pnWorkflowRuleType;

	private PnWfRuleAuth pnWfRuleAuth;

	private PnWorkflowRuleStatus pnWorkflowRuleStatus;

	public PnWorkflowRule() {
	}

	public PnWorkflowRule(PnWorkflowRulePK comp_id, Integer createdById, Date createdDatetime, Date crc,
			String recordStatus) {
		this.comp_id = comp_id;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnWorkflowRule(net.project.hibernate.model.PnWorkflowRulePK comp_id, Integer createdById,
			Date createdDatetime, Date crc, String recordStatus,
			net.project.hibernate.model.PnWorkflowRuleType pnWorkflowRuleType,
			net.project.hibernate.model.PnWorkflowRuleStatus pnWorkflowRuleStatus) {
		this.comp_id = comp_id;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflowRuleType = pnWorkflowRuleType;
		this.pnWorkflowRuleStatus = pnWorkflowRuleStatus;
	}

	public PnWorkflowRule(net.project.hibernate.model.PnWorkflowRulePK comp_id, String ruleName,
			String ruleDescription, String notes, Integer createdById, Date createdDatetime, Integer modifiedById,
			Date modifiedDatetime, Date crc, String recordStatus,
			net.project.hibernate.model.PnWfRuleAuth pnWfRuleAuth,
			net.project.hibernate.model.PnWorkflowTransition pnWorkflowTransition,
			net.project.hibernate.model.PnWorkflowRuleType pnWorkflowRuleType,
			net.project.hibernate.model.PnWorkflowRuleStatus pnWorkflowRuleStatus) {
		this.comp_id = comp_id;
		this.ruleName = ruleName;
		this.ruleDescription = ruleDescription;
		this.notes = notes;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWfRuleAuth = pnWfRuleAuth;
		this.pnWorkflowTransition = pnWorkflowTransition;
		this.pnWorkflowRuleType = pnWorkflowRuleType;
		this.pnWorkflowRuleStatus = pnWorkflowRuleStatus;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "ruleId", column = @Column(name = "RULE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "transitionId", column = @Column(name = "TRANSITION_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "workflowId", column = @Column(name = "WORKFLOW_ID", nullable = false, length = 20)) })
	public PnWorkflowRulePK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnWorkflowRulePK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "RULE_NAME", length = 80)
	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	@Column(name = "RULE_DESCRIPTION", length = 500)
	public String getRuleDescription() {
		return this.ruleDescription;
	}

	public void setRuleDescription(String ruleDescription) {
		this.ruleDescription = ruleDescription;
	}

	@Column(name = "NOTES", length = 4000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflowTransition.class)
	//@JoinColumns( {
	//		@JoinColumn(name = "TRANSITION_ID", referencedColumnName = "WORKFLOW_ID", insertable = false, updatable = false),
	//		@JoinColumn(name = "WORKFLOW_ID", referencedColumnName = "TRANSITION_ID", insertable = false, updatable = false) })
	@Transient
	public PnWorkflowTransition getPnWorkflowTransition() {
		return this.pnWorkflowTransition;
	}

	public void setPnWorkflowTransition(PnWorkflowTransition pnWorkflowTransition) {
		this.pnWorkflowTransition = pnWorkflowTransition;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflowRuleType.class)
	//@JoinColumn(name = "RULE_TYPE_ID")
	@Transient
	public PnWorkflowRuleType getPnWorkflowRuleType() {
		return this.pnWorkflowRuleType;
	}

	public void setPnWorkflowRuleType(PnWorkflowRuleType pnWorkflowRuleType) {
		this.pnWorkflowRuleType = pnWorkflowRuleType;
	}

	//@OneToOne(fetch = FetchType.LAZY, targetEntity = PnWfRuleAuth.class)
	@Transient
	public PnWfRuleAuth getPnWfRuleAuth() {
		return this.pnWfRuleAuth;
	}

	public void setPnWfRuleAuth(PnWfRuleAuth pnWfRuleAuth) {
		this.pnWfRuleAuth = pnWfRuleAuth;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflowRuleStatus.class)	
	//@JoinColumn(name = "RULE_STATUS_ID")
	@Transient
	public PnWorkflowRuleStatus getPnWorkflowRuleStatus() {
		return this.pnWorkflowRuleStatus;
	}

	public void setPnWorkflowRuleStatus(PnWorkflowRuleStatus pnWorkflowRuleStatus) {
		this.pnWorkflowRuleStatus = pnWorkflowRuleStatus;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWorkflowRule))
			return false;
		PnWorkflowRule castOther = (PnWorkflowRule) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
