CREATE TABLE PN_PROJECT_FINANCIAL (
  PROJECT_ID number(20),
  COST_CALCULATION_METHOD varchar(20),
  EXTRA_COSTS number(20,2),
  constraint PROJECT_FINANCIAL_PK primary key (PROJECT_ID),
  constraint PROJECT_FINANCIAL_FK FOREIGN KEY (PROJECT_ID) REFERENCES PN_PROJECT_SPACE(PROJECT_ID)
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_PROJECT_FINANCIAL FOR PNET.PN_PROJECT_FINANCIAL;

CREATE TABLE PN_FINANCIAL_SPACE (
  FINANCIAL_SPACE_ID number(20),
  FINANCIAL_SPACE_NAME varchar(40),
  RECORD_STATUS varchar(1),
  constraint FINANCIAL_SPACE_PK primary key (FINANCIAL_SPACE_ID),
  constraint RECORD_STATUS_FS1 check (RECORD_STATUS in ('A','D'))
);
CREATE OR REPLACE SYNONYM PNET_USER.PN_FINANCIAL_SPACE FOR PNET.PN_FINANCIAL_SPACE;
