ALTER VIEW "PNET"."PN_BUSINESS_SPACE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_BUSINESS_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_DOC_BY_SPACE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_DOC_DELETED_BY_SPACE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_ENVELOPE_ACTIVE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_USER_DOMAIN_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_BUSINESS_SPACE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_DOC_CONTAINER_LIST_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_DOC_DEL_CONTAINER_LIST_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_WORKFLOW_ENVELOPE_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_METHODOLOGY_BY_USER_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_WORKFLOW_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_ENVELOPE_HAS_OBJECT_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_ENVELOPE_HAS_PERSON_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_WORKFLOW_STEP_VIEW" COMPILE;
ALTER VIEW "PNET"."PN_BOOKMARK_VIEW" COMPILE;
exit
