package net.project.hibernate.model;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * PnActivityLog generated by hbm2java
 */
@Entity
@Table(name = "PN_ACTIVITY_LOG")
public class PnActivityLog implements java.io.Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private Integer activityLogId;

	private String activityType;

	private Timestamp activityOnDate;

	private Integer activityBy;

	private String targetObjectType;

	private Integer targetObjectId;

	private String description;

	private Integer spaceId;

	private Integer parentObjectId;

	private Integer isImportant;
	
	private String objectName;
	
	private String personName;

	public PnActivityLog() {
	}

	/**
	 * Constructor for primary key
	 */
	public PnActivityLog(java.lang.Integer activityLogId) {
		this.setActivityLogId(activityLogId);
	}

	/**
	 * Constructor for required fields
	 */
	public PnActivityLog(java.lang.Integer activityLogId, java.lang.String activityType, Timestamp activityOnDate,
			java.lang.Integer activityBy, java.lang.String targetObjectType, java.lang.Integer targetObjectId,
			java.lang.Integer spaceId) {

		this.setActivityLogId(activityLogId);
		this.setActivityType(activityType);
		this.setActivityOnDate(activityOnDate);
		this.setActivityBy(activityBy);
		this.setTargetObjectType(targetObjectType);
		this.setTargetObjectId(targetObjectId);
		this.setSpaceId(spaceId);
	}

	/**
	 * Constructor for required fields
	 */
	public PnActivityLog(java.lang.Integer activityLogId, java.lang.String activityType, Timestamp activityOnDate,
			java.lang.Integer activityBy, java.lang.String targetObjectType, java.lang.Integer targetObjectId,
			java.lang.String description, java.lang.Integer spaceId) {

		this.setActivityLogId(activityLogId);
		this.setActivityType(activityType);
		this.setActivityOnDate(activityOnDate);
		this.setActivityBy(activityBy);
		this.setTargetObjectType(targetObjectType);
		this.setTargetObjectId(targetObjectId);
		this.setDescription(description);
		this.setSpaceId(spaceId);
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ACTIVITY_LOG_ID", nullable = false, length = 20)
	public Integer getActivityLogId() {
		return this.activityLogId;
	}

	public void setActivityLogId(Integer activityLogId) {
		this.activityLogId = activityLogId;
	}

	@Column(name = "ACTIVITY_TYPE", nullable = false, length = 240)
	public String getActivityType() {
		return this.activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}

	@Column(name = "ACTIVITY_ON_DATE", nullable = false, length = 7)
	public Timestamp getActivityOnDate() {
		return this.activityOnDate;
	}

	public void setActivityOnDate(Timestamp activityOnDate) {
		this.activityOnDate = activityOnDate;
	}

	@Column(name = "ACTIVITY_BY", nullable = false, length = 20)
	public Integer getActivityBy() {
		return this.activityBy;
	}

	public void setActivityBy(Integer activityBy) {
		this.activityBy = activityBy;
	}

	@Column(name = "TARGET_OBJECT_TYPE", nullable = false, length = 240)
	public String getTargetObjectType() {
		return this.targetObjectType;
	}

	public void setTargetObjectType(String targetObjectType) {
		this.targetObjectType = targetObjectType;
	}

	@Column(name = "TARGET_OBJECT_ID", nullable = false, length = 20)
	public Integer getTargetObjectId() {
		return this.targetObjectId;
	}

	public void setTargetObjectId(Integer targetObjectId) {
		this.targetObjectId = targetObjectId;
	}

	@Column(name = "DESCRIPTION", length = 240)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SPACE_ID", nullable = false, length = 20)
	public Integer getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	@Column(name = "PARENT_OBJECT_ID", length = 20)
	public Integer getParentObjectId() {
		return this.parentObjectId;
	}

	public void setParentObjectId(Integer parentObjectId) {
		this.parentObjectId = parentObjectId;
	}

	@Column(name = "IS_IMPORTANT", length = 1)
	public Integer getIsImportant() {
		return this.isImportant;
	}

	public void setIsImportant(Integer isImportant) {
		this.isImportant = isImportant;
	}

	/**
	 * @return the objectName
	 */
	@Transient
	public String getObjectName() {
		return objectName;
	}

	/**
	 * @param objectName the objectName to set
	 */
	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	/**
	 * @return the personName
	 */
	@Transient
	public String getPersonName() {
		return personName;
	}

	/**
	 * @param personName the personName to set
	 */
	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof net.project.hibernate.model.PnActivityLog))
			return false;
		else {
			net.project.hibernate.model.PnActivityLog pnActivityLog = (net.project.hibernate.model.PnActivityLog) obj;
			if (null == this.getActivityLogId() || null == pnActivityLog.getActivityLogId())
				return false;
			else
				return (this.getActivityLogId().equals(pnActivityLog.getActivityLogId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getActivityLogId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getActivityLogId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

}
