/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import net.project.util.NumberFormat;

/**
 * PnAssignment generated by hbm2java
 */
@Entity
@Table(name = "PN_ASSIGNMENT")
public class PnAssignment implements java.io.Serializable {

	private PnAssignmentPK comp_id;

	private int statusId;

	private BigDecimal percentAllocated;

	private String role;

	private int isPrimaryOwner;

	private String recordStatus;

	private Date startDate;

	private Date endDate;

	private BigDecimal work;

	private Integer workUnits;

	private BigDecimal workComplete;

	private Integer workCompleteUnits;

	private Date dateCreated;

	private Date modifiedDate;

	private Integer modifiedBy;

	private Integer isComplete;

	private BigDecimal percentComplete;

	private Date actualStart;

	private Date actualFinish;

	private Date estimatedFinish;

	private PnObject pnObject;

	private PnSpaceHasPerson pnSpaceHasPerson;

	private PnPerson pnAssignor;

	private PnTask pnTask;

	private PnProjectSpace pnProjectSpace;

	private PnSpaceHasSpace pnSpaceHasSpace;

	private PnPerson pnPerson;

	private String month;

	private String personName;

	private String taskName;

	private String startDateString;

	private String endDateString;

	private String rowClass;

	private PnObjectType pnObjectType;

	private PnObjectName pnObjectName;

	private String spaceName;

	private Integer spaceId;

	private String spaceType;

	private PnClassInstance pnClassInstance;

	public PnAssignment() {
	}

	public PnAssignment(PnAssignmentPK comp_id, int statusId, int isPrimaryOwner, String recordStatus) {
		this.comp_id = comp_id;
		this.statusId = statusId;
		this.isPrimaryOwner = isPrimaryOwner;
		this.recordStatus = recordStatus;
	}

	public PnAssignment(PnAssignmentPK comp_id, int statusId, BigDecimal percentAllocated, String role,
			int isPrimaryOwner, String recordStatus, Date startDate, Date endDate, BigDecimal work, Integer workUnits,
			BigDecimal workComplete, Integer workCompleteUnits, Date dateCreated, Date modifiedDate,
			Integer modifiedBy, Integer isComplete, BigDecimal percentComplete, Date actualStart, Date actualFinish,
			Date estimatedFinish, PnObject pnObject, PnSpaceHasPerson pnSpaceHasPerson, PnPerson pnAssignor,
			PnTask pnTask, PnClassInstance pnClassInstance) {
		this.comp_id = comp_id;
		this.statusId = statusId;
		this.percentAllocated = percentAllocated;
		this.role = role;
		this.isPrimaryOwner = isPrimaryOwner;
		this.recordStatus = recordStatus;
		this.startDate = startDate;
		this.endDate = endDate;
		this.work = work;
		this.workUnits = workUnits;
		this.workComplete = workComplete;
		this.workCompleteUnits = workCompleteUnits;
		this.dateCreated = dateCreated;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.isComplete = isComplete;
		this.percentComplete = percentComplete;
		this.actualStart = actualStart;
		this.actualFinish = actualFinish;
		this.estimatedFinish = estimatedFinish;
		this.pnObject = pnObject;
		this.pnSpaceHasPerson = pnSpaceHasPerson;
		this.pnAssignor = pnAssignor;
		this.pnTask = pnTask;
		this.pnClassInstance = pnClassInstance;
	}

	/*For View Details Page ResourceTab*/
	public PnAssignment(BigDecimal percentAllocated, BigDecimal workComplete, Date startDate, Date endDate,
			BigDecimal work) {
		this.percentAllocated = percentAllocated;
		this.work = work;
		this.workComplete = workComplete;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	/*For View Summary Page ResourceTab*/
	public PnAssignment(net.project.hibernate.model.PnAssignmentPK comp_id, String month, BigDecimal work) {
		this.comp_id = comp_id;
		this.month = month;
		this.work = work;
	}

	/*For View Summary Page ResourceTab*/
	public PnAssignment(String personName, Integer projectId, String projectName, String taskName,
			BigDecimal percentComplete, String objectType, BigDecimal work, Integer workUnits, BigDecimal workComplete,
			Date startDate, Date endDate, BigDecimal percentAllocated, Integer objectId) {
		this.personName = personName;
		PnProjectSpace pnProjectSpace = new PnProjectSpace(projectId, projectName);
		this.pnProjectSpace = pnProjectSpace;
		this.taskName = taskName;
		this.percentComplete = percentComplete;
		PnObjectType pnObjectType = new PnObjectType();
		pnObjectType.setObjectType(objectType);
		this.pnObjectType = pnObjectType;
		this.work = work;
		this.workUnits = workUnits;
		this.workComplete = workComplete;
		this.startDate = startDate;
		this.endDate = endDate;
		this.percentAllocated = percentAllocated;
		PnTask task = new PnTask();
		task.setTaskId(objectId);
		this.pnTask = task;
	}

	/*For Assignment PersonalTab*/
	public PnAssignment(String personFirstName, String personLastName, String assignorFirstName,
			String assignorLastName, Integer spaceId, String spaceName, String spaceType, String objectType,
			BigDecimal work, Integer workUnits, BigDecimal workComplete, Integer workCompleteUnits,
			BigDecimal percentComplete, Date startDate, Date endDate, Date actualStart, Date actualFinish,
			BigDecimal percentAllocated, Integer assignmentId, String assignmentName, String taskType,
			Integer parentTaskId, Integer classId, Integer personId, Integer statusId, Integer sequenceNo) {
		this.pnPerson = new PnPerson();
		pnPerson.setFirstName(personFirstName);
		pnPerson.setLastName(personLastName);
		this.pnAssignor = new PnPerson();
		pnAssignor.setFirstName(assignorFirstName);
		pnAssignor.setLastName(assignorLastName);
		this.spaceId = spaceId;
		this.spaceName = spaceName;
		this.spaceType = spaceType;
		PnObjectType pnObjectType = new PnObjectType();
		pnObjectType.setObjectType(objectType);
		this.pnObjectType = pnObjectType;
		this.work = work;
		this.workUnits = workUnits;
		this.workComplete = workComplete;
		this.workCompleteUnits = workCompleteUnits;
		this.percentComplete = percentComplete;
		this.startDate = startDate;
		this.endDate = endDate;
		this.actualStart = actualStart;
		this.actualFinish = actualFinish;
		this.percentAllocated = percentAllocated;
		PnObjectName objectName = new PnObjectName(assignmentId, assignmentName);
		pnObjectName = objectName;
		PnTask task = new PnTask();
		task.setTaskType(taskType);
		task.setParentTaskId(parentTaskId);
		this.pnTask = task;
		PnClassInstance pnClassInstance = new PnClassInstance();
		pnClassInstance.setClassId(classId);
		pnClassInstance.setSequenceNo(sequenceNo);
		this.pnClassInstance = pnClassInstance;
		pnPerson.setPersonId(personId);
		this.statusId = statusId;
	}

	/**
	 * @param dateCreated
	 * @param percentAllocated
	 */
	public PnAssignment(Date startDate, BigDecimal percentAllocated) {
		this.startDate = startDate;
		this.percentAllocated = percentAllocated;
	}

	/**
	 * @param startDate
	 * @param endDate
	 * @param percentAllocated
	 * @param work
	 */
	public PnAssignment(Date startDate, Date endDate, BigDecimal percentAllocated, BigDecimal work) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.percentAllocated = percentAllocated;
		this.work = work;
	}

	/**
	 * @param startDate
	 * @param endDate
	 * @param percentAllocated
	 * @param work
	 */
	public PnAssignment(Date startDate, Date endDate, BigDecimal percentAllocated, BigDecimal work,
			BigDecimal percentComplete) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.percentAllocated = percentAllocated;
		this.work = work;
		this.percentComplete = percentComplete;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "spaceId", column = @Column(name = "SPACE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "objectId", column = @Column(name = "OBJECT_ID", nullable = false, length = 20)) })
	public PnAssignmentPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnAssignmentPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "STATUS_ID", nullable = false, length = 3)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "PERCENT_ALLOCATED", length = 22)
	public BigDecimal getPercentAllocated() {
		return this.percentAllocated;
	}

	public void setPercentAllocated(BigDecimal percentAllocated) {
		this.percentAllocated = percentAllocated;
	}

	@Column(name = "ROLE", length = 80)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "IS_PRIMARY_OWNER", nullable = false, length = 1)
	public int getIsPrimaryOwner() {
		return this.isPrimaryOwner;
	}

	public void setIsPrimaryOwner(int isPrimaryOwner) {
		this.isPrimaryOwner = isPrimaryOwner;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
    
	@Column(name = "WORK", length = 22)
	public BigDecimal getWork() {
		return this.work;
	}

	public void setWork(BigDecimal work) {
		this.work = work;
	}

	@Column(name = "WORK_UNITS", length = 22)
	public Integer getWorkUnits() {
		return this.workUnits;
	}

	public void setWorkUnits(Integer workUnits) {
		this.workUnits = workUnits;
	}

	@Column(name = "WORK_COMPLETE", length = 22)
	public BigDecimal getWorkComplete() {
		return this.workComplete;
	}

	public void setWorkComplete(BigDecimal workComplete) {
		this.workComplete = workComplete;
	}

	@Column(name = "WORK_COMPLETE_UNITS", length = 22)
	public Integer getWorkCompleteUnits() {
		return this.workCompleteUnits;
	}

	public void setWorkCompleteUnits(Integer workCompleteUnits) {
		this.workCompleteUnits = workCompleteUnits;
	}

	@Column(name = "DATE_CREATED", length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 20)
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "IS_COMPLETE", length = 22)
	public Integer getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(Integer isComplete) {
		this.isComplete = isComplete;
	}

	@Column(name = "PERCENT_COMPLETE", length = 22)
	public BigDecimal getPercentComplete() {
		return this.percentComplete;
	}

	public void setPercentComplete(BigDecimal percentComplete) {
		this.percentComplete = percentComplete;
	}

	@Column(name = "ACTUAL_START", length = 7)
	public Date getActualStart() {
		return this.actualStart;
	}

	public void setActualStart(Date actualStart) {
		this.actualStart = actualStart;
	}

	@Column(name = "ACTUAL_FINISH", length = 7)
	public Date getActualFinish() {
		return this.actualFinish;
	}

	public void setActualFinish(Date actualFinish) {
		this.actualFinish = actualFinish;
	}

	@Column(name = "ESTIMATED_FINISH", length = 7)
	public Date getEstimatedFinish() {
		return this.estimatedFinish;
	}

	public void setEstimatedFinish(Date estimatedFinish) {
		this.estimatedFinish = estimatedFinish;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	@JoinColumn(name = "OBJECT_ID", insertable = false, updatable = false)
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnSpaceHasPerson.class)
	//@JoinColumns( {
	//		@JoinColumn(name = "SPACE_ID", referencedColumnName = "SPACE_ID", insertable = false, updatable = false),
	//		@JoinColumn(name = "PERSON_ID", referencedColumnName = "PERSON_ID", insertable = false, updatable = false) })
	@Transient
	public PnSpaceHasPerson getPnSpaceHasPerson() {
		return this.pnSpaceHasPerson;
	}

	public void setPnSpaceHasPerson(PnSpaceHasPerson pnSpaceHasPerson) {
		this.pnSpaceHasPerson = pnSpaceHasPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "ASSIGNOR_ID", insertable = false, updatable = false)
	public PnPerson getPnAssignor() {
		return this.pnAssignor;
	}

	public void setPnAssignor(PnPerson pnAssignor) {
		this.pnAssignor = pnAssignor;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnTask.class)
	@JoinColumn(name = "OBJECT_ID", insertable = false, updatable = false)
	public PnTask getPnTask() {
		return this.pnTask;
	}

	public void setPnTask(PnTask pnTask) {
		this.pnTask = pnTask;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnClassInstance.class)
	@JoinColumn(name = "OBJECT_ID", insertable = false, updatable = false)
	public PnClassInstance getPnClassInstance() {
		return this.pnClassInstance;
	}

	public void setPnClassInstance(PnClassInstance pnClassInstance) {
		this.pnClassInstance = pnClassInstance;
	}

	/**
	 * @return the endDateString
	 */
	@Transient
	public String getEndDateString() {
		return endDateString;
	}

	/**
	 * @param endDateString the endDateString to set
	 */
	public void setEndDateString(String endDateString) {
		this.endDateString = endDateString;
	}

	/**
	 * @return the month
	 */
	@Transient
	public String getMonth() {
		return month;
	}

	/**
	 * @param month the month to set
	 */
	public void setMonth(String month) {
		this.month = month;
	}

	/**
	 * @return the personName
	 */
	@Transient
	public String getPersonName() {
		return personName;
	}

	/**
	 * @param personName the personName to set
	 */
	public void setPersonName(String personName) {
		this.personName = personName;
	}

	/**
	 * @return the pnObjectName
	 */
	@Transient
	public PnObjectName getPnObjectName() {
		return pnObjectName;
	}

	/**
	 * @param pnObjectName the pnObjectName to set
	 */
	public void setPnObjectName(PnObjectName pnObjectName) {
		this.pnObjectName = pnObjectName;
	}

	/**
	 * @return the pnObjectType
	 */
	@Transient
	public PnObjectType getPnObjectType() {
		return pnObjectType;
	}

	/**
	 * @param pnObjectType the pnObjectType to set
	 */
	public void setPnObjectType(PnObjectType pnObjectType) {
		this.pnObjectType = pnObjectType;
	}

	/**
	 * @return the pnPerson
	 */
	@Transient
	public PnPerson getPnPerson() {
		return pnPerson;
	}

	/**
	 * @param pnPerson the pnPerson to set
	 */
	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	/**
	 * @return the pnProjectSpace
	 */
	@Transient
	public PnProjectSpace getPnProjectSpace() {
		return pnProjectSpace;
	}

	/**
	 * @param pnProjectSpace the pnProjectSpace to set
	 */
	public void setPnProjectSpace(PnProjectSpace pnProjectSpace) {
		this.pnProjectSpace = pnProjectSpace;
	}

	/**
	 * @return the pnSpaceHasSpace
	 */
	@Transient
	public PnSpaceHasSpace getPnSpaceHasSpace() {
		return pnSpaceHasSpace;
	}

	/**
	 * @param pnSpaceHasSpace the pnSpaceHasSpace to set
	 */
	public void setPnSpaceHasSpace(PnSpaceHasSpace pnSpaceHasSpace) {
		this.pnSpaceHasSpace = pnSpaceHasSpace;
	}

	/**
	 * @return the rowClass
	 */
	@Transient
	public String getRowClass() {
		return rowClass;
	}

	/**
	 * @param rowClass the rowClass to set
	 */
	public void setRowClass(String rowClass) {
		this.rowClass = rowClass;
	}

	/**
	 * @return the spaceId
	 */
	@Transient
	public Integer getSpaceId() {
		return spaceId;
	}

	/**
	 * @param spaceId the spaceId to set
	 */
	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	/**
	 * @return the spaceName
	 */
	@Transient
	public String getSpaceName() {
		return spaceName;
	}

	/**
	 * @param spaceName the spaceName to set
	 */
	public void setSpaceName(String spaceName) {
		this.spaceName = spaceName;
	}

	/**
	 * @return the spaceType
	 */
	@Transient
	public String getSpaceType() {
		return spaceType;
	}

	/**
	 * @param spaceType the spaceType to set
	 */
	public void setSpaceType(String spaceType) {
		this.spaceType = spaceType;
	}

	/**
	 * @return the startDateString
	 */
	@Transient
	public String getStartDateString() {
		return startDateString;
	}

	/**
	 * @param startDateString the startDateString to set
	 */
	public void setStartDateString(String startDateString) {
		this.startDateString = startDateString;
	}

	/**
	 * @return the taskName
	 */
	@Transient
	public String getTaskName() {
		return taskName;
	}

	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	
	@Transient
    public String getWorkString() {
        return NumberFormat.getInstance().formatPercent(this.work.floatValue(), "###.##");
    }
	
	@Transient
	public String getWorkCompleteString() {
        return NumberFormat.getInstance().formatPercent(this.workComplete.floatValue(), "###.##");
    }

}
