package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBaselineHasPlanPK generated by hbm2java
 */
@Embeddable
public class PnBaselineHasPlanPK  implements java.io.Serializable {


     private Integer baselineId;
     
     private Integer planId;

    public PnBaselineHasPlanPK() {
    }

    public PnBaselineHasPlanPK(Integer baselineId, Integer planId) {
       this.baselineId = baselineId;
       this.planId = planId;
    }
   


    @Column(name="BASELINE_ID", nullable=false, length=20)
    public Integer getBaselineId() {
        return this.baselineId;
    }
    
    public void setBaselineId(Integer baselineId) {
        this.baselineId = baselineId;
    }


    @Column(name="PLAN_ID", nullable=false, length=20)
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("baselineId", getBaselineId())
            .append("planId", getPlanId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnBaselineHasPlanPK) ) return false;
        PnBaselineHasPlanPK castOther = (PnBaselineHasPlanPK) other;
        return new EqualsBuilder()
            .append(this.getBaselineId(), castOther.getBaselineId())
            .append(this.getPlanId(), castOther.getPlanId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getBaselineId())
            .append(getPlanId())
            .toHashCode();
    }

}


