package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBaselineHasTaskPK generated by hbm2java
 */
@Embeddable
public class PnBaselineHasTaskPK  implements java.io.Serializable {


     private Integer baselineId;
     private Integer taskId;

    public PnBaselineHasTaskPK() {
    }

    public PnBaselineHasTaskPK(Integer baselineId, Integer taskId) {
       this.baselineId = baselineId;
       this.taskId = taskId;
    }
   


    @Column(name="BASELINE_ID", nullable=false, length=20)
    public Integer getBaselineId() {
        return this.baselineId;
    }
    
    public void setBaselineId(Integer baselineId) {
        this.baselineId = baselineId;
    }


    @Column(name="TASK_ID", nullable=false, length=20)
    public Integer getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

public String toString() {
        return new ToStringBuilder(this)
            .append("baselineId", getBaselineId())
            .append("taskId", getTaskId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnBaselineHasTaskPK) ) return false;
        PnBaselineHasTaskPK castOther = (PnBaselineHasTaskPK) other;
        return new EqualsBuilder()
            .append(this.getBaselineId(), castOther.getBaselineId())
            .append(this.getTaskId(), castOther.getTaskId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getBaselineId())
            .append(getTaskId())
            .toHashCode();
    }

}


