package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBookmark generated by hbm2java
 */
@Entity
@Table(name="PN_BOOKMARK"
)
public class PnBookmark  implements java.io.Serializable {

    private Integer bookmarkId;
     
    private String name;
     
    private String description;
     
    private String url;
     
    private Integer statusId;
     
    private String comments;
     
    private Date modifiedDate;
     
    private String recordStatus;
     
    private Date crc;
     
    private PnPerson pnPersonByOwnerId;
     
    private PnPerson pnPersonByModifiedById;

    public PnBookmark() {
    }

    public PnBookmark(Integer bookmarkId, String name, String url, String recordStatus, Date crc) {
        this.bookmarkId = bookmarkId;
        this.name = name;
        this.url = url;
        this.recordStatus = recordStatus;
        this.crc = crc;
    }
    public PnBookmark(Integer bookmarkId, String name, String description, String url, Integer statusId, String comments, Date modifiedDate, String recordStatus, Date crc, PnPerson pnPersonByOwnerId, PnPerson pnPersonByModifiedById) {
       this.bookmarkId = bookmarkId;
       this.name = name;
       this.description = description;
       this.url = url;
       this.statusId = statusId;
       this.comments = comments;
       this.modifiedDate = modifiedDate;
       this.recordStatus = recordStatus;
       this.crc = crc;
       this.pnPersonByOwnerId = pnPersonByOwnerId;
       this.pnPersonByModifiedById = pnPersonByModifiedById;
    }
   
    /** minimal constructor */
    public PnBookmark(Integer bookmarkId, String name, String url, String recordStatus, Date crc, net.project.hibernate.model.PnPerson pnPersonByOwnerId, net.project.hibernate.model.PnPerson pnPersonByModifiedById) {
        this.bookmarkId = bookmarkId;
        this.name = name;
        this.url = url;
        this.recordStatus = recordStatus;
        this.crc = crc;
        this.pnPersonByOwnerId = pnPersonByOwnerId;
        this.pnPersonByModifiedById = pnPersonByModifiedById;
    }
    
    @Id 
    @Column(name="BOOKMARK_ID", nullable=false)
    public Integer getBookmarkId() {
        return this.bookmarkId;
    }
    
    public void setBookmarkId(Integer bookmarkId) {
        this.bookmarkId = bookmarkId;
    }

    
    @Column(name="NAME", nullable=false, length=240)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="URL", nullable=false, length=500)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="STATUS_ID", length=20)
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="COMMENTS", length=500)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="MODIFIED_DATE", length=7)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="OWNER_ID")
    public PnPerson getPnPersonByOwnerId() {
        return this.pnPersonByOwnerId;
    }
    
    public void setPnPersonByOwnerId(PnPerson pnPersonByOwnerId) {
        this.pnPersonByOwnerId = pnPersonByOwnerId;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="MODIFIED_BY_ID")
    public PnPerson getPnPersonByModifiedById() {
        return this.pnPersonByModifiedById;
    }
    
    public void setPnPersonByModifiedById(PnPerson pnPersonByModifiedById) {
        this.pnPersonByModifiedById = pnPersonByModifiedById;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("bookmarkId", getBookmarkId())
            .toString();
    }

}


