/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBrand generated by hbm2java
 */
@Entity
@Table(name = "PN_BRAND")
public class PnBrand implements java.io.Serializable {

	private Integer brandId;

	private String brandAbbrv;

	private String brandName;

	private String brandDesc;

	private int isSystemDefault;

	private String recordStatus;

	private PnLanguage pnLanguage;

	private Set pnBrandHasHosts = new HashSet(0);

	public PnBrand() {
	}

	public PnBrand(Integer brandId, String brandAbbrv, String brandName, int isSystemDefault) {
		this.brandId = brandId;
		this.brandAbbrv = brandAbbrv;
		this.brandName = brandName;
		this.isSystemDefault = isSystemDefault;
	}

	public PnBrand(Integer brandId, String brandAbbrv, String brandName, String brandDesc, int isSystemDefault,
			String recordStatus, PnLanguage pnLanguage, Set pnBrandHasHosts) {
		this.brandId = brandId;
		this.brandAbbrv = brandAbbrv;
		this.brandName = brandName;
		this.brandDesc = brandDesc;
		this.isSystemDefault = isSystemDefault;
		this.recordStatus = recordStatus;
		this.pnLanguage = pnLanguage;
		this.pnBrandHasHosts = pnBrandHasHosts;
	}

	/** minimal constructor */
	public PnBrand(Integer brandId, String brandAbbrv, String brandName, int isSystemDefault,
			net.project.hibernate.model.PnLanguage pnLanguage, Set pnBrandHasHosts) {
		this.brandId = brandId;
		this.brandAbbrv = brandAbbrv;
		this.brandName = brandName;
		this.isSystemDefault = isSystemDefault;
		this.pnLanguage = pnLanguage;
		this.pnBrandHasHosts = pnBrandHasHosts;
	}

	@Id
	@Column(name = "BRAND_ID", nullable = false)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@Column(name = "BRAND_ABBRV", nullable = false, length = 20)
	public String getBrandAbbrv() {
		return this.brandAbbrv;
	}

	public void setBrandAbbrv(String brandAbbrv) {
		this.brandAbbrv = brandAbbrv;
	}

	@Column(name = "BRAND_NAME", nullable = false, length = 80)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	@Column(name = "BRAND_DESC", length = 1000)
	public String getBrandDesc() {
		return this.brandDesc;
	}

	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc;
	}

	@Column(name = "IS_SYSTEM_DEFAULT", nullable = false, length = 1)
	public int getIsSystemDefault() {
		return this.isSystemDefault;
	}

	public void setIsSystemDefault(int isSystemDefault) {
		this.isSystemDefault = isSystemDefault;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnLanguage.class)
	@JoinColumn(name = "DEFAULT_LANGUAGE")
	public PnLanguage getPnLanguage() {
		return this.pnLanguage;
	}

	public void setPnLanguage(PnLanguage pnLanguage) {
		this.pnLanguage = pnLanguage;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnBrand", targetEntity = PnBrandHasHost.class)
	@Transient
	public Set getPnBrandHasHosts() {
		return this.pnBrandHasHosts;
	}

	public void setPnBrandHasHosts(Set pnBrandHasHosts) {
		this.pnBrandHasHosts = pnBrandHasHosts;
	}

	public String toString() {
		return new ToStringBuilder(this).append("brandId", getBrandId()).toString();
	}

}
