package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBrandHasHost generated by hbm2java
 */
@Entity
@Table(name="PN_BRAND_HAS_HOST"
)
public class PnBrandHasHost  implements java.io.Serializable {

     private PnBrandHasHostPK comp_id;
     
     private String recordStatus;
     
     private PnBrand pnBrand;

    public PnBrandHasHost() {
    }

	
    public PnBrandHasHost(PnBrandHasHostPK comp_id) {
        this.comp_id = comp_id;
    }
    public PnBrandHasHost(PnBrandHasHostPK comp_id, String recordStatus, PnBrand pnBrand) {
       this.comp_id = comp_id;
       this.recordStatus = recordStatus;
       this.pnBrand = pnBrand;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="brandId", column=@Column(name="BRAND_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="hostName", column=@Column(name="HOST_NAME", nullable=false, length=120) ) } )
    public PnBrandHasHostPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnBrandHasHostPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="RECORD_STATUS", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnBrand.class)
    @JoinColumn(name="BRAND_ID", insertable=false, updatable=false)
    public PnBrand getPnBrand() {
        return this.pnBrand;
    }
    
    public void setPnBrand(PnBrand pnBrand) {
        this.pnBrand = pnBrand;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnBrandHasHost) ) return false;
        PnBrandHasHost castOther = (PnBrandHasHost) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }


}


