package net.project.hibernate.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBusinessSpace generated by hbm2java
 */
@Entity
@Table(name = "PN_BUSINESS_SPACE")
public class PnBusinessSpace implements java.io.Serializable {

	/** identifier field */
	private Integer businessSpaceId;

	/** nullable persistent field */
	private Integer spaceType;

	/** nullable persistent field */
	private Integer completePortfolioId;

	/** persistent field */
	private String recordStatus;

	/** persistent field */
	private int includesEveryone;

	/** persistent field */
	private PnBusiness pnBusiness;

	/** Default constructor */
	public PnBusinessSpace() {
	}

	public PnBusinessSpace(Integer businessSpaceId, String recordStatus, int includesEveryone) {
		this.businessSpaceId = businessSpaceId;
		this.recordStatus = recordStatus;
		this.includesEveryone = includesEveryone;
	}

	/** minimal constructor */
	public PnBusinessSpace(Integer businessSpaceId, String recordStatus, int includesEveryone,
			net.project.hibernate.model.PnBusiness pnBusiness) {
		this.businessSpaceId = businessSpaceId;
		this.recordStatus = recordStatus;
		this.includesEveryone = includesEveryone;
		this.pnBusiness = pnBusiness;
	}

	public PnBusinessSpace(Integer businessSpaceId, Integer spaceType, Integer completePortfolioId,
			String recordStatus, int includesEveryone, PnBusiness pnBusiness) {
		this.businessSpaceId = businessSpaceId;
		this.spaceType = spaceType;
		this.completePortfolioId = completePortfolioId;
		this.recordStatus = recordStatus;
		this.includesEveryone = includesEveryone;
		this.pnBusiness = pnBusiness;
	}

	@Id
	@Column(name = "BUSINESS_SPACE_ID", nullable = false)
	public Integer getBusinessSpaceId() {
		return this.businessSpaceId;
	}

	public void setBusinessSpaceId(Integer businessSpaceId) {
		this.businessSpaceId = businessSpaceId;
	}

	@Column(name = "SPACE_TYPE", length = 20)
	public Integer getSpaceType() {
		return this.spaceType;
	}

	public void setSpaceType(Integer spaceType) {
		this.spaceType = spaceType;
	}

	@Column(name = "COMPLETE_PORTFOLIO_ID", length = 20)
	public Integer getCompletePortfolioId() {
		return this.completePortfolioId;
	}

	public void setCompletePortfolioId(Integer completePortfolioId) {
		this.completePortfolioId = completePortfolioId;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "INCLUDES_EVERYONE", nullable = false, length = 1)
	public int getIncludesEveryone() {
		return this.includesEveryone;
	}

	public void setIncludesEveryone(int includesEveryone) {
		this.includesEveryone = includesEveryone;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnBusiness.class)
	@JoinColumn(name = "BUSINESS_ID")
	public PnBusiness getPnBusiness() {
		return this.pnBusiness;
	}

	public void setPnBusiness(PnBusiness pnBusiness) {
		this.pnBusiness = pnBusiness;
	}

	public String toString() {
		return new ToStringBuilder(this).append("businessSpaceId", getBusinessSpaceId()).toString();
	}

}
