package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnBusinessCategory generated by hbm2java
 */
@Entity
@Table(name="PN_BUSINESS_CATEGORY"
)
public class PnBusinessCategory  implements java.io.Serializable {

    /** identifier field */
    private Integer businessCategoryId;

    /** persistent field */
    private String categoryName;

    /** persistent field */
    private String categoryDescription;

    /** full constructor */
    public PnBusinessCategory(Integer businessCategoryId, String categoryName, String categoryDescription) {
        this.businessCategoryId = businessCategoryId;
        this.categoryName = categoryName;
        this.categoryDescription = categoryDescription;
    }

    /** default constructor */
    public PnBusinessCategory() {
    }

    @Id 
    @Column(name="BUSINESS_CATEGORY_ID", nullable=false)
    public Integer getBusinessCategoryId() {
        return this.businessCategoryId;
    }
    
    public void setBusinessCategoryId(Integer businessCategoryId) {
        this.businessCategoryId = businessCategoryId;
    }

    
    @Column(name="CATEGORY_NAME", nullable=false, length=80)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="CATEGORY_DESCRIPTION", nullable=false, length=80)
    public String getCategoryDescription() {
        return this.categoryDescription;
    }
    
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("businessCategoryId", getBusinessCategoryId())
            .toString();
    }

}


