/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnCalEventHasAttendeePK generated by hbm2java
 */
@Embeddable
public class PnCalEventHasAttendeePK  implements java.io.Serializable {

    /** identifier field */
    private Integer personId;

    /** identifier field */
    private Integer calendarEventId;

    public PnCalEventHasAttendeePK() {
    }

    public PnCalEventHasAttendeePK(Integer personId, Integer calendarEventId) {
       this.personId = personId;
       this.calendarEventId = calendarEventId;
    }

    @Column(name="PERSON_ID", nullable=false, length=20)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }


    @Column(name="CALENDAR_EVENT_ID", nullable=false, length=20)
    public Integer getCalendarEventId() {
        return this.calendarEventId;
    }
    
    public void setCalendarEventId(Integer calendarEventId) {
        this.calendarEventId = calendarEventId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("personId", getPersonId())
            .append("calendarEventId", getCalendarEventId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnCalEventHasAttendeePK) ) return false;
        PnCalEventHasAttendeePK castOther = (PnCalEventHasAttendeePK) other;
        return new EqualsBuilder()
            .append(this.getPersonId(), castOther.getPersonId())
            .append(this.getCalendarEventId(), castOther.getCalendarEventId())
            .isEquals();
    }

 public int hashCode() {
        return new HashCodeBuilder()
            .append(getPersonId())
            .append(getCalendarEventId())
            .toHashCode();
    }
}


