/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassListFilterPK generated by hbm2java
 */
@Embeddable
public class PnClassListFilterPK  implements java.io.Serializable {

    /** identifier field */
    private Integer classId;

    /** identifier field */
    private Integer listId;

    /** identifier field */
    private Integer fieldId;

    /** identifier field */
    private Integer valueId;

    public PnClassListFilterPK() {
    }

    public PnClassListFilterPK(Integer classId, Integer listId, Integer fieldId, Integer valueId) {
       this.classId = classId;
       this.listId = listId;
       this.fieldId = fieldId;
       this.valueId = valueId;
    }
   


    @Column(name="CLASS_ID", nullable=false, length=20)
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }


    @Column(name="LIST_ID", nullable=false, length=20)
    public Integer getListId() {
        return this.listId;
    }
    
    public void setListId(Integer listId) {
        this.listId = listId;
    }


    @Column(name="FIELD_ID", nullable=false, length=20)
    public Integer getFieldId() {
        return this.fieldId;
    }
    
    public void setFieldId(Integer fieldId) {
        this.fieldId = fieldId;
    }


    @Column(name="VALUE_ID", nullable=false, length=20)
    public Integer getValueId() {
        return this.valueId;
    }
    
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("classId", getClassId())
            .append("listId", getListId())
            .append("fieldId", getFieldId())
            .append("valueId", getValueId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnClassListFilterPK) ) return false;
        PnClassListFilterPK castOther = (PnClassListFilterPK) other;
        return new EqualsBuilder()
            .append(this.getClassId(), castOther.getClassId())
            .append(this.getListId(), castOther.getListId())
            .append(this.getFieldId(), castOther.getFieldId())
            .append(this.getValueId(), castOther.getValueId())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getClassId())
            .append(getListId())
            .append(getFieldId())
            .append(getValueId())
            .toHashCode();
    }
}


