/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClassListField generated by hbm2java
 */
@Entity
@Table(name="PN_CLASS_LIST_FIELD"
)
public class PnClassListField  implements java.io.Serializable {

	/** identifier field */
    private PnClassListFieldPK comp_id;
    
    /** nullable persistent field */
    private Integer fieldWidth;

    /** nullable persistent field */
    private Integer fieldOrder;

    /** persistent field */
    private int wrapMode;

    /** nullable persistent field */
    private Integer isSubfield;

    /** nullable persistent field */
    private Integer isListField;

    /** persistent field */
    private int isSortField;

    /** nullable persistent field */
    private Integer sortOrder;

    /** nullable persistent field */
    private Integer sortAscending;

    /** nullable persistent field */
    private Integer isCalculateTotal;
    
    private PnClassList pnClassList;

    public PnClassListField() {
    }

	
    public PnClassListField(PnClassListFieldPK comp_id, int wrapMode, int isSortField) {
        this.comp_id = comp_id;
        this.wrapMode = wrapMode;
        this.isSortField = isSortField;
    }
    public PnClassListField(PnClassListFieldPK comp_id, Integer fieldWidth, Integer fieldOrder, int wrapMode, Integer isSubfield, Integer isListField, int isSortField, Integer sortOrder, Integer sortAscending, Integer isCalculateTotal, PnClassList pnClassList) {
       this.comp_id = comp_id;
       this.fieldWidth = fieldWidth;
       this.fieldOrder = fieldOrder;
       this.wrapMode = wrapMode;
       this.isSubfield = isSubfield;
       this.isListField = isListField;
       this.isSortField = isSortField;
       this.sortOrder = sortOrder;
       this.sortAscending = sortAscending;
       this.isCalculateTotal = isCalculateTotal;
       this.pnClassList = pnClassList;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="classId", column=@Column(name="CLASS_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="listId", column=@Column(name="LIST_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="fieldId", column=@Column(name="FIELD_ID", nullable=false, length=20) ) } )
    public PnClassListFieldPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnClassListFieldPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="FIELD_WIDTH", length=8)
    public Integer getFieldWidth() {
        return this.fieldWidth;
    }
    
    public void setFieldWidth(Integer fieldWidth) {
        this.fieldWidth = fieldWidth;
    }

    
    @Column(name="FIELD_ORDER", length=8)
    public Integer getFieldOrder() {
        return this.fieldOrder;
    }
    
    public void setFieldOrder(Integer fieldOrder) {
        this.fieldOrder = fieldOrder;
    }

    
    @Column(name="WRAP_MODE", nullable=false, length=1)
    public int getWrapMode() {
        return this.wrapMode;
    }
    
    public void setWrapMode(int wrapMode) {
        this.wrapMode = wrapMode;
    }

    
    @Column(name="IS_SUBFIELD", length=1)
    public Integer getIsSubfield() {
        return this.isSubfield;
    }
    
    public void setIsSubfield(Integer isSubfield) {
        this.isSubfield = isSubfield;
    }

    
    @Column(name="IS_LIST_FIELD", length=1)
    public Integer getIsListField() {
        return this.isListField;
    }
    
    public void setIsListField(Integer isListField) {
        this.isListField = isListField;
    }

    
    @Column(name="IS_SORT_FIELD", nullable=false, length=1)
    public int getIsSortField() {
        return this.isSortField;
    }
    
    public void setIsSortField(int isSortField) {
        this.isSortField = isSortField;
    }

    
    @Column(name="SORT_ORDER", length=2)
    public Integer getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    
    @Column(name="SORT_ASCENDING", length=1)
    public Integer getSortAscending() {
        return this.sortAscending;
    }
    
    public void setSortAscending(Integer sortAscending) {
        this.sortAscending = sortAscending;
    }

    
    @Column(name="IS_CALCULATE_TOTAL", length=1)
    public Integer getIsCalculateTotal() {
        return this.isCalculateTotal;
    }
    
    public void setIsCalculateTotal(Integer isCalculateTotal) {
        this.isCalculateTotal = isCalculateTotal;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnClassList.class)
    @JoinColumns( { 
        @JoinColumn(name="CLASS_ID", referencedColumnName="CLASS_ID", insertable=false, updatable=false), 
        @JoinColumn(name="LIST_ID", referencedColumnName="LIST_ID", insertable=false, updatable=false) } )
    public PnClassList getPnClassList() {
        return this.pnClassList;
    }
    
    public void setPnClassList(PnClassList pnClassList) {
        this.pnClassList = pnClassList;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnClassListField) ) return false;
        PnClassListField castOther = (PnClassListField) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }
}


