/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnClientType generated by hbm2java
 */
@Entity
@Table(name = "PN_CLIENT_TYPE")
public class PnClientType implements java.io.Serializable {

	/** identifier field */
	private Integer clientTypeId;

	/** persistent field */
	private String clientName;

	/** nullable persistent field */
	private String clientDesc;

	private Set pnElementProperties = new HashSet(0);

	private Set pnClassFieldProperties = new HashSet(0);

	public PnClientType() {
	}

	public PnClientType(Integer clientTypeId, String clientName) {
		this.clientTypeId = clientTypeId;
		this.clientName = clientName;
	}

	public PnClientType(Integer clientTypeId, String clientName, String clientDesc, Set pnElementProperties,
			Set pnClassFieldProperties) {
		this.clientTypeId = clientTypeId;
		this.clientName = clientName;
		this.clientDesc = clientDesc;
		this.pnElementProperties = pnElementProperties;
		this.pnClassFieldProperties = pnClassFieldProperties;
	}

	/** minimal constructor */
	public PnClientType(Integer clientTypeId, String clientName, Set pnElementProperties, Set pnClassFieldProperties) {
		this.clientTypeId = clientTypeId;
		this.clientName = clientName;
		this.pnElementProperties = pnElementProperties;
		this.pnClassFieldProperties = pnClassFieldProperties;
	}

	@Id
	@Column(name = "CLIENT_TYPE_ID", nullable = false)
	public Integer getClientTypeId() {
		return this.clientTypeId;
	}

	public void setClientTypeId(Integer clientTypeId) {
		this.clientTypeId = clientTypeId;
	}

	@Column(name = "CLIENT_NAME", nullable = false, length = 80)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "CLIENT_DESC", length = 500)
	public String getClientDesc() {
		return this.clientDesc;
	}

	public void setClientDesc(String clientDesc) {
		this.clientDesc = clientDesc;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnClientType", targetEntity = PnElementProperty.class)
	@Transient
	public Set getPnElementProperties() {
		return this.pnElementProperties;
	}

	public void setPnElementProperties(Set pnElementProperties) {
		this.pnElementProperties = pnElementProperties;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnClientType", targetEntity = PnClassFieldProperty.class)
	@Transient
	public Set getPnClassFieldProperties() {
		return this.pnClassFieldProperties;
	}

	public void setPnClassFieldProperties(Set pnClassFieldProperties) {
		this.pnClassFieldProperties = pnClassFieldProperties;
	}

	public String toString() {
		return new ToStringBuilder(this).append("clientTypeId", getClientTypeId()).toString();
	}

}
