/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnCountryLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_COUNTRY_LOOKUP")
public class PnCountryLookup implements java.io.Serializable {

	/** identifier field */
	private String countryCode;

	/** persistent field */
	private String countryName;

	/** persistent field */
	private Set pnAddresses = new HashSet(0);

	/** persistent field */
	private Set pnSpaceHasWeathers = new HashSet(0);

	/** persistent field */
	private Set pnStateLookups = new HashSet(0);

	public PnCountryLookup() {
	}

	public PnCountryLookup(String countryCode, String countryName) {
		this.countryCode = countryCode;
		this.countryName = countryName;
	}

	public PnCountryLookup(String countryCode, String countryName, Set pnAddresses, Set pnSpaceHasWeathers,
			Set pnStateLookups) {
		this.countryCode = countryCode;
		this.countryName = countryName;
		this.pnAddresses = pnAddresses;
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
		this.pnStateLookups = pnStateLookups;
	}

	public PnCountryLookup(String countryCode) {
		this.countryCode = countryCode;
	}

	@Id
	@Column(name = "COUNTRY_CODE", nullable = false)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "COUNTRY_NAME", nullable = false, length = 500)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	//@OneToMany(fetch = FetchType.LAZY, targetEntity = PnAddress.class)
	@Transient
	public Set getPnAddresses() {
		return this.pnAddresses;
	}

	public void setPnAddresses(Set pnAddresses) {
		this.pnAddresses = pnAddresses;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnCountryLookup", targetEntity = PnSpaceHasWeather.class)
	@Transient
	public Set getPnSpaceHasWeathers() {
		return this.pnSpaceHasWeathers;
	}

	public void setPnSpaceHasWeathers(Set pnSpaceHasWeathers) {
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnCountryLookup", targetEntity = PnStateLookup.class)
	@Transient
	public Set getPnStateLookups() {
		return this.pnStateLookups;
	}

	public void setPnStateLookups(Set pnStateLookups) {
		this.pnStateLookups = pnStateLookups;
	}

	public String toString() {
		return new ToStringBuilder(this).append("countryCode", getCountryCode()).toString();
	}

}
