/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnConfigurationSpace generated by hbm2java
 */
@Entity
@Table(name = "PN_CONFIGURATION_SPACE")
public class PnConfigurationSpace implements java.io.Serializable {

	/** identifier field */
	private Integer configurationId;

	/** persistent field */
	private String configurationName;

	/** nullable persistent field */
	private String configurationDesc;

	/** persistent field */
	private Integer createdById;

	/** persistent field */
	private Date createdDatetime;

	/** nullable persistent field */
	private Integer modifiedById;

	/** nullable persistent field */
	private Date modifiedDatetime;

	/** persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	/** persistent field */
	private Integer brandId;

	private Set pnPortfolioHasConfigurations = new HashSet(0);

	public PnConfigurationSpace() {
	}

	public PnConfigurationSpace(Integer configurationId, String configurationName, Integer createdById,
			Date createdDatetime, Date crc, String recordStatus, Integer brandId) {
		this.configurationId = configurationId;
		this.configurationName = configurationName;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.brandId = brandId;
	}

	public PnConfigurationSpace(Integer configurationId, String configurationName, String configurationDesc,
			Integer createdById, Date createdDatetime, Integer modifiedById, Date modifiedDatetime, Date crc,
			String recordStatus, Integer brandId, Set pnPortfolioHasConfigurations) {
		this.configurationId = configurationId;
		this.configurationName = configurationName;
		this.configurationDesc = configurationDesc;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.brandId = brandId;
		this.pnPortfolioHasConfigurations = pnPortfolioHasConfigurations;
	}

	/** minimal constructor */
	public PnConfigurationSpace(Integer configurationId, String configurationName, Integer createdById,
			Date createdDatetime, Date crc, String recordStatus, Integer brandId, Set pnPortfolioHasConfigurations) {
		this.configurationId = configurationId;
		this.configurationName = configurationName;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.brandId = brandId;
		this.pnPortfolioHasConfigurations = pnPortfolioHasConfigurations;
	}

	@Id
	@Column(name = "CONFIGURATION_ID", nullable = false)
	public Integer getConfigurationId() {
		return this.configurationId;
	}

	public void setConfigurationId(Integer configurationId) {
		this.configurationId = configurationId;
	}

	@Column(name = "CONFIGURATION_NAME", nullable = false, length = 80)
	public String getConfigurationName() {
		return this.configurationName;
	}

	public void setConfigurationName(String configurationName) {
		this.configurationName = configurationName;
	}

	@Column(name = "CONFIGURATION_DESC", length = 1000)
	public String getConfigurationDesc() {
		return this.configurationDesc;
	}

	public void setConfigurationDesc(String configurationDesc) {
		this.configurationDesc = configurationDesc;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "BRAND_ID", nullable = false, length = 20)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnConfigurationSpace", targetEntity = PnPortfolioHasConfiguration.class)
	@Transient
	public Set getPnPortfolioHasConfigurations() {
		return this.pnPortfolioHasConfigurations;
	}

	public void setPnPortfolioHasConfigurations(Set pnPortfolioHasConfigurations) {
		this.pnPortfolioHasConfigurations = pnPortfolioHasConfigurations;
	}

	public String toString() {
		return new ToStringBuilder(this).append("configurationId", getConfigurationId()).toString();
	}

}
