/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnCreditCardTransaction generated by hbm2java
 */
@Entity
@Table(name = "PN_CREDIT_CARD_TRANSACTION")
public class PnCreditCardTransaction implements java.io.Serializable {

	/** identifier field */
	private Integer transactionId;

	/** nullable persistent field */
	private String vendorTransactionId;

	/** persistent field */
	private Date dateSubmitted;

	/** persistent field */
	private String transactionType;

	/** persistent field */
	private Integer transactionAmount;

	/** persistent field */
	private String transactionAmountCurrency;

	/** nullable persistent field */
	private String authorizationCode;

	/** nullable persistent field */
	private Integer isDuplicate;

	private Set pnCcTransactionPayments = new HashSet(0);

	public PnCreditCardTransaction() {
	}

	public PnCreditCardTransaction(Integer transactionId, Date dateSubmitted, String transactionType,
			Integer transactionAmount, String transactionAmountCurrency) {
		this.transactionId = transactionId;
		this.dateSubmitted = dateSubmitted;
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.transactionAmountCurrency = transactionAmountCurrency;
	}

	public PnCreditCardTransaction(Integer transactionId, String vendorTransactionId, Date dateSubmitted,
			String transactionType, Integer transactionAmount, String transactionAmountCurrency,
			String authorizationCode, Integer isDuplicate, Set pnCcTransactionPayments) {
		this.transactionId = transactionId;
		this.vendorTransactionId = vendorTransactionId;
		this.dateSubmitted = dateSubmitted;
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.transactionAmountCurrency = transactionAmountCurrency;
		this.authorizationCode = authorizationCode;
		this.isDuplicate = isDuplicate;
		this.pnCcTransactionPayments = pnCcTransactionPayments;
	}

	/** minimal constructor */
	public PnCreditCardTransaction(Integer transactionId, Date dateSubmitted, String transactionType,
			Integer transactionAmount, String transactionAmountCurrency, Set pnCcTransactionPayments) {
		this.transactionId = transactionId;
		this.dateSubmitted = dateSubmitted;
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.transactionAmountCurrency = transactionAmountCurrency;
		this.pnCcTransactionPayments = pnCcTransactionPayments;
	}

	@Id
	@Column(name = "TRANSACTION_ID", nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "VENDOR_TRANSACTION_ID", length = 20)
	public String getVendorTransactionId() {
		return this.vendorTransactionId;
	}

	public void setVendorTransactionId(String vendorTransactionId) {
		this.vendorTransactionId = vendorTransactionId;
	}

	@Column(name = "DATE_SUBMITTED", nullable = false, length = 7)
	public Date getDateSubmitted() {
		return this.dateSubmitted;
	}

	public void setDateSubmitted(Date dateSubmitted) {
		this.dateSubmitted = dateSubmitted;
	}

	@Column(name = "TRANSACTION_TYPE", nullable = false, length = 5)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "TRANSACTION_AMOUNT", nullable = false, length = 22)
	public Integer getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(Integer transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	@Column(name = "TRANSACTION_AMOUNT_CURRENCY", nullable = false, length = 3)
	public String getTransactionAmountCurrency() {
		return this.transactionAmountCurrency;
	}

	public void setTransactionAmountCurrency(String transactionAmountCurrency) {
		this.transactionAmountCurrency = transactionAmountCurrency;
	}

	@Column(name = "AUTHORIZATION_CODE", length = 20)
	public String getAuthorizationCode() {
		return this.authorizationCode;
	}

	public void setAuthorizationCode(String authorizationCode) {
		this.authorizationCode = authorizationCode;
	}

	@Column(name = "IS_DUPLICATE", length = 1)
	public Integer getIsDuplicate() {
		return this.isDuplicate;
	}

	public void setIsDuplicate(Integer isDuplicate) {
		this.isDuplicate = isDuplicate;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnCreditCardTransaction", targetEntity = PnCcTransactionPayment.class)
	@Transient
	public Set getPnCcTransactionPayments() {
		return this.pnCcTransactionPayments;
	}

	public void setPnCcTransactionPayments(Set pnCcTransactionPayments) {
		this.pnCcTransactionPayments = pnCcTransactionPayments;
	}

	public String toString() {
		return new ToStringBuilder(this).append("transactionId", getTransactionId()).toString();
	}

}
