/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDateFormat generated by hbm2java
 */
@Entity
@Table(name="PN_DATE_FORMAT"
)
public class PnDateFormat  implements java.io.Serializable {

    /** identifier field */
    private Integer dateFormatId;

    /** persistent field */
    private String formatString;

    /** persistent field */
    private String display;

    /** nullable persistent field */
    private String example;

    public PnDateFormat() {
    }

	
    public PnDateFormat(Integer dateFormatId, String formatString, String display) {
        this.dateFormatId = dateFormatId;
        this.formatString = formatString;
        this.display = display;
    }
    public PnDateFormat(Integer dateFormatId, String formatString, String display, String example) {
       this.dateFormatId = dateFormatId;
       this.formatString = formatString;
       this.display = display;
       this.example = example;
    }
   
     @Id 

    
    @Column(name="DATE_FORMAT_ID", nullable=false)
    public Integer getDateFormatId() {
        return this.dateFormatId;
    }
    
    public void setDateFormatId(Integer dateFormatId) {
        this.dateFormatId = dateFormatId;
    }

    
    @Column(name="FORMAT_STRING", nullable=false, length=80)
    public String getFormatString() {
        return this.formatString;
    }
    
    public void setFormatString(String formatString) {
        this.formatString = formatString;
    }

    
    @Column(name="DISPLAY", nullable=false, length=80)
    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }

    
    @Column(name="EXAMPLE", length=80)
    public String getExample() {
        return this.example;
    }
    
    public void setExample(String example) {
        this.example = example;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("dateFormatId", getDateFormatId())
            .toString();
    }

}


