/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDefaultObjectPermission generated by hbm2java
 */
@Entity
@Table(name="PN_DEFAULT_OBJECT_PERMISSION"
)
public class PnDefaultObjectPermission  implements java.io.Serializable {


    private PnDefaultObjectPermissionPK comp_id;
     
    private long actions;
     
    private PnGroup pnGroup;
     
    private PnObjectType pnObjectType;

    public PnDefaultObjectPermission() {
    }

	
    public PnDefaultObjectPermission(PnDefaultObjectPermissionPK comp_id, long actions) {
        this.comp_id = comp_id;
        this.actions = actions;
    }
    public PnDefaultObjectPermission(PnDefaultObjectPermissionPK comp_id, long actions, PnGroup pnGroup, PnObjectType pnObjectType) {
       this.comp_id = comp_id;
       this.actions = actions;
       this.pnGroup = pnGroup;
       this.pnObjectType = pnObjectType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="spaceId", column=@Column(name="SPACE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="objectType", column=@Column(name="OBJECT_TYPE", nullable=false, length=80) ), 
        @AttributeOverride(name="groupId", column=@Column(name="GROUP_ID", nullable=false, length=20) ) } )
    public PnDefaultObjectPermissionPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnDefaultObjectPermissionPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="ACTIONS", nullable=false, length=10)
    public long getActions() {
        return this.actions;
    }
    
    public void setActions(long actions) {
        this.actions = actions;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnGroup.class)
    @JoinColumn(name="GROUP_ID", insertable=false, updatable=false)
    public PnGroup getPnGroup() {
        return this.pnGroup;
    }
    
    public void setPnGroup(PnGroup pnGroup) {
        this.pnGroup = pnGroup;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnObjectType.class)
    @JoinColumn(name="OBJECT_TYPE", insertable=false, updatable=false)
    public PnObjectType getPnObjectType() {
        return this.pnObjectType;
    }
    
    public void setPnObjectType(PnObjectType pnObjectType) {
        this.pnObjectType = pnObjectType;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDefaultObjectPermission) ) return false;
        PnDefaultObjectPermission castOther = (PnDefaultObjectPermission) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }
}


