/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocVersion generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_VERSION")
public class PnDocVersion implements java.io.Serializable {

	/** identifier field */
	private Integer docVersionId;

	/** nullable persistent field */
	private String docVersionName;

	/** nullable persistent field */
	private String sourceFileName;

	/** nullable persistent field */
	private String docDescription;

	/** nullable persistent field */
	private Date dateModified;

	/** persistent field */
	private int isCheckedOut;

	/** nullable persistent field */
	private Date dateCheckedOut;

	/** nullable persistent field */
	private String docComment;

	/** persistent field */
	private Integer docVersionNum;

	/** nullable persistent field */
	private String docVersionLabel;

	/** nullable persistent field */
	private Date checkoutDue;

	/** nullable persistent field */
	private String shortFileName;

	/** persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	/** nullable persistent field */
	private PnObject pnObject;

	/** persistent field */
	private PnDocument pnDocument;

	/** persistent field */
	private PnPerson pnPersonByDocAuthorId;

	/** persistent field */
	private PnPerson pnPersonByModifiedById;

	/** persistent field */
	private PnPerson pnPersonByCheckedOutById;

	/** persistent field */
	private Set pnDocVersionHasContents = new HashSet(0);

	/** persistent field */
	private Set pnDocConfigurationHasDocs = new HashSet(0);

	public PnDocVersion() {
	}

	public PnDocVersion(Integer docVersionId, int isCheckedOut, Integer docVersionNum, Date crc, String recordStatus) {
		this.docVersionId = docVersionId;
		this.isCheckedOut = isCheckedOut;
		this.docVersionNum = docVersionNum;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnDocVersion(Integer docVersionId, String docVersionName, String sourceFileName, String docDescription,
			Date dateModified, int isCheckedOut, Date dateCheckedOut, String docComment, Integer docVersionNum,
			String docVersionLabel, Date checkoutDue, String shortFileName, Date crc, String recordStatus,
			PnObject pnObject, PnDocument pnDocument, PnPerson pnPersonByDocAuthorId, PnPerson pnPersonByModifiedById,
			PnPerson pnPersonByCheckedOutById, Set pnDocVersionHasContents, Set pnDocConfigurationHasDocs) {
		this.docVersionId = docVersionId;
		this.docVersionName = docVersionName;
		this.sourceFileName = sourceFileName;
		this.docDescription = docDescription;
		this.dateModified = dateModified;
		this.isCheckedOut = isCheckedOut;
		this.dateCheckedOut = dateCheckedOut;
		this.docComment = docComment;
		this.docVersionNum = docVersionNum;
		this.docVersionLabel = docVersionLabel;
		this.checkoutDue = checkoutDue;
		this.shortFileName = shortFileName;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnObject = pnObject;
		this.pnDocument = pnDocument;
		this.pnPersonByDocAuthorId = pnPersonByDocAuthorId;
		this.pnPersonByModifiedById = pnPersonByModifiedById;
		this.pnPersonByCheckedOutById = pnPersonByCheckedOutById;
		this.pnDocVersionHasContents = pnDocVersionHasContents;
		this.pnDocConfigurationHasDocs = pnDocConfigurationHasDocs;
	}

	/** minimal constructor */
	public PnDocVersion(Integer docVersionId, int isCheckedOut, Integer docVersionNum, Date crc, String recordStatus,
			net.project.hibernate.model.PnDocument pnDocument,
			net.project.hibernate.model.PnPerson pnPersonByDocAuthorId,
			net.project.hibernate.model.PnPerson pnPersonByModifiedById,
			net.project.hibernate.model.PnPerson pnPersonByCheckedOutById, Set pnDocVersionHasContents,
			Set pnDocConfigurationHasDocs) {
		this.docVersionId = docVersionId;
		this.isCheckedOut = isCheckedOut;
		this.docVersionNum = docVersionNum;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnDocument = pnDocument;
		this.pnPersonByDocAuthorId = pnPersonByDocAuthorId;
		this.pnPersonByModifiedById = pnPersonByModifiedById;
		this.pnPersonByCheckedOutById = pnPersonByCheckedOutById;
		this.pnDocVersionHasContents = pnDocVersionHasContents;
		this.pnDocConfigurationHasDocs = pnDocConfigurationHasDocs;
	}

	@Id
	@Column(name = "DOC_VERSION_ID", nullable = false)
	public Integer getDocVersionId() {
		return this.docVersionId;
	}

	public void setDocVersionId(Integer docVersionId) {
		this.docVersionId = docVersionId;
	}

	@Column(name = "DOC_VERSION_NAME", length = 256)
	public String getDocVersionName() {
		return this.docVersionName;
	}

	public void setDocVersionName(String docVersionName) {
		this.docVersionName = docVersionName;
	}

	@Column(name = "SOURCE_FILE_NAME", length = 240)
	public String getSourceFileName() {
		return this.sourceFileName;
	}

	public void setSourceFileName(String sourceFileName) {
		this.sourceFileName = sourceFileName;
	}

	@Column(name = "DOC_DESCRIPTION", length = 4000)
	public String getDocDescription() {
		return this.docDescription;
	}

	public void setDocDescription(String docDescription) {
		this.docDescription = docDescription;
	}

	@Column(name = "DATE_MODIFIED", length = 7)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "IS_CHECKED_OUT", nullable = false, length = 1)
	public int getIsCheckedOut() {
		return this.isCheckedOut;
	}

	public void setIsCheckedOut(int isCheckedOut) {
		this.isCheckedOut = isCheckedOut;
	}

	@Column(name = "DATE_CHECKED_OUT", length = 7)
	public Date getDateCheckedOut() {
		return this.dateCheckedOut;
	}

	public void setDateCheckedOut(Date dateCheckedOut) {
		this.dateCheckedOut = dateCheckedOut;
	}

	@Column(name = "DOC_COMMENT", length = 500)
	public String getDocComment() {
		return this.docComment;
	}

	public void setDocComment(String docComment) {
		this.docComment = docComment;
	}

	@Column(name = "DOC_VERSION_NUM", nullable = false, length = 20)
	public Integer getDocVersionNum() {
		return this.docVersionNum;
	}

	public void setDocVersionNum(Integer docVersionNum) {
		this.docVersionNum = docVersionNum;
	}

	@Column(name = "DOC_VERSION_LABEL", length = 240)
	public String getDocVersionLabel() {
		return this.docVersionLabel;
	}

	public void setDocVersionLabel(String docVersionLabel) {
		this.docVersionLabel = docVersionLabel;
	}

	@Column(name = "CHECKOUT_DUE", length = 7)
	public Date getCheckoutDue() {
		return this.checkoutDue;
	}

	public void setCheckoutDue(Date checkoutDue) {
		this.checkoutDue = checkoutDue;
	}

	@Column(name = "SHORT_FILE_NAME", length = 240)
	public String getShortFileName() {
		return this.shortFileName;
	}

	public void setShortFileName(String shortFileName) {
		this.shortFileName = shortFileName;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name = "DOC_VERSION_ID")
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocument.class)
	@JoinColumn(name = "DOC_ID")
	public PnDocument getPnDocument() {
		return this.pnDocument;
	}

	public void setPnDocument(PnDocument pnDocument) {
		this.pnDocument = pnDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "DOC_AUTHOR_ID")
	public PnPerson getPnPersonByDocAuthorId() {
		return this.pnPersonByDocAuthorId;
	}

	public void setPnPersonByDocAuthorId(PnPerson pnPersonByDocAuthorId) {
		this.pnPersonByDocAuthorId = pnPersonByDocAuthorId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "MODIFIED_BY_ID")
	public PnPerson getPnPersonByModifiedById() {
		return this.pnPersonByModifiedById;
	}

	public void setPnPersonByModifiedById(PnPerson pnPersonByModifiedById) {
		this.pnPersonByModifiedById = pnPersonByModifiedById;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "CHECKED_OUT_BY_ID")
	public PnPerson getPnPersonByCheckedOutById() {
		return this.pnPersonByCheckedOutById;
	}

	public void setPnPersonByCheckedOutById(PnPerson pnPersonByCheckedOutById) {
		this.pnPersonByCheckedOutById = pnPersonByCheckedOutById;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocVersion", targetEntity = PnDocVersionHasContent.class)
	@Transient
	public Set getPnDocVersionHasContents() {
		return this.pnDocVersionHasContents;
	}

	public void setPnDocVersionHasContents(Set pnDocVersionHasContents) {
		this.pnDocVersionHasContents = pnDocVersionHasContents;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocVersion", targetEntity = PnDocConfigurationHasDoc.class)
	@Transient
	public Set getPnDocConfigurationHasDocs() {
		return this.pnDocConfigurationHasDocs;
	}

	public void setPnDocConfigurationHasDocs(Set pnDocConfigurationHasDocs) {
		this.pnDocConfigurationHasDocs = pnDocConfigurationHasDocs;
	}

	public String toString() {
		return new ToStringBuilder(this).append("docVersionId", getDocVersionId()).toString();
	}

}
