/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocSpaceHasContainerPK generated by hbm2java
 */
@Embeddable
public class PnDocSpaceHasContainerPK  implements java.io.Serializable {


     private Integer docSpaceId;
     private Integer docContainerId;

    public PnDocSpaceHasContainerPK() {
    }

    public PnDocSpaceHasContainerPK(Integer docSpaceId, Integer docContainerId) {
       this.docSpaceId = docSpaceId;
       this.docContainerId = docContainerId;
    }
   


    @Column(name="DOC_SPACE_ID", nullable=false, length=20)
    public Integer getDocSpaceId() {
        return this.docSpaceId;
    }
    
    public void setDocSpaceId(Integer docSpaceId) {
        this.docSpaceId = docSpaceId;
    }


    @Column(name="DOC_CONTAINER_ID", nullable=false, length=20)
    public Integer getDocContainerId() {
        return this.docContainerId;
    }
    
    public void setDocContainerId(Integer docContainerId) {
        this.docContainerId = docContainerId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docSpaceId", getDocSpaceId())
            .append("docContainerId", getDocContainerId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocSpaceHasContainerPK) ) return false;
        PnDocSpaceHasContainerPK castOther = (PnDocSpaceHasContainerPK) other;
        return new EqualsBuilder()
            .append(this.getDocSpaceId(), castOther.getDocSpaceId())
            .append(this.getDocContainerId(), castOther.getDocContainerId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getDocSpaceId())
            .append(getDocContainerId())
            .toHashCode();
    }
}


