/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocRepositoryBase generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_REPOSITORY_BASE")
public class PnDocRepositoryBase implements java.io.Serializable {

	/** identifier field */
	private Integer repositoryId;

	/** persistent field */
	private String repositoryPath;

	/** persistent field */
	private int isActive;

	/** persistent field */
	private Set pnDocContentElements = new HashSet(0);

	public PnDocRepositoryBase() {
	}

	public PnDocRepositoryBase(Integer repositoryId, String repositoryPath, int isActive) {
		this.repositoryId = repositoryId;
		this.repositoryPath = repositoryPath;
		this.isActive = isActive;
	}

	public PnDocRepositoryBase(Integer repositoryId, String repositoryPath, int isActive, Set pnDocContentElements) {
		this.repositoryId = repositoryId;
		this.repositoryPath = repositoryPath;
		this.isActive = isActive;
		this.pnDocContentElements = pnDocContentElements;
	}

	@Id
	@Column(name = "REPOSITORY_ID", nullable = false)
	public Integer getRepositoryId() {
		return this.repositoryId;
	}

	public void setRepositoryId(Integer repositoryId) {
		this.repositoryId = repositoryId;
	}

	@Column(name = "REPOSITORY_PATH", nullable = false, length = 240)
	public String getRepositoryPath() {
		return this.repositoryPath;
	}

	public void setRepositoryPath(String repositoryPath) {
		this.repositoryPath = repositoryPath;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 1)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocRepositoryBase", targetEntity = PnDocContentElement.class)
	@Transient
	public Set getPnDocContentElements() {
		return this.pnDocContentElements;
	}

	public void setPnDocContentElements(Set pnDocContentElements) {
		this.pnDocContentElements = pnDocContentElements;
	}

	public String toString() {
		return new ToStringBuilder(this).append("repositoryId", getRepositoryId()).toString();
	}

}
