/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocCheckoutLocation generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_CHECKOUT_LOCATION")
public class PnDocCheckoutLocation implements java.io.Serializable {

	/** identifier field */
	private PnDocCheckoutLocationPK comp_id;

	/** nullable persistent field */
	private String absoluteFilename;

	/** nullable persistent field */
	private PnDocument pnDocument;

	private PnPerson pnPerson;

	public PnDocCheckoutLocation() {
	}

	public PnDocCheckoutLocation(PnDocCheckoutLocationPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnDocCheckoutLocation(PnDocCheckoutLocationPK comp_id, String absoluteFilename, PnDocument pnDocument,
			PnPerson pnPerson) {
		this.comp_id = comp_id;
		this.absoluteFilename = absoluteFilename;
		this.pnDocument = pnDocument;
		this.pnPerson = pnPerson;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "docId", column = @Column(name = "DOC_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "clientMachineId", column = @Column(name = "CLIENT_MACHINE_ID", nullable = false, length = 20)) })
	public PnDocCheckoutLocationPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnDocCheckoutLocationPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "ABSOLUTE_FILENAME", length = 240)
	public String getAbsoluteFilename() {
		return this.absoluteFilename;
	}

	public void setAbsoluteFilename(String absoluteFilename) {
		this.absoluteFilename = absoluteFilename;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocument.class)
	@JoinColumn(name = "DOC_ID", insertable = false, updatable = false)
	public PnDocument getPnDocument() {
		return this.pnDocument;
	}

	public void setPnDocument(PnDocument pnDocument) {
		this.pnDocument = pnDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID", insertable = false, updatable = false)
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnDocCheckoutLocation))
			return false;
		PnDocCheckoutLocation castOther = (PnDocCheckoutLocation) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}
}
