/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnDocContentElement generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_CONTENT_ELEMENT")
public class PnDocContentElement implements java.io.Serializable {

	private Integer docContentId;

	private Integer docFormatId;

	private Integer displaySequence;

	private Integer fileSize;

	private String fileHandle;

	private String recordStatus;

	private PnDocRepositoryBase pnDocRepositoryBase;

	private Set pnDocContentRenditions = new HashSet(0);

	private Set pnDocVersionHasContents = new HashSet(0);

	public PnDocContentElement() {
	}

	public PnDocContentElement(Integer docContentId, String recordStatus) {
		this.docContentId = docContentId;
		this.recordStatus = recordStatus;
	}

	public PnDocContentElement(Integer docContentId, Integer docFormatId, Integer displaySequence, Integer fileSize,
			String fileHandle, String recordStatus, PnDocRepositoryBase pnDocRepositoryBase,
			Set pnDocContentRenditions, Set pnDocVersionHasContents) {
		this.docContentId = docContentId;
		this.docFormatId = docFormatId;
		this.displaySequence = displaySequence;
		this.fileSize = fileSize;
		this.fileHandle = fileHandle;
		this.recordStatus = recordStatus;
		this.pnDocRepositoryBase = pnDocRepositoryBase;
		this.pnDocContentRenditions = pnDocContentRenditions;
		this.pnDocVersionHasContents = pnDocVersionHasContents;
	}

	@Id
	@Column(name = "DOC_CONTENT_ID", nullable = false)
	public Integer getDocContentId() {
		return this.docContentId;
	}

	public void setDocContentId(Integer docContentId) {
		this.docContentId = docContentId;
	}

	@Column(name = "DOC_FORMAT_ID", length = 20)
	public Integer getDocFormatId() {
		return this.docFormatId;
	}

	public void setDocFormatId(Integer docFormatId) {
		this.docFormatId = docFormatId;
	}

	@Column(name = "DISPLAY_SEQUENCE", length = 8)
	public Integer getDisplaySequence() {
		return this.displaySequence;
	}

	public void setDisplaySequence(Integer displaySequence) {
		this.displaySequence = displaySequence;
	}

	@Column(name = "FILE_SIZE", length = 20)
	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "FILE_HANDLE", length = 240)
	public String getFileHandle() {
		return this.fileHandle;
	}

	public void setFileHandle(String fileHandle) {
		this.fileHandle = fileHandle;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocRepositoryBase.class)
	@JoinColumn(name = "REPOSITORY_ID")
	public PnDocRepositoryBase getPnDocRepositoryBase() {
		return this.pnDocRepositoryBase;
	}

	public void setPnDocRepositoryBase(PnDocRepositoryBase pnDocRepositoryBase) {
		this.pnDocRepositoryBase = pnDocRepositoryBase;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocContentElement", targetEntity = PnDocContentRendition.class)
	@Transient
	public Set getPnDocContentRenditions() {
		return this.pnDocContentRenditions;
	}

	public void setPnDocContentRenditions(Set pnDocContentRenditions) {
		this.pnDocContentRenditions = pnDocContentRenditions;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocContentElement", targetEntity = PnDocVersionHasContent.class)
	@Transient
	public Set getPnDocVersionHasContents() {
		return this.pnDocVersionHasContents;
	}

	public void setPnDocVersionHasContents(Set pnDocVersionHasContents) {
		this.pnDocVersionHasContents = pnDocVersionHasContents;
	}

}
