/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocDeletedBySpaceView generated by hbm2java
 */
@Entity
@Table(name="PN_DOC_DELETED_BY_SPACE_VIEW"
)
public class PnDocDeletedBySpaceView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal docId;

    /** identifier field */
    private String docName;

    /** identifier field */
    private Date crc;

    /** identifier field */
    private String objectType;

    /** identifier field */
    private BigDecimal docStatusId;

    /** identifier field */
    private String docStatus;

    /** identifier field */
    private String docDescription;

    /** identifier field */
    private BigDecimal currentVersionId;

    /** identifier field */
    private String recordStatus;

    /** identifier field */
    private BigDecimal docSpaceId;

    /** identifier field */
    private String docSpaceName;

    /** identifier field */
    private BigDecimal docContainerId;

    /** identifier field */
    private String containerName;
	 /** identifier field */
     private int isHidden;

    /** identifier field */
    private BigDecimal docAuthorId;

    /** identifier field */
    private String docAuthor;

    /** identifier field */
    private BigDecimal docVersionId;

    /** identifier field */
    private BigDecimal docVersionNum;

    /** identifier field */
    private String docVersionLabel;

    /** identifier field */
    private String docVersionName;

    /** identifier field */
    private String sourceFileName;

    /** identifier field */
    private String shortFileName;

    /** identifier field */
    private String versionDescription;

    /** identifier field */
    private Date dateModified;

    /** identifier field */
    private BigDecimal modifiedById;

    /** identifier field */
    private String modifiedBy;
	/** identifier field */
     private int isCheckedOut;
    /** identifier field */
    private BigDecimal checkedOutById;

    /** identifier field */
    private String checkedOutBy;

    /** identifier field */
    private Date dateCheckedOut;

    /** identifier field */
    private Date checkoutDue;

    /** identifier field */
    private String docComment;

    /** identifier field */
    private BigDecimal docContentId;

    /** identifier field */
    private BigDecimal docFormatId;

    /** identifier field */
    private BigDecimal fileSize;

    /** identifier field */
    private String fileHandle;
	 /** identifier field */
     private int repositoryId;
    /** identifier field */
    private String repositoryPath;

    /** identifier field */
    private String formatName;

    /** identifier field */
    private String mimeType;

    /** identifier field */
    private String appIconUrl;

    /** identifier field */
    private BigDecimal hasLinks;

    /** identifier field */
    private BigDecimal hasWorkflows;

    /** identifier field */
    private BigDecimal hasDiscussions;

    /** identifier field */
    private Date dateCreated;

    public PnDocDeletedBySpaceView() {
    }

    public PnDocDeletedBySpaceView(BigDecimal docId, String docName, Date crc, String objectType, BigDecimal docStatusId, String docStatus, String docDescription, BigDecimal currentVersionId, String recordStatus, BigDecimal docSpaceId, String docSpaceName, BigDecimal docContainerId, String containerName, int isHidden, BigDecimal docAuthorId, String docAuthor, BigDecimal docVersionId, BigDecimal docVersionNum, String docVersionLabel, String docVersionName, String sourceFileName, String shortFileName, String versionDescription, Date dateModified, BigDecimal modifiedById, String modifiedBy, int isCheckedOut, BigDecimal checkedOutById, String checkedOutBy, Date dateCheckedOut, Date checkoutDue, String docComment, BigDecimal docContentId, BigDecimal docFormatId, BigDecimal fileSize, String fileHandle, int repositoryId, String repositoryPath, String formatName, String mimeType, String appIconUrl, BigDecimal hasLinks, BigDecimal hasWorkflows, BigDecimal hasDiscussions, Date dateCreated) {
       this.docId = docId;
       this.docName = docName;
       this.crc = crc;
       this.objectType = objectType;
       this.docStatusId = docStatusId;
       this.docStatus = docStatus;
       this.docDescription = docDescription;
       this.currentVersionId = currentVersionId;
       this.recordStatus = recordStatus;
       this.docSpaceId = docSpaceId;
       this.docSpaceName = docSpaceName;
       this.docContainerId = docContainerId;
       this.containerName = containerName;
       this.isHidden = isHidden;
       this.docAuthorId = docAuthorId;
       this.docAuthor = docAuthor;
       this.docVersionId = docVersionId;
       this.docVersionNum = docVersionNum;
       this.docVersionLabel = docVersionLabel;
       this.docVersionName = docVersionName;
       this.sourceFileName = sourceFileName;
       this.shortFileName = shortFileName;
       this.versionDescription = versionDescription;
       this.dateModified = dateModified;
       this.modifiedById = modifiedById;
       this.modifiedBy = modifiedBy;
       this.isCheckedOut = isCheckedOut;
       this.checkedOutById = checkedOutById;
       this.checkedOutBy = checkedOutBy;
       this.dateCheckedOut = dateCheckedOut;
       this.checkoutDue = checkoutDue;
       this.docComment = docComment;
       this.docContentId = docContentId;
       this.docFormatId = docFormatId;
       this.fileSize = fileSize;
       this.fileHandle = fileHandle;
       this.repositoryId = repositoryId;
       this.repositoryPath = repositoryPath;
       this.formatName = formatName;
       this.mimeType = mimeType;
       this.appIconUrl = appIconUrl;
       this.hasLinks = hasLinks;
       this.hasWorkflows = hasWorkflows;
       this.hasDiscussions = hasDiscussions;
       this.dateCreated = dateCreated;
    }
   

    
    @Column(name="DOC_ID", nullable=false, length=20)
    public BigDecimal getDocId() {
        return this.docId;
    }
    
    public void setDocId(BigDecimal docId) {
        this.docId = docId;
    }

    
    @Column(name="DOC_NAME", nullable=false, length=256)
    public String getDocName() {
        return this.docName;
    }
    
    public void setDocName(String docName) {
        this.docName = docName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="OBJECT_TYPE", nullable=false, length=8)
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    
    @Column(name="DOC_STATUS_ID", nullable=false, length=20)
    public BigDecimal getDocStatusId() {
        return this.docStatusId;
    }
    
    public void setDocStatusId(BigDecimal docStatusId) {
        this.docStatusId = docStatusId;
    }

    
    @Column(name="DOC_STATUS", nullable=false, length=80)
    public String getDocStatus() {
        return this.docStatus;
    }
    
    public void setDocStatus(String docStatus) {
        this.docStatus = docStatus;
    }

    
    @Column(name="DOC_DESCRIPTION", nullable=false, length=4000)
    public String getDocDescription() {
        return this.docDescription;
    }
    
    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription;
    }

    
    @Column(name="CURRENT_VERSION_ID", nullable=false, length=20)
    public BigDecimal getCurrentVersionId() {
        return this.currentVersionId;
    }
    
    public void setCurrentVersionId(BigDecimal currentVersionId) {
        this.currentVersionId = currentVersionId;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="DOC_SPACE_ID", nullable=false, length=20)
    public BigDecimal getDocSpaceId() {
        return this.docSpaceId;
    }
    
    public void setDocSpaceId(BigDecimal docSpaceId) {
        this.docSpaceId = docSpaceId;
    }

    
    @Column(name="DOC_SPACE_NAME", nullable=false, length=80)
    public String getDocSpaceName() {
        return this.docSpaceName;
    }
    
    public void setDocSpaceName(String docSpaceName) {
        this.docSpaceName = docSpaceName;
    }

    
    @Column(name="DOC_CONTAINER_ID", nullable=false, length=20)
    public BigDecimal getDocContainerId() {
        return this.docContainerId;
    }
    
    public void setDocContainerId(BigDecimal docContainerId) {
        this.docContainerId = docContainerId;
    }

    
    @Column(name="CONTAINER_NAME", nullable=false, length=80)
    public String getContainerName() {
        return this.containerName;
    }
    
    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }

    
    @Column(name="IS_HIDDEN", nullable=false, length=1)
    public int getIsHidden() {
        return this.isHidden;
    }
    
    public void setIsHidden(int isHidden) {
        this.isHidden = isHidden;
    }

    
    @Column(name="DOC_AUTHOR_ID", nullable=false, length=20)
    public BigDecimal getDocAuthorId() {
        return this.docAuthorId;
    }
    
    public void setDocAuthorId(BigDecimal docAuthorId) {
        this.docAuthorId = docAuthorId;
    }

    
    @Column(name="DOC_AUTHOR", nullable=false, length=4000)
    public String getDocAuthor() {
        return this.docAuthor;
    }
    
    public void setDocAuthor(String docAuthor) {
        this.docAuthor = docAuthor;
    }

    
    @Column(name="DOC_VERSION_ID", nullable=false, length=20)
    public BigDecimal getDocVersionId() {
        return this.docVersionId;
    }
    
    public void setDocVersionId(BigDecimal docVersionId) {
        this.docVersionId = docVersionId;
    }

    
    @Column(name="DOC_VERSION_NUM", nullable=false, length=20)
    public BigDecimal getDocVersionNum() {
        return this.docVersionNum;
    }
    
    public void setDocVersionNum(BigDecimal docVersionNum) {
        this.docVersionNum = docVersionNum;
    }

    
    @Column(name="DOC_VERSION_LABEL", nullable=false, length=240)
    public String getDocVersionLabel() {
        return this.docVersionLabel;
    }
    
    public void setDocVersionLabel(String docVersionLabel) {
        this.docVersionLabel = docVersionLabel;
    }

    
    @Column(name="DOC_VERSION_NAME", nullable=false, length=256)
    public String getDocVersionName() {
        return this.docVersionName;
    }
    
    public void setDocVersionName(String docVersionName) {
        this.docVersionName = docVersionName;
    }

    
    @Column(name="SOURCE_FILE_NAME", nullable=false, length=240)
    public String getSourceFileName() {
        return this.sourceFileName;
    }
    
    public void setSourceFileName(String sourceFileName) {
        this.sourceFileName = sourceFileName;
    }

    
    @Column(name="SHORT_FILE_NAME", nullable=false, length=240)
    public String getShortFileName() {
        return this.shortFileName;
    }
    
    public void setShortFileName(String shortFileName) {
        this.shortFileName = shortFileName;
    }

    
    @Column(name="VERSION_DESCRIPTION", nullable=false, length=4000)
    public String getVersionDescription() {
        return this.versionDescription;
    }
    
    public void setVersionDescription(String versionDescription) {
        this.versionDescription = versionDescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MODIFIED", nullable=false, length=7)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="MODIFIED_BY_ID", nullable=false, length=20)
    public BigDecimal getModifiedById() {
        return this.modifiedById;
    }
    
    public void setModifiedById(BigDecimal modifiedById) {
        this.modifiedById = modifiedById;
    }

    
    @Column(name="MODIFIED_BY", nullable=false, length=4000)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    
    @Column(name="IS_CHECKED_OUT", nullable=false, length=1)
    public int getIsCheckedOut() {
        return this.isCheckedOut;
    }
    
    public void setIsCheckedOut(int isCheckedOut) {
        this.isCheckedOut = isCheckedOut;
    }

    
    @Column(name="CHECKED_OUT_BY_ID", nullable=false, length=20)
    public BigDecimal getCheckedOutById() {
        return this.checkedOutById;
    }
    
    public void setCheckedOutById(BigDecimal checkedOutById) {
        this.checkedOutById = checkedOutById;
    }

    
    @Column(name="CHECKED_OUT_BY", nullable=false, length=4000)
    public String getCheckedOutBy() {
        return this.checkedOutBy;
    }
    
    public void setCheckedOutBy(String checkedOutBy) {
        this.checkedOutBy = checkedOutBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CHECKED_OUT", nullable=false, length=7)
    public Date getDateCheckedOut() {
        return this.dateCheckedOut;
    }
    
    public void setDateCheckedOut(Date dateCheckedOut) {
        this.dateCheckedOut = dateCheckedOut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CHECKOUT_DUE", nullable=false, length=7)
    public Date getCheckoutDue() {
        return this.checkoutDue;
    }
    
    public void setCheckoutDue(Date checkoutDue) {
        this.checkoutDue = checkoutDue;
    }

    
    @Column(name="DOC_COMMENT", nullable=false, length=500)
    public String getDocComment() {
        return this.docComment;
    }
    
    public void setDocComment(String docComment) {
        this.docComment = docComment;
    }

    
    @Column(name="DOC_CONTENT_ID", nullable=false, length=20)
    public BigDecimal getDocContentId() {
        return this.docContentId;
    }
    
    public void setDocContentId(BigDecimal docContentId) {
        this.docContentId = docContentId;
    }

    
    @Column(name="DOC_FORMAT_ID", nullable=false, length=20)
    public BigDecimal getDocFormatId() {
        return this.docFormatId;
    }
    
    public void setDocFormatId(BigDecimal docFormatId) {
        this.docFormatId = docFormatId;
    }

    
    @Column(name="FILE_SIZE", nullable=false, length=20)
    public BigDecimal getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="FILE_HANDLE", nullable=false, length=240)
    public String getFileHandle() {
        return this.fileHandle;
    }
    
    public void setFileHandle(String fileHandle) {
        this.fileHandle = fileHandle;
    }

    
    @Column(name="REPOSITORY_ID", nullable=false, length=4)
    public int getRepositoryId() {
        return this.repositoryId;
    }
    
    public void setRepositoryId(int repositoryId) {
        this.repositoryId = repositoryId;
    }

    
    @Column(name="REPOSITORY_PATH", nullable=false, length=240)
    public String getRepositoryPath() {
        return this.repositoryPath;
    }
    
    public void setRepositoryPath(String repositoryPath) {
        this.repositoryPath = repositoryPath;
    }

    
    @Column(name="FORMAT_NAME", nullable=false, length=240)
    public String getFormatName() {
        return this.formatName;
    }
    
    public void setFormatName(String formatName) {
        this.formatName = formatName;
    }

    
    @Column(name="MIME_TYPE", nullable=false, length=240)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="APP_ICON_URL", nullable=false, length=240)
    public String getAppIconUrl() {
        return this.appIconUrl;
    }
    
    public void setAppIconUrl(String appIconUrl) {
        this.appIconUrl = appIconUrl;
    }

    
    @Column(name="HAS_LINKS", nullable=false, length=22)
    public BigDecimal getHasLinks() {
        return this.hasLinks;
    }
    
    public void setHasLinks(BigDecimal hasLinks) {
        this.hasLinks = hasLinks;
    }

    
    @Column(name="HAS_WORKFLOWS", nullable=false, length=22)
    public BigDecimal getHasWorkflows() {
        return this.hasWorkflows;
    }
    
    public void setHasWorkflows(BigDecimal hasWorkflows) {
        this.hasWorkflows = hasWorkflows;
    }

    
    @Column(name="HAS_DISCUSSIONS", nullable=false, length=22)
    public BigDecimal getHasDiscussions() {
        return this.hasDiscussions;
    }
    
    public void setHasDiscussions(BigDecimal hasDiscussions) {
        this.hasDiscussions = hasDiscussions;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATED", nullable=false, length=7)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docId", getDocId())
            .append("docName", getDocName())
            .append("crc", getCrc())
            .append("objectType", getObjectType())
            .append("docStatusId", getDocStatusId())
            .append("docStatus", getDocStatus())
            .append("docDescription", getDocDescription())
            .append("currentVersionId", getCurrentVersionId())
            .append("recordStatus", getRecordStatus())
            .append("docSpaceId", getDocSpaceId())
            .append("docSpaceName", getDocSpaceName())
            .append("docContainerId", getDocContainerId())
            .append("containerName", getContainerName())
            .append("isHidden", getIsHidden())
            .append("docAuthorId", getDocAuthorId())
            .append("docAuthor", getDocAuthor())
            .append("docVersionId", getDocVersionId())
            .append("docVersionNum", getDocVersionNum())
            .append("docVersionLabel", getDocVersionLabel())
            .append("docVersionName", getDocVersionName())
            .append("sourceFileName", getSourceFileName())
            .append("shortFileName", getShortFileName())
            .append("versionDescription", getVersionDescription())
            .append("dateModified", getDateModified())
            .append("modifiedById", getModifiedById())
            .append("modifiedBy", getModifiedBy())
            .append("isCheckedOut", getIsCheckedOut())
            .append("checkedOutById", getCheckedOutById())
            .append("checkedOutBy", getCheckedOutBy())
            .append("dateCheckedOut", getDateCheckedOut())
            .append("checkoutDue", getCheckoutDue())
            .append("docComment", getDocComment())
            .append("docContentId", getDocContentId())
            .append("docFormatId", getDocFormatId())
            .append("fileSize", getFileSize())
            .append("fileHandle", getFileHandle())
            .append("repositoryId", getRepositoryId())
            .append("repositoryPath", getRepositoryPath())
            .append("formatName", getFormatName())
            .append("mimeType", getMimeType())
            .append("appIconUrl", getAppIconUrl())
            .append("hasLinks", getHasLinks())
            .append("hasWorkflows", getHasWorkflows())
            .append("hasDiscussions", getHasDiscussions())
            .append("dateCreated", getDateCreated())
            .toString();
    }

}


