/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocVersionHasContent generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_VERSION_HAS_CONTENT")
public class PnDocVersionHasContent implements java.io.Serializable {

	private PnDocVersionHasContentPK comp_id;

	private Integer docId;

	private PnDocVersion pnDocVersion;

	private PnDocContentElement pnDocContentElement;

	public PnDocVersionHasContent() {
	}

	public PnDocVersionHasContent(PnDocVersionHasContentPK comp_id, Integer docId) {
		this.comp_id = comp_id;
		this.docId = docId;
	}

	public PnDocVersionHasContent(PnDocVersionHasContentPK comp_id, Integer docId, PnDocVersion pnDocVersion,
			PnDocContentElement pnDocContentElement) {
		this.comp_id = comp_id;
		this.docId = docId;
		this.pnDocVersion = pnDocVersion;
		this.pnDocContentElement = pnDocContentElement;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "docVersionId", column = @Column(name = "DOC_VERSION_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "docContentId", column = @Column(name = "DOC_CONTENT_ID", nullable = false, length = 20)) })
	public PnDocVersionHasContentPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnDocVersionHasContentPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "DOC_ID", nullable = false, length = 20)
	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocVersion.class)
	@JoinColumn(name = "DOC_VERSION_ID", insertable = false, updatable = false)
	public PnDocVersion getPnDocVersion() {
		return this.pnDocVersion;
	}

	public void setPnDocVersion(PnDocVersion pnDocVersion) {
		this.pnDocVersion = pnDocVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnDocContentElement.class)
	@JoinColumn(name = "DOC_CONTENT_ID", insertable = false, updatable = false)
	public PnDocContentElement getPnDocContentElement() {
		return this.pnDocContentElement;
	}

	public void setPnDocContentElement(PnDocContentElement pnDocContentElement) {
		this.pnDocContentElement = pnDocContentElement;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnDocVersionHasContent))
			return false;
		PnDocVersionHasContent castOther = (PnDocVersionHasContent) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}
}
