/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocDelContainerListView generated by hbm2java
 */
@Entity
@Table(name="PN_DOC_DEL_CONTAINER_LIST_VIEW"
)
public class PnDocDelContainerListView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal objectId;

    /** identifier field */
    private String name;

    /** identifier field */
    private BigDecimal isHidden;

    /** identifier field */
    private String objectType;

    /** identifier field */
    private BigDecimal docContainerId;

    /** identifier field */
    private String format;

    /** identifier field */
    private String appIconUrl;

    /** identifier field */
    private String url;

    /** identifier field */
    private BigDecimal version;

    /** identifier field */
    private BigDecimal isCheckedOut;

    /** identifier field */
    private BigDecimal checkedOutById;

    /** identifier field */
    private String checkedOutBy;

    /** identifier field */
    private String status;

    /** identifier field */
    private String author;

    /** identifier field */
    private Date dateModified;

    /** identifier field */
    private String modifiedBy;

    /** identifier field */
    private BigDecimal fileSize;

    /** identifier field */
    private String shortFileName;

    /** identifier field */
    private BigDecimal hasLinks;

    /** identifier field */
    private BigDecimal hasWorkflows;

    /** identifier field */
    private BigDecimal hasDiscussions;

    /** identifier field */
    private String description;

    /** identifier field */
    private String comments;

    public PnDocDelContainerListView() {
    }

    public PnDocDelContainerListView(BigDecimal objectId, String name, BigDecimal isHidden, String objectType, BigDecimal docContainerId, String format, String appIconUrl, String url, BigDecimal version, BigDecimal isCheckedOut, BigDecimal checkedOutById, String checkedOutBy, String status, String author, Date dateModified, String modifiedBy, BigDecimal fileSize, String shortFileName, BigDecimal hasLinks, BigDecimal hasWorkflows, BigDecimal hasDiscussions, String description, String comments) {
       this.objectId = objectId;
       this.name = name;
       this.isHidden = isHidden;
       this.objectType = objectType;
       this.docContainerId = docContainerId;
       this.format = format;
       this.appIconUrl = appIconUrl;
       this.url = url;
       this.version = version;
       this.isCheckedOut = isCheckedOut;
       this.checkedOutById = checkedOutById;
       this.checkedOutBy = checkedOutBy;
       this.status = status;
       this.author = author;
       this.dateModified = dateModified;
       this.modifiedBy = modifiedBy;
       this.fileSize = fileSize;
       this.shortFileName = shortFileName;
       this.hasLinks = hasLinks;
       this.hasWorkflows = hasWorkflows;
       this.hasDiscussions = hasDiscussions;
       this.description = description;
       this.comments = comments;
    }
    
    @Column(name="OBJECT_ID", nullable=false, length=20)
    public BigDecimal getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(BigDecimal objectId) {
        this.objectId = objectId;
    }

    @Column(name="NAME", nullable=false, length=256)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IS_HIDDEN", nullable=false, length=22)
    public BigDecimal getIsHidden() {
        return this.isHidden;
    }
    
    public void setIsHidden(BigDecimal isHidden) {
        this.isHidden = isHidden;
    }

    
    @Column(name="OBJECT_TYPE", nullable=false, length=13)
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    
    @Column(name="DOC_CONTAINER_ID", nullable=false, length=20)
    public BigDecimal getDocContainerId() {
        return this.docContainerId;
    }
    
    public void setDocContainerId(BigDecimal docContainerId) {
        this.docContainerId = docContainerId;
    }

    
    @Column(name="FORMAT", nullable=false, length=240)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="APP_ICON_URL", nullable=false, length=240)
    public String getAppIconUrl() {
        return this.appIconUrl;
    }
    
    public void setAppIconUrl(String appIconUrl) {
        this.appIconUrl = appIconUrl;
    }

    
    @Column(name="URL", nullable=false, length=500)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="VERSION", nullable=false, length=22)
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    
    @Column(name="IS_CHECKED_OUT", nullable=false, length=22)
    public BigDecimal getIsCheckedOut() {
        return this.isCheckedOut;
    }
    
    public void setIsCheckedOut(BigDecimal isCheckedOut) {
        this.isCheckedOut = isCheckedOut;
    }

    
    @Column(name="CHECKED_OUT_BY_ID", nullable=false, length=22)
    public BigDecimal getCheckedOutById() {
        return this.checkedOutById;
    }
    
    public void setCheckedOutById(BigDecimal checkedOutById) {
        this.checkedOutById = checkedOutById;
    }

    
    @Column(name="CHECKED_OUT_BY", nullable=false, length=4000)
    public String getCheckedOutBy() {
        return this.checkedOutBy;
    }
    
    public void setCheckedOutBy(String checkedOutBy) {
        this.checkedOutBy = checkedOutBy;
    }

    
    @Column(name="STATUS", nullable=false, length=80)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="AUTHOR", nullable=false, length=4000)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MODIFIED", nullable=false, length=7)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="MODIFIED_BY", nullable=false, length=4000)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    
    @Column(name="FILE_SIZE", nullable=false, length=22)
    public BigDecimal getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="SHORT_FILE_NAME", nullable=false, length=240)
    public String getShortFileName() {
        return this.shortFileName;
    }
    
    public void setShortFileName(String shortFileName) {
        this.shortFileName = shortFileName;
    }

    
    @Column(name="HAS_LINKS", nullable=false, length=22)
    public BigDecimal getHasLinks() {
        return this.hasLinks;
    }
    
    public void setHasLinks(BigDecimal hasLinks) {
        this.hasLinks = hasLinks;
    }

    
    @Column(name="HAS_WORKFLOWS", nullable=false, length=22)
    public BigDecimal getHasWorkflows() {
        return this.hasWorkflows;
    }
    
    public void setHasWorkflows(BigDecimal hasWorkflows) {
        this.hasWorkflows = hasWorkflows;
    }

    
    @Column(name="HAS_DISCUSSIONS", nullable=false, length=22)
    public BigDecimal getHasDiscussions() {
        return this.hasDiscussions;
    }
    
    public void setHasDiscussions(BigDecimal hasDiscussions) {
        this.hasDiscussions = hasDiscussions;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=4000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="COMMENTS", nullable=false, length=500)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("objectId", getObjectId())
            .append("name", getName())
            .append("isHidden", getIsHidden())
            .append("objectType", getObjectType())
            .append("docContainerId", getDocContainerId())
            .append("format", getFormat())
            .append("appIconUrl", getAppIconUrl())
            .append("url", getUrl())
            .append("version", getVersion())
            .append("isCheckedOut", getIsCheckedOut())
            .append("checkedOutById", getCheckedOutById())
            .append("checkedOutBy", getCheckedOutBy())
            .append("status", getStatus())
            .append("author", getAuthor())
            .append("dateModified", getDateModified())
            .append("modifiedBy", getModifiedBy())
            .append("fileSize", getFileSize())
            .append("shortFileName", getShortFileName())
            .append("hasLinks", getHasLinks())
            .append("hasWorkflows", getHasWorkflows())
            .append("hasDiscussions", getHasDiscussions())
            .append("description", getDescription())
            .append("comments", getComments())
            .toString();
    }

}


