/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnDocBySpaceView generated by hbm2java
 */
@Entity
@Table(name="PN_DOC_BY_SPACE_VIEW"
)
public class PnDocBySpaceView  implements java.io.Serializable {


     private Integer doc_id;
     private Integer docSpaceId;
     private Integer docStatusId;
     private Date dateModified;
     private String appIconUrl;

    public PnDocBySpaceView() {
    }

	
    public PnDocBySpaceView(Integer doc_id) {
        this.doc_id = doc_id;
    }
    public PnDocBySpaceView(Integer doc_id, Integer docSpaceId, Integer docStatusId, Date dateModified) {
       this.doc_id = doc_id;
       this.docSpaceId = docSpaceId;
       this.docStatusId = docStatusId;
       this.dateModified = dateModified;
    }
   
     @Id 

    
    @Column(name="doc_id", nullable=false)
    public Integer getDoc_id() {
        return this.doc_id;
    }
    
    public void setDoc_id(Integer doc_id) {
        this.doc_id = doc_id;
    }

    
    @Column(name="doc_space_id")
    public Integer getDocSpaceId() {
        return this.docSpaceId;
    }
    
    public void setDocSpaceId(Integer docSpaceId) {
        this.docSpaceId = docSpaceId;
    }

    
    @Column(name="doc_status_id")
    public Integer getDocStatusId() {
        return this.docStatusId;
    }
    
    public void setDocStatusId(Integer docStatusId) {
        this.docStatusId = docStatusId;
    }

    
    @Column(name="date_modified")
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    
    @Column(name="app_icon_url")
    public String getAppIconUrl() {
		return appIconUrl;
	}


	public void setAppIconUrl(String appIconUrl) {
		this.appIconUrl = appIconUrl;
	}


}


