/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocProviderHasDocSpacePK generated by hbm2java
 */
@Embeddable
public class PnDocProviderHasDocSpacePK  implements java.io.Serializable {


    private Integer docProviderId;
     
    private Integer docSpaceId;

    public PnDocProviderHasDocSpacePK() {
    }

    public PnDocProviderHasDocSpacePK(Integer docProviderId, Integer docSpaceId) {
       this.docProviderId = docProviderId;
       this.docSpaceId = docSpaceId;
    }
   
    @Column(name="DOC_PROVIDER_ID", nullable=false, length=20)
    public Integer getDocProviderId() {
        return this.docProviderId;
    }
    
    public void setDocProviderId(Integer docProviderId) {
        this.docProviderId = docProviderId;
    }

    @Column(name="DOC_SPACE_ID", nullable=false, length=20)
    public Integer getDocSpaceId() {
        return this.docSpaceId;
    }
    
    public void setDocSpaceId(Integer docSpaceId) {
        this.docSpaceId = docSpaceId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("docProviderId", getDocProviderId())
            .append("docSpaceId", getDocSpaceId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocProviderHasDocSpacePK) ) return false;
        PnDocProviderHasDocSpacePK castOther = (PnDocProviderHasDocSpacePK) other;
        return new EqualsBuilder()
            .append(this.getDocProviderId(), castOther.getDocProviderId())
            .append(this.getDocSpaceId(), castOther.getDocSpaceId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getDocProviderId())
            .append(getDocSpaceId())
            .toHashCode();
    }
}


