/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocContentRendition generated by hbm2java
 */
@Entity
@Table(name="PN_DOC_CONTENT_RENDITION"
)
public class PnDocContentRendition  implements java.io.Serializable {

	/** identifier field */
     private PnDocContentRenditionPK comp_id;
     
    /** nullable persistent field */
    private String renderedAs;

    /** persistent field */
    private String recordStatus;
    
	/** nullable persistent field */
    private PnDocContentElement pnDocContentElement;

    public PnDocContentRendition() {
    }

	
    public PnDocContentRendition(PnDocContentRenditionPK comp_id, String recordStatus) {
        this.comp_id = comp_id;
        this.recordStatus = recordStatus;
    }
    public PnDocContentRendition(PnDocContentRenditionPK comp_id, String renderedAs, String recordStatus, PnDocContentElement pnDocContentElement) {
       this.comp_id = comp_id;
       this.renderedAs = renderedAs;
       this.recordStatus = recordStatus;
       this.pnDocContentElement = pnDocContentElement;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="docRenditionId", column=@Column(name="DOC_RENDITION_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="docContentId", column=@Column(name="DOC_CONTENT_ID", nullable=false, length=20) ) } )
    public PnDocContentRenditionPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnDocContentRenditionPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="RENDERED_AS", length=500)
    public String getRenderedAs() {
        return this.renderedAs;
    }
    
    public void setRenderedAs(String renderedAs) {
        this.renderedAs = renderedAs;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnDocContentElement.class)
    @JoinColumn(name="DOC_CONTENT_ID", insertable=false, updatable=false)
    public PnDocContentElement getPnDocContentElement() {
        return this.pnDocContentElement;
    }
    
    public void setPnDocContentElement(PnDocContentElement pnDocContentElement) {
        this.pnDocContentElement = pnDocContentElement;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnDocContentRendition) ) return false;
        PnDocContentRendition castOther = (PnDocContentRendition) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

	public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }
}


