/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnDocConfiguration generated by hbm2java
 */
@Entity
@Table(name = "PN_DOC_CONFIGURATION")
public class PnDocConfiguration implements java.io.Serializable {

	/** identifier field */
	private Integer docConfigurationId;

	/** persistent field */
	private Date dateFrozen;

	/** persistent field */
	private String docConfigurationName;

	/** persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	private PnPerson pnPerson;

	private Set pnDocConfigurationHasDocs = new HashSet(0);

	public PnDocConfiguration() {
	}

	public PnDocConfiguration(Integer docConfigurationId, Date dateFrozen, String docConfigurationName, Date crc,
			String recordStatus) {
		this.docConfigurationId = docConfigurationId;
		this.dateFrozen = dateFrozen;
		this.docConfigurationName = docConfigurationName;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnDocConfiguration(Integer docConfigurationId, Date dateFrozen, String docConfigurationName, Date crc,
			String recordStatus, PnPerson pnPerson, Set pnDocConfigurationHasDocs) {
		this.docConfigurationId = docConfigurationId;
		this.dateFrozen = dateFrozen;
		this.docConfigurationName = docConfigurationName;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnPerson = pnPerson;
		this.pnDocConfigurationHasDocs = pnDocConfigurationHasDocs;
	}

	@Id
	@Column(name = "DOC_CONFIGURATION_ID", nullable = false)
	public Integer getDocConfigurationId() {
		return this.docConfigurationId;
	}

	public void setDocConfigurationId(Integer docConfigurationId) {
		this.docConfigurationId = docConfigurationId;
	}

	@Column(name = "DATE_FROZEN", nullable = false, length = 7)
	public Date getDateFrozen() {
		return this.dateFrozen;
	}

	public void setDateFrozen(Date dateFrozen) {
		this.dateFrozen = dateFrozen;
	}

	@Column(name = "DOC_CONFIGURATION_NAME", nullable = false, length = 80)
	public String getDocConfigurationName() {
		return this.docConfigurationName;
	}

	public void setDocConfigurationName(String docConfigurationName) {
		this.docConfigurationName = docConfigurationName;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "CREATED_BY")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnDocConfiguration", targetEntity = PnDocConfigurationHasDoc.class)
	@Transient
	public Set getPnDocConfigurationHasDocs() {
		return this.pnDocConfigurationHasDocs;
	}

	public void setPnDocConfigurationHasDocs(Set pnDocConfigurationHasDocs) {
		this.pnDocConfigurationHasDocs = pnDocConfigurationHasDocs;
	}

	public String toString() {
		return new ToStringBuilder(this).append("docConfigurationId", getDocConfigurationId()).toString();
	}

}
