/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnElementDisplayClass generated by hbm2java
 */
@Entity
@Table(name = "PN_ELEMENT_DISPLAY_CLASS")
public class PnElementDisplayClass implements java.io.Serializable {

	private PnElementDisplayClassPK comp_id;

	private PnElement pnElement;

	private PnClass pnClass;

	public PnElementDisplayClass() {
	}

	public PnElementDisplayClass(PnElementDisplayClassPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnElementDisplayClass(PnElementDisplayClassPK comp_id, PnElement pnElement, PnClass pnClass) {
		this.comp_id = comp_id;
		this.pnElement = pnElement;
		this.pnClass = pnClass;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "elementId", column = @Column(name = "ELEMENT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "classId", column = @Column(name = "CLASS_ID", nullable = false, length = 20)) })
	public PnElementDisplayClassPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnElementDisplayClassPK comp_id) {
		this.comp_id = comp_id;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnElement.class)
	@JoinColumn(name = "ELEMENT_ID", insertable = false, updatable = false)
	public PnElement getPnElement() {
		return this.pnElement;
	}

	public void setPnElement(PnElement pnElement) {
		this.pnElement = pnElement;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnClass.class)
	@JoinColumn(name = "CLASS_ID", insertable = false, updatable = false)
	public PnClass getPnClass() {
		return this.pnClass;
	}

	public void setPnClass(PnClass pnClass) {
		this.pnClass = pnClass;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnElementDisplayClass))
			return false;
		PnElementDisplayClass castOther = (PnElementDisplayClass) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}
}
