/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeHasObjectView generated by hbm2java
 */
@Entity
@Table(name="PN_ENVELOPE_HAS_OBJECT_VIEW"
)
public class PnEnvelopeHasObjectView  implements java.io.Serializable {

    /** identifier field */
    private BigDecimal envelopeId;

    /** identifier field */
    private BigDecimal workflowId;

    /** identifier field */
    private String workflowName;

    /** identifier field */
    private String workflowDescription;

    /** identifier field */
    private BigDecimal spaceId;

    /** identifier field */
    private BigDecimal strictnessId;

    /** identifier field */
    private String strictnessName;

    /** identifier field */
    private String strictnessDescription;

    /** identifier field */
    private BigDecimal currentVersionId;

    /** identifier field */
    private String envelopeName;

    /** identifier field */
    private String envelopeDescription;

    /** identifier field */
    private BigDecimal createdById;

    /** identifier field */
    private String createdByFullName;

    /** identifier field */
    private Date createdDatetime;

    /** identifier field */
    private BigDecimal modifiedById;

    /** identifier field */
    private String modifiedByFullName;

    /** identifier field */
    private Date modifiedDatetime;

    /** identifier field */
    private Date crc;

    /** identifier field */
    private String recordStatus;

    /** identifier field */
    private BigDecimal isActive;

    /** identifier field */
    private BigDecimal currentStepId;

    /** identifier field */
    private String currentStepName;

    /** identifier field */
    private String currentStepDescription;

    /** identifier field */
    private Clob currentStepNotesClob;

    /** identifier field */
    private BigDecimal currentStatusId;

    /** identifier field */
    private String currentStatusName;

    /** identifier field */
    private String currentStatusDescription;

    /** identifier field */
    private BigDecimal lastTransitionId;

    /** identifier field */
    private String lastTransitionVerb;

    /** identifier field */
    private String lastTransitionDescription;

    /** identifier field */
    private BigDecimal currentPriorityId;

    /** identifier field */
    private String currentPriorityName;

    /** identifier field */
    private String currentPriorityDescription;

    /** identifier field */
    private Clob currentCommentsClob;

    /** identifier field */
    private BigDecimal currentCreatedById;

    /** identifier field */
    private String currentCreatedByFullName;

    /** identifier field */
    private Date currentCreatedDatetime;

    /** identifier field */
    private Date currentVersionCrc;

    /** identifier field */
    private String currentVersionRecordStatus;

    /** identifier field */
    private BigDecimal objectId;

    public PnEnvelopeHasObjectView() {
    }

    public PnEnvelopeHasObjectView(BigDecimal envelopeId, BigDecimal workflowId, String workflowName, String workflowDescription, BigDecimal spaceId, BigDecimal strictnessId, String strictnessName, String strictnessDescription, BigDecimal currentVersionId, String envelopeName, String envelopeDescription, BigDecimal createdById, String createdByFullName, Date createdDatetime, BigDecimal modifiedById, String modifiedByFullName, Date modifiedDatetime, Date crc, String recordStatus, BigDecimal isActive, BigDecimal currentStepId, String currentStepName, String currentStepDescription, Clob currentStepNotesClob, BigDecimal currentStatusId, String currentStatusName, String currentStatusDescription, BigDecimal lastTransitionId, String lastTransitionVerb, String lastTransitionDescription, BigDecimal currentPriorityId, String currentPriorityName, String currentPriorityDescription, Clob currentCommentsClob, BigDecimal currentCreatedById, String currentCreatedByFullName, Date currentCreatedDatetime, Date currentVersionCrc, String currentVersionRecordStatus, BigDecimal objectId) {
       this.envelopeId = envelopeId;
       this.workflowId = workflowId;
       this.workflowName = workflowName;
       this.workflowDescription = workflowDescription;
       this.spaceId = spaceId;
       this.strictnessId = strictnessId;
       this.strictnessName = strictnessName;
       this.strictnessDescription = strictnessDescription;
       this.currentVersionId = currentVersionId;
       this.envelopeName = envelopeName;
       this.envelopeDescription = envelopeDescription;
       this.createdById = createdById;
       this.createdByFullName = createdByFullName;
       this.createdDatetime = createdDatetime;
       this.modifiedById = modifiedById;
       this.modifiedByFullName = modifiedByFullName;
       this.modifiedDatetime = modifiedDatetime;
       this.crc = crc;
       this.recordStatus = recordStatus;
       this.isActive = isActive;
       this.currentStepId = currentStepId;
       this.currentStepName = currentStepName;
       this.currentStepDescription = currentStepDescription;
       this.currentStepNotesClob = currentStepNotesClob;
       this.currentStatusId = currentStatusId;
       this.currentStatusName = currentStatusName;
       this.currentStatusDescription = currentStatusDescription;
       this.lastTransitionId = lastTransitionId;
       this.lastTransitionVerb = lastTransitionVerb;
       this.lastTransitionDescription = lastTransitionDescription;
       this.currentPriorityId = currentPriorityId;
       this.currentPriorityName = currentPriorityName;
       this.currentPriorityDescription = currentPriorityDescription;
       this.currentCommentsClob = currentCommentsClob;
       this.currentCreatedById = currentCreatedById;
       this.currentCreatedByFullName = currentCreatedByFullName;
       this.currentCreatedDatetime = currentCreatedDatetime;
       this.currentVersionCrc = currentVersionCrc;
       this.currentVersionRecordStatus = currentVersionRecordStatus;
       this.objectId = objectId;
    }
   

    
    @Column(name="ENVELOPE_ID", nullable=false, length=20)
    public BigDecimal getEnvelopeId() {
        return this.envelopeId;
    }
    
    public void setEnvelopeId(BigDecimal envelopeId) {
        this.envelopeId = envelopeId;
    }

    
    @Column(name="WORKFLOW_ID", nullable=false, length=20)
    public BigDecimal getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(BigDecimal workflowId) {
        this.workflowId = workflowId;
    }

    
    @Column(name="WORKFLOW_NAME", nullable=false, length=80)
    public String getWorkflowName() {
        return this.workflowName;
    }
    
    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    
    @Column(name="WORKFLOW_DESCRIPTION", nullable=false, length=500)
    public String getWorkflowDescription() {
        return this.workflowDescription;
    }
    
    public void setWorkflowDescription(String workflowDescription) {
        this.workflowDescription = workflowDescription;
    }

    
    @Column(name="SPACE_ID", nullable=false, length=20)
    public BigDecimal getSpaceId() {
        return this.spaceId;
    }
    
    public void setSpaceId(BigDecimal spaceId) {
        this.spaceId = spaceId;
    }

    
    @Column(name="STRICTNESS_ID", nullable=false, length=20)
    public BigDecimal getStrictnessId() {
        return this.strictnessId;
    }
    
    public void setStrictnessId(BigDecimal strictnessId) {
        this.strictnessId = strictnessId;
    }

    
    @Column(name="STRICTNESS_NAME", nullable=false, length=80)
    public String getStrictnessName() {
        return this.strictnessName;
    }
    
    public void setStrictnessName(String strictnessName) {
        this.strictnessName = strictnessName;
    }

    
    @Column(name="STRICTNESS_DESCRIPTION", nullable=false, length=500)
    public String getStrictnessDescription() {
        return this.strictnessDescription;
    }
    
    public void setStrictnessDescription(String strictnessDescription) {
        this.strictnessDescription = strictnessDescription;
    }

    
    @Column(name="CURRENT_VERSION_ID", nullable=false, length=20)
    public BigDecimal getCurrentVersionId() {
        return this.currentVersionId;
    }
    
    public void setCurrentVersionId(BigDecimal currentVersionId) {
        this.currentVersionId = currentVersionId;
    }

    
    @Column(name="ENVELOPE_NAME", nullable=false, length=80)
    public String getEnvelopeName() {
        return this.envelopeName;
    }
    
    public void setEnvelopeName(String envelopeName) {
        this.envelopeName = envelopeName;
    }

    
    @Column(name="ENVELOPE_DESCRIPTION", nullable=false, length=500)
    public String getEnvelopeDescription() {
        return this.envelopeDescription;
    }
    
    public void setEnvelopeDescription(String envelopeDescription) {
        this.envelopeDescription = envelopeDescription;
    }

    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public BigDecimal getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(BigDecimal createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="CREATED_BY_FULL_NAME", nullable=false, length=240)
    public String getCreatedByFullName() {
        return this.createdByFullName;
    }
    
    public void setCreatedByFullName(String createdByFullName) {
        this.createdByFullName = createdByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    
    @Column(name="MODIFIED_BY_ID", nullable=false, length=20)
    public BigDecimal getModifiedById() {
        return this.modifiedById;
    }
    
    public void setModifiedById(BigDecimal modifiedById) {
        this.modifiedById = modifiedById;
    }

    
    @Column(name="MODIFIED_BY_FULL_NAME", nullable=false, length=240)
    public String getModifiedByFullName() {
        return this.modifiedByFullName;
    }
    
    public void setModifiedByFullName(String modifiedByFullName) {
        this.modifiedByFullName = modifiedByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFIED_DATETIME", nullable=false, length=7)
    public Date getModifiedDatetime() {
        return this.modifiedDatetime;
    }
    
    public void setModifiedDatetime(Date modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="IS_ACTIVE", nullable=false, length=22)
    public BigDecimal getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(BigDecimal isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="CURRENT_STEP_ID", nullable=false, length=20)
    public BigDecimal getCurrentStepId() {
        return this.currentStepId;
    }
    
    public void setCurrentStepId(BigDecimal currentStepId) {
        this.currentStepId = currentStepId;
    }

    
    @Column(name="CURRENT_STEP_NAME", nullable=false, length=80)
    public String getCurrentStepName() {
        return this.currentStepName;
    }
    
    public void setCurrentStepName(String currentStepName) {
        this.currentStepName = currentStepName;
    }

    
    @Column(name="CURRENT_STEP_DESCRIPTION", nullable=false, length=500)
    public String getCurrentStepDescription() {
        return this.currentStepDescription;
    }
    
    public void setCurrentStepDescription(String currentStepDescription) {
        this.currentStepDescription = currentStepDescription;
    }

    
    @Column(name="CURRENT_STEP_NOTES_CLOB", nullable=false, length=4000)
    public Clob getCurrentStepNotesClob() {
        return this.currentStepNotesClob;
    }
    
    public void setCurrentStepNotesClob(Clob currentStepNotesClob) {
        this.currentStepNotesClob = currentStepNotesClob;
    }

    
    @Column(name="CURRENT_STATUS_ID", nullable=false, length=20)
    public BigDecimal getCurrentStatusId() {
        return this.currentStatusId;
    }
    
    public void setCurrentStatusId(BigDecimal currentStatusId) {
        this.currentStatusId = currentStatusId;
    }

    
    @Column(name="CURRENT_STATUS_NAME", nullable=false, length=80)
    public String getCurrentStatusName() {
        return this.currentStatusName;
    }
    
    public void setCurrentStatusName(String currentStatusName) {
        this.currentStatusName = currentStatusName;
    }

    
    @Column(name="CURRENT_STATUS_DESCRIPTION", nullable=false, length=500)
    public String getCurrentStatusDescription() {
        return this.currentStatusDescription;
    }
    
    public void setCurrentStatusDescription(String currentStatusDescription) {
        this.currentStatusDescription = currentStatusDescription;
    }

    
    @Column(name="LAST_TRANSITION_ID", nullable=false, length=20)
    public BigDecimal getLastTransitionId() {
        return this.lastTransitionId;
    }
    
    public void setLastTransitionId(BigDecimal lastTransitionId) {
        this.lastTransitionId = lastTransitionId;
    }

    
    @Column(name="LAST_TRANSITION_VERB", nullable=false, length=80)
    public String getLastTransitionVerb() {
        return this.lastTransitionVerb;
    }
    
    public void setLastTransitionVerb(String lastTransitionVerb) {
        this.lastTransitionVerb = lastTransitionVerb;
    }

    
    @Column(name="LAST_TRANSITION_DESCRIPTION", nullable=false, length=500)
    public String getLastTransitionDescription() {
        return this.lastTransitionDescription;
    }
    
    public void setLastTransitionDescription(String lastTransitionDescription) {
        this.lastTransitionDescription = lastTransitionDescription;
    }

    
    @Column(name="CURRENT_PRIORITY_ID", nullable=false, length=20)
    public BigDecimal getCurrentPriorityId() {
        return this.currentPriorityId;
    }
    
    public void setCurrentPriorityId(BigDecimal currentPriorityId) {
        this.currentPriorityId = currentPriorityId;
    }

    
    @Column(name="CURRENT_PRIORITY_NAME", nullable=false, length=80)
    public String getCurrentPriorityName() {
        return this.currentPriorityName;
    }
    
    public void setCurrentPriorityName(String currentPriorityName) {
        this.currentPriorityName = currentPriorityName;
    }

    
    @Column(name="CURRENT_PRIORITY_DESCRIPTION", nullable=false, length=80)
    public String getCurrentPriorityDescription() {
        return this.currentPriorityDescription;
    }
    
    public void setCurrentPriorityDescription(String currentPriorityDescription) {
        this.currentPriorityDescription = currentPriorityDescription;
    }

    
    @Column(name="CURRENT_COMMENTS_CLOB", nullable=false, length=4000)
    public Clob getCurrentCommentsClob() {
        return this.currentCommentsClob;
    }
    
    public void setCurrentCommentsClob(Clob currentCommentsClob) {
        this.currentCommentsClob = currentCommentsClob;
    }

    
    @Column(name="CURRENT_CREATED_BY_ID", nullable=false, length=20)
    public BigDecimal getCurrentCreatedById() {
        return this.currentCreatedById;
    }
    
    public void setCurrentCreatedById(BigDecimal currentCreatedById) {
        this.currentCreatedById = currentCreatedById;
    }

    
    @Column(name="CURRENT_CREATED_BY_FULL_NAME", nullable=false, length=240)
    public String getCurrentCreatedByFullName() {
        return this.currentCreatedByFullName;
    }
    
    public void setCurrentCreatedByFullName(String currentCreatedByFullName) {
        this.currentCreatedByFullName = currentCreatedByFullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CURRENT_CREATED_DATETIME", nullable=false, length=7)
    public Date getCurrentCreatedDatetime() {
        return this.currentCreatedDatetime;
    }
    
    public void setCurrentCreatedDatetime(Date currentCreatedDatetime) {
        this.currentCreatedDatetime = currentCreatedDatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CURRENT_VERSION_CRC", nullable=false, length=7)
    public Date getCurrentVersionCrc() {
        return this.currentVersionCrc;
    }
    
    public void setCurrentVersionCrc(Date currentVersionCrc) {
        this.currentVersionCrc = currentVersionCrc;
    }

    
    @Column(name="CURRENT_VERSION_RECORD_STATUS", nullable=false, length=1)
    public String getCurrentVersionRecordStatus() {
        return this.currentVersionRecordStatus;
    }
    
    public void setCurrentVersionRecordStatus(String currentVersionRecordStatus) {
        this.currentVersionRecordStatus = currentVersionRecordStatus;
    }

    
    @Column(name="OBJECT_ID", nullable=false, length=20)
    public BigDecimal getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(BigDecimal objectId) {
        this.objectId = objectId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("envelopeId", getEnvelopeId())
            .append("workflowId", getWorkflowId())
            .append("workflowName", getWorkflowName())
            .append("workflowDescription", getWorkflowDescription())
            .append("spaceId", getSpaceId())
            .append("strictnessId", getStrictnessId())
            .append("strictnessName", getStrictnessName())
            .append("strictnessDescription", getStrictnessDescription())
            .append("currentVersionId", getCurrentVersionId())
            .append("envelopeName", getEnvelopeName())
            .append("envelopeDescription", getEnvelopeDescription())
            .append("createdById", getCreatedById())
            .append("createdByFullName", getCreatedByFullName())
            .append("createdDatetime", getCreatedDatetime())
            .append("modifiedById", getModifiedById())
            .append("modifiedByFullName", getModifiedByFullName())
            .append("modifiedDatetime", getModifiedDatetime())
            .append("crc", getCrc())
            .append("recordStatus", getRecordStatus())
            .append("isActive", getIsActive())
            .append("currentStepId", getCurrentStepId())
            .append("currentStepName", getCurrentStepName())
            .append("currentStepDescription", getCurrentStepDescription())
            .append("currentStepNotesClob", getCurrentStepNotesClob())
            .append("currentStatusId", getCurrentStatusId())
            .append("currentStatusName", getCurrentStatusName())
            .append("currentStatusDescription", getCurrentStatusDescription())
            .append("lastTransitionId", getLastTransitionId())
            .append("lastTransitionVerb", getLastTransitionVerb())
            .append("lastTransitionDescription", getLastTransitionDescription())
            .append("currentPriorityId", getCurrentPriorityId())
            .append("currentPriorityName", getCurrentPriorityName())
            .append("currentPriorityDescription", getCurrentPriorityDescription())
            .append("currentCommentsClob", getCurrentCommentsClob())
            .append("currentCreatedById", getCurrentCreatedById())
            .append("currentCreatedByFullName", getCurrentCreatedByFullName())
            .append("currentCreatedDatetime", getCurrentCreatedDatetime())
            .append("currentVersionCrc", getCurrentVersionCrc())
            .append("currentVersionRecordStatus", getCurrentVersionRecordStatus())
            .append("objectId", getObjectId())
            .toString();
    }

}


