/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeHistoryAction generated by hbm2java
 */
@Entity
@Table(name = "PN_ENVELOPE_HISTORY_ACTION")
public class PnEnvelopeHistoryAction implements java.io.Serializable {

	/** identifier field */
	private Integer historyActionId;

	/** nullable persistent field */
	private String actionName;

	/** nullable persistent field */
	private String actionDescription;

	/** persistent field */
	private Integer createdById;

	/** persistent field */
	private Date createdDatetime;

	/** nullable persistent field */
	private Integer modifiedById;

	/** nullable persistent field */
	private Date modifiedDatetime;

	/** persistent field */
	private Date crc;

	/** persistent field */
	private String recordStatus;

	/** persistent field */
	private Set pnEnvelopeHistories = new HashSet(0);

	public PnEnvelopeHistoryAction() {
	}

	public PnEnvelopeHistoryAction(Integer historyActionId, Integer createdById, Date createdDatetime, Date crc,
			String recordStatus) {
		this.historyActionId = historyActionId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnEnvelopeHistoryAction(Integer historyActionId, String actionName, String actionDescription,
			Integer createdById, Date createdDatetime, Integer modifiedById, Date modifiedDatetime, Date crc,
			String recordStatus, Set pnEnvelopeHistories) {
		this.historyActionId = historyActionId;
		this.actionName = actionName;
		this.actionDescription = actionDescription;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	/** minimal constructor */
	public PnEnvelopeHistoryAction(Integer historyActionId, Integer createdById, Date createdDatetime, Date crc,
			String recordStatus, Set pnEnvelopeHistories) {
		this.historyActionId = historyActionId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	@Id
	@Column(name = "HISTORY_ACTION_ID", nullable = false)
	public Integer getHistoryActionId() {
		return this.historyActionId;
	}

	public void setHistoryActionId(Integer historyActionId) {
		this.historyActionId = historyActionId;
	}

	@Column(name = "ACTION_NAME", length = 80)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "ACTION_DESCRIPTION", length = 500)
	public String getActionDescription() {
		return this.actionDescription;
	}

	public void setActionDescription(String actionDescription) {
		this.actionDescription = actionDescription;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnEnvelopeHistoryAction", targetEntity = PnEnvelopeHistory.class)
	@Transient
	public Set getPnEnvelopeHistories() {
		return this.pnEnvelopeHistories;
	}

	public void setPnEnvelopeHistories(Set pnEnvelopeHistories) {
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	public String toString() {
		return new ToStringBuilder(this).append("historyActionId", getHistoryActionId()).toString();
	}

}
