/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnEnvelopeHistory generated by hbm2java
 */
@Entity
@Table(name="PN_ENVELOPE_HISTORY"
)
public class PnEnvelopeHistory  implements java.io.Serializable {

	/** identifier field */
    private PnEnvelopeHistoryPK comp_id;
     
    /** persistent field */
    private Integer actionById;

    /** persistent field */
    private Date actionDatetime;

    /** persistent field */
    private Date crc;

    /** persistent field */
    private String recordStatus;

    /** nullable persistent field */
    private PnWorkflowEnvelope pnWorkflowEnvelope;
     
    private PnEnvelopeHistoryAction pnEnvelopeHistoryAction;
    
    private PnEnvelopeHistoryClob pnEnvelopeHistoryClob;

    public PnEnvelopeHistory() {
    }

	
    public PnEnvelopeHistory(PnEnvelopeHistoryPK comp_id, Integer actionById, Date actionDatetime, Date crc, String recordStatus) {
        this.comp_id = comp_id;
        this.actionById = actionById;
        this.actionDatetime = actionDatetime;
        this.crc = crc;
        this.recordStatus = recordStatus;
    }
    public PnEnvelopeHistory(PnEnvelopeHistoryPK comp_id, Integer actionById, Date actionDatetime, Date crc, String recordStatus, PnWorkflowEnvelope pnWorkflowEnvelope, PnEnvelopeHistoryAction pnEnvelopeHistoryAction, PnEnvelopeHistoryClob pnEnvelopeHistoryClob) {
       this.comp_id = comp_id;
       this.actionById = actionById;
       this.actionDatetime = actionDatetime;
       this.crc = crc;
       this.recordStatus = recordStatus;
       this.pnWorkflowEnvelope = pnWorkflowEnvelope;
       this.pnEnvelopeHistoryAction = pnEnvelopeHistoryAction;
       this.pnEnvelopeHistoryClob = pnEnvelopeHistoryClob;
    }

    /** minimal constructor */
    public PnEnvelopeHistory(net.project.hibernate.model.PnEnvelopeHistoryPK comp_id, Integer actionById, Date actionDatetime, Date crc, String recordStatus, net.project.hibernate.model.PnEnvelopeHistoryAction pnEnvelopeHistoryAction, net.project.hibernate.model.PnEnvelopeHistoryClob pnEnvelopeHistoryClob) {
        this.comp_id = comp_id;
        this.actionById = actionById;
        this.actionDatetime = actionDatetime;
        this.crc = crc;
        this.recordStatus = recordStatus;
        this.pnEnvelopeHistoryAction = pnEnvelopeHistoryAction;
        this.pnEnvelopeHistoryClob = pnEnvelopeHistoryClob;
    }
    
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="historyId", column=@Column(name="HISTORY_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="envelopeId", column=@Column(name="ENVELOPE_ID", nullable=false, length=20) ) } )
    public PnEnvelopeHistoryPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnEnvelopeHistoryPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="ACTION_BY_ID", nullable=false, length=20)
    public Integer getActionById() {
        return this.actionById;
    }
    
    public void setActionById(Integer actionById) {
        this.actionById = actionById;
    }

    
    @Column(name="ACTION_DATETIME", nullable=false, length=7)
    public Date getActionDatetime() {
        return this.actionDatetime;
    }
    
    public void setActionDatetime(Date actionDatetime) {
        this.actionDatetime = actionDatetime;
    }

    
    @Column(name="CRC", nullable=false, length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWorkflowEnvelope.class)
    @JoinColumn(name="ENVELOPE_ID", insertable=false, updatable=false)
    public PnWorkflowEnvelope getPnWorkflowEnvelope() {
        return this.pnWorkflowEnvelope;
    }
    
    public void setPnWorkflowEnvelope(PnWorkflowEnvelope pnWorkflowEnvelope) {
        this.pnWorkflowEnvelope = pnWorkflowEnvelope;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnEnvelopeHistoryAction.class)
    @JoinColumn(name="HISTORY_ACTION_ID")
    public PnEnvelopeHistoryAction getPnEnvelopeHistoryAction() {
        return this.pnEnvelopeHistoryAction;
    }
    
    public void setPnEnvelopeHistoryAction(PnEnvelopeHistoryAction pnEnvelopeHistoryAction) {
        this.pnEnvelopeHistoryAction = pnEnvelopeHistoryAction;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity=PnEnvelopeHistoryClob.class)
    @JoinColumn(name="HISTORY_MESSAGE_ID")
    public PnEnvelopeHistoryClob getPnEnvelopeHistoryClob() {
        return this.pnEnvelopeHistoryClob;
    }
    
    public void setPnEnvelopeHistoryClob(PnEnvelopeHistoryClob pnEnvelopeHistoryClob) {
        this.pnEnvelopeHistoryClob = pnEnvelopeHistoryClob;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnEnvelopeHistory) ) return false;
        PnEnvelopeHistory castOther = (PnEnvelopeHistory) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }
}


