/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnFormsHistory generated by hbm2java
 */
@Entity
@Table(name = "PN_FORMS_HISTORY")
public class PnFormsHistory implements java.io.Serializable {

	/** identifier field */
	private PnFormsHistoryPK comp_id;

	/** nullable persistent field */
	private String actionComment;

	/** nullable persistent field */
	private Date actionDate;

	/** nullable persistent field */
	private String actionName;

	/** nullable persistent field */
	private PnObject pnObject;

	/** persistent field */
	private PnPerson pnPerson;

	/** persistent field */
	private PnFormsActionLookup pnFormsActionLookup;

	public PnFormsHistory() {
	}

	public PnFormsHistory(PnFormsHistoryPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnFormsHistory(PnFormsHistoryPK comp_id, String actionComment, Date actionDate, String actionName,
			PnObject pnObject, PnPerson pnPerson, PnFormsActionLookup pnFormsActionLookup) {
		this.comp_id = comp_id;
		this.actionComment = actionComment;
		this.actionDate = actionDate;
		this.actionName = actionName;
		this.pnObject = pnObject;
		this.pnPerson = pnPerson;
		this.pnFormsActionLookup = pnFormsActionLookup;
	}

	/** minimal constructor */
	public PnFormsHistory(net.project.hibernate.model.PnFormsHistoryPK comp_id,
			net.project.hibernate.model.PnPerson pnPerson,
			net.project.hibernate.model.PnFormsActionLookup pnFormsActionLookup) {
		this.comp_id = comp_id;
		this.pnPerson = pnPerson;
		this.pnFormsActionLookup = pnFormsActionLookup;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "objectId", column = @Column(name = "OBJECT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "formsHistoryId", column = @Column(name = "FORMS_HISTORY_ID", nullable = false, length = 20)) })
	public PnFormsHistoryPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnFormsHistoryPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "ACTION_COMMENT")
	public String getActionComment() {
		return this.actionComment;
	}

	public void setActionComment(String actionComment) {
		this.actionComment = actionComment;
	}

	@Column(name = "ACTION_DATE", length = 7)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Column(name = "ACTION_NAME", length = 80)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name = "OBJECT_ID", insertable = false, updatable = false)
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "ACTION_BY_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnFormsActionLookup.class)
	@JoinColumn(name = "ACTION")
	public PnFormsActionLookup getPnFormsActionLookup() {
		return this.pnFormsActionLookup;
	}

	public void setPnFormsActionLookup(PnFormsActionLookup pnFormsActionLookup) {
		this.pnFormsActionLookup = pnFormsActionLookup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnFormsHistory))
			return false;
		PnFormsHistory castOther = (PnFormsHistory) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
