/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnGroupType generated by hbm2java
 */
@Entity
@Table(name = "PN_GROUP_TYPE")
public class PnGroupType implements java.io.Serializable {

	/** identifier field */
	private Integer groupTypeId;

	/** persistent field */
	private String className;

	/** persistent field */
	private Set pnGroups = new HashSet(0);

	public PnGroupType() {
	}

	public PnGroupType(Integer groupTypeId) {
		this.groupTypeId = groupTypeId;
	}

	public PnGroupType(Integer groupTypeId, String className) {
		this.groupTypeId = groupTypeId;
		this.className = className;
	}

	public PnGroupType(Integer groupTypeId, String className, Set pnGroups) {
		this.groupTypeId = groupTypeId;
		this.className = className;
		this.pnGroups = pnGroups;
	}

	@Id
	@Column(name = "GROUP_TYPE_ID", nullable = false)
	public Integer getGroupTypeId() {
		return this.groupTypeId;
	}

	public void setGroupTypeId(Integer groupTypeId) {
		this.groupTypeId = groupTypeId;
	}

	@Column(name = "CLASS_NAME", nullable = false, length = 1000)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnGroupType", targetEntity = PnGroup.class)
	@Transient
	public Set getPnGroups() {
		return this.pnGroups;
	}

	public void setPnGroups(Set pnGroups) {
		this.pnGroups = pnGroups;
	}

	public String toString() {
		return new ToStringBuilder(this).append("groupTypeId", getGroupTypeId()).toString();
	}
}
