/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnJavaErrorLog generated by hbm2java
 */
@Entity
@Table(name = "PN_JAVA_ERROR_LOG")
public class PnJavaErrorLog implements java.io.Serializable {

	/** identifier field */
	private PnJavaErrorLogPK comp_id;

	public PnJavaErrorLog() {
	}

	public PnJavaErrorLog(PnJavaErrorLogPK comp_id) {
		this.comp_id = comp_id;
	}
	
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "errorDate", column = @Column(name = "ERROR_DATE", nullable = false, length = 7)),
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "errorName", column = @Column(name = "ERROR_NAME", nullable = false)),
			@AttributeOverride(name = "errorMessage", column = @Column(name = "ERROR_MESSAGE", nullable = false, length = 4000)),
			@AttributeOverride(name = "stackTrace", column = @Column(name = "STACK_TRACE", nullable = false, length = 4000)),
			@AttributeOverride(name = "severity", column = @Column(name = "SEVERITY", nullable = false, length = 80)) })
	public PnJavaErrorLogPK getComp_id() {
		return comp_id;
	}

	public void setComp_id(PnJavaErrorLogPK comp_id) {
		this.comp_id = comp_id;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

}
