/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;
// Generated Jun 13, 2009 11:41:49 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLdapConfigurationContext generated by hbm2java
 */
@Entity
@Table(name="PN_LDAP_CONFIGURATION_CONTEXT"
)
public class PnLdapConfigurationContext  implements java.io.Serializable {

    /** identifier field */
    private Integer contextId;

    /** persistent field */
    private String protocol;

    /** persistent field */
    private String host;

    /** persistent field */
    private String port;

    /** persistent field */
    private String searchBase;

    /** persistent field */
    private String authenticationMethod;

    /** nullable persistent field */
    private String authenticatedUserDn;

    /** nullable persistent field */
    private String authenticatedUserPassword;

    /** nullable persistent field */
    private String description;

    public PnLdapConfigurationContext() {
    }

    public PnLdapConfigurationContext(Integer contextId, String protocol, String host, String port, String searchBase, String authenticationMethod) {
        this.contextId = contextId;
        this.protocol = protocol;
        this.host = host;
        this.port = port;
        this.searchBase = searchBase;
        this.authenticationMethod = authenticationMethod;
    }
    
    public PnLdapConfigurationContext(Integer contextId, String protocol, String host, String port, String searchBase, String authenticationMethod, String authenticatedUserDn, String authenticatedUserPassword, String description) {
       this.contextId = contextId;
       this.protocol = protocol;
       this.host = host;
       this.port = port;
       this.searchBase = searchBase;
       this.authenticationMethod = authenticationMethod;
       this.authenticatedUserDn = authenticatedUserDn;
       this.authenticatedUserPassword = authenticatedUserPassword;
       this.description = description;
    }
   
    @Id 
    @Column(name="CONTEXT_ID", nullable=false)
    public Integer getContextId() {
        return this.contextId;
    }
    
    public void setContextId(Integer contextId) {
        this.contextId = contextId;
    }

    @Column(name="PROTOCOL", nullable=false, length=20)
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    
    @Column(name="HOST", nullable=false, length=120)
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }

    
    @Column(name="PORT", nullable=false, length=20)
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }

    @Column(name="SEARCH_BASE", nullable=false, length=500)
    public String getSearchBase() {
        return this.searchBase;
    }
    
    public void setSearchBase(String searchBase) {
        this.searchBase = searchBase;
    }
    
    @Column(name="AUTHENTICATION_METHOD", nullable=false, length=20)
    public String getAuthenticationMethod() {
        return this.authenticationMethod;
    }
    
    public void setAuthenticationMethod(String authenticationMethod) {
        this.authenticationMethod = authenticationMethod;
    }

    @Column(name="AUTHENTICATED_USER_DN", length=500)
    public String getAuthenticatedUserDn() {
        return this.authenticatedUserDn;
    }
    
    public void setAuthenticatedUserDn(String authenticatedUserDn) {
        this.authenticatedUserDn = authenticatedUserDn;
    }

    @Column(name="AUTHENTICATED_USER_PASSWORD", length=240)
    public String getAuthenticatedUserPassword() {
        return this.authenticatedUserPassword;
    }
    
    public void setAuthenticatedUserPassword(String authenticatedUserPassword) {
        this.authenticatedUserPassword = authenticatedUserPassword;
    }

    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("contextId", getContextId())
            .toString();
    }

}


