/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLicense generated by hbm2java
 */
@Entity
@Table(name = "PN_LICENSE")
public class PnLicense implements java.io.Serializable {

	private Integer licenseId;

	private String licenseKeyValue;

	private int isTrial;

	private Integer licenseStatus;

	private PnLicenseCertificate pnLicenseCertificate;

	private PnPerson pnPerson;

	private PnLicenseStatusReason pnLicenseStatusReason;

	private Set pnBills = new HashSet(0);

	private PnLicensePurchaser pnLicensePurchaser;

	private Set pnPersonHasLicenses = new HashSet(0);

	private PnPaymentInformation pnPaymentInformation;

	public PnLicense() {
	}

	public PnLicense(Integer licenseId, String licenseKeyValue, int isTrial) {
		this.licenseId = licenseId;
		this.licenseKeyValue = licenseKeyValue;
		this.isTrial = isTrial;
	}

	public PnLicense(Integer licenseId, String licenseKeyValue, int isTrial, Integer licenseStatus,
			PnLicenseCertificate pnLicenseCertificate, PnPerson pnPerson, PnLicenseStatusReason pnLicenseStatusReason,
			Set pnBills, PnLicensePurchaser pnLicensePurchaser, Set pnPersonHasLicenses,
			PnPaymentInformation pnPaymentInformation) {
		this.licenseId = licenseId;
		this.licenseKeyValue = licenseKeyValue;
		this.isTrial = isTrial;
		this.licenseStatus = licenseStatus;
		this.pnLicenseCertificate = pnLicenseCertificate;
		this.pnPerson = pnPerson;
		this.pnLicenseStatusReason = pnLicenseStatusReason;
		this.pnBills = pnBills;
		this.pnLicensePurchaser = pnLicensePurchaser;
		this.pnPersonHasLicenses = pnPersonHasLicenses;
		this.pnPaymentInformation = pnPaymentInformation;
	}

	/** minimal constructor */
	public PnLicense(Integer licenseId, String licenseKeyValue, int isTrial,
			net.project.hibernate.model.PnLicenseCertificate pnLicenseCertificate,
			net.project.hibernate.model.PnPerson pnPerson,
			net.project.hibernate.model.PnLicenseStatusReason pnLicenseStatusReason,
			net.project.hibernate.model.PnPaymentInformation pnPaymentInformation, Set pnBills, Set pnPersonHasLicenses) {
		this.licenseId = licenseId;
		this.licenseKeyValue = licenseKeyValue;
		this.isTrial = isTrial;
		this.pnLicenseCertificate = pnLicenseCertificate;
		this.pnPerson = pnPerson;
		this.pnLicenseStatusReason = pnLicenseStatusReason;
		this.pnPaymentInformation = pnPaymentInformation;
		this.pnBills = pnBills;
		this.pnPersonHasLicenses = pnPersonHasLicenses;
	}

	@Id
	@Column(name = "LICENSE_ID", nullable = false)
	public Integer getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Integer licenseId) {
		this.licenseId = licenseId;
	}

	@Column(name = "LICENSE_KEY_VALUE", nullable = false, length = 100)
	public String getLicenseKeyValue() {
		return this.licenseKeyValue;
	}

	public void setLicenseKeyValue(String licenseKeyValue) {
		this.licenseKeyValue = licenseKeyValue;
	}

	@Column(name = "IS_TRIAL", nullable = false, length = 1)
	public int getIsTrial() {
		return this.isTrial;
	}

	public void setIsTrial(int isTrial) {
		this.isTrial = isTrial;
	}

	@Column(name = "LICENSE_STATUS", length = 3)
	public Integer getLicenseStatus() {
		return this.licenseStatus;
	}

	public void setLicenseStatus(Integer licenseStatus) {
		this.licenseStatus = licenseStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnLicenseCertificate.class)
	@JoinColumn(name = "CERTIFICATE_ID")
	public PnLicenseCertificate getPnLicenseCertificate() {
		return this.pnLicenseCertificate;
	}

	public void setPnLicenseCertificate(PnLicenseCertificate pnLicenseCertificate) {
		this.pnLicenseCertificate = pnLicenseCertificate;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "RESPONSIBLE_USER_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnLicenseStatusReason.class)
	@JoinColumn(name = "STATUS_REASON_CODE")
	public PnLicenseStatusReason getPnLicenseStatusReason() {
		return this.pnLicenseStatusReason;
	}

	public void setPnLicenseStatusReason(PnLicenseStatusReason pnLicenseStatusReason) {
		this.pnLicenseStatusReason = pnLicenseStatusReason;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnLicense", targetEntity = PnBill.class)
	@Transient
	public Set getPnBills() {
		return this.pnBills;
	}

	public void setPnBills(Set pnBills) {
		this.pnBills = pnBills;
	}

	@OneToOne(fetch = FetchType.LAZY, targetEntity = PnLicensePurchaser.class)
	public PnLicensePurchaser getPnLicensePurchaser() {
		return this.pnLicensePurchaser;
	}

	public void setPnLicensePurchaser(PnLicensePurchaser pnLicensePurchaser) {
		this.pnLicensePurchaser = pnLicensePurchaser;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnLicense", targetEntity = PnPersonHasLicense.class)
	@Transient
	public Set getPnPersonHasLicenses() {
		return this.pnPersonHasLicenses;
	}

	public void setPnPersonHasLicenses(Set pnPersonHasLicenses) {
		this.pnPersonHasLicenses = pnPersonHasLicenses;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPaymentInformation.class)
	@JoinColumn(name = "PAYMENT_ID")
	public PnPaymentInformation getPnPaymentInformation() {
		return this.pnPaymentInformation;
	}

	public void setPnPaymentInformation(PnPaymentInformation pnPaymentInformation) {
		this.pnPaymentInformation = pnPaymentInformation;
	}

	public String toString() {
		return new ToStringBuilder(this).append("licenseId", getLicenseId()).toString();
	}

}
