/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnLicenseStatusReason generated by hbm2java
 */
@Entity
@Table(name = "PN_LICENSE_STATUS_REASONS")
public class PnLicenseStatusReason implements java.io.Serializable {

	/** identifier field */
	private Integer reasonCode;

	/** persistent field */
	private String shortName;

	/** persistent field */
	private String message;

	private Set pnLicenses = new HashSet(0);

	public PnLicenseStatusReason() {
	}

	public PnLicenseStatusReason(Integer reasonCode, String shortName, String message) {
		this.reasonCode = reasonCode;
		this.shortName = shortName;
		this.message = message;
	}

	public PnLicenseStatusReason(Integer reasonCode, String shortName, String message, Set pnLicenses) {
		this.reasonCode = reasonCode;
		this.shortName = shortName;
		this.message = message;
		this.pnLicenses = pnLicenses;
	}

	@Id
	@Column(name = "REASON_CODE", nullable = false)
	public Integer getReasonCode() {
		return this.reasonCode;
	}

	public void setReasonCode(Integer reasonCode) {
		this.reasonCode = reasonCode;
	}

	@Column(name = "SHORT_NAME", nullable = false, length = 200)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "MESSAGE", nullable = false, length = 1000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnLicenseStatusReason", targetEntity = PnLicense.class)
	@Transient
	public Set getPnLicenses() {
		return this.pnLicenses;
	}

	public void setPnLicenses(Set pnLicenses) {
		this.pnLicenses = pnLicenses;
	}

	public String toString() {
		return new ToStringBuilder(this).append("reasonCode", getReasonCode()).toString();
	}

}
