/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnMethodologyInIndustryPK generated by hbm2java
 */
@Embeddable
public class PnMethodologyInIndustryPK  implements java.io.Serializable {

    /** identifier field */
    private Integer industryId;

    /** identifier field */
    private Integer methodologyId;

    public PnMethodologyInIndustryPK() {
    }

    public PnMethodologyInIndustryPK(Integer industryId, Integer methodologyId) {
       this.industryId = industryId;
       this.methodologyId = methodologyId;
    }

    @Column(name="INDUSTRY_ID", nullable=false, length=20)
    public Integer getIndustryId() {
        return this.industryId;
    }
    
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    @Column(name="METHODOLOGY_ID", nullable=false, length=20)
    public Integer getMethodologyId() {
        return this.methodologyId;
    }
    
    public void setMethodologyId(Integer methodologyId) {
        this.methodologyId = methodologyId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("industryId", getIndustryId())
            .append("methodologyId", getMethodologyId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnMethodologyInIndustryPK) ) return false;
        PnMethodologyInIndustryPK castOther = (PnMethodologyInIndustryPK) other;
        return new EqualsBuilder()
            .append(this.getIndustryId(), castOther.getIndustryId())
            .append(this.getMethodologyId(), castOther.getMethodologyId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getIndustryId())
            .append(getMethodologyId())
            .toHashCode();
    }

}
