/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnModuleHasObjectType generated by hbm2java
 */
@Entity
@Table(name = "PN_MODULE_HAS_OBJECT_TYPE")
public class PnModuleHasObjectType implements Serializable {

	private PnModuleHasObjectTypePK comp_id;

	private int isOwner;

	private PnModule pnModule;

	private PnObjectType pnObjectType;

	public PnModuleHasObjectType() {
	}

	public PnModuleHasObjectType(PnModuleHasObjectTypePK comp_id, int isOwner) {
		this.comp_id = comp_id;
		this.isOwner = isOwner;
	}

	public PnModuleHasObjectType(PnModuleHasObjectTypePK comp_id, int isOwner, PnModule pnModule,
			PnObjectType pnObjectType) {
		this.comp_id = comp_id;
		this.isOwner = isOwner;
		this.pnModule = pnModule;
		this.pnObjectType = pnObjectType;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "moduleId", column = @Column(name = "MODULE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "objectType", column = @Column(name = "OBJECT_TYPE", nullable = false, length = 80)) })
	public PnModuleHasObjectTypePK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnModuleHasObjectTypePK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "IS_OWNER", nullable = false, length = 1)
	public int getIsOwner() {
		return this.isOwner;
	}

	public void setIsOwner(int isOwner) {
		this.isOwner = isOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnModule.class)
	@JoinColumn(name = "MODULE_ID", insertable = false, updatable = false)
	public PnModule getPnModule() {
		return this.pnModule;
	}

	public void setPnModule(PnModule pnModule) {
		this.pnModule = pnModule;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnObjectType.class)
	@JoinColumn(name = "OBJECT_TYPE", insertable = false, updatable = false)
	public PnObjectType getPnObjectType() {
		return this.pnObjectType;
	}

	public void setPnObjectType(PnObjectType pnObjectType) {
		this.pnObjectType = pnObjectType;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnModuleHasObjectType))
			return false;
		PnModuleHasObjectType castOther = (PnModuleHasObjectType) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
