/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnNewsHistoryPK generated by hbm2java
 */
@Embeddable
public class PnNewsHistoryPK implements Serializable {

     private Integer newsId;
     private Integer newsHistoryId;

    public PnNewsHistoryPK() {
    }

    public PnNewsHistoryPK(Integer newsId, Integer newsHistoryId) {
       this.newsId = newsId;
       this.newsHistoryId = newsHistoryId;
    }
   
    @Column(name="NEWS_ID", nullable=false, length=20)
    public Integer getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    @Column(name="NEWS_HISTORY_ID", nullable=false, length=20)
    public Integer getNewsHistoryId() {
        return this.newsHistoryId;
    }
    
    public void setNewsHistoryId(Integer newsHistoryId) {
        this.newsHistoryId = newsHistoryId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("newsId", getNewsId())
            .append("newsHistoryId", getNewsHistoryId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnNewsHistoryPK) ) return false;
        PnNewsHistoryPK castOther = (PnNewsHistoryPK) other;
        return new EqualsBuilder()
            .append(this.getNewsId(), castOther.getNewsId())
            .append(this.getNewsHistoryId(), castOther.getNewsHistoryId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getNewsId())
            .append(getNewsHistoryId())
            .toHashCode();
    }

}
