/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnNewsView generated by hbm2java
 */
@Entity
@Table(name = "PN_NEWS_VIEW")
public class PnNewsView implements Serializable {

	private BigDecimal spaceId;

	private BigDecimal newsId;

	private String topic;

	private Clob messageClob;

	private BigDecimal priorityId;

	private String priorityName;

	private String priorityDescription;

	private BigDecimal notificationId;

	private BigDecimal postedById;

	private Date postedDatetime;

	private String postedByFullName;

	private BigDecimal createdById;

	private Date createdDatetime;

	private String createdByFullName;

	private BigDecimal modifiedById;

	private Date modifiedDatetime;

	private String modifiedByFullName;

	private Date crc;

	private String recordStatus;

	public PnNewsView() {
	}

	public PnNewsView(BigDecimal newsId, String topic, String recordStatus) {
		this.newsId = newsId;
		this.topic = topic;
		this.recordStatus = recordStatus;
	}

	public PnNewsView(BigDecimal spaceId, BigDecimal newsId, String topic, Clob messageClob, BigDecimal priorityId,
			String priorityName, String priorityDescription, BigDecimal notificationId, BigDecimal postedById,
			Date postedDatetime, String postedByFullName, BigDecimal createdById, Date createdDatetime,
			String createdByFullName, BigDecimal modifiedById, Date modifiedDatetime, String modifiedByFullName,
			Date crc, String recordStatus) {
		this.spaceId = spaceId;
		this.newsId = newsId;
		this.topic = topic;
		this.messageClob = messageClob;
		this.priorityId = priorityId;
		this.priorityName = priorityName;
		this.priorityDescription = priorityDescription;
		this.notificationId = notificationId;
		this.postedById = postedById;
		this.postedDatetime = postedDatetime;
		this.postedByFullName = postedByFullName;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.createdByFullName = createdByFullName;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.modifiedByFullName = modifiedByFullName;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	@Column(name = "SPACE_ID", nullable = false, length = 20)
	public BigDecimal getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(BigDecimal spaceId) {
		this.spaceId = spaceId;
	}

	@Id
	@Column(name = "NEWS_ID", nullable = false, length = 20)
	public BigDecimal getNewsId() {
		return this.newsId;
	}

	public void setNewsId(BigDecimal newsId) {
		this.newsId = newsId;
	}

	@Column(name = "TOPIC", nullable = false, length = 80)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Column(name = "MESSAGE_CLOB", nullable = false, length = 4000)
	public Clob getMessageClob() {
		return this.messageClob;
	}

	public void setMessageClob(Clob messageClob) {
		this.messageClob = messageClob;
	}

	@Column(name = "PRIORITY_ID", nullable = false, length = 20)
	public BigDecimal getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(BigDecimal priorityId) {
		this.priorityId = priorityId;
	}

	@Column(name = "PRIORITY_NAME", nullable = false, length = 80)
	public String getPriorityName() {
		return this.priorityName;
	}

	public void setPriorityName(String priorityName) {
		this.priorityName = priorityName;
	}

	@Column(name = "PRIORITY_DESCRIPTION", nullable = false, length = 80)
	public String getPriorityDescription() {
		return this.priorityDescription;
	}

	public void setPriorityDescription(String priorityDescription) {
		this.priorityDescription = priorityDescription;
	}

	@Column(name = "NOTIFICATION_ID", nullable = false, length = 22)
	public BigDecimal getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(BigDecimal notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "POSTED_BY_ID", nullable = false, length = 20)
	public BigDecimal getPostedById() {
		return this.postedById;
	}

	public void setPostedById(BigDecimal postedById) {
		this.postedById = postedById;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "POSTED_DATETIME", nullable = false, length = 7)
	public Date getPostedDatetime() {
		return this.postedDatetime;
	}

	public void setPostedDatetime(Date postedDatetime) {
		this.postedDatetime = postedDatetime;
	}

	@Column(name = "POSTED_BY_FULL_NAME", nullable = false, length = 240)
	public String getPostedByFullName() {
		return this.postedByFullName;
	}

	public void setPostedByFullName(String postedByFullName) {
		this.postedByFullName = postedByFullName;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public BigDecimal getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(BigDecimal createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "CREATED_BY_FULL_NAME", nullable = false, length = 240)
	public String getCreatedByFullName() {
		return this.createdByFullName;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}

	@Column(name = "MODIFIED_BY_ID", nullable = false, length = 20)
	public BigDecimal getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(BigDecimal modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATETIME", nullable = false, length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "MODIFIED_BY_FULL_NAME", nullable = false, length = 240)
	public String getModifiedByFullName() {
		return this.modifiedByFullName;
	}

	public void setModifiedByFullName(String modifiedByFullName) {
		this.modifiedByFullName = modifiedByFullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	public String toString() {
		return new ToStringBuilder(this).append("spaceId", getSpaceId()).append("newsId", getNewsId()).append("topic",
				getTopic()).append("messageClob", getMessageClob()).append("priorityId", getPriorityId()).append(
				"priorityName", getPriorityName()).append("priorityDescription", getPriorityDescription()).append(
				"notificationId", getNotificationId()).append("postedById", getPostedById()).append("postedDatetime",
				getPostedDatetime()).append("postedByFullName", getPostedByFullName()).append("createdById",
				getCreatedById()).append("createdDatetime", getCreatedDatetime()).append("createdByFullName",
				getCreatedByFullName()).append("modifiedById", getModifiedById()).append("modifiedDatetime",
				getModifiedDatetime()).append("modifiedByFullName", getModifiedByFullName()).append("crc", getCrc())
				.append("recordStatus", getRecordStatus()).toString();
	}

}
