/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnNotificationDeliveryType generated by hbm2java
 */
@Entity
@Table(name = "PN_NOTIFICATION_DELIVERY_TYPE")
public class PnNotificationDeliveryType implements Serializable {

	private Integer deliveryTypeId;

	private String name;

	private String description;

	private String recordStatus;

	private Set pnPersonNotificationAddresses = new HashSet(0);

	private Set pnDeliveryAddresses = new HashSet(0);

	private Set pnSubscriptionHasGroups = new HashSet(0);

	private Set pnNotifications = new HashSet(0);

	public PnNotificationDeliveryType() {
	}

	public PnNotificationDeliveryType(Integer deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	public PnNotificationDeliveryType(Integer deliveryTypeId, String name, Set pnPersonNotificationAddresses,
			Set pnDeliveryAddresses, Set pnSubscriptionHasGroups, Set pnNotifications) {
		this.deliveryTypeId = deliveryTypeId;
		this.name = name;
		this.pnPersonNotificationAddresses = pnPersonNotificationAddresses;
		this.pnDeliveryAddresses = pnDeliveryAddresses;
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
		this.pnNotifications = pnNotifications;
	}

	public PnNotificationDeliveryType(Integer deliveryTypeId, String name, String description, String recordStatus,
			Set pnPersonNotificationAddresses, Set pnDeliveryAddresses, Set pnSubscriptionHasGroups, Set pnNotifications) {
		this.deliveryTypeId = deliveryTypeId;
		this.name = name;
		this.description = description;
		this.recordStatus = recordStatus;
		this.pnPersonNotificationAddresses = pnPersonNotificationAddresses;
		this.pnDeliveryAddresses = pnDeliveryAddresses;
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
		this.pnNotifications = pnNotifications;
	}

	@Id
	@Column(name = "DELIVERY_TYPE_ID", nullable = false)
	public Integer getDeliveryTypeId() {
		return this.deliveryTypeId;
	}

	public void setDeliveryTypeId(Integer deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnNotificationDeliveryType", targetEntity = PnPersonNotificationAddress.class)
	@Transient
	public Set getPnPersonNotificationAddresses() {
		return this.pnPersonNotificationAddresses;
	}

	public void setPnPersonNotificationAddresses(Set pnPersonNotificationAddresses) {
		this.pnPersonNotificationAddresses = pnPersonNotificationAddresses;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnNotificationDeliveryType", targetEntity = PnDeliveryAddress.class)
	@Transient
	public Set getPnDeliveryAddresses() {
		return this.pnDeliveryAddresses;
	}

	public void setPnDeliveryAddresses(Set pnDeliveryAddresses) {
		this.pnDeliveryAddresses = pnDeliveryAddresses;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnNotificationDeliveryType", targetEntity = PnSubscriptionHasGroup.class)
	@Transient
	public Set getPnSubscriptionHasGroups() {
		return this.pnSubscriptionHasGroups;
	}

	public void setPnSubscriptionHasGroups(Set pnSubscriptionHasGroups) {
		this.pnSubscriptionHasGroups = pnSubscriptionHasGroups;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnNotificationDeliveryType", targetEntity = PnNotification.class)
	@Transient
	public Set getPnNotifications() {
		return this.pnNotifications;
	}

	public void setPnNotifications(Set pnNotifications) {
		this.pnNotifications = pnNotifications;
	}

	public String toString() {
		return new ToStringBuilder(this).append("deliveryTypeId", getDeliveryTypeId()).toString();
	}

}
