/**
 * 
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.Column;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnObjectHasChargeCodePK generated by hbm2java
 * 
 * @author Ritesh S
 *
 */
public class PnObjectHasChargeCodePK implements Serializable {

    private Integer objectId;
    private Integer spaceId;

	public PnObjectHasChargeCodePK() {
	}

	public PnObjectHasChargeCodePK(Integer objectId,Integer spaceId) {
		this.objectId = objectId;
		this.spaceId = spaceId;
	}
  
	@Column(name="OBJECT_ID", nullable=false, length=20)
	public Integer getObjectId() {
		return this.objectId;
	}
   
	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name="SPACE_ID", nullable=false, length=20)
	public Integer getSpaceId() {
		return spaceId;
	}

	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	public String toString() {
       return new ToStringBuilder(this)
           .append("objectId", getObjectId())
           .append("spaceId",getSpaceId())
           .toString();
	}

	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( !(other instanceof PnObjectHasChargeCodePK) ) return false;
		PnObjectHasChargeCodePK castOther = (PnObjectHasChargeCodePK) other;
		return new EqualsBuilder()
			.append(this.getObjectId(), castOther.getObjectId())
			.append(this.getSpaceId(), castOther.getSpaceId())
			.isEquals();
	}

	public int hashCode() {
    	return new HashCodeBuilder()
        	.append(getObjectId())
        	.append(getSpaceId())
        	.toHashCode();
	}
}
