/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPaymentInformation generated by hbm2java
 */
@Entity
@Table(name = "PN_PAYMENT_INFORMATION")
public class PnPaymentInformation implements Serializable {

	private Integer paymentId;

	private Integer partyId;

	private Set pnBills = new HashSet(0);

	private Set pnCcTransactionPayments = new HashSet(0);

	private Set pnLicenses = new HashSet(0);

	private Set pnLedgers = new HashSet(0);

	private PnPaymentModel pnPaymentModel;

	public PnPaymentInformation() {
	}

	public PnPaymentInformation(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public PnPaymentInformation(Integer paymentId, net.project.hibernate.model.PnPaymentModel pnPaymentModel,
			Set pnBills, Set pnCcTransactionPayments, Set pnLicenses, Set pnLedgers) {
		this.paymentId = paymentId;
		this.pnPaymentModel = pnPaymentModel;
		this.pnBills = pnBills;
		this.pnCcTransactionPayments = pnCcTransactionPayments;
		this.pnLicenses = pnLicenses;
		this.pnLedgers = pnLedgers;
	}

	public PnPaymentInformation(Integer paymentId, Integer partyId,
			net.project.hibernate.model.PnPaymentModel pnPaymentModel, Set pnBills, Set pnCcTransactionPayments,
			Set pnLicenses, Set pnLedgers) {
		this.paymentId = paymentId;
		this.partyId = partyId;
		this.pnPaymentModel = pnPaymentModel;
		this.pnBills = pnBills;
		this.pnCcTransactionPayments = pnCcTransactionPayments;
		this.pnLicenses = pnLicenses;
		this.pnLedgers = pnLedgers;
	}

	@Id
	@Column(name = "PAYMENT_ID", nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "PARTY_ID", length = 20)
	public Integer getPartyId() {
		return this.partyId;
	}

	public void setPartyId(Integer partyId) {
		this.partyId = partyId;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPaymentInformation", targetEntity = PnBill.class)
	@Transient
	public Set getPnBills() {
		return this.pnBills;
	}

	public void setPnBills(Set pnBills) {
		this.pnBills = pnBills;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPaymentInformation", targetEntity = PnCcTransactionPayment.class)
	@Transient
	public Set getPnCcTransactionPayments() {
		return this.pnCcTransactionPayments;
	}

	public void setPnCcTransactionPayments(Set pnCcTransactionPayments) {
		this.pnCcTransactionPayments = pnCcTransactionPayments;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPaymentInformation", targetEntity = PnLicense.class)
	@Transient
	public Set getPnLicenses() {
		return this.pnLicenses;
	}

	public void setPnLicenses(Set pnLicenses) {
		this.pnLicenses = pnLicenses;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPaymentInformation", targetEntity = PnLedger.class)
	@Transient
	public Set getPnLedgers() {
		return this.pnLedgers;
	}

	public void setPnLedgers(Set pnLedgers) {
		this.pnLedgers = pnLedgers;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPaymentModel.class)
	@JoinColumn(name = "PAYMENT_MODEL_ID")
	public PnPaymentModel getPnPaymentModel() {
		return this.pnPaymentModel;
	}

	public void setPnPaymentModel(PnPaymentModel pnPaymentModel) {
		this.pnPaymentModel = pnPaymentModel;
	}

	public String toString() {
		return new ToStringBuilder(this).append("paymentId", getPaymentId()).toString();
	}

}
