/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * PnPersonNotificationPref generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_NOTIFICATION_PREFS")
public class PnPersonNotificationPref implements Serializable {

	private Integer personId;

	private Integer dailyTime;

	private Integer weeklyDay;

	private Integer weeklyTime;

	private PnPerson pnPerson;

	public PnPersonNotificationPref() {
	}

	public PnPersonNotificationPref(Integer personId) {
		this.personId = personId;
	}

	public PnPersonNotificationPref(Integer personId, Integer dailyTime, Integer weeklyDay, Integer weeklyTime,
			PnPerson pnPerson) {
		this.personId = personId;
		this.dailyTime = dailyTime;
		this.weeklyDay = weeklyDay;
		this.weeklyTime = weeklyTime;
		this.pnPerson = pnPerson;
	}

	@Id
	@Column(name = "PERSON_ID", nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "DAILY_TIME", length = 22)
	public Integer getDailyTime() {
		return this.dailyTime;
	}

	public void setDailyTime(Integer dailyTime) {
		this.dailyTime = dailyTime;
	}

	@Column(name = "WEEKLY_DAY", length = 22)
	public Integer getWeeklyDay() {
		return this.weeklyDay;
	}

	public void setWeeklyDay(Integer weeklyDay) {
		this.weeklyDay = weeklyDay;
	}

	@Column(name = "WEEKLY_TIME", length = 22)
	public Integer getWeeklyTime() {
		return this.weeklyTime;
	}

	public void setWeeklyTime(Integer weeklyTime) {
		this.weeklyTime = weeklyTime;
	}

	@OneToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).toString();
	}

}
