/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPersonView generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_VIEW")
public class PnPersonView implements Serializable {

	private BigDecimal personId;

	private String email;

	private String alternateEmail1;

	private String alternateEmail2;

	private String alternateEmail3;

	private String firstName;

	private String lastName;

	private String displayName;

	private String prefixName;

	private String middleName;

	private String secondLastName;

	private String suffixName;

	private String userStatus;

	private String recordStatus;

	private BigDecimal addressId;

	private String companyName;

	private String companyDivision;

	private Integer jobDescriptionCode;

	private String localeCode;

	private String languageCode;

	private String timezoneCode;

	private BigDecimal membershipPortfolioId;

	private String personalSpaceName;

	private String verificationCode;

	private BigDecimal hasLicense;

	public PnPersonView() {
	}

	public PnPersonView(BigDecimal personId, String email, String alternateEmail1, String alternateEmail2,
			String alternateEmail3, String firstName, String lastName, String displayName, String prefixName,
			String middleName, String secondLastName, String suffixName, String userStatus, String recordStatus,
			BigDecimal addressId, String companyName, String companyDivision, Integer jobDescriptionCode,
			String localeCode, String languageCode, String timezoneCode, BigDecimal membershipPortfolioId,
			String personalSpaceName, String verificationCode, BigDecimal hasLicense) {
		this.personId = personId;
		this.email = email;
		this.alternateEmail1 = alternateEmail1;
		this.alternateEmail2 = alternateEmail2;
		this.alternateEmail3 = alternateEmail3;
		this.firstName = firstName;
		this.lastName = lastName;
		this.displayName = displayName;
		this.prefixName = prefixName;
		this.middleName = middleName;
		this.secondLastName = secondLastName;
		this.suffixName = suffixName;
		this.userStatus = userStatus;
		this.recordStatus = recordStatus;
		this.addressId = addressId;
		this.companyName = companyName;
		this.companyDivision = companyDivision;
		this.jobDescriptionCode = jobDescriptionCode;
		this.localeCode = localeCode;
		this.languageCode = languageCode;
		this.timezoneCode = timezoneCode;
		this.membershipPortfolioId = membershipPortfolioId;
		this.personalSpaceName = personalSpaceName;
		this.verificationCode = verificationCode;
		this.hasLicense = hasLicense;
	}

	@Id
	@Column(name = "PERSON_ID", nullable = false, length = 20)
	public BigDecimal getPersonId() {
		return this.personId;
	}

	public void setPersonId(BigDecimal personId) {
		this.personId = personId;
	}

	@Column(name = "EMAIL", nullable = false, length = 240)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ALTERNATE_EMAIL_1", nullable = false, length = 240)
	public String getAlternateEmail1() {
		return this.alternateEmail1;
	}

	public void setAlternateEmail1(String alternateEmail1) {
		this.alternateEmail1 = alternateEmail1;
	}

	@Column(name = "ALTERNATE_EMAIL_2", nullable = false, length = 240)
	public String getAlternateEmail2() {
		return this.alternateEmail2;
	}

	public void setAlternateEmail2(String alternateEmail2) {
		this.alternateEmail2 = alternateEmail2;
	}

	@Column(name = "ALTERNATE_EMAIL_3", nullable = false, length = 240)
	public String getAlternateEmail3() {
		return this.alternateEmail3;
	}

	public void setAlternateEmail3(String alternateEmail3) {
		this.alternateEmail3 = alternateEmail3;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 40)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 60)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "DISPLAY_NAME", nullable = false, length = 240)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "PREFIX_NAME", nullable = false, length = 80)
	public String getPrefixName() {
		return this.prefixName;
	}

	public void setPrefixName(String prefixName) {
		this.prefixName = prefixName;
	}

	@Column(name = "MIDDLE_NAME", nullable = false, length = 80)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "SECOND_LAST_NAME", nullable = false, length = 80)
	public String getSecondLastName() {
		return this.secondLastName;
	}

	public void setSecondLastName(String secondLastName) {
		this.secondLastName = secondLastName;
	}

	@Column(name = "SUFFIX_NAME", nullable = false, length = 80)
	public String getSuffixName() {
		return this.suffixName;
	}

	public void setSuffixName(String suffixName) {
		this.suffixName = suffixName;
	}

	@Column(name = "USER_STATUS", nullable = false, length = 80)
	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "ADDRESS_ID", nullable = false, length = 20)
	public BigDecimal getAddressId() {
		return this.addressId;
	}

	public void setAddressId(BigDecimal addressId) {
		this.addressId = addressId;
	}

	@Column(name = "COMPANY_NAME", nullable = false, length = 120)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "COMPANY_DIVISION", nullable = false, length = 120)
	public String getCompanyDivision() {
		return this.companyDivision;
	}

	public void setCompanyDivision(String companyDivision) {
		this.companyDivision = companyDivision;
	}

	@Column(name = "JOB_DESCRIPTION_CODE", nullable = false, length = 4)
	public Integer getJobDescriptionCode() {
		return this.jobDescriptionCode;
	}

	public void setJobDescriptionCode(Integer jobDescriptionCode) {
		this.jobDescriptionCode = jobDescriptionCode;
	}

	@Column(name = "LOCALE_CODE", nullable = false, length = 20)
	public String getLocaleCode() {
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	@Column(name = "LANGUAGE_CODE", nullable = false, length = 80)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "TIMEZONE_CODE", nullable = false, length = 60)
	public String getTimezoneCode() {
		return this.timezoneCode;
	}

	public void setTimezoneCode(String timezoneCode) {
		this.timezoneCode = timezoneCode;
	}

	@Column(name = "MEMBERSHIP_PORTFOLIO_ID", nullable = false, length = 20)
	public BigDecimal getMembershipPortfolioId() {
		return this.membershipPortfolioId;
	}

	public void setMembershipPortfolioId(BigDecimal membershipPortfolioId) {
		this.membershipPortfolioId = membershipPortfolioId;
	}

	@Column(name = "PERSONAL_SPACE_NAME", nullable = false, length = 240)
	public String getPersonalSpaceName() {
		return this.personalSpaceName;
	}

	public void setPersonalSpaceName(String personalSpaceName) {
		this.personalSpaceName = personalSpaceName;
	}

	@Column(name = "VERIFICATION_CODE", nullable = false, length = 80)
	public String getVerificationCode() {
		return this.verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Column(name = "HAS_LICENSE", nullable = false, length = 22)
	public BigDecimal getHasLicense() {
		return this.hasLicense;
	}

	public void setHasLicense(BigDecimal hasLicense) {
		this.hasLicense = hasLicense;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).append("email", getEmail()).append(
				"alternateEmail1", getAlternateEmail1()).append("alternateEmail2", getAlternateEmail2()).append(
				"alternateEmail3", getAlternateEmail3()).append("firstName", getFirstName()).append("lastName",
				getLastName()).append("displayName", getDisplayName()).append("prefixName", getPrefixName()).append(
				"middleName", getMiddleName()).append("secondLastName", getSecondLastName()).append("suffixName",
				getSuffixName()).append("userStatus", getUserStatus()).append("recordStatus", getRecordStatus())
				.append("addressId", getAddressId()).append("companyName", getCompanyName()).append("companyDivision",
						getCompanyDivision()).append("jobDescriptionCode", getJobDescriptionCode()).append(
						"localeCode", getLocaleCode()).append("languageCode", getLanguageCode()).append("timezoneCode",
						getTimezoneCode()).append("membershipPortfolioId", getMembershipPortfolioId()).append(
						"personalSpaceName", getPersonalSpaceName()).append("verificationCode", getVerificationCode())
				.append("hasLicense", getHasLicense()).toString();
	}

}
