/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnPersonHasStateReg generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_HAS_STATE_REG")
public class PnPersonHasStateReg implements Serializable {

	private PnPersonHasStateRegPK comp_id;

	private String otherRegState;

	private PnPerson pnPerson;

	private PnStateLookup pnStateLookup;

	public PnPersonHasStateReg() {
	}

	public PnPersonHasStateReg(PnPersonHasStateRegPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnPersonHasStateReg(PnPersonHasStateRegPK comp_id, String otherRegState, PnPerson pnPerson,
			PnStateLookup pnStateLookup) {
		this.comp_id = comp_id;
		this.otherRegState = otherRegState;
		this.pnPerson = pnPerson;
		this.pnStateLookup = pnStateLookup;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "stateCode", column = @Column(name = "STATE_CODE", nullable = false, length = 2)) })
	public PnPersonHasStateRegPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnPersonHasStateRegPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "OTHER_REG_STATE", length = 20)
	public String getOtherRegState() {
		return this.otherRegState;
	}

	public void setOtherRegState(String otherRegState) {
		this.otherRegState = otherRegState;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID", insertable = false, updatable = false)
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnStateLookup.class)
	@JoinColumn(name = "STATE_CODE", insertable = false, updatable = false)
	public PnStateLookup getPnStateLookup() {
		return this.pnStateLookup;
	}

	public void setPnStateLookup(PnStateLookup pnStateLookup) {
		this.pnStateLookup = pnStateLookup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnPersonHasStateReg))
			return false;
		PnPersonHasStateReg castOther = (PnPersonHasStateReg) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
