/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPersonSurvey generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_SURVEY")
public class PnPersonSurvey implements Serializable {

	private Integer personId;

	private String spamAllowed;

	private String spamMethod;

	private String modelvistaSource;

	private String previousBentleyExp;

	private String referralPage;

	private PnPerson pnPerson;

	private Set pnPersonPicksSpams = new HashSet(0);

	public PnPersonSurvey() {
	}

	public PnPersonSurvey(Integer personId, String spamAllowed, String modelvistaSource, String previousBentleyExp,
			String referralPage) {
		this.personId = personId;
		this.spamAllowed = spamAllowed;
		this.modelvistaSource = modelvistaSource;
		this.previousBentleyExp = previousBentleyExp;
		this.referralPage = referralPage;
	}

	public PnPersonSurvey(Integer personId, String spamAllowed, String modelvistaSource, String previousBentleyExp,
			String referralPage, Set pnPersonPicksSpams) {
		this.personId = personId;
		this.spamAllowed = spamAllowed;
		this.modelvistaSource = modelvistaSource;
		this.previousBentleyExp = previousBentleyExp;
		this.referralPage = referralPage;
		this.pnPersonPicksSpams = pnPersonPicksSpams;
	}

	public PnPersonSurvey(Integer personId, String spamAllowed, String spamMethod, String modelvistaSource,
			String previousBentleyExp, String referralPage, PnPerson pnPerson, Set pnPersonPicksSpams) {
		this.personId = personId;
		this.spamAllowed = spamAllowed;
		this.spamMethod = spamMethod;
		this.modelvistaSource = modelvistaSource;
		this.previousBentleyExp = previousBentleyExp;
		this.referralPage = referralPage;
		this.pnPerson = pnPerson;
		this.pnPersonPicksSpams = pnPersonPicksSpams;
	}

	@Id
	@Column(name = "PERSON_ID", nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "SPAM_ALLOWED", nullable = false, length = 1)
	public String getSpamAllowed() {
		return this.spamAllowed;
	}

	public void setSpamAllowed(String spamAllowed) {
		this.spamAllowed = spamAllowed;
	}

	@Column(name = "SPAM_METHOD", length = 20)
	public String getSpamMethod() {
		return this.spamMethod;
	}

	public void setSpamMethod(String spamMethod) {
		this.spamMethod = spamMethod;
	}

	@Column(name = "MODELVISTA_SOURCE", nullable = false, length = 20)
	public String getModelvistaSource() {
		return this.modelvistaSource;
	}

	public void setModelvistaSource(String modelvistaSource) {
		this.modelvistaSource = modelvistaSource;
	}

	@Column(name = "PREVIOUS_BENTLEY_EXP", nullable = false, length = 1)
	public String getPreviousBentleyExp() {
		return this.previousBentleyExp;
	}

	public void setPreviousBentleyExp(String previousBentleyExp) {
		this.previousBentleyExp = previousBentleyExp;
	}

	@Column(name = "REFERRAL_PAGE", nullable = false, length = 240)
	public String getReferralPage() {
		return this.referralPage;
	}

	public void setReferralPage(String referralPage) {
		this.referralPage = referralPage;
	}

	@OneToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPersonSurvey", targetEntity = PnPersonPicksSpam.class)
	@Transient
	public Set getPnPersonPicksSpams() {
		return this.pnPersonPicksSpams;
	}

	public void setPnPersonPicksSpams(Set pnPersonPicksSpams) {
		this.pnPersonPicksSpams = pnPersonPicksSpams;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).toString();
	}

}
