/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * PnPersonNotificationAddress generated by hbm2java
 */
@Entity
@Table(name = "PN_PERSON_NOTIFICATION_ADDRESS")
public class PnPersonNotificationAddress implements Serializable {

	private Integer personId;

	private String deliveryAddress;

	private Integer isDefault;

	private PnPerson pnPerson;

	private PnNotificationDeliveryType pnNotificationDeliveryType;

	public PnPersonNotificationAddress() {
	}

	public PnPersonNotificationAddress(Integer personId, String deliveryAddress) {
		this.personId = personId;
		this.deliveryAddress = deliveryAddress;
	}

	public PnPersonNotificationAddress(Integer personId, String deliveryAddress,
			net.project.hibernate.model.PnNotificationDeliveryType pnNotificationDeliveryType) {
		this.personId = personId;
		this.deliveryAddress = deliveryAddress;
		this.pnNotificationDeliveryType = pnNotificationDeliveryType;
	}

	public PnPersonNotificationAddress(Integer personId, Integer deliveryTypeId, String deliveryAddress,
			Integer isDefault) {
		this.personId = personId;
		this.deliveryAddress = deliveryAddress;
		PnNotificationDeliveryType pnNotificationDeliveryTypeNew = new PnNotificationDeliveryType(deliveryTypeId);
		this.pnNotificationDeliveryType = pnNotificationDeliveryTypeNew;
		this.isDefault = isDefault;
	}

	public PnPersonNotificationAddress(Integer personId, String deliveryAddress, Integer isDefault, PnPerson pnPerson,
			PnNotificationDeliveryType pnNotificationDeliveryType) {
		this.personId = personId;
		this.deliveryAddress = deliveryAddress;
		this.isDefault = isDefault;
		this.pnPerson = pnPerson;
		this.pnNotificationDeliveryType = pnNotificationDeliveryType;
	}

	@Id
	@Column(name = "PERSON_ID", nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "DELIVERY_ADDRESS", nullable = false, length = 240)
	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "IS_DEFAULT", length = 1)
	public Integer getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

	@OneToOne(fetch = FetchType.LAZY, targetEntity = PnPerson.class)
	@JoinColumn(name = "PERSON_ID")
	public PnPerson getPnPerson() {
		return this.pnPerson;
	}

	public void setPnPerson(PnPerson pnPerson) {
		this.pnPerson = pnPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnNotificationDeliveryType.class)
	@JoinColumn(name = "DELIVERY_TYPE_ID")
	public PnNotificationDeliveryType getPnNotificationDeliveryType() {
		return this.pnNotificationDeliveryType;
	}

	public void setPnNotificationDeliveryType(PnNotificationDeliveryType pnNotificationDeliveryType) {
		this.pnNotificationDeliveryType = pnNotificationDeliveryType;
	}

	public String toString() {
		return new ToStringBuilder(this).append("personId", getPersonId()).toString();
	}

}
