/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PnPersonCosts generated by hbm2java
 */
@Entity
@Table(name="PN_PERSON_COSTS"
)
public class PnPersonCosts implements Serializable {


     private BigInteger personId;
     private BigInteger rateTable;
     private BigInteger spaceId;
     private BigDecimal costPerUse;
     private BigDecimal overtimeRate;
     private BigInteger overtimeRateFormat;
     private Date ratesFrom;
     private Date ratesTo;
     private BigDecimal standardRate;
     private BigInteger standardRateFormat;

    public PnPersonCosts() {
    }

	
    public PnPersonCosts(BigInteger personId, BigInteger rateTable) {
        this.personId = personId;
        this.rateTable = rateTable;
    }

	public PnPersonCosts(BigInteger id, BigInteger personId, BigInteger spaceId, BigDecimal costPerUse, BigDecimal overtimeRate, BigInteger overtimeRateFormat, Date ratesFrom, Date ratesTo, BigInteger rateTable, BigDecimal standardRate, BigInteger standardRateFormat) {
		this.personId = id;
		this.personId = personId;
		this.spaceId = spaceId;
		this.costPerUse = costPerUse;
		this.overtimeRate = overtimeRate;
		this.overtimeRateFormat = overtimeRateFormat;
		this.ratesFrom = ratesFrom;
		this.ratesTo = ratesTo;
		this.rateTable = rateTable;
		this.standardRate = standardRate;
		this.standardRateFormat = standardRateFormat;
	}
    
    @Column(name="PERSONID", nullable=false, length=20)
    public BigInteger getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(BigInteger personId) {
        this.personId = personId;
    }

    @Column(name="RATETABLE", nullable=false, length=20)
    public BigInteger getRateTable() {
        return this.rateTable;
    }
    
    public void setRateTable(BigInteger rateTable) {
        this.rateTable = rateTable;
    }

    @Column(name="SPACEID", length=20)
    public BigInteger getSpaceId() {
        return this.spaceId;
    }
    
    public void setSpaceId(BigInteger spaceId) {
        this.spaceId = spaceId;
    }

    @Column(name="COSTPERUSE", length=20)
    public BigDecimal getCostPerUse() {
        return this.costPerUse;
    }
    
    public void setCostPerUse(BigDecimal costPerUse) {
        this.costPerUse = costPerUse;
    }

    @Column(name="OVERTIMERATE", length=20)
    public BigDecimal getOvertimeRate() {
        return this.overtimeRate;
    }
    
    public void setOvertimeRate(BigDecimal overtimeRate) {
        this.overtimeRate = overtimeRate;
    }

    @Column(name="OVERTIMERATEFORMAT", length=20)
    public BigInteger getOvertimeRateFormat() {
        return this.overtimeRateFormat;
    }
    
    public void setOvertimeRateFormat(BigInteger overtimeRateFormat) {
        this.overtimeRateFormat = overtimeRateFormat;
    }

    @Column(name="RATESFROM", length=20)
    public Date getRatesFrom() {
        return this.ratesFrom;
    }
    
    public void setRatesFrom(Date ratesFrom) {
        this.ratesFrom = ratesFrom;
    }

    @Column(name="RATESTO", length=20)
    public Date getRatesTo() {
        return this.ratesTo;
    }
    
    public void setRatesTo(Date ratesTo) {
        this.ratesTo = ratesTo;
    }

    @Column(name="STANDARDRATE", length=20)
    public BigDecimal getStandardRate() {
        return this.standardRate;
    }
    
    public void setStandardRate(BigDecimal standardRate) {
        this.standardRate = standardRate;
    }

    @Column(name="STANDARDRATEFORMAT", length=20)
    public BigInteger getStandardRateFormat() {
        return this.standardRateFormat;
    }
    
    public void setStandardRateFormat(BigInteger standardRateFormat) {
        this.standardRateFormat = standardRateFormat;
    }

	@Override
	public boolean equals(Object obj) {
		if(!(obj instanceof PnPersonCosts))
			return false;
		else
			return (((PnPersonCosts) obj).getPersonId() == this.getPersonId()) && 
			(((PnPersonCosts) obj).getRateTable() == this.getRateTable());
	}
}
