/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPhaseHasTaskPK generated by hbm2java
 */
@Embeddable
public class PnPhaseHasTaskPK implements Serializable {


     private Integer phaseId;
     private Integer taskId;

    public PnPhaseHasTaskPK() {
    }

    public PnPhaseHasTaskPK(Integer phaseId, Integer taskId) {
       this.phaseId = phaseId;
       this.taskId = taskId;
    }
   
    @Column(name="PHASE_ID", nullable=false, length=20)
    public Integer getPhaseId() {
        return this.phaseId;
    }
    
    public void setPhaseId(Integer phaseId) {
        this.phaseId = phaseId;
    }


    @Column(name="TASK_ID", nullable=false, length=20)
    public Integer getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("phaseId", getPhaseId())
            .append("taskId", getTaskId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPhaseHasTaskPK) ) return false;
        PnPhaseHasTaskPK castOther = (PnPhaseHasTaskPK) other;
        return new EqualsBuilder()
            .append(this.getPhaseId(), castOther.getPhaseId())
            .append(this.getTaskId(), castOther.getTaskId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getPhaseId())
            .append(getTaskId())
            .toHashCode();
    }

}
