/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPhase generated by hbm2java
 */
@Entity
@Table(name = "PN_PHASE")
public class PnPhase implements Serializable {

	private Integer phaseId;

	private String phaseName;

	private String phaseDesc;

	private Date startDate;

	private Date endDate;

	private Integer sequence;

	private Integer statusId;

	private Integer enteredPercentComplete;

	private String recordStatus;

	private String progressReportingMethod;

	private PnObject pnObject;

	private PnProcess pnProcess;

	private Set pnGates = new HashSet(0);

	private Set pnProcesses = new HashSet(0);

	private Set pnPhaseHasTasks = new HashSet(0);

	private Set pnPhaseHasDeliverables = new HashSet(0);

	public PnPhase() {
	}

	public PnPhase(Integer phaseId, String phaseName, Integer sequence, Integer statusId, String recordStatus,
			String progressReportingMethod) {
		this.phaseId = phaseId;
		this.phaseName = phaseName;
		this.sequence = sequence;
		this.statusId = statusId;
		this.recordStatus = recordStatus;
		this.progressReportingMethod = progressReportingMethod;
	}

	public PnPhase(Integer phaseId, String phaseName, Integer sequence, Integer statusId, String recordStatus,
			String progressReportingMethod, net.project.hibernate.model.PnProcess pnProcess, Set pnGates,
			Set pnProcesses, Set pnPhaseHasTasks, Set pnPhaseHasDeliverables) {
		this.phaseId = phaseId;
		this.phaseName = phaseName;
		this.sequence = sequence;
		this.statusId = statusId;
		this.recordStatus = recordStatus;
		this.progressReportingMethod = progressReportingMethod;
		this.pnProcess = pnProcess;
		this.pnGates = pnGates;
		this.pnProcesses = pnProcesses;
		this.pnPhaseHasTasks = pnPhaseHasTasks;
		this.pnPhaseHasDeliverables = pnPhaseHasDeliverables;
	}

	public PnPhase(Integer phaseId, String phaseName, String phaseDesc, Date startDate, Date endDate, Integer sequence,
			Integer statusId, Integer enteredPercentComplete, String recordStatus, String progressReportingMethod,
			PnObject pnObject, PnProcess pnProcess, Set pnGates, Set pnProcesses, Set pnPhaseHasTasks,
			Set pnPhaseHasDeliverables) {
		this.phaseId = phaseId;
		this.phaseName = phaseName;
		this.phaseDesc = phaseDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.sequence = sequence;
		this.statusId = statusId;
		this.enteredPercentComplete = enteredPercentComplete;
		this.recordStatus = recordStatus;
		this.progressReportingMethod = progressReportingMethod;
		this.pnObject = pnObject;
		this.pnProcess = pnProcess;
		this.pnGates = pnGates;
		this.pnProcesses = pnProcesses;
		this.pnPhaseHasTasks = pnPhaseHasTasks;
		this.pnPhaseHasDeliverables = pnPhaseHasDeliverables;
	}

	@Id
	@Column(name = "PHASE_ID", nullable = false)
	public Integer getPhaseId() {
		return this.phaseId;
	}

	public void setPhaseId(Integer phaseId) {
		this.phaseId = phaseId;
	}

	@Column(name = "PHASE_NAME", nullable = false, length = 80)
	public String getPhaseName() {
		return this.phaseName;
	}

	public void setPhaseName(String phaseName) {
		this.phaseName = phaseName;
	}

	@Column(name = "PHASE_DESC", length = 4000)
	public String getPhaseDesc() {
		return this.phaseDesc;
	}

	public void setPhaseDesc(String phaseDesc) {
		this.phaseDesc = phaseDesc;
	}

	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "SEQUENCE", nullable = false, length = 22)
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Column(name = "STATUS_ID", nullable = false, length = 20)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "ENTERED_PERCENT_COMPLETE", length = 22)
	public Integer getEnteredPercentComplete() {
		return this.enteredPercentComplete;
	}

	public void setEnteredPercentComplete(Integer enteredPercentComplete) {
		this.enteredPercentComplete = enteredPercentComplete;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "PROGRESS_REPORTING_METHOD", nullable = false, length = 80)
	public String getProgressReportingMethod() {
		return this.progressReportingMethod;
	}

	public void setProgressReportingMethod(String progressReportingMethod) {
		this.progressReportingMethod = progressReportingMethod;
	}

	//@OneToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name="PHASE_ID")
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnProcess.class)
	@JoinColumn(name = "PROCESS_ID")
	public PnProcess getPnProcess() {
		return this.pnProcess;
	}

	public void setPnProcess(PnProcess pnProcess) {
		this.pnProcess = pnProcess;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPhase", targetEntity = PnGate.class)
	@Transient
	public Set getPnGates() {
		return this.pnGates;
	}

	public void setPnGates(Set pnGates) {
		this.pnGates = pnGates;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPhase", targetEntity = PnProcess.class)
	@Transient
	public Set getPnProcesses() {
		return this.pnProcesses;
	}

	public void setPnProcesses(Set pnProcesses) {
		this.pnProcesses = pnProcesses;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPhase", targetEntity = PnPhaseHasTask.class)
	@Transient
	public Set getPnPhaseHasTasks() {
		return this.pnPhaseHasTasks;
	}

	public void setPnPhaseHasTasks(Set pnPhaseHasTasks) {
		this.pnPhaseHasTasks = pnPhaseHasTasks;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPhase", targetEntity = PnPhaseHasDeliverable.class)
	@Transient
	public Set getPnPhaseHasDeliverables() {
		return this.pnPhaseHasDeliverables;
	}

	public void setPnPhaseHasDeliverables(Set pnPhaseHasDeliverables) {
		this.pnPhaseHasDeliverables = pnPhaseHasDeliverables;
	}

	public String toString() {
		return new ToStringBuilder(this).append("phaseId", getPhaseId()).toString();
	}

}
