/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnPhaseHasDeliverablePK generated by hbm2java
 */
@Embeddable
public class PnPhaseHasDeliverablePK implements Serializable {


     private Integer phaseId;
     private Integer deliverableId;

    public PnPhaseHasDeliverablePK() {
    }

    public PnPhaseHasDeliverablePK(Integer phaseId, Integer deliverableId) {
       this.phaseId = phaseId;
       this.deliverableId = deliverableId;
    }
   


    @Column(name="PHASE_ID", nullable=false, length=20)
    public Integer getPhaseId() {
        return this.phaseId;
    }
    
    public void setPhaseId(Integer phaseId) {
        this.phaseId = phaseId;
    }


    @Column(name="DELIVERABLE_ID", nullable=false, length=20)
    public Integer getDeliverableId() {
        return this.deliverableId;
    }
    
    public void setDeliverableId(Integer deliverableId) {
        this.deliverableId = deliverableId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("phaseId", getPhaseId())
            .append("deliverableId", getDeliverableId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPhaseHasDeliverablePK) ) return false;
        PnPhaseHasDeliverablePK castOther = (PnPhaseHasDeliverablePK) other;
        return new EqualsBuilder()
            .append(this.getPhaseId(), castOther.getPhaseId())
            .append(this.getDeliverableId(), castOther.getDeliverableId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getPhaseId())
            .append(getDeliverableId())
            .toHashCode();
    }

}
