/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPhaseHasTaskView generated by hbm2java
 */
@Entity
@Table(name="PN_PHASE_HAS_TASK_VIEW"
)
public class PnPhaseHasTaskView implements Serializable {


     private BigDecimal phaseId;
     private BigDecimal taskId;
     private String phaseRecordStatus;
     private String taskRecordStatus;

    public PnPhaseHasTaskView() {
    }

    public PnPhaseHasTaskView(BigDecimal phaseId, BigDecimal taskId, String phaseRecordStatus, String taskRecordStatus) {
       this.phaseId = phaseId;
       this.taskId = taskId;
       this.phaseRecordStatus = phaseRecordStatus;
       this.taskRecordStatus = taskRecordStatus;
    }
   
    @Id
    @Column(name="PHASE_ID", nullable=false, length=20)
    public BigDecimal getPhaseId() {
        return this.phaseId;
    }
    
    public void setPhaseId(BigDecimal phaseId) {
        this.phaseId = phaseId;
    }

    @Column(name="TASK_ID", nullable=false, length=20)
    public BigDecimal getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(BigDecimal taskId) {
        this.taskId = taskId;
    }

    @Column(name="PHASE_RECORD_STATUS", nullable=false, length=1)
    public String getPhaseRecordStatus() {
        return this.phaseRecordStatus;
    }
    
    public void setPhaseRecordStatus(String phaseRecordStatus) {
        this.phaseRecordStatus = phaseRecordStatus;
    }

    @Column(name="TASK_RECORD_STATUS", nullable=false, length=1)
    public String getTaskRecordStatus() {
        return this.taskRecordStatus;
    }
    
    public void setTaskRecordStatus(String taskRecordStatus) {
        this.taskRecordStatus = taskRecordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("phaseId", getPhaseId())
            .append("taskId", getTaskId())
            .append("phaseRecordStatus", getPhaseRecordStatus())
            .append("taskRecordStatus", getTaskRecordStatus())
            .toString();
    }

}
