/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnPlanHasTask generated by hbm2java
 */
@Entity
@Table(name = "PN_PLAN_HAS_TASK")
public class PnPlanHasTask implements Serializable {

	private PnPlanHasTaskPK comp_id;

	private PnTask pnTask;

	private PnPlan pnPlan;

	public PnPlanHasTask() {
	}

	public PnPlanHasTask(PnPlanHasTaskPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnPlanHasTask(PnPlanHasTaskPK comp_id, PnTask pnTask, PnPlan pnPlan) {
		this.comp_id = comp_id;
		this.pnTask = pnTask;
		this.pnPlan = pnPlan;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "planId", column = @Column(name = "PLAN_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "taskId", column = @Column(name = "TASK_ID", nullable = false, length = 20)) })
	public PnPlanHasTaskPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnPlanHasTaskPK comp_id) {
		this.comp_id = comp_id;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnTask.class)
	@JoinColumn(name = "TASK_ID", insertable = false, updatable = false)
	public PnTask getPnTask() {
		return this.pnTask;
	}

	public void setPnTask(PnTask pnTask) {
		this.pnTask = pnTask;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnPlan.class)
	@JoinColumn(name = "PLAN_ID", insertable = false, updatable = false)
	public PnPlan getPnPlan() {
		return this.pnPlan;
	}

	public void setPnPlan(PnPlan pnPlan) {
		this.pnPlan = pnPlan;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnPlanHasTask))
			return false;
		PnPlanHasTask castOther = (PnPlanHasTask) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
