/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPostActionLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_POST_ACTION_LOOKUP")
public class PnPostActionLookup implements Serializable {

	private String action;

	private String recordStatus;

	private Set pnPostHistories = new HashSet(0);

	public PnPostActionLookup() {
	}

	public PnPostActionLookup(String action, String recordStatus) {
		this.action = action;
		this.recordStatus = recordStatus;
	}

	public PnPostActionLookup(String action, String recordStatus, Set pnPostHistories) {
		this.action = action;
		this.recordStatus = recordStatus;
		this.pnPostHistories = pnPostHistories;
	}

	@Id
	@Column(name = "ACTION", nullable = false)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPostActionLookup", targetEntity = PnPostHistory.class)
	@Transient
	public Set getPnPostHistories() {
		return this.pnPostHistories;
	}

	public void setPnPostHistories(Set pnPostHistories) {
		this.pnPostHistories = pnPostHistories;
	}

	public String toString() {
		return new ToStringBuilder(this).append("action", getAction()).toString();
	}

}
