/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPostBodyClob generated by hbm2java
 */
@Entity
@Table(name = "PN_POST_BODY_CLOB")
public class PnPostBodyClob implements Serializable {

	private Integer objectId;

	private Clob clobField;

	private Set pnPosts = new HashSet(0);

	public PnPostBodyClob() {
	}

	public PnPostBodyClob(Integer objectId) {
		this.objectId = objectId;
	}

	public PnPostBodyClob(Integer objectId, Set pnPosts) {
		this.objectId = objectId;
		this.pnPosts = pnPosts;
	}

	public PnPostBodyClob(Integer objectId, Clob clobField, Set pnPosts) {
		this.objectId = objectId;
		this.clobField = clobField;
		this.pnPosts = pnPosts;
	}

	@Id
	@Column(name = "OBJECT_ID", nullable = false)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "CLOB_FIELD", length = 4000)
	public Clob getClobField() {
		return this.clobField;
	}

	public void setClobField(Clob clobField) {
		this.clobField = clobField;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPostBodyClob", targetEntity = PnPost.class)
	@Transient
	public Set getPnPosts() {
		return this.pnPosts;
	}

	public void setPnPosts(Set pnPosts) {
		this.pnPosts = pnPosts;
	}

	public String toString() {
		return new ToStringBuilder(this).append("objectId", getObjectId()).toString();
	}

}
