/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnPropertySheet generated by hbm2java
 */
@Entity
@Table(name = "PN_PROPERTY_SHEET")
public class PnPropertySheet implements Serializable {

	private Integer propertySheetId;

	private Integer propertyGroupId;

	private PnPropertySheetType pnPropertySheetType;

	private Set pnSpaceHasPropertySheets = new HashSet(0);

	public PnPropertySheet() {
	}

	public PnPropertySheet(Integer propertySheetId) {
		this.propertySheetId = propertySheetId;
	}

	public PnPropertySheet(Integer propertySheetId, PnPropertySheetType pnPropertySheetType, Integer propertyGroupId) {
		this.propertySheetId = propertySheetId;
		this.propertyGroupId = propertyGroupId;
		this.pnPropertySheetType = pnPropertySheetType;
	}

	public PnPropertySheet(Integer propertySheetId,
			net.project.hibernate.model.PnPropertySheetType pnPropertySheetType, Set pnSpaceHasPropertySheets) {
		this.propertySheetId = propertySheetId;
		this.pnPropertySheetType = pnPropertySheetType;
		this.pnSpaceHasPropertySheets = pnSpaceHasPropertySheets;
	}

	public PnPropertySheet(Integer propertySheetId, Integer propertyGroupId, PnPropertySheetType pnPropertySheetType,
			Set pnSpaceHasPropertySheets) {
		this.propertySheetId = propertySheetId;
		this.propertyGroupId = propertyGroupId;
		this.pnPropertySheetType = pnPropertySheetType;
		this.pnSpaceHasPropertySheets = pnSpaceHasPropertySheets;
	}

	@Id
	@Column(name = "PROPERTY_SHEET_ID", nullable = false)
	public Integer getPropertySheetId() {
		return this.propertySheetId;
	}

	public void setPropertySheetId(Integer propertySheetId) {
		this.propertySheetId = propertySheetId;
	}

	@Column(name = "PROPERTY_GROUP_ID", length = 20)
	public Integer getPropertyGroupId() {
		return this.propertyGroupId;
	}

	public void setPropertyGroupId(Integer propertyGroupId) {
		this.propertyGroupId = propertyGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnPropertySheetType.class)
	@JoinColumn(name = "PROPERTY_SHEET_TYPE")
	public PnPropertySheetType getPnPropertySheetType() {
		return this.pnPropertySheetType;
	}

	public void setPnPropertySheetType(PnPropertySheetType pnPropertySheetType) {
		this.pnPropertySheetType = pnPropertySheetType;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnPropertySheet", targetEntity = PnSpaceHasPropertySheet.class)
	@Transient
	public Set getPnSpaceHasPropertySheets() {
		return this.pnSpaceHasPropertySheets;
	}

	public void setPnSpaceHasPropertySheets(Set pnSpaceHasPropertySheets) {
		this.pnSpaceHasPropertySheets = pnSpaceHasPropertySheets;
	}

	public String toString() {
		return new ToStringBuilder(this).append("propertySheetId", getPropertySheetId()).toString();
	}

}
