/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnProjectSpaceMetaValue generated by hbm2java
 */
@Entity
@Table(name="PN_PROJECT_SPACE_META_VALUE"
)
public class PnProjectSpaceMetaValue  implements java.io.Serializable {


     private PnProjectSpaceMetaValuePK comp_id;
     private String propertyValue;
     private PnProjectSpace pnProjectSpace;
     private PnProjectSpaceMetaProp pnProjectSpaceMetaProp;

    public PnProjectSpaceMetaValue() {
    }

	
    public PnProjectSpaceMetaValue(PnProjectSpaceMetaValuePK comp_id) {
        this.comp_id = comp_id;
    }
    
    public PnProjectSpaceMetaValue(Integer projectId, Integer propertyId, String propertyValue, PnProjectSpaceMetaProp pnProjectSpaceMetaProp) {
    	PnProjectSpaceMetaValuePK compId = new PnProjectSpaceMetaValuePK(projectId, propertyId);
    	this.comp_id = compId;
    	this.propertyValue = propertyValue;
    	this.pnProjectSpaceMetaProp = pnProjectSpaceMetaProp;
        
    }

    public PnProjectSpaceMetaValue(PnProjectSpaceMetaValuePK comp_id, String propertyValue, PnProjectSpace pnProjectSpace, PnProjectSpaceMetaProp pnProjectSpaceMetaProp) {
       this.comp_id = comp_id;
       this.propertyValue = propertyValue;
       this.pnProjectSpace = pnProjectSpace;
       this.pnProjectSpaceMetaProp = pnProjectSpaceMetaProp;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="projectId", column=@Column(name="PROJECT_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="propertyId", column=@Column(name="PROPERTY_ID", nullable=false, length=20) ) } )
    public PnProjectSpaceMetaValuePK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnProjectSpaceMetaValuePK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="PROPERTY_VALUE", length=1000)
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnProjectSpace.class)
    @JoinColumn(name="PROJECT_ID", insertable=false, updatable=false)
    public PnProjectSpace getPnProjectSpace() {
        return this.pnProjectSpace;
    }
    
    public void setPnProjectSpace(PnProjectSpace pnProjectSpace) {
        this.pnProjectSpace = pnProjectSpace;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnProjectSpaceMetaProp.class)
    @JoinColumn(name="PROPERTY_ID", insertable=false, updatable=false)
    public PnProjectSpaceMetaProp getPnProjectSpaceMetaProp() {
        return this.pnProjectSpaceMetaProp;
    }
    
    public void setPnProjectSpaceMetaProp(PnProjectSpaceMetaProp pnProjectSpaceMetaProp) {
        this.pnProjectSpaceMetaProp = pnProjectSpaceMetaProp;
    }




}


