/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import net.project.gui.html.IHTMLOption;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PnProjectSpaceMetaCombo generated by hbm2java
 */
@Entity
@Table(name = "PN_PROJECT_SPACE_META_COMBO")
public class PnProjectSpaceMetaCombo implements java.io.Serializable, IHTMLOption {

	private PnProjectSpaceMetaComboPK comp_id;

	private String comboLabel;

	public PnProjectSpaceMetaCombo() {
	}

	public PnProjectSpaceMetaCombo(PnProjectSpaceMetaComboPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnProjectSpaceMetaCombo(PnProjectSpaceMetaComboPK comp_id, String comboLabel) {
		this.comp_id = comp_id;
		this.comboLabel = comboLabel;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "comboValue", column = @Column(name = "COMBO_VALUE", nullable = false, length = 500)),
			@AttributeOverride(name = "propertyId", column = @Column(name = "PROPERTY_ID", nullable = false, length = 20)) })
	public PnProjectSpaceMetaComboPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnProjectSpaceMetaComboPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "COMBO_LABEL", length = 500)
	public String getComboLabel() {
		return this.comboLabel;
	}

	public void setComboLabel(String comboLabel) {
		this.comboLabel = comboLabel;
	}

	@Transient
	public String getHtmlOptionDisplay() {
		return this.comboLabel;
	}

	@Transient
	public String getHtmlOptionValue() {
		return this.comp_id.getComboValue();
	}

}
