/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PnPropertyChange generated by hbm2java
 */
@Entity
@Table(name="PN_PROPERTY_CHANGE"
)
public class PnPropertyChange implements Serializable {


     private PnPropertyChangePK comp_id;
     private Date lastUpdatedDatetime;

    public PnPropertyChange() {
    }

    public PnPropertyChange(PnPropertyChangePK comp_id, Date lastUpdatedDatetime) {
       this.comp_id = comp_id;
       this.lastUpdatedDatetime = lastUpdatedDatetime;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="contextId", column=@Column(name="CONTEXT_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="language", column=@Column(name="LANGUAGE", nullable=false, length=2) ) } )
    public PnPropertyChangePK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnPropertyChangePK comp_id) {
        this.comp_id = comp_id;
    }

    @Column(name="LAST_UPDATED_DATETIME", nullable=false, length=7)
    public Date getLastUpdatedDatetime() {
        return this.lastUpdatedDatetime;
    }
    
    public void setLastUpdatedDatetime(Date lastUpdatedDatetime) {
        this.lastUpdatedDatetime = lastUpdatedDatetime;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnPropertyChange) ) return false;
        PnPropertyChange castOther = (PnPropertyChange) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
