/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnProjectView generated by hbm2java
 */
@Entity
@Table(name = "PN_PROJECT_VIEW")
public class PnProjectView implements Serializable {

	private BigDecimal projectId;

	private String projectName;

	private String projectDesc;

	private String percentCalculationMethod;

	private Integer percentComplete;

	private BigDecimal statusCodeId;

	private String status;

	private BigDecimal colorCodeId;

	private String color;

	private String colorImageUrl;

	private Integer isSubproject;

	private String recordStatus;

	private BigDecimal projectLogoId;

	private Date startDate;

	private Date endDate;

	private Date dateModified;

	private String defaultCurrencyCode;

	private String sponsorDesc;

	private BigDecimal improvementCodeId;

	private String currentStatusDescription;

	private BigDecimal financialStatusColorCodeId;

	private BigDecimal financialStatusImpCodeId;

	private BigDecimal budgetedTotalCostValue;

	private String budgetedTotalCostCc;

	private BigDecimal currentEstTotalCostValue;

	private String currentEstTotalCostCc;

	private BigDecimal actualToDateCostValue;

	private String actualToDateCostCc;

	private BigDecimal estimatedRoiCostValue;

	private String estimatedRoiCostCc;

	private String costCenter;

	private BigDecimal scheduleStatusColorCodeId;

	private BigDecimal scheduleStatusImpCodeId;

	private BigDecimal resourceStatusColorCodeId;

	private BigDecimal resourceStatusImpCodeId;

	private BigDecimal priorityCodeId;

	private BigDecimal riskRatingCodeId;

	private BigDecimal visibilityId;

	public PnProjectView() {
	}

	public PnProjectView(BigDecimal projectId, String projectName, String projectDesc, String percentCalculationMethod,
			Integer percentComplete, BigDecimal statusCodeId, String status, BigDecimal colorCodeId, String color,
			String colorImageUrl, Integer isSubproject, String recordStatus, BigDecimal projectLogoId, Date startDate,
			Date endDate, Date dateModified, String defaultCurrencyCode, String sponsorDesc,
			BigDecimal improvementCodeId, String currentStatusDescription, BigDecimal financialStatusColorCodeId,
			BigDecimal financialStatusImpCodeId, BigDecimal budgetedTotalCostValue, String budgetedTotalCostCc,
			BigDecimal currentEstTotalCostValue, String currentEstTotalCostCc, BigDecimal actualToDateCostValue,
			String actualToDateCostCc, BigDecimal estimatedRoiCostValue, String estimatedRoiCostCc, String costCenter,
			BigDecimal scheduleStatusColorCodeId, BigDecimal scheduleStatusImpCodeId,
			BigDecimal resourceStatusColorCodeId, BigDecimal resourceStatusImpCodeId, BigDecimal priorityCodeId,
			BigDecimal riskRatingCodeId, BigDecimal visibilityId) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.percentCalculationMethod = percentCalculationMethod;
		this.percentComplete = percentComplete;
		this.statusCodeId = statusCodeId;
		this.status = status;
		this.colorCodeId = colorCodeId;
		this.color = color;
		this.colorImageUrl = colorImageUrl;
		this.isSubproject = isSubproject;
		this.recordStatus = recordStatus;
		this.projectLogoId = projectLogoId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.dateModified = dateModified;
		this.defaultCurrencyCode = defaultCurrencyCode;
		this.sponsorDesc = sponsorDesc;
		this.improvementCodeId = improvementCodeId;
		this.currentStatusDescription = currentStatusDescription;
		this.financialStatusColorCodeId = financialStatusColorCodeId;
		this.financialStatusImpCodeId = financialStatusImpCodeId;
		this.budgetedTotalCostValue = budgetedTotalCostValue;
		this.budgetedTotalCostCc = budgetedTotalCostCc;
		this.currentEstTotalCostValue = currentEstTotalCostValue;
		this.currentEstTotalCostCc = currentEstTotalCostCc;
		this.actualToDateCostValue = actualToDateCostValue;
		this.actualToDateCostCc = actualToDateCostCc;
		this.estimatedRoiCostValue = estimatedRoiCostValue;
		this.estimatedRoiCostCc = estimatedRoiCostCc;
		this.costCenter = costCenter;
		this.scheduleStatusColorCodeId = scheduleStatusColorCodeId;
		this.scheduleStatusImpCodeId = scheduleStatusImpCodeId;
		this.resourceStatusColorCodeId = resourceStatusColorCodeId;
		this.resourceStatusImpCodeId = resourceStatusImpCodeId;
		this.priorityCodeId = priorityCodeId;
		this.riskRatingCodeId = riskRatingCodeId;
		this.visibilityId = visibilityId;
	}

	@Id
	@Column(name = "PROJECT_ID", nullable = false, length = 20)
	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	@Column(name = "PROJECT_NAME", nullable = false, length = 80)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "PROJECT_DESC", nullable = false, length = 1000)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "PERCENT_CALCULATION_METHOD", nullable = false, length = 80)
	public String getPercentCalculationMethod() {
		return this.percentCalculationMethod;
	}

	public void setPercentCalculationMethod(String percentCalculationMethod) {
		this.percentCalculationMethod = percentCalculationMethod;
	}

	@Column(name = "PERCENT_COMPLETE", nullable = false, length = 3)
	public Integer getPercentComplete() {
		return this.percentComplete;
	}

	public void setPercentComplete(Integer percentComplete) {
		this.percentComplete = percentComplete;
	}

	@Column(name = "STATUS_CODE_ID", nullable = false, length = 20)
	public BigDecimal getStatusCodeId() {
		return this.statusCodeId;
	}

	public void setStatusCodeId(BigDecimal statusCodeId) {
		this.statusCodeId = statusCodeId;
	}

	@Column(name = "STATUS", nullable = false, length = 80)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COLOR_CODE_ID", nullable = false, length = 20)
	public BigDecimal getColorCodeId() {
		return this.colorCodeId;
	}

	public void setColorCodeId(BigDecimal colorCodeId) {
		this.colorCodeId = colorCodeId;
	}

	@Column(name = "COLOR", nullable = false, length = 80)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "COLOR_IMAGE_URL", nullable = false, length = 240)
	public String getColorImageUrl() {
		return this.colorImageUrl;
	}

	public void setColorImageUrl(String colorImageUrl) {
		this.colorImageUrl = colorImageUrl;
	}

	@Column(name = "IS_SUBPROJECT", nullable = false, length = 1)
	public Integer getIsSubproject() {
		return this.isSubproject;
	}

	public void setIsSubproject(Integer isSubproject) {
		this.isSubproject = isSubproject;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "PROJECT_LOGO_ID", nullable = false, length = 20)
	public BigDecimal getProjectLogoId() {
		return this.projectLogoId;
	}

	public void setProjectLogoId(BigDecimal projectLogoId) {
		this.projectLogoId = projectLogoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MODIFIED", nullable = false, length = 7)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "DEFAULT_CURRENCY_CODE", nullable = false, length = 3)
	public String getDefaultCurrencyCode() {
		return this.defaultCurrencyCode;
	}

	public void setDefaultCurrencyCode(String defaultCurrencyCode) {
		this.defaultCurrencyCode = defaultCurrencyCode;
	}

	@Column(name = "SPONSOR_DESC", nullable = false, length = 1000)
	public String getSponsorDesc() {
		return this.sponsorDesc;
	}

	public void setSponsorDesc(String sponsorDesc) {
		this.sponsorDesc = sponsorDesc;
	}

	@Column(name = "IMPROVEMENT_CODE_ID", nullable = false, length = 20)
	public BigDecimal getImprovementCodeId() {
		return this.improvementCodeId;
	}

	public void setImprovementCodeId(BigDecimal improvementCodeId) {
		this.improvementCodeId = improvementCodeId;
	}

	@Column(name = "CURRENT_STATUS_DESCRIPTION", nullable = false, length = 4000)
	public String getCurrentStatusDescription() {
		return this.currentStatusDescription;
	}

	public void setCurrentStatusDescription(String currentStatusDescription) {
		this.currentStatusDescription = currentStatusDescription;
	}

	@Column(name = "FINANCIAL_STATUS_COLOR_CODE_ID", nullable = false, length = 20)
	public BigDecimal getFinancialStatusColorCodeId() {
		return this.financialStatusColorCodeId;
	}

	public void setFinancialStatusColorCodeId(BigDecimal financialStatusColorCodeId) {
		this.financialStatusColorCodeId = financialStatusColorCodeId;
	}

	@Column(name = "FINANCIAL_STATUS_IMP_CODE_ID", nullable = false, length = 20)
	public BigDecimal getFinancialStatusImpCodeId() {
		return this.financialStatusImpCodeId;
	}

	public void setFinancialStatusImpCodeId(BigDecimal financialStatusImpCodeId) {
		this.financialStatusImpCodeId = financialStatusImpCodeId;
	}

	@Column(name = "BUDGETED_TOTAL_COST_VALUE", nullable = false, length = 22)
	public BigDecimal getBudgetedTotalCostValue() {
		return this.budgetedTotalCostValue;
	}

	public void setBudgetedTotalCostValue(BigDecimal budgetedTotalCostValue) {
		this.budgetedTotalCostValue = budgetedTotalCostValue;
	}

	@Column(name = "BUDGETED_TOTAL_COST_CC", nullable = false, length = 3)
	public String getBudgetedTotalCostCc() {
		return this.budgetedTotalCostCc;
	}

	public void setBudgetedTotalCostCc(String budgetedTotalCostCc) {
		this.budgetedTotalCostCc = budgetedTotalCostCc;
	}

	@Column(name = "CURRENT_EST_TOTAL_COST_VALUE", nullable = false, length = 22)
	public BigDecimal getCurrentEstTotalCostValue() {
		return this.currentEstTotalCostValue;
	}

	public void setCurrentEstTotalCostValue(BigDecimal currentEstTotalCostValue) {
		this.currentEstTotalCostValue = currentEstTotalCostValue;
	}

	@Column(name = "CURRENT_EST_TOTAL_COST_CC", nullable = false, length = 3)
	public String getCurrentEstTotalCostCc() {
		return this.currentEstTotalCostCc;
	}

	public void setCurrentEstTotalCostCc(String currentEstTotalCostCc) {
		this.currentEstTotalCostCc = currentEstTotalCostCc;
	}

	@Column(name = "ACTUAL_TO_DATE_COST_VALUE", nullable = false, length = 22)
	public BigDecimal getActualToDateCostValue() {
		return this.actualToDateCostValue;
	}

	public void setActualToDateCostValue(BigDecimal actualToDateCostValue) {
		this.actualToDateCostValue = actualToDateCostValue;
	}

	@Column(name = "ACTUAL_TO_DATE_COST_CC", nullable = false, length = 3)
	public String getActualToDateCostCc() {
		return this.actualToDateCostCc;
	}

	public void setActualToDateCostCc(String actualToDateCostCc) {
		this.actualToDateCostCc = actualToDateCostCc;
	}

	@Column(name = "ESTIMATED_ROI_COST_VALUE", nullable = false, length = 22)
	public BigDecimal getEstimatedRoiCostValue() {
		return this.estimatedRoiCostValue;
	}

	public void setEstimatedRoiCostValue(BigDecimal estimatedRoiCostValue) {
		this.estimatedRoiCostValue = estimatedRoiCostValue;
	}

	@Column(name = "ESTIMATED_ROI_COST_CC", nullable = false, length = 3)
	public String getEstimatedRoiCostCc() {
		return this.estimatedRoiCostCc;
	}

	public void setEstimatedRoiCostCc(String estimatedRoiCostCc) {
		this.estimatedRoiCostCc = estimatedRoiCostCc;
	}

	@Column(name = "COST_CENTER", nullable = false, length = 1000)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "SCHEDULE_STATUS_COLOR_CODE_ID", nullable = false, length = 20)
	public BigDecimal getScheduleStatusColorCodeId() {
		return this.scheduleStatusColorCodeId;
	}

	public void setScheduleStatusColorCodeId(BigDecimal scheduleStatusColorCodeId) {
		this.scheduleStatusColorCodeId = scheduleStatusColorCodeId;
	}

	@Column(name = "SCHEDULE_STATUS_IMP_CODE_ID", nullable = false, length = 20)
	public BigDecimal getScheduleStatusImpCodeId() {
		return this.scheduleStatusImpCodeId;
	}

	public void setScheduleStatusImpCodeId(BigDecimal scheduleStatusImpCodeId) {
		this.scheduleStatusImpCodeId = scheduleStatusImpCodeId;
	}

	@Column(name = "RESOURCE_STATUS_COLOR_CODE_ID", nullable = false, length = 20)
	public BigDecimal getResourceStatusColorCodeId() {
		return this.resourceStatusColorCodeId;
	}

	public void setResourceStatusColorCodeId(BigDecimal resourceStatusColorCodeId) {
		this.resourceStatusColorCodeId = resourceStatusColorCodeId;
	}

	@Column(name = "RESOURCE_STATUS_IMP_CODE_ID", nullable = false, length = 20)
	public BigDecimal getResourceStatusImpCodeId() {
		return this.resourceStatusImpCodeId;
	}

	public void setResourceStatusImpCodeId(BigDecimal resourceStatusImpCodeId) {
		this.resourceStatusImpCodeId = resourceStatusImpCodeId;
	}

	@Column(name = "PRIORITY_CODE_ID", nullable = false, length = 20)
	public BigDecimal getPriorityCodeId() {
		return this.priorityCodeId;
	}

	public void setPriorityCodeId(BigDecimal priorityCodeId) {
		this.priorityCodeId = priorityCodeId;
	}

	@Column(name = "RISK_RATING_CODE_ID", nullable = false, length = 20)
	public BigDecimal getRiskRatingCodeId() {
		return this.riskRatingCodeId;
	}

	public void setRiskRatingCodeId(BigDecimal riskRatingCodeId) {
		this.riskRatingCodeId = riskRatingCodeId;
	}

	@Column(name = "VISIBILITY_ID", nullable = false, length = 20)
	public BigDecimal getVisibilityId() {
		return this.visibilityId;
	}

	public void setVisibilityId(BigDecimal visibilityId) {
		this.visibilityId = visibilityId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("projectId", getProjectId()).append("projectName", getProjectName())
				.append("projectDesc", getProjectDesc()).append("percentCalculationMethod",
						getPercentCalculationMethod()).append("percentComplete", getPercentComplete()).append(
						"statusCodeId", getStatusCodeId()).append("status", getStatus()).append("colorCodeId",
						getColorCodeId()).append("color", getColor()).append("colorImageUrl", getColorImageUrl())
				.append("isSubproject", getIsSubproject()).append("recordStatus", getRecordStatus()).append(
						"projectLogoId", getProjectLogoId()).append("startDate", getStartDate()).append("endDate",
						getEndDate()).append("dateModified", getDateModified()).append("defaultCurrencyCode",
						getDefaultCurrencyCode()).append("sponsorDesc", getSponsorDesc()).append("improvementCodeId",
						getImprovementCodeId()).append("currentStatusDescription", getCurrentStatusDescription())
				.append("financialStatusColorCodeId", getFinancialStatusColorCodeId()).append(
						"financialStatusImpCodeId", getFinancialStatusImpCodeId()).append("budgetedTotalCostValue",
						getBudgetedTotalCostValue()).append("budgetedTotalCostCc", getBudgetedTotalCostCc()).append(
						"currentEstTotalCostValue", getCurrentEstTotalCostValue()).append("currentEstTotalCostCc",
						getCurrentEstTotalCostCc()).append("actualToDateCostValue", getActualToDateCostValue()).append(
						"actualToDateCostCc", getActualToDateCostCc()).append("estimatedRoiCostValue",
						getEstimatedRoiCostValue()).append("estimatedRoiCostCc", getEstimatedRoiCostCc()).append(
						"costCenter", getCostCenter()).append("scheduleStatusColorCodeId",
						getScheduleStatusColorCodeId()).append("scheduleStatusImpCodeId", getScheduleStatusImpCodeId())
				.append("resourceStatusColorCodeId", getResourceStatusColorCodeId()).append("resourceStatusImpCodeId",
						getResourceStatusImpCodeId()).append("priorityCodeId", getPriorityCodeId()).append(
						"riskRatingCodeId", getRiskRatingCodeId()).append("visibilityId", getVisibilityId()).toString();
	}

}
