/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PnResourceList generated by hbm2java
 */
@Entity
@Table(name="PN_RESOURCE_LIST"
)
public class PnResourceList implements Serializable {


     private Integer id;
     private String name;
     private Integer createdBy;
     private String status;
     private Date createdDate;

    public PnResourceList() {
    }

	public PnResourceList(Integer resourceListId) {
		this.id = resourceListId;
	}
	
	public PnResourceList(Integer resourceListId, String listname) {
		this.id = resourceListId;
		this.name = listname;
	}

    public PnResourceList(String name, Integer createdBy, String status, Date createdDate) {
       this.name = name;
       this.createdBy = createdBy;
       this.status = status;
       this.createdDate = createdDate;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CREATED_BY", length=20)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="DATE_CREATED", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnResourceList) ) return false;
        PnResourceList castOther = (PnResourceList) other;
        return new EqualsBuilder()
            .append(this.id, castOther.id)
            .isEquals();
    }	
	
	@Override
	public int hashCode() {
		return new HashCodeBuilder()
		.append(getId())
		.toHashCode();
	}
	
}
