/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnScheduledSubscription generated by hbm2java
 */
@Entity
@Table(name="PN_SCHEDULED_SUBSCRIPTION"
)
public class PnScheduledSubscription implements Serializable {


     private Integer scheduledSubscriptionId;
     private String name;
     private String description;
     private Integer targetObjectId;
     private String targetObjectType;
     private String targetObjectXml;
     private Date eventTime;
     private Integer eventType;
     private Integer isQueued;
     private Date createDate;
     private Integer createdById;
     private Date modifiedDate;
     private Integer modifiedById;
     private String recordStatus;
     private Date crc;
     private Integer deliveryInterval;
     private Date deliveryDate;
     private Integer targetObjectClobId;
     private Integer batchId;
     private Integer subscriberBatchId;
     private Clob customMessageClob;
     private Integer spaceId;
     private PnPerson pnPerson;
     private PnNotificationType pnNotificationType;

    public PnScheduledSubscription() {
    }

    public PnScheduledSubscription(Integer scheduledSubscriptionId, Integer createdById, Integer modifiedById, net.project.hibernate.model.PnPerson pnPerson, net.project.hibernate.model.PnNotificationType pnNotificationType) {
        this.scheduledSubscriptionId = scheduledSubscriptionId;
        this.createdById = createdById;
        this.modifiedById = modifiedById;
        this.pnPerson = pnPerson;
        this.pnNotificationType = pnNotificationType;
    }
	

    public PnScheduledSubscription(Integer scheduledSubscriptionId, String name, String description, Integer targetObjectId, String targetObjectType, String targetObjectXml, Date eventTime, Integer eventType, Integer isQueued, Date createDate, Integer createdById, Date modifiedDate, Integer modifiedById, String recordStatus, Date crc, Integer deliveryInterval, Date deliveryDate, Integer targetObjectClobId, Integer batchId, Integer subscriberBatchId, Clob customMessageClob, Integer spaceId, PnPerson pnPerson, PnNotificationType pnNotificationType) {
       this.scheduledSubscriptionId = scheduledSubscriptionId;
       this.name = name;
       this.description = description;
       this.targetObjectId = targetObjectId;
       this.targetObjectType = targetObjectType;
       this.targetObjectXml = targetObjectXml;
       this.eventTime = eventTime;
       this.eventType = eventType;
       this.isQueued = isQueued;
       this.createDate = createDate;
       this.createdById = createdById;
       this.modifiedDate = modifiedDate;
       this.modifiedById = modifiedById;
       this.recordStatus = recordStatus;
       this.crc = crc;
       this.deliveryInterval = deliveryInterval;
       this.deliveryDate = deliveryDate;
       this.targetObjectClobId = targetObjectClobId;
       this.batchId = batchId;
       this.subscriberBatchId = subscriberBatchId;
       this.customMessageClob = customMessageClob;
       this.spaceId = spaceId;
       this.pnPerson = pnPerson;
       this.pnNotificationType = pnNotificationType;
    }
   
     @Id 
    @Column(name="SCHEDULED_SUBSCRIPTION_ID", nullable=false)
    public Integer getScheduledSubscriptionId() {
        return this.scheduledSubscriptionId;
    }
    
    public void setScheduledSubscriptionId(Integer scheduledSubscriptionId) {
        this.scheduledSubscriptionId = scheduledSubscriptionId;
    }

    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TARGET_OBJECT_ID", length=20)
    public Integer getTargetObjectId() {
        return this.targetObjectId;
    }
    
    public void setTargetObjectId(Integer targetObjectId) {
        this.targetObjectId = targetObjectId;
    }

    
    @Column(name="TARGET_OBJECT_TYPE", length=80)
    public String getTargetObjectType() {
        return this.targetObjectType;
    }
    
    public void setTargetObjectType(String targetObjectType) {
        this.targetObjectType = targetObjectType;
    }

    
    @Column(name="TARGET_OBJECT_XML", length=4000)
    public String getTargetObjectXml() {
        return this.targetObjectXml;
    }
    
    public void setTargetObjectXml(String targetObjectXml) {
        this.targetObjectXml = targetObjectXml;
    }

    
    @Column(name="EVENT_TIME", length=7)
    public Date getEventTime() {
        return this.eventTime;
    }
    
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    
    @Column(name="EVENT_TYPE", length=20)
    public Integer getEventType() {
        return this.eventType;
    }
    
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    
    @Column(name="IS_QUEUED", length=22)
    public Integer getIsQueued() {
        return this.isQueued;
    }
    
    public void setIsQueued(Integer isQueued) {
        this.isQueued = isQueued;
    }

    
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public Integer getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="MODIFIED_DATE", length=7)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="MODIFIED_BY_ID", nullable=false, length=20)
    public Integer getModifiedById() {
        return this.modifiedById;
    }
    
    public void setModifiedById(Integer modifiedById) {
        this.modifiedById = modifiedById;
    }

    
    @Column(name="RECORD_STATUS", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="CRC", length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    
    @Column(name="DELIVERY_INTERVAL", length=4)
    public Integer getDeliveryInterval() {
        return this.deliveryInterval;
    }
    
    public void setDeliveryInterval(Integer deliveryInterval) {
        this.deliveryInterval = deliveryInterval;
    }

    
    @Column(name="DELIVERY_DATE", length=7)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    
    @Column(name="TARGET_OBJECT_CLOB_ID", length=20)
    public Integer getTargetObjectClobId() {
        return this.targetObjectClobId;
    }
    
    public void setTargetObjectClobId(Integer targetObjectClobId) {
        this.targetObjectClobId = targetObjectClobId;
    }

    
    @Column(name="BATCH_ID", length=20)
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    
    @Column(name="SUBSCRIBER_BATCH_ID", length=20)
    public Integer getSubscriberBatchId() {
        return this.subscriberBatchId;
    }
    
    public void setSubscriberBatchId(Integer subscriberBatchId) {
        this.subscriberBatchId = subscriberBatchId;
    }

    
    @Column(name="CUSTOM_MESSAGE_CLOB", length=4000)
    public Clob getCustomMessageClob() {
        return this.customMessageClob;
    }
    
    public void setCustomMessageClob(Clob customMessageClob) {
        this.customMessageClob = customMessageClob;
    }

    
    @Column(name="SPACE_ID", length=20)
    public Integer getSpaceId() {
        return this.spaceId;
    }
    
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnPerson.class)
    @JoinColumn(name="INITIATOR_ID")
    public PnPerson getPnPerson() {
        return this.pnPerson;
    }
    
    public void setPnPerson(PnPerson pnPerson) {
        this.pnPerson = pnPerson;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnNotificationType.class)
    @JoinColumn(name="NOTIFICATION_TYPE_ID")
    public PnNotificationType getPnNotificationType() {
        return this.pnNotificationType;
    }
    
    public void setPnNotificationType(PnNotificationType pnNotificationType) {
        this.pnNotificationType = pnNotificationType;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("scheduledSubscriptionId", getScheduledSubscriptionId())
            .toString();
    }

}
