/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnSecurityAction generated by hbm2java
 */
@Entity
@Table(name = "PN_SECURITY_ACTION")
public class PnSecurityAction implements Serializable {

	private Integer actionId;

	private String name;

	private String description;

	private Integer bitMask;

	private Set pnObjectTypeSupportsActions = new HashSet(0);

	public PnSecurityAction() {
	}

	public PnSecurityAction(Integer actionId, String name, Integer bitMask, Set pnObjectTypeSupportsActions) {
		this.actionId = actionId;
		this.name = name;
		this.bitMask = bitMask;
		this.pnObjectTypeSupportsActions = pnObjectTypeSupportsActions;
	}

	public PnSecurityAction(Integer actionId, String name, String description, Integer bitMask,
			Set pnObjectTypeSupportsActions) {
		this.actionId = actionId;
		this.name = name;
		this.description = description;
		this.bitMask = bitMask;
		this.pnObjectTypeSupportsActions = pnObjectTypeSupportsActions;
	}

	@Id
	@Column(name = "ACTION_ID", nullable = false)
	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	@Column(name = "NAME", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "BIT_MASK", nullable = false, length = 20)
	public Integer getBitMask() {
		return this.bitMask;
	}

	public void setBitMask(Integer bitMask) {
		this.bitMask = bitMask;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnSecurityAction", targetEntity = PnObjectTypeSupportsAction.class)
	@Transient
	public Set getPnObjectTypeSupportsActions() {
		return this.pnObjectTypeSupportsActions;
	}

	public void setPnObjectTypeSupportsActions(Set pnObjectTypeSupportsActions) {
		this.pnObjectTypeSupportsActions = pnObjectTypeSupportsActions;
	}

	public String toString() {
		return new ToStringBuilder(this).append("actionId", getActionId()).toString();
	}

}
