/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnShareable generated by hbm2java
 */
@Entity
@Table(name = "PN_SHAREABLE")
public class PnShareable implements Serializable {

	private Integer objectId;

	private Integer permissionType;

	private Integer containerId;

	private Integer spaceId;

	private Integer allowableActions;

	private BigDecimal propagateToChildren;

	private PnObject pnObject;

	public PnShareable() {
	}

	public PnShareable(Integer objectId, Integer permissionType) {
		this.objectId = objectId;
		this.permissionType = permissionType;
	}

	public PnShareable(Integer objectId, Integer permissionType, Integer containerId, Integer spaceId,
			Integer allowableActions, BigDecimal propagateToChildren, PnObject pnObject) {
		this.objectId = objectId;
		this.permissionType = permissionType;
		this.containerId = containerId;
		this.spaceId = spaceId;
		this.allowableActions = allowableActions;
		this.propagateToChildren = propagateToChildren;
		this.pnObject = pnObject;
	}

	@Id
	@Column(name = "OBJECT_ID", nullable = false)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "PERMISSION_TYPE", nullable = false, length = 22)
	public Integer getPermissionType() {
		return this.permissionType;
	}

	public void setPermissionType(Integer permissionType) {
		this.permissionType = permissionType;
	}

	@Column(name = "CONTAINER_ID", length = 20)
	public Integer getContainerId() {
		return this.containerId;
	}

	public void setContainerId(Integer containerId) {
		this.containerId = containerId;
	}

	@Column(name = "SPACE_ID", length = 20)
	public Integer getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	@Column(name = "ALLOWABLE_ACTIONS", length = 20)
	public Integer getAllowableActions() {
		return this.allowableActions;
	}

	public void setAllowableActions(Integer allowableActions) {
		this.allowableActions = allowableActions;
	}

	@Column(name = "PROPAGATE_TO_CHILDREN", length = 15)
	public BigDecimal getPropagateToChildren() {
		return this.propagateToChildren;
	}

	public void setPropagateToChildren(BigDecimal propagateToChildren) {
		this.propagateToChildren = propagateToChildren;
	}

	//@OneToOne(fetch = FetchType.LAZY, targetEntity = PnObject.class)
	//@JoinColumn(name="OBJECT_ID")
	@Transient
	public PnObject getPnObject() {
		return this.pnObject;
	}

	public void setPnObject(PnObject pnObject) {
		this.pnObject = pnObject;
	}

	public String toString() {
		return new ToStringBuilder(this).append("objectId", getObjectId()).toString();
	}

}
