/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnSharedFormsVisibility generated by hbm2java
 */
@Entity
@Table(name = "PN_SHARED_FORMS_VISIBLITY")
public class PnSharedFormsVisibility implements Serializable {

	private PnSharedFormsVisibilityPK comp_id;

	private String childIds;

	private PnClass pnClass;

	public PnSharedFormsVisibility() {
	}

	public PnSharedFormsVisibility(PnSharedFormsVisibilityPK comp_id) {
		this.comp_id = comp_id;
	}

	public PnSharedFormsVisibility(PnSharedFormsVisibilityPK comp_id, String childIds, PnClass pnClass) {
		this.comp_id = comp_id;
		this.childIds = childIds;
		this.pnClass = pnClass;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "spaceId", column = @Column(name = "SPACE_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "classId", column = @Column(name = "CLASS_ID", nullable = false, length = 20)) })
	public PnSharedFormsVisibilityPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnSharedFormsVisibilityPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "CHILD_IDS", length = 1000)
	public String getChildIds() {
		return this.childIds;
	}

	public void setChildIds(String childIds) {
		this.childIds = childIds;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnClass.class)
	@JoinColumn(name = "CLASS_ID", insertable = false, updatable = false)
	public PnClass getPnClass() {
		return this.pnClass;
	}

	public void setPnClass(PnClass pnClass) {
		this.pnClass = pnClass;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnSharedFormsVisibility))
			return false;
		PnSharedFormsVisibility castOther = (PnSharedFormsVisibility) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}
}
