/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnSpaceView generated by hbm2java
 */
@Entity
@Table(name="PN_SPACE_VIEW"
)
public class PnSpaceView implements Serializable {


     private BigDecimal spaceId;
     private String spaceName;
     private String spaceDesc;
     private String spaceType;
     private String recordStatus;
     private String parentSpaceName;

    public PnSpaceView() {
    }

    public PnSpaceView(BigDecimal spaceId, String spaceName, String spaceDesc, String spaceType, String recordStatus, String parentSpaceName) {
       this.spaceId = spaceId;
       this.spaceName = spaceName;
       this.spaceDesc = spaceDesc;
       this.spaceType = spaceType;
       this.recordStatus = recordStatus;
       this.parentSpaceName = parentSpaceName;
    }
   

    @Id
    @Column(name="SPACE_ID", nullable=false, length=22)
    public BigDecimal getSpaceId() {
        return this.spaceId;
    }
    
    public void setSpaceId(BigDecimal spaceId) {
        this.spaceId = spaceId;
    }

    
    @Column(name="SPACE_NAME", nullable=false, length=240)
    public String getSpaceName() {
        return this.spaceName;
    }
    
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName;
    }

    
    @Column(name="SPACE_DESC", nullable=false, length=1000)
    public String getSpaceDesc() {
        return this.spaceDesc;
    }
    
    public void setSpaceDesc(String spaceDesc) {
        this.spaceDesc = spaceDesc;
    }

    
    @Column(name="SPACE_TYPE", nullable=false, length=13)
    public String getSpaceType() {
        return this.spaceType;
    }
    
    public void setSpaceType(String spaceType) {
        this.spaceType = spaceType;
    }

    
    @Column(name="RECORD_STATUS", nullable=false, length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="PARENT_SPACE_NAME", nullable=false, length=80)
    public String getParentSpaceName() {
        return this.parentSpaceName;
    }
    
    public void setParentSpaceName(String parentSpaceName) {
        this.parentSpaceName = parentSpaceName;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("spaceId", getSpaceId())
            .append("spaceName", getSpaceName())
            .append("spaceDesc", getSpaceDesc())
            .append("spaceType", getSpaceType())
            .append("recordStatus", getRecordStatus())
            .append("parentSpaceName", getParentSpaceName())
            .toString();
    }

}
