/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnStateLookup generated by hbm2java
 */
@Entity
@Table(name = "PN_STATE_LOOKUP")
public class PnStateLookup implements Serializable {

	private String stateCode;

	private String stateName;

	private Set pnSpaceHasWeathers = new HashSet(0);

	private Set pnPersonHasStateRegs = new HashSet(0);

	private PnCountryLookup pnCountryLookup;

	public PnStateLookup() {
	}

	public PnStateLookup(String stateCode, String stateName) {
		this.stateCode = stateCode;
		this.stateName = stateName;
	}

	public PnStateLookup(String stateCode, String stateName,
			net.project.hibernate.model.PnCountryLookup pnCountryLookup, Set pnSpaceHasWeathers,
			Set pnPersonHasStateRegs) {
		this.stateCode = stateCode;
		this.stateName = stateName;
		this.pnCountryLookup = pnCountryLookup;
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
		this.pnPersonHasStateRegs = pnPersonHasStateRegs;
	}

	@Id
	@Column(name = "STATE_CODE", nullable = false)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "STATE_NAME", nullable = false, length = 80)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnStateLookup", targetEntity = PnSpaceHasWeather.class)
	@Transient
	public Set getPnSpaceHasWeathers() {
		return this.pnSpaceHasWeathers;
	}

	public void setPnSpaceHasWeathers(Set pnSpaceHasWeathers) {
		this.pnSpaceHasWeathers = pnSpaceHasWeathers;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnStateLookup", targetEntity = PnPersonHasStateReg.class)
	@Transient
	public Set getPnPersonHasStateRegs() {
		return this.pnPersonHasStateRegs;
	}

	public void setPnPersonHasStateRegs(Set pnPersonHasStateRegs) {
		this.pnPersonHasStateRegs = pnPersonHasStateRegs;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnCountryLookup.class)
	@JoinColumn(name = "COUNTRY_CODE")
	public PnCountryLookup getPnCountryLookup() {
		return this.pnCountryLookup;
	}

	public void setPnCountryLookup(PnCountryLookup pnCountryLookup) {
		this.pnCountryLookup = pnCountryLookup;
	}

	public String toString() {
		return new ToStringBuilder(this).append("stateCode", getStateCode()).toString();
	}

}
