/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnSubscriptionRecurrence generated by hbm2java
 */
@Entity
@Table(name="PN_SUBSCRIPTION_RECURRENCE"
)
public class PnSubscriptionRecurrence implements Serializable {


     private Integer recurrenceId;
     private String name;
     private String description;
     private String recordStatus;
     private Date crc;

    public PnSubscriptionRecurrence() {
    }
	
    public PnSubscriptionRecurrence(Integer recurrenceId) {
        this.recurrenceId = recurrenceId;
    }

    public PnSubscriptionRecurrence(Integer recurrenceId, String name, String description, String recordStatus, Date crc) {
       this.recurrenceId = recurrenceId;
       this.name = name;
       this.description = description;
       this.recordStatus = recordStatus;
       this.crc = crc;
    }
   
     @Id 
    @Column(name="RECURRENCE_ID", nullable=false)
    public Integer getRecurrenceId() {
        return this.recurrenceId;
    }
    
    public void setRecurrenceId(Integer recurrenceId) {
        this.recurrenceId = recurrenceId;
    }

    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="RECORD_STATUS", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    
    @Column(name="CRC", length=7)
    public Date getCrc() {
        return this.crc;
    }
    
    public void setCrc(Date crc) {
        this.crc = crc;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("recurrenceId", getRecurrenceId())
            .toString();
    }

}
