/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PnSubHasNotifyType generated by hbm2java
 */
@Entity
@Table(name="PN_SUB_HAS_NOTIFY_TYPE"
)
public class PnSubHasNotifyType implements Serializable {


     private PnSubHasNotifyTypePK comp_id;
     private PnSubscription pnSubscription;
     private PnNotificationType pnNotificationType;

    public PnSubHasNotifyType() {
    }

	
    public PnSubHasNotifyType(PnSubHasNotifyTypePK comp_id) {
        this.comp_id = comp_id;
    }

    public PnSubHasNotifyType(PnSubHasNotifyTypePK comp_id, PnSubscription pnSubscription, PnNotificationType pnNotificationType) {
       this.comp_id = comp_id;
       this.pnSubscription = pnSubscription;
       this.pnNotificationType = pnNotificationType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="notificationTypeId", column=@Column(name="NOTIFICATION_TYPE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="subscriptionId", column=@Column(name="SUBSCRIPTION_ID", nullable=false, length=20) ) } )
    public PnSubHasNotifyTypePK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnSubHasNotifyTypePK comp_id) {
        this.comp_id = comp_id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnSubscription.class)
    @JoinColumn(name="SUBSCRIPTION_ID", insertable=false, updatable=false)
    public PnSubscription getPnSubscription() {
        return this.pnSubscription;
    }
    
    public void setPnSubscription(PnSubscription pnSubscription) {
        this.pnSubscription = pnSubscription;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnNotificationType.class)
    @JoinColumn(name="NOTIFICATION_TYPE_ID", insertable=false, updatable=false)
    public PnNotificationType getPnNotificationType() {
        return this.pnNotificationType;
    }
    
    public void setPnNotificationType(PnNotificationType pnNotificationType) {
        this.pnNotificationType = pnNotificationType;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSubHasNotifyType) ) return false;
        PnSubHasNotifyType castOther = (PnSubHasNotifyType) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
