/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnSubscriptionHasGroupPK generated by hbm2java
 */
@Embeddable
public class PnSubscriptionHasGroupPK implements Serializable {


     private Integer subscriptionId;
     private Integer deliveryGroupId;

    public PnSubscriptionHasGroupPK() {
    }

    public PnSubscriptionHasGroupPK(Integer subscriptionId, Integer deliveryGroupId) {
       this.subscriptionId = subscriptionId;
       this.deliveryGroupId = deliveryGroupId;
    }
   


    @Column(name="SUBSCRIPTION_ID", nullable=false, length=20)
    public Integer getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(Integer subscriptionId) {
        this.subscriptionId = subscriptionId;
    }


    @Column(name="DELIVERY_GROUP_ID", nullable=false, length=20)
    public Integer getDeliveryGroupId() {
        return this.deliveryGroupId;
    }
    
    public void setDeliveryGroupId(Integer deliveryGroupId) {
        this.deliveryGroupId = deliveryGroupId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("subscriptionId", getSubscriptionId())
            .append("deliveryGroupId", getDeliveryGroupId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnSubscriptionHasGroupPK) ) return false;
        PnSubscriptionHasGroupPK castOther = (PnSubscriptionHasGroupPK) other;
        return new EqualsBuilder()
            .append(this.getSubscriptionId(), castOther.getSubscriptionId())
            .append(this.getDeliveryGroupId(), castOther.getDeliveryGroupId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getSubscriptionId())
            .append(getDeliveryGroupId())
            .toHashCode();
    }

}
