/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnSystemConfig generated by hbm2java
 */
@Entity
@Table(name="PN_SYSTEM_CONFIG"
)
public class PnSystemConfig implements Serializable {


     private Integer systemSpaceId;

    public PnSystemConfig() {
    }

    public PnSystemConfig(Integer systemSpaceId) {
       this.systemSpaceId = systemSpaceId;
    }
   
     @Id 
    @Column(name="SYSTEM_SPACE_ID", nullable=false)
    public Integer getSystemSpaceId() {
        return this.systemSpaceId;
    }
    
    public void setSystemSpaceId(Integer systemSpaceId) {
        this.systemSpaceId = systemSpaceId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("systemSpaceId", getSystemSpaceId())
            .toString();
    }

}
