/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnTaskComment generated by hbm2java
 */
@Entity
@Table(name="PN_TASK_COMMENT"
)
public class PnTaskComment implements Serializable {


     private PnTaskCommentPK comp_id;
     private Integer createdById;
     private Date createdDatetime;
     private Clob textClob;

    public PnTaskComment() {
    }

	
    public PnTaskComment(PnTaskCommentPK comp_id, Integer createdById, Date createdDatetime) {
        this.comp_id = comp_id;
        this.createdById = createdById;
        this.createdDatetime = createdDatetime;
    }
    public PnTaskComment(PnTaskCommentPK comp_id, Integer createdById, Date createdDatetime, Clob textClob) {
       this.comp_id = comp_id;
       this.createdById = createdById;
       this.createdDatetime = createdDatetime;
       this.textClob = textClob;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="taskId", column=@Column(name="TASK_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="baselineId", column=@Column(name="BASELINE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="seq", column=@Column(name="SEQ", nullable=false, length=20) ) } )
    public PnTaskCommentPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnTaskCommentPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="CREATED_BY_ID", nullable=false, length=20)
    public Integer getCreatedById() {
        return this.createdById;
    }
    
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    
    @Column(name="CREATED_DATETIME", nullable=false, length=7)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    
    @Column(name="TEXT_CLOB", length=4000)
    public Clob getTextClob() {
        return this.textClob;
    }
    
    public void setTextClob(Clob textClob) {
        this.textClob = textClob;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnTaskComment) ) return false;
        PnTaskComment castOther = (PnTaskComment) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
