/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnTaskCommentPK generated by hbm2java
 */
@Embeddable
public class PnTaskCommentPK implements Serializable {


     private Integer taskId;
     private Integer baselineId;
     private Integer seq;

    public PnTaskCommentPK() {
    }

    public PnTaskCommentPK(Integer taskId, Integer baselineId, Integer seq) {
       this.taskId = taskId;
       this.baselineId = baselineId;
       this.seq = seq;
    }
   


    @Column(name="TASK_ID", nullable=false, length=20)
    public Integer getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }


    @Column(name="BASELINE_ID", nullable=false, length=20)
    public Integer getBaselineId() {
        return this.baselineId;
    }
    
    public void setBaselineId(Integer baselineId) {
        this.baselineId = baselineId;
    }


    @Column(name="SEQ", nullable=false, length=20)
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("taskId", getTaskId())
            .append("baselineId", getBaselineId())
            .append("seq", getSeq())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnTaskCommentPK) ) return false;
        PnTaskCommentPK castOther = (PnTaskCommentPK) other;
        return new EqualsBuilder()
            .append(this.getTaskId(), castOther.getTaskId())
            .append(this.getBaselineId(), castOther.getBaselineId())
            .append(this.getSeq(), castOther.getSeq())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTaskId())
            .append(getBaselineId())
            .append(getSeq())
            .toHashCode();
    }

}
