/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnTmpDocument generated by hbm2java
 */
@Entity
@Table(name="PN_TMP_DOCUMENT"
)
public class PnTmpDocument implements Serializable {


     private Integer tmpDocId;
     private Integer docId;
     private Integer docVersionId;
     private String docName;
     private String docDescription;
     private Integer currentVersionId;
     private String docVersionName;
     private String verDocDescription;
     private String sourceFileName;
     private Integer modifiedById;
     private Date dateModified;
     private Integer isCheckedOut;
     private Integer checkedOutById;
     private Date dateCheckedOut;
     private String docComment;
     private String verRecordStatus;
     private Integer docContentId;
     private Integer docFormatId;
     private Integer displaySequence;
     private String contentRecordStatus;
     private Integer docVersionNum;
     private String docVersionLabel;
     private Integer fileSize;
     private String fileHandle;
     private Integer docHistoryId;
     private Integer actionId;
     private Integer actionById;
     private String actionComment;
     private String actionDesc;
     private Integer docContainerId;
     private Date checkoutDue;
     private Integer docStatusId;
     private Integer docTypeId;
     private Integer docAuthorId;
     private String shortFileName;
     private Integer repositoryId;
     private String recordStatus;

    public PnTmpDocument() {
    }

	
    public PnTmpDocument(Integer tmpDocId) {
        this.tmpDocId = tmpDocId;
    }
    public PnTmpDocument(Integer tmpDocId, Integer docId, Integer docVersionId, String docName, String docDescription, Integer currentVersionId, String docVersionName, String verDocDescription, String sourceFileName, Integer modifiedById, Date dateModified, Integer isCheckedOut, Integer checkedOutById, Date dateCheckedOut, String docComment, String verRecordStatus, Integer docContentId, Integer docFormatId, Integer displaySequence, String contentRecordStatus, Integer docVersionNum, String docVersionLabel, Integer fileSize, String fileHandle, Integer docHistoryId, Integer actionId, Integer actionById, String actionComment, String actionDesc, Integer docContainerId, Date checkoutDue, Integer docStatusId, Integer docTypeId, Integer docAuthorId, String shortFileName, Integer repositoryId, String recordStatus) {
       this.tmpDocId = tmpDocId;
       this.docId = docId;
       this.docVersionId = docVersionId;
       this.docName = docName;
       this.docDescription = docDescription;
       this.currentVersionId = currentVersionId;
       this.docVersionName = docVersionName;
       this.verDocDescription = verDocDescription;
       this.sourceFileName = sourceFileName;
       this.modifiedById = modifiedById;
       this.dateModified = dateModified;
       this.isCheckedOut = isCheckedOut;
       this.checkedOutById = checkedOutById;
       this.dateCheckedOut = dateCheckedOut;
       this.docComment = docComment;
       this.verRecordStatus = verRecordStatus;
       this.docContentId = docContentId;
       this.docFormatId = docFormatId;
       this.displaySequence = displaySequence;
       this.contentRecordStatus = contentRecordStatus;
       this.docVersionNum = docVersionNum;
       this.docVersionLabel = docVersionLabel;
       this.fileSize = fileSize;
       this.fileHandle = fileHandle;
       this.docHistoryId = docHistoryId;
       this.actionId = actionId;
       this.actionById = actionById;
       this.actionComment = actionComment;
       this.actionDesc = actionDesc;
       this.docContainerId = docContainerId;
       this.checkoutDue = checkoutDue;
       this.docStatusId = docStatusId;
       this.docTypeId = docTypeId;
       this.docAuthorId = docAuthorId;
       this.shortFileName = shortFileName;
       this.repositoryId = repositoryId;
       this.recordStatus = recordStatus;
    }
   
     @Id 

    
    @Column(name="TMP_DOC_ID", nullable=false)
    public Integer getTmpDocId() {
        return this.tmpDocId;
    }
    
    public void setTmpDocId(Integer tmpDocId) {
        this.tmpDocId = tmpDocId;
    }

    
    @Column(name="DOC_ID", length=20)
    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    
    @Column(name="DOC_VERSION_ID", length=20)
    public Integer getDocVersionId() {
        return this.docVersionId;
    }
    
    public void setDocVersionId(Integer docVersionId) {
        this.docVersionId = docVersionId;
    }

    
    @Column(name="DOC_NAME", length=240)
    public String getDocName() {
        return this.docName;
    }
    
    public void setDocName(String docName) {
        this.docName = docName;
    }

    
    @Column(name="DOC_DESCRIPTION", length=500)
    public String getDocDescription() {
        return this.docDescription;
    }
    
    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription;
    }

    
    @Column(name="CURRENT_VERSION_ID", length=20)
    public Integer getCurrentVersionId() {
        return this.currentVersionId;
    }
    
    public void setCurrentVersionId(Integer currentVersionId) {
        this.currentVersionId = currentVersionId;
    }

    
    @Column(name="DOC_VERSION_NAME", length=240)
    public String getDocVersionName() {
        return this.docVersionName;
    }
    
    public void setDocVersionName(String docVersionName) {
        this.docVersionName = docVersionName;
    }

    
    @Column(name="VER_DOC_DESCRIPTION", length=20)
    public String getVerDocDescription() {
        return this.verDocDescription;
    }
    
    public void setVerDocDescription(String verDocDescription) {
        this.verDocDescription = verDocDescription;
    }

    
    @Column(name="SOURCE_FILE_NAME", length=240)
    public String getSourceFileName() {
        return this.sourceFileName;
    }
    
    public void setSourceFileName(String sourceFileName) {
        this.sourceFileName = sourceFileName;
    }

    
    @Column(name="MODIFIED_BY_ID", length=20)
    public Integer getModifiedById() {
        return this.modifiedById;
    }
    
    public void setModifiedById(Integer modifiedById) {
        this.modifiedById = modifiedById;
    }

    
    @Column(name="DATE_MODIFIED", length=7)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="IS_CHECKED_OUT", length=1)
    public Integer getIsCheckedOut() {
        return this.isCheckedOut;
    }
    
    public void setIsCheckedOut(Integer isCheckedOut) {
        this.isCheckedOut = isCheckedOut;
    }

    
    @Column(name="CHECKED_OUT_BY_ID", length=20)
    public Integer getCheckedOutById() {
        return this.checkedOutById;
    }
    
    public void setCheckedOutById(Integer checkedOutById) {
        this.checkedOutById = checkedOutById;
    }

    
    @Column(name="DATE_CHECKED_OUT", length=7)
    public Date getDateCheckedOut() {
        return this.dateCheckedOut;
    }
    
    public void setDateCheckedOut(Date dateCheckedOut) {
        this.dateCheckedOut = dateCheckedOut;
    }

    
    @Column(name="DOC_COMMENT", length=4000)
    public String getDocComment() {
        return this.docComment;
    }
    
    public void setDocComment(String docComment) {
        this.docComment = docComment;
    }

    
    @Column(name="VER_RECORD_STATUS", length=1)
    public String getVerRecordStatus() {
        return this.verRecordStatus;
    }
    
    public void setVerRecordStatus(String verRecordStatus) {
        this.verRecordStatus = verRecordStatus;
    }

    
    @Column(name="DOC_CONTENT_ID", length=20)
    public Integer getDocContentId() {
        return this.docContentId;
    }
    
    public void setDocContentId(Integer docContentId) {
        this.docContentId = docContentId;
    }

    
    @Column(name="DOC_FORMAT_ID", length=20)
    public Integer getDocFormatId() {
        return this.docFormatId;
    }
    
    public void setDocFormatId(Integer docFormatId) {
        this.docFormatId = docFormatId;
    }

    
    @Column(name="DISPLAY_SEQUENCE", length=8)
    public Integer getDisplaySequence() {
        return this.displaySequence;
    }
    
    public void setDisplaySequence(Integer displaySequence) {
        this.displaySequence = displaySequence;
    }

    
    @Column(name="CONTENT_RECORD_STATUS", length=1)
    public String getContentRecordStatus() {
        return this.contentRecordStatus;
    }
    
    public void setContentRecordStatus(String contentRecordStatus) {
        this.contentRecordStatus = contentRecordStatus;
    }

    
    @Column(name="DOC_VERSION_NUM", length=20)
    public Integer getDocVersionNum() {
        return this.docVersionNum;
    }
    
    public void setDocVersionNum(Integer docVersionNum) {
        this.docVersionNum = docVersionNum;
    }

    
    @Column(name="DOC_VERSION_LABEL", length=240)
    public String getDocVersionLabel() {
        return this.docVersionLabel;
    }
    
    public void setDocVersionLabel(String docVersionLabel) {
        this.docVersionLabel = docVersionLabel;
    }

    
    @Column(name="FILE_SIZE", length=20)
    public Integer getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="FILE_HANDLE", length=240)
    public String getFileHandle() {
        return this.fileHandle;
    }
    
    public void setFileHandle(String fileHandle) {
        this.fileHandle = fileHandle;
    }

    
    @Column(name="DOC_HISTORY_ID", length=20)
    public Integer getDocHistoryId() {
        return this.docHistoryId;
    }
    
    public void setDocHistoryId(Integer docHistoryId) {
        this.docHistoryId = docHistoryId;
    }

    
    @Column(name="ACTION_ID", length=20)
    public Integer getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    
    @Column(name="ACTION_BY_ID", length=20)
    public Integer getActionById() {
        return this.actionById;
    }
    
    public void setActionById(Integer actionById) {
        this.actionById = actionById;
    }

    
    @Column(name="ACTION_COMMENT")
    public String getActionComment() {
        return this.actionComment;
    }
    
    public void setActionComment(String actionComment) {
        this.actionComment = actionComment;
    }

    
    @Column(name="ACTION_DESC")
    public String getActionDesc() {
        return this.actionDesc;
    }
    
    public void setActionDesc(String actionDesc) {
        this.actionDesc = actionDesc;
    }

    
    @Column(name="DOC_CONTAINER_ID", length=20)
    public Integer getDocContainerId() {
        return this.docContainerId;
    }
    
    public void setDocContainerId(Integer docContainerId) {
        this.docContainerId = docContainerId;
    }

    
    @Column(name="CHECKOUT_DUE", length=7)
    public Date getCheckoutDue() {
        return this.checkoutDue;
    }
    
    public void setCheckoutDue(Date checkoutDue) {
        this.checkoutDue = checkoutDue;
    }

    
    @Column(name="DOC_STATUS_ID", length=20)
    public Integer getDocStatusId() {
        return this.docStatusId;
    }
    
    public void setDocStatusId(Integer docStatusId) {
        this.docStatusId = docStatusId;
    }

    
    @Column(name="DOC_TYPE_ID", length=20)
    public Integer getDocTypeId() {
        return this.docTypeId;
    }
    
    public void setDocTypeId(Integer docTypeId) {
        this.docTypeId = docTypeId;
    }

    
    @Column(name="DOC_AUTHOR_ID", length=20)
    public Integer getDocAuthorId() {
        return this.docAuthorId;
    }
    
    public void setDocAuthorId(Integer docAuthorId) {
        this.docAuthorId = docAuthorId;
    }

    
    @Column(name="SHORT_FILE_NAME", length=240)
    public String getShortFileName() {
        return this.shortFileName;
    }
    
    public void setShortFileName(String shortFileName) {
        this.shortFileName = shortFileName;
    }

    
    @Column(name="REPOSITORY_ID", length=4)
    public Integer getRepositoryId() {
        return this.repositoryId;
    }
    
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    
    @Column(name="RECORD_STATUS", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("tmpDocId", getTmpDocId())
            .toString();
    }

}
