/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PnUserDomainMigrationPK generated by hbm2java
 */
@Embeddable
public class PnUserDomainMigrationPK  implements Serializable {


     private Integer userId;
     private Integer domainMigrationId;

    public PnUserDomainMigrationPK() {
    }

    public PnUserDomainMigrationPK(Integer userId, Integer domainMigrationId) {
       this.userId = userId;
       this.domainMigrationId = domainMigrationId;
    }
   


    @Column(name="USER_ID", nullable=false, length=20)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    @Column(name="DOMAIN_MIGRATION_ID", nullable=false, length=20)
    public Integer getDomainMigrationId() {
        return this.domainMigrationId;
    }
    
    public void setDomainMigrationId(Integer domainMigrationId) {
        this.domainMigrationId = domainMigrationId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("userId", getUserId())
            .append("domainMigrationId", getDomainMigrationId())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnUserDomainMigrationPK) ) return false;
        PnUserDomainMigrationPK castOther = (PnUserDomainMigrationPK) other;
        return new EqualsBuilder()
            .append(this.getUserId(), castOther.getUserId())
            .append(this.getDomainMigrationId(), castOther.getDomainMigrationId())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getUserId())
            .append(getDomainMigrationId())
            .toHashCode();
    }

}
