/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PnUserDefaultCredential generated by hbm2java
 */
@Entity
@Table(name="PN_USER_DEFAULT_CREDENTIALS"
)
public class PnUserDefaultCredential implements Serializable {


     private PnUserDefaultCredentialPK comp_id;
     private String password;
     private String jogPhrase;
     private String jogAnswer;

    public PnUserDefaultCredential() {
    }

    public PnUserDefaultCredential(PnUserDefaultCredentialPK comp_id, String password, String jogPhrase, String jogAnswer) {
       this.comp_id = comp_id;
       this.password = password;
       this.jogPhrase = jogPhrase;
       this.jogAnswer = jogAnswer;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="domainId", column=@Column(name="DOMAIN_ID", nullable=false, length=20) ) } )
    public PnUserDefaultCredentialPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(PnUserDefaultCredentialPK comp_id) {
        this.comp_id = comp_id;
    }

    
    @Column(name="PASSWORD", nullable=false, length=240)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="JOG_PHRASE", nullable=false, length=240)
    public String getJogPhrase() {
        return this.jogPhrase;
    }
    
    public void setJogPhrase(String jogPhrase) {
        this.jogPhrase = jogPhrase;
    }

    
    @Column(name="JOG_ANSWER", nullable=false, length=240)
    public String getJogAnswer() {
        return this.jogAnswer;
    }
    
    public void setJogAnswer(String jogAnswer) {
        this.jogAnswer = jogAnswer;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PnUserDefaultCredential) ) return false;
        PnUserDefaultCredential castOther = (PnUserDefaultCredential) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
