/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PnUserDomainSupportsConfig generated by hbm2java
 */
@Entity
@Table(name="PN_USER_DOMAIN_SUPPORTS_CONFIG"
)
public class PnUserDomainSupportsConfig implements Serializable {


     private Integer domainId;
     private Integer configurationId;

    public PnUserDomainSupportsConfig() {
    }

    public PnUserDomainSupportsConfig(Integer domainId, Integer configurationId) {
       this.domainId = domainId;
       this.configurationId = configurationId;
    }
   

    @Id
    @Column(name="DOMAIN_ID", nullable=false, length=20)
    public Integer getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    
    @Column(name="CONFIGURATION_ID", nullable=false, length=20)
    public Integer getConfigurationId() {
        return this.configurationId;
    }
    
    public void setConfigurationId(Integer configurationId) {
        this.configurationId = configurationId;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("domainId", getDomainId())
            .append("configurationId", getConfigurationId())
            .toString();
    }

}
