/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * PnWeblogEntryAttribute generated by hbm2java
 */
@Entity
@Table(name="PN_WEBLOG_ENTRY_ATTRIBUTE"
)
public class PnWeblogEntryAttribute implements Serializable {


     private Integer weblogEntryAttributeId;
     private String name;
     private String value;
     private PnWeblogEntry pnWeblogEntry;

    public PnWeblogEntryAttribute() {
    }

	public PnWeblogEntryAttribute(Integer weblogEntryAttributeId) {
		this.setWeblogEntryAttributeId(weblogEntryAttributeId);
	}

	
    public PnWeblogEntryAttribute(String value) {
        this.value = value;
    }

	public PnWeblogEntryAttribute(Integer weblogEntryAttributeId, PnWeblogEntry pnWeblogEntry, String value) {

		this.setWeblogEntryAttributeId(weblogEntryAttributeId);		
		this.setPnWeblogEntry(pnWeblogEntry);
		this.setValue(value);
	}
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="WEBLOG_ENTRY_ATTRIBUTE_ID", nullable=false)
    public Integer getWeblogEntryAttributeId() {
        return this.weblogEntryAttributeId;
    }
    
    public void setWeblogEntryAttributeId(Integer weblogEntryAttributeId) {
        this.weblogEntryAttributeId = weblogEntryAttributeId;
    }

    
    @Column(name="NAME", length=240)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="VALUE", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=PnWeblogEntry.class)
    @JoinColumn(name="WEBLOG_ENTRY_ID")
    public PnWeblogEntry getPnWeblogEntry() {
        return this.pnWeblogEntry;
    }
    
    public void setPnWeblogEntry(PnWeblogEntry pnWeblogEntry) {
        this.pnWeblogEntry = pnWeblogEntry;
    }

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof PnWeblogEntryAttribute))
			return false;
		else {
			PnWeblogEntryAttribute pnEntryAttribute = (PnWeblogEntryAttribute) obj;
			if (null == this.getWeblogEntryAttributeId() || null == pnEntryAttribute.getWeblogEntryAttributeId())
				return false;
			else
				return (this.getWeblogEntryAttributeId().equals(pnEntryAttribute.getWeblogEntryAttributeId()));
		}
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder()
        .append(getWeblogEntryAttributeId())
        .toHashCode();
	}
	
	public String toString() {
		return new ToStringBuilder(this)
        .append("entryAttributeId", getWeblogEntryAttributeId())
        .toString();
	}

}
