/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWikiAssignment generated by hbm2java
 */
@Entity
@Table(name = "PN_WIKI_ASSIGNMENT")
public class PnWikiAssignment implements Serializable {

	private Integer objectId;

	private Integer wikiPageId;

	public PnWikiAssignment() {
	}

	public PnWikiAssignment(Integer objectId, Integer wikiPageId) {
		this.objectId = objectId;
		this.wikiPageId = wikiPageId;
	}

	@Id
	@Column(name = "OBJECT_ID", nullable = false)
	public Integer getObjectId() {
		return objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "WIKI_PAGE_ID", nullable = false)
	public Integer getWikiPageId() {
		return wikiPageId;
	}

	public void setWikiPageId(Integer wikiPageId) {
		this.wikiPageId = wikiPageId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("objectId", getObjectId()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWikiAssignment))
			return false;
		PnWikiAssignment castOther = (PnWikiAssignment) other;
		return new EqualsBuilder().append(this.getObjectId(), castOther.getObjectId()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getObjectId()).toHashCode();
	}

}