/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflowTransition generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW_TRANSITION")
public class PnWorkflowTransition implements Serializable {

	private PnWorkflowTransitionPK comp_id;

	private String transitionVerb;

	private String transitionDescription;

	private Integer createdById;

	private Date createdDatetime;

	private Integer modifiedById;

	private Date modifiedDatetime;

	private Date crc;

	private String recordStatus;

	private PnWorkflow pnWorkflow;

	private Set pnWorkflowRules = new HashSet(0);

	private Set pnEnvelopeVersions = new HashSet(0);

	private PnWorkflowStep pnWorkflowStepByEndStepIdAndWorkflowId;

	private PnWorkflowStep pnWorkflowStepByBeginStepIdAndWorkflowId;

	public PnWorkflowTransition() {
	}

	public PnWorkflowTransition(PnWorkflowTransitionPK comp_id, Integer createdById, Date createdDatetime, Date crc,
			String recordStatus) {
		this.comp_id = comp_id;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnWorkflowTransition(net.project.hibernate.model.PnWorkflowTransitionPK comp_id, Integer createdById,
			Date createdDatetime, Date crc, String recordStatus,
			net.project.hibernate.model.PnWorkflowStep pnWorkflowStepByEndStepIdAndWorkflowId,
			net.project.hibernate.model.PnWorkflowStep pnWorkflowStepByBeginStepIdAndWorkflowId, Set pnWorkflowRules,
			Set pnEnvelopeVersions) {
		this.comp_id = comp_id;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflowStepByEndStepIdAndWorkflowId = pnWorkflowStepByEndStepIdAndWorkflowId;
		this.pnWorkflowStepByBeginStepIdAndWorkflowId = pnWorkflowStepByBeginStepIdAndWorkflowId;
		this.pnWorkflowRules = pnWorkflowRules;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	public PnWorkflowTransition(net.project.hibernate.model.PnWorkflowTransitionPK comp_id, String transitionVerb,
			String transitionDescription, Integer createdById, Date createdDatetime, Integer modifiedById,
			Date modifiedDatetime, Date crc, String recordStatus, net.project.hibernate.model.PnWorkflow pnWorkflow,
			net.project.hibernate.model.PnWorkflowStep pnWorkflowStepByEndStepIdAndWorkflowId,
			net.project.hibernate.model.PnWorkflowStep pnWorkflowStepByBeginStepIdAndWorkflowId, Set pnWorkflowRules,
			Set pnEnvelopeVersions) {
		this.comp_id = comp_id;
		this.transitionVerb = transitionVerb;
		this.transitionDescription = transitionDescription;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflow = pnWorkflow;
		this.pnWorkflowStepByEndStepIdAndWorkflowId = pnWorkflowStepByEndStepIdAndWorkflowId;
		this.pnWorkflowStepByBeginStepIdAndWorkflowId = pnWorkflowStepByBeginStepIdAndWorkflowId;
		this.pnWorkflowRules = pnWorkflowRules;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "workflowId", column = @Column(name = "WORKFLOW_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "transitionId", column = @Column(name = "TRANSITION_ID", nullable = false, length = 20)) })
	public PnWorkflowTransitionPK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PnWorkflowTransitionPK comp_id) {
		this.comp_id = comp_id;
	}

	@Column(name = "TRANSITION_VERB", length = 80)
	public String getTransitionVerb() {
		return this.transitionVerb;
	}

	public void setTransitionVerb(String transitionVerb) {
		this.transitionVerb = transitionVerb;
	}

	@Column(name = "TRANSITION_DESCRIPTION", length = 500)
	public String getTransitionDescription() {
		return this.transitionDescription;
	}

	public void setTransitionDescription(String transitionDescription) {
		this.transitionDescription = transitionDescription;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflow.class)
	@JoinColumn(name = "WORKFLOW_ID", insertable = false, updatable = false)
	public PnWorkflow getPnWorkflow() {
		return this.pnWorkflow;
	}

	public void setPnWorkflow(PnWorkflow pnWorkflow) {
		this.pnWorkflow = pnWorkflow;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowTransition", targetEntity = PnWorkflowRule.class)
	@Transient
	public Set getPnWorkflowRules() {
		return this.pnWorkflowRules;
	}

	public void setPnWorkflowRules(Set pnWorkflowRules) {
		this.pnWorkflowRules = pnWorkflowRules;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowTransition", targetEntity = PnEnvelopeVersion.class)
	@Transient
	public Set getPnEnvelopeVersions() {
		return this.pnEnvelopeVersions;
	}

	public void setPnEnvelopeVersions(Set pnEnvelopeVersions) {
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflowStep.class)
	//@JoinColumns( {
	//		@JoinColumn(name = "END_STEP_ID", referencedColumnName = "STEP_ID", insertable = false, updatable = false),
	//		@JoinColumn(name = "WORKFLOW_ID", referencedColumnName = "WORKFLOW_ID", insertable = false, updatable = false) })
	@Transient
	public PnWorkflowStep getPnWorkflowStepByEndStepIdAndWorkflowId() {
		return this.pnWorkflowStepByEndStepIdAndWorkflowId;
	}

	public void setPnWorkflowStepByEndStepIdAndWorkflowId(PnWorkflowStep pnWorkflowStepByEndStepIdAndWorkflowId) {
		this.pnWorkflowStepByEndStepIdAndWorkflowId = pnWorkflowStepByEndStepIdAndWorkflowId;
	}

	//@ManyToOne(fetch = FetchType.LAZY, targetEntity = PnWorkflowStep.class)
	//@JoinColumns( {
	//		@JoinColumn(name = "BEGIN_STEP_ID", referencedColumnName = "STEP_ID", insertable = false, updatable = false),
	//		@JoinColumn(name = "WORKFLOW_ID", referencedColumnName = "WORKFLOW_ID", insertable = false, updatable = false) })
	@Transient
	public PnWorkflowStep getPnWorkflowStepByBeginStepIdAndWorkflowId() {
		return this.pnWorkflowStepByBeginStepIdAndWorkflowId;
	}

	public void setPnWorkflowStepByBeginStepIdAndWorkflowId(PnWorkflowStep pnWorkflowStepByBeginStepIdAndWorkflowId) {
		this.pnWorkflowStepByBeginStepIdAndWorkflowId = pnWorkflowStepByBeginStepIdAndWorkflowId;
	}

	public String toString() {
		return new ToStringBuilder(this).append("comp_id", getComp_id()).toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if (!(other instanceof PnWorkflowTransition))
			return false;
		PnWorkflowTransition castOther = (PnWorkflowTransition) other;
		return new EqualsBuilder().append(this.getComp_id(), castOther.getComp_id()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getComp_id()).toHashCode();
	}

}
