/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package net.project.hibernate.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * PnWorkflowEnvelope generated by hbm2java
 */
@Entity
@Table(name = "PN_WORKFLOW_ENVELOPE")
public class PnWorkflowEnvelope implements Serializable {

	private Integer envelopeId;

	private Integer currentVersionId;

	private String envelopeName;

	private String envelopeDescription;

	private Integer createdById;

	private Date createdDatetime;

	private Integer modifiedById;

	private Date modifiedDatetime;

	private Date crc;

	private String recordStatus;

	private PnWorkflow pnWorkflow;

	private PnWorkflowStrictness pnWorkflowStrictness;

	private Set pnEnvelopeHasObjects = new HashSet(0);

	private Set pnEnvelopeHistories = new HashSet(0);

	private Set pnEnvelopeVersions = new HashSet(0);

	public PnWorkflowEnvelope() {
	}

	public PnWorkflowEnvelope(Integer envelopeId, Integer currentVersionId, Integer createdById, Date createdDatetime,
			Date crc, String recordStatus) {
		this.envelopeId = envelopeId;
		this.currentVersionId = currentVersionId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
	}

	public PnWorkflowEnvelope(Integer envelopeId, Integer currentVersionId, Integer createdById, Date createdDatetime,
			Date crc, String recordStatus, net.project.hibernate.model.PnWorkflow pnWorkflow,
			net.project.hibernate.model.PnWorkflowStrictness pnWorkflowStrictness, Set pnEnvelopeHasObjects,
			Set pnEnvelopeHistories, Set pnEnvelopeVersions) {
		this.envelopeId = envelopeId;
		this.currentVersionId = currentVersionId;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflow = pnWorkflow;
		this.pnWorkflowStrictness = pnWorkflowStrictness;
		this.pnEnvelopeHasObjects = pnEnvelopeHasObjects;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	public PnWorkflowEnvelope(Integer envelopeId, Integer currentVersionId, String envelopeName,
			String envelopeDescription, Integer createdById, Date createdDatetime, Integer modifiedById,
			Date modifiedDatetime, Date crc, String recordStatus, PnWorkflow pnWorkflow,
			PnWorkflowStrictness pnWorkflowStrictness, Set pnEnvelopeHasObjects, Set pnEnvelopeHistories,
			Set pnEnvelopeVersions) {
		this.envelopeId = envelopeId;
		this.currentVersionId = currentVersionId;
		this.envelopeName = envelopeName;
		this.envelopeDescription = envelopeDescription;
		this.createdById = createdById;
		this.createdDatetime = createdDatetime;
		this.modifiedById = modifiedById;
		this.modifiedDatetime = modifiedDatetime;
		this.crc = crc;
		this.recordStatus = recordStatus;
		this.pnWorkflow = pnWorkflow;
		this.pnWorkflowStrictness = pnWorkflowStrictness;
		this.pnEnvelopeHasObjects = pnEnvelopeHasObjects;
		this.pnEnvelopeHistories = pnEnvelopeHistories;
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	@Id
	@Column(name = "ENVELOPE_ID", nullable = false)
	public Integer getEnvelopeId() {
		return this.envelopeId;
	}

	public void setEnvelopeId(Integer envelopeId) {
		this.envelopeId = envelopeId;
	}

	@Column(name = "CURRENT_VERSION_ID", nullable = false, length = 20)
	public Integer getCurrentVersionId() {
		return this.currentVersionId;
	}

	public void setCurrentVersionId(Integer currentVersionId) {
		this.currentVersionId = currentVersionId;
	}

	@Column(name = "ENVELOPE_NAME", length = 80)
	public String getEnvelopeName() {
		return this.envelopeName;
	}

	public void setEnvelopeName(String envelopeName) {
		this.envelopeName = envelopeName;
	}

	@Column(name = "ENVELOPE_DESCRIPTION", length = 500)
	public String getEnvelopeDescription() {
		return this.envelopeDescription;
	}

	public void setEnvelopeDescription(String envelopeDescription) {
		this.envelopeDescription = envelopeDescription;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 20)
	public Integer getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(Integer createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREATED_DATETIME", nullable = false, length = 7)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Column(name = "MODIFIED_BY_ID", length = 20)
	public Integer getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Integer modifiedById) {
		this.modifiedById = modifiedById;
	}

	@Column(name = "MODIFIED_DATETIME", length = 7)
	public Date getModifiedDatetime() {
		return this.modifiedDatetime;
	}

	public void setModifiedDatetime(Date modifiedDatetime) {
		this.modifiedDatetime = modifiedDatetime;
	}

	@Column(name = "CRC", nullable = false, length = 7)
	public Date getCrc() {
		return this.crc;
	}

	public void setCrc(Date crc) {
		this.crc = crc;
	}

	@Column(name = "RECORD_STATUS", nullable = false, length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnWorkflow.class)
	@JoinColumn(name = "WORKFLOW_ID")
	public PnWorkflow getPnWorkflow() {
		return this.pnWorkflow;
	}

	public void setPnWorkflow(PnWorkflow pnWorkflow) {
		this.pnWorkflow = pnWorkflow;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=PnWorkflowStrictness.class)
	@JoinColumn(name = "STRICTNESS_ID")
	public PnWorkflowStrictness getPnWorkflowStrictness() {
		return this.pnWorkflowStrictness;
	}

	public void setPnWorkflowStrictness(PnWorkflowStrictness pnWorkflowStrictness) {
		this.pnWorkflowStrictness = pnWorkflowStrictness;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowEnvelope", targetEntity = PnEnvelopeHasObject.class)
	@Transient
	public Set getPnEnvelopeHasObjects() {
		return this.pnEnvelopeHasObjects;
	}

	public void setPnEnvelopeHasObjects(Set pnEnvelopeHasObjects) {
		this.pnEnvelopeHasObjects = pnEnvelopeHasObjects;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowEnvelope", targetEntity = PnEnvelopeHistory.class)
	@Transient
	public Set getPnEnvelopeHistories() {
		return this.pnEnvelopeHistories;
	}

	public void setPnEnvelopeHistories(Set pnEnvelopeHistories) {
		this.pnEnvelopeHistories = pnEnvelopeHistories;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnWorkflowEnvelope", targetEntity = PnEnvelopeVersion.class)
	@Transient
	public Set getPnEnvelopeVersions() {
		return this.pnEnvelopeVersions;
	}

	public void setPnEnvelopeVersions(Set pnEnvelopeVersions) {
		this.pnEnvelopeVersions = pnEnvelopeVersions;
	}

	public String toString() {
		return new ToStringBuilder(this).append("envelopeId", getEnvelopeId()).toString();
	}

}
