/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QrtzTriggerListener generated by hbm2java
 */
@Entity
@Table(name="QRTZ_TRIGGER_LISTENERS"
)
public class QrtzTriggerListener  implements Serializable {


     private QrtzTriggerListenerPK comp_id;
     private QrtzTrigger qrtzTrigger;

    public QrtzTriggerListener() {
    }

	
    public QrtzTriggerListener(QrtzTriggerListenerPK comp_id) {
        this.comp_id = comp_id;
    }
    public QrtzTriggerListener(QrtzTriggerListenerPK comp_id, QrtzTrigger qrtzTrigger) {
       this.comp_id = comp_id;
       this.qrtzTrigger = qrtzTrigger;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="triggerName", column=@Column(name="TRIGGER_NAME", nullable=false, length=80) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=80) ), 
        @AttributeOverride(name="triggerListener", column=@Column(name="TRIGGER_LISTENER", nullable=false, length=80) ) } )
    public QrtzTriggerListenerPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(QrtzTriggerListenerPK comp_id) {
        this.comp_id = comp_id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity=QrtzTrigger.class)
    @JoinColumns( { 
        @JoinColumn(name="TRIGGER_NAME", referencedColumnName="TRIGGER_NAME", insertable=false, updatable=false), 
        @JoinColumn(name="TRIGGER_GROUP", referencedColumnName="TRIGGER_GROUP", insertable=false, updatable=false) } )
    public QrtzTrigger getQrtzTrigger() {
        return this.qrtzTrigger;
    }
    
    public void setQrtzTrigger(QrtzTrigger qrtzTrigger) {
        this.qrtzTrigger = qrtzTrigger;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("comp_id", getComp_id())
            .toString();
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof QrtzTriggerListener) ) return false;
        QrtzTriggerListener castOther = (QrtzTriggerListener) other;
        return new EqualsBuilder()
            .append(this.getComp_id(), castOther.getComp_id())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getComp_id())
            .toHashCode();
    }

}
