/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
*/
package net.project.hibernate.model;

import java.io.Serializable;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * QrtzCalendar generated by hbm2java
 */
@Entity
@Table(name="QRTZ_CALENDARS"
)
public class QrtzCalendar implements Serializable {


     private String calendarName;
     private Blob calendar;

    public QrtzCalendar() {
    }

    public QrtzCalendar(String calendarName, Blob calendar) {
       this.calendarName = calendarName;
       this.calendar = calendar;
    }
   
     @Id 

    
    @Column(name="CALENDAR_NAME", nullable=false)
    public String getCalendarName() {
        return this.calendarName;
    }
    
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }

    
    @Column(name="CALENDAR", nullable=false, length=4000)
    public Blob getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Blob calendar) {
        this.calendar = calendar;
    }

    public String toString() {
        return new ToStringBuilder(this)
            .append("calendarName", getCalendarName())
            .toString();
    }

}
