PROMPT Connecting &1 
conn &1/&2@&3;

PROMPT creating synonym for PN_WIKI_HISTORY table.  
CREATE OR REPLACE SYNONYM PN_WIKI_HISTORY FOR PNET.PN_WIKI_HISTORY;

PROMPT creating synonym for PN_PROJECT_SPACE_META_COMBO table.                                                                                                    
CREATE OR REPLACE SYNONYM PN_PROJECT_SPACE_META_COMBO FOR PNET.PN_PROJECT_SPACE_META_COMBO;         

PROMPT creating synonym for PN_WIKI_ASSIGNMENT table.
CREATE OR REPLACE SYNONYM PN_WIKI_ASSIGNMENT FOR PNET.PN_WIKI_ASSIGNMENT;

PROMPT creating synonym for PN_ACTIVITY_LOG_MARKED table.  
CREATE OR REPLACE SYNONYM PN_ACTIVITY_LOG_MARKED FOR PNET.PN_ACTIVITY_LOG_MARKED;

PROMPT creating synonym for PN_ACTIVITY_LOG table.  
CREATE OR REPLACE SYNONYM PN_ACTIVITY_LOG FOR PNET.PN_ACTIVITY_LOG;

PROMPT creating synonym for PN_SHARED_FORMS_VISIBLITY table.     
CREATE OR REPLACE SYNONYM PN_SHARED_FORMS_VISIBLITY FOR PNET.PN_SHARED_FORMS_VISIBLITY;

PROMPT creating synonym for PN_WEBLOG table.     
CREATE OR REPLACE SYNONYM PN_WEBLOG FOR PNET.PN_WEBLOG;

PROMPT creating synonym for PN_WEBLOG_COMMENT table.    
CREATE OR REPLACE SYNONYM PN_WEBLOG_COMMENT FOR PNET.PN_WEBLOG_COMMENT;

PROMPT creating synonym for PN_WEBLOG_ENTRY table.  
CREATE OR REPLACE SYNONYM PN_WEBLOG_ENTRY FOR PNET.PN_WEBLOG_ENTRY;

PROMPT creating synonym for PN_WEBLOG_ENTRY_ATTRIBUTE table.
CREATE OR REPLACE SYNONYM PN_WEBLOG_ENTRY_ATTRIBUTE FOR PNET.PN_WEBLOG_ENTRY_ATTRIBUTE;

PROMPT creating synonym for PN_WIKI_HISTORY table.
CREATE OR REPLACE SYNONYM PN_WIKI_HISTORY FOR PNET.PN_WIKI_HISTORY;

PROMPT creating synonym for PN_WIKI_PAGE table.
CREATE OR REPLACE SYNONYM PN_WIKI_PAGE FOR PNET.PN_WIKI_PAGE;

PROMPT creating synonym for PN_WIKI_PAGE_BACKUP table.
CREATE OR REPLACE SYNONYM PN_WIKI_PAGE_BACKUP FOR PNET.PN_WIKI_PAGE_BACKUP;

PROMPT creating synonym for PN_WIKI_ASSIGNMENT table.
CREATE OR REPLACE SYNONYM PN_WIKI_ASSIGNMENT FOR PNET.PN_WIKI_ASSIGNMENT;

PROMPT creating synonym for PN_WIKI_ATTACHMENT table.
CREATE OR REPLACE SYNONYM PN_WIKI_ATTACHMENT FOR PNET.PN_WIKI_ATTACHMENT;
